### ISSUE TITLE
Complete the Taxa section of the editor

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/metacatui#10]
- [x] Display a taxa section in the editor form
- [x] Update the EMLTaxonCoverage model when the UI is changed
- [x] Update or add the taxonomic info in the EML doc during serialize()

**Comment by amoeba** [comment]
Hooked a basic impl just now. Still need to trigger events off `change` and deal with serialization.
![taxa](https://cloud.githubusercontent.com/assets/563/22393263/0a7276da-e4b0-11e6-8c13-438e4fc974b2.gif)

**Comment by laurenwalker** [comment]
Can we make the UI look like the mockups (found in the [nceas-design](https://github.nceas.ucsb.edu/NCEAS/nceas-design) repo)? I think we also decided that instead of having an "Add" button, we would just automatically add a new empty row to the list anytime the user fills out the currently empty row. It's one less click for the user. I have some code you can reuse for that in EML211View. createBasicTextFields and EML211View.updateBasicText

[Edit-Metadata-View-Taxa.pdf](https://github.com/NCEAS/metacatui/files/739260/Edit-Metadata-View-Taxa.pdf)

**Comment by amoeba** [comment]
Will do.

**Comment by amoeba** [comment]
This is pretty much half-done but I'm out this week so if someone wants to take this over that'd be fine. I just tidied things up a bit but still need to link up DOM events and look at serialization.

**Comment by amoeba** [comment]
I'll wrap this up this week and move onto #19

**Comment by amoeba** [comment]
I pushed these changes up. I've tested parsing/editing/serialization on a few variants and things appear to be working nicely.

I wrote most of the code on the EML211View and I'd like to refactor most of it into an EMLTaxonView. I'll close this issue and open another for improvements.
