### ISSUE TITLE
Nothing was found error shows up then the metadata is rendered anyway

### ISSUE THREAD

**Issue by amoeba** [NCEAS/metacatui#100]
Ran into a weird edge case to the "Nothing was found" error. On 

https://search.dataone.org/#view/urn:uuid:0592c5e8-3445-48ab-9873-2da324090ee8

when I'm not logged in, the "Nothing was found message" appears and stays visible (like it should, this package is not public read). When I'm logged in, I can get into a state where the message appears but then disappears and the metadata landing page is shown anyway.

To reproduce:

0. Be a member of the sasap or arctic-data admin groups and be logged in
1. Visit https://search.dataone.org/#view/urn:uuid:0592c5e8-3445-48ab-9873-2da324090ee8
2. Notice the page is rendered without the "Nothing was found error"
3. Refresh the page
4. See the "Nothing was found" message, which disappears, followed by the landing page being rendered

![cast](https://cloud.githubusercontent.com/assets/563/25462335/cad49a90-2a9a-11e7-8ddb-32c1f99748c1.gif)

**Comment by laurenwalker** [comment]
This behavior seems to be fixed already
