### ISSUE TITLE
Complete the ImageView

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/metacatui#1004]
The ImageView will include an ImageUploaderView, and text inputs for the image label and URL.

![Screen Shot 2019-09-16 at 12.46.27 PM.png](https://images.zenhubusercontent.com/5d152e12c27d0c306f021863/d34a9f9e-40c0-4220-9206-2035cec4cebf)

- When the name or URL is changed, update the ImageModel `label` and `associatedURL` attributes.

**Comment by robyngit** [comment]
The last task related to this issue is to ensure that validation errors are displayed correctly.
