### ISSUE TITLE
Complete the PortalLogosView

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/metacatui#1006]
The PortalLogosView will contain multiple ImageViews for each portal logo. 

![Screen Shot 2019-09-16 at 12.46.27 PM.png](https://images.zenhubusercontent.com/5d152e12c27d0c306f021863/6a5c46ac-b841-4249-ac42-51f92875954b)

- When the Remove icon is clicked, the ImageModel should be removed from the PortalModel.

Eventually, this view will handle reordering too (after the MVP)

**Comment by robyngit** [comment]
The logos view still needs to be styled, but this is part of [issue 1012](https://github.com/NCEAS/metacatui/issues/1012)
