### ISSUE TITLE
Obsoleted parent packages remain displayed on child's landing page

### ISSUE THREAD

**Issue by jagoldstein** [NCEAS/metacatui#1025]
When a parent package is obsoleted, a link to _both_ the newest version _and_ the obsoleted one are displayed on the child's landing page. See this example from https://arcticdata.io/catalog/view/urn:uuid:875272a3-52dd-4c21-8e14-984015832955 :

<img width="1747" alt="Screen Shot 2019-07-22 at 11 00 05 AM" src="https://user-images.githubusercontent.com/18270215/61654623-ade10d00-ac71-11e9-803c-cd00ac8cb9f8.png">

To avoid confusing users and to make obsoleted versions less discoverable, **only** the link to the newest version ought to appear on a child's landing page.

**Comment by laurenwalker** [comment]
Thanks Jesse. Not sure how this one slipped by me!
