### ISSUE TITLE
System metadata "fileName"s are changed for data objects uploaded through editor, causing mismatch with EML

### ISSUE THREAD

**Issue by jagoldstein** [NCEAS/metacatui#1027]
For data object `fileName`s created via the editor, we made the decision to replace all non [A-Za-z0-9] characters with _ (underscore); #915 . This effort was spurred by NCEI during our content replication planning. However, this approach causes a mismatch between a data object's `fileName` in its system metadata and its `entityName` in the EML (the latter is not changed by the editor; the name the `submitter` enters is retained).

This mismatch can lead to the absence of the "More Info" link, no "Download" button within `otherEntity` on the landing page, and `submitter` confusion. In the case noted [here](https://support.nceas.ucsb.edu/rt/Ticket/Display.html?id=18814#txn-429534), the user only included characters that are [generally deemed acceptable and machine-readable](https://esajournals.onlinelibrary.wiley.com/doi/full/10.1890/0012-9623-90.2.205); he did not use special characters. He only used letters, numbers, and a hyphen before the extension.

We should rethink our approach for naming data objects OR the editor should also update the object's `entityName` in the EML to match its `fileName` in the system metadata.

**Comment by laurenwalker** [comment]
The above referenced commits changed two things to fix this issue:

1. The object identifier is inserted into the EML as the `id` attribute on the entity node. I changed the Metacat stylesheets to pass that `id` attribute into the HTML of the entity section. (NCEAS/metacat@57916d87f552295cd1231df81400c2df2a9ec50e) The MetadataView uses that id in the HTML for the "More info" link.
2. The Editor will update the EML entity name to match the data object file name, unless the user has changed the entity name to a custom value.

These changes won't affect any existing datasets, but will affect any datasets that are edited or created in the future.
