### ISSUE TITLE
metrics tab on DBO project page spins indefinitely

### ISSUE THREAD

**Issue by jeanetteclark** [NCEAS/metacatui#1028]
https://arcticdata.io/catalog/projects/DBO/metrics

**Comment by laurenwalker** [comment]
It looks like the POSTs to the query service are not working:

```xml
<?xml version="1.0" encoding="UTF-8"?><error detailCode="2821" errorCode="500" name="ServiceFailure">
    <description>Solr server error: org.apache.solr.client.solrj.SolrServerException: org.apache.solr.common.SolrException</description>
</error>
```

It looks like the Metacat on arcticdata.io is on version 2.10.2, which supports POSTs to the query service. Any idea why that's failing, @taojing2002 or @csjx ?

**Comment by jeanetteclark** [comment]
any progress on this one @taojing2002 @laurenwalker or @csjx?

**Comment by laurenwalker** [comment]
This was fixed by increasing the maxBooleanClauses config in the solrconfig.xml file
