### ISSUE TITLE
Attributes pane w/ annotations displays below attributes list on narrow browsers

### ISSUE THREAD

**Issue by amoeba** [NCEAS/metacatui#1029]
(I think we had an issue for this in the past but I can't find it, please merge if you can find it).

On narrow (~1200px, not that narrow, really), the pane to the right of the attributes list shows below the list of attributes rather than to the right, as designed:

<img width="501" alt="Screen Shot 2019-07-24 at 9 49 51 AM" src="https://user-images.githubusercontent.com/563/61816522-055db500-adf9-11e9-876a-61d78d18bb71.png">

I don't think this happens on all deployments and I think this is just happening due to how I'm using annotations. I'm filing this so I don't forget but I need to do more research before working on fix.

**Comment by jagoldstein** [comment]
@amoeba is this the previously filed issue that you are looking for? (I'm unsure how to "merge" issues.)
https://github.com/NCEAS/metacatui/issues/916

That bug was supposedly squashed already.

**Comment by amoeba** [comment]
Thanks @jagoldstein 	I knew it was out there. I think I'll leave this open until I can figure out whether it's the same issue or new. 

Re: 
>  (I'm unsure how to "merge" issues.)

I made that term up. Oops!
