### ISSUE TITLE
Forward to newest version in the editor is broken

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/metacatui#103]
The functionality that forwards you to the newest version of a dataset in the Editor isn't working anymore. Not sure what broke it, but will investigate.

**Comment by laurenwalker** [comment]
Looks like this is being caused by incorrect solr resourceMap field values, which may be caused by multiple identifier statements in the RDF:

Example:

`<rdf:Description rdf:about="https://cn.dataone.org/cn/v2/resolve/urn%3Auuid%3Abec379ac-4756-411f-a944-d99a088e2b45">
        <n0:creator>
            <rdf:Description>
                <rdf:type rdf:resource="http://purl.org/dc/terms/Agent"/>
                <n1:name>Lauren Walker</n1:name>
            </rdf:Description>
        </n0:creator>
        <terms:identifier>urn:uuid:bec379ac-4756-411f-a944-d99a088e2b45</terms:identifier>
        <terms:identifier>urn:uuid:416bae48-e53f-440f-acb2-f65cd091ad56</terms:identifier>
        <terms:identifier>urn:uuid:bec379ac-4756-411f-a944-d99a088e2b45</terms:identifier>
        <terms:modified rdf:datatype="http://www.w3.org/2001/XMLSchema#dateTime">2017-04-28T16:26:12.133Z</terms:modified>
        <ter:describes rdf:resource="https://cn.dataone.org/cn/v2/resolve/urn%3Auuid%3Abec379ac-4756-411f-a944-d99a088e2b45#aggregation"/>
        <rdf:type rdf:resource="http://www.openarchives.org/ore/terms/ResourceMap"/>
    </rdf:Description>`

**Comment by csjx** [comment]
Hmm, looks like I missed some of the duplicate stuff.  I found this to be an issue in `DataPackage.serialize()`  lines 1117ish where we change the resource map identifiers.

https://github.com/NCEAS/metacatui/blame/METACATUI_2_0_BRANCH/metacatui/src/main/webapp/js/collections/DataPackage.js#L1117

Let me know if you'd like me to look at it.

**Comment by laurenwalker** [comment]
I committed a fix to the duplicate identifier node issue AND this forwarding to newest version issue. Both should be fixed now.
