### ISSUE TITLE
"Submit Data" and "Submit Dataset" buttons confusing

### ISSUE THREAD

**Issue by vchendrix** [NCEAS/metacatui#1035]
It has been noted by several of our users that the "Submit Data" and "Submit Dataset" buttons are confusing.  On several occaison users said they lost their entered metadata after they clicked "Submit Data" thinking that they were saving their metadata.

**Comment by mbjones** [comment]
Agreed. We've also talked about needing to differentiate a 'Save' from a 'Submit' function.  In the new portals work, we've discussed switching our top level buttons to "New Dataset" and "New Portal" or "Add Dataset" and "Add Portal", and then have the 'Submit' language only on the form, possibly associated with a 'Save'. Let's discuss with @laurenwalker @csjx and @robyngit.  There may be existing issues with these as well.

**Comment by laurenwalker** [comment]
We had a user confuse those buttons as well, so we decided to remove the button styling from the "Submit Dataset" link in the main app navigation (i.e. just display it as a regular link). See https://arcticdata.io/catalog. 

Changing the link text would probably be helpful as well. This would just need to be done in the ESS-DIVE theme template.

**Comment by laurenwalker** [comment]
This has been resolved in [2.13.3](https://github.com/NCEAS/metacatui/tree/2.13.3) which allows custom configuration of the editor save button text.
