### ISSUE TITLE
Upgrade MetacatUI editor to allow creation and editing of EML 2.2

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/metacatui#1037]

**Comment by laurenwalker** [comment]
The editor should automatically upgrade EML 2.1.1 docs to EML 2.2.0. New EML docs should bbe EML 2.2.0.
EML Annotations on the attributes should not be removed unless the attribute itself is removed. Other annotations shouldn't be removed either, but special attention should be paid to those on attributes since those will be in production on the ADC soon

**Comment by yvanlebras** [comment]
Hi NCEAS. We were searching why we don't have "direct edit access" on our test metacat instance and with this issue I understand that this is because we uploaded EML 2.2 docs... So your advice can be to change it to 2.1.1 to have the possibility to edit it directly from the web, then ~this summer, after updating metacatui all docs will be automatically converted to 2.2 with the same edit possibility? 

Thank you for your amazing work on EML and metacat!

**Comment by laurenwalker** [comment]
Hi @yvanlebras  - Yes, only EML 2.2.0 docs are supported in the MetacatUI editor right now. 

> this summer, after updating metacatui all docs will be automatically converted to 2.2 with the same edit possibility?

Yes, in the next few months we will be updating MetacatUI so EML 2.2.0 docs can be edited, and all EML 2.1.1 docs will be automatically upgraded to EML 2.2.0 when/if they are edited in MetacatUI.

**Comment by yvanlebras** [comment]
Thank you for your answer.Just to be sure, "Yes, only EML 2.2.0 docs are supported in the MetacatUI editor right now." -> "Yes, only EML 2.1.1 docs are supported in the MetacatUI editor right now." Isn't it ?
Wishing you a very good end of week
Le 5 mars 2020 17:49, Lauren Walker <notifications@github.com> a écrit :


Hi @yvanlebras  - Yes, only EML 2.2.0 docs are supported in the MetacatUI editor right now. 

> this summer, after updating metacatui all docs will be automatically converted to 2.2 with the same edit possibility?

Yes, in the next few months we will be updating MetacatUI so EML 2.2.0 docs can be edited, and all EML 2.1.1 docs will be automatically upgraded to EML 2.2.0 when/if they are edited in MetacatUI.

**Comment by laurenwalker** [comment]
Oops, yes, I meant to say only EML 2.1.1 docs are supported in the MetacatUI editor right now.

**Comment by yvanlebras** [comment]
;)
Le 5 mars 2020 18:46, Lauren Walker <notifications@github.com> a écrit :


Oops, yes, I meant to say only EML 2.1.1 docs are supported in the MetacatUI editor right now.

**Comment by amoeba** [comment]
This started out straightforward but ended up being more complicated than I thought. It's easy to get the editor to start upgrading older 2.1.1 docs to EML 2.2.0 and serialize/edit 2.2.0 docs _created from the editor or other 2.1.1 docs_.

But then went on to test round-tripping w/ our data papers example 2.2.0 doc from the EML repo which has a lot more stuff than is supposed in the editor. I found two types of bugs we need to squash:

1. Sub-module models (e.g., project) aren't aware of node-order so supported and unsupported elements clash and get serialized in the wrong order in edge cases. e.g., funding gets serialized after award which is backwards
2. I see some odd mangling when round-tripping:

With a doc that has this snippet inside it:

```xml
<citation>
  <title>Title for a paper that used this dataset.</title>
  <creator>
    <individualName>
      <givenName>Mark</givenName>
      <surName>Jarkady</surName>
    </individualName>
  </creator>
  <pubDate>2017</pubDate>
  <article>
    <journal>EcoSphere</journal>
    <publicationPlace>https://doi.org/10.1002/ecs2.2166</publicationPlace>
  </article>
</citation>
```

the editor spits out

```xml
<citation>


  <article>
    <journal>EcoSphere</journal>
    <publicationPlace>https://doi.org/10.1002/ecs2.2166</publicationPlace>
  </article>
</citation>
```

I think I see a way forward on (1) but I haven't looked into (2) yet. I'll pick this up next week.

**Comment by amoeba** [comment]
Nearly done on this. I found a few programming errors and a few other areas where there was hard-coded logic that needed to be updated. I'm now able upgrade existing EML 2.1.1 docs and also round-trip existing EML 2.2.0 that use portions of EML we don't support in the editor (annotations, data paper stuff, etc). I think I can wrap this up by the end of the week if not earlier.

**Comment by amoeba** [comment]
Okay, took another look at this tonight and I'm happy with where things are. I ended up finding a few unrelated bugs while testing so it was useful overall.

I spent the most time testing round-tripping to ensure we're not losing anything when we bring in EML 2.1.1 docs or when we're editing EML 2.2.0 docs that make use of elements that don't have associated fields in the editor to manipulate. I tested a number of docs and found no meaningful round-trip errors. I tested:

- Simple EML 2.1.1 doc
- A richer EML 2.1.1 doc
- Five random EML 2.1.1 docs from the ADC
- Five random _recent_ (last 100) EML 2.1.1 docs from the ADC
- Our `eml-data-paper.xml` test doc which exercises all of the new stuff EML 2.2.0 supports
- A full data package with annotations at the entity and attribute level

@laurenwalker can you think of any other good tests I'm not thinking of here?

I'm waiting to make the commits here until we create a 2.13 branch but will push things up and send in a PR once that's done.

**Comment by laurenwalker** [comment]
Awesome Bryce, that's great news. Here are some other testing ideas:

- old EML 2.1.1 docs from KNB (usually created from the old registry or Morpho)
- complex EML 2.1.1 created from Morpho
- Multiple rounds of editing and saving, with and without navigating away from editor view

**Comment by amoeba** [comment]
Ooh, those are great suggestions. Thanks.

**Comment by amoeba** [comment]
Okay, I ran through a few variants of those and didn't find anything. I did find a latent bug in the taxon model which I'll fix with this work. Done testing for now.

**Comment by mbjones** [comment]
That's awesome @amoeba . 

Given the critical changes proposed here, I suggest that we should create a release candidate for this release that can be deployed on a testing server for @jeanetteclark, @laijasmine, and the datateam to give it a thorough spin. Or rather than a release candidate, I suppose it could go in the release if the EML 2.2 behavior is initially configurable on/off, and it gets thoroughly tested out on test.arcticdata.io before deployment on production.

Also, some round-tripping tests with the R EML package might expose some issues, e.g.:
- Create EML 2.2.0 in R EML, then edit in MetacatUI, and re-open and edit in R EML
- Create EML 2.2.0 in MetacatUI, then edit in R EML, and re-open and edit in MetacatUI

**Comment by laurenwalker** [comment]
I agree with Matt about testing on test.arcticdata.io first. We could just deploy the feature branch there. Let's make sure the latest from `master` is merged in before we do that

**Comment by amoeba** [comment]
Good idea on the R<->MetacatUI round-tripping @mbjones. I didn't find any specific bugs with this work but it did help me find a few pre-existing ones that I'll file separate or find an existing ticket for. Nothing high priority I'd say:

- Creates IDs when there aren't any and there's no reason to
- Overwrites existing `intellectualRights` values
- Rejects `boundingAltitude` sub-element of `geographicCoverage`
- Rejects `dataTable/physical/dataFormat/textFormat/recordDelimiter` value of `<recordDelimiter>&#13;</recordDelimiter>` (carriage return). On first pass, removes the `&#13;`. On second pass, removes the element entirely.

Now that the `dev-2.13` ref is pushed here I can get my work pushed up and we can move to testing this on test.arcticdata.

**Comment by laurenwalker** [comment]
Thanks for finding those, Bryce!

**Comment by laurenwalker** [comment]
BTW I have a config file for test.arcticdata.io here: https://github.nceas.ucsb.edu/walker/metacatui-config

Let me know if you'd like me to update test.arcticdata.io

**Comment by amoeba** [comment]
test.arcticdata.io has been upgraded to `feature-eml220-support` which has been recently rebased off of `dev-2.13`. @laurenwalker I used https://github.nceas.ucsb.edu/walker/metacatui-config and it worked like a charm. Thanks for putting that together.

I've coordinated with Jasmine and notified @jeanetteclark with some details and asked them to let us know if any issues pop up.

**Comment by laurenwalker** [comment]
Great, thank you! Thanks for testing out the upgrade script from metacatui-config; I'm glad it worked well.

**Comment by laurenwalker** [comment]
@amoeba - I checked with the arctic team Friday and they've been able to do some testing with no problems. I think we're ready to merge your feature branch to dev-2.13 so it can be released soon.

**Comment by amoeba** [comment]
Glad to hear that. I'll go ahead and do the merge today.

**Comment by amoeba** [comment]
Merge onto `dev-2.13` done in 793bbc55c818df28825c920b060b3536065840ce. Came out clean.
