### ISSUE TITLE
Missing authors in citation

### ISSUE THREAD

**Issue by charuleka** [NCEAS/metacatui#1044]
When two creators are entered with the same first name and last name, but different organizations, the citation doesn't have both the names.

See
https://data-stage.ess-dive.lbl.gov/view/ess-dive-673951be334c80e-20190807T155749903

**Comment by amoeba** [comment]
I think this is fundamentally caused by the same issue as https://github.com/NCEAS/metacat/issues/1374 and resolved by the same fixes.

**Comment by mbjones** [comment]
This issue arose again today for the Arctic Data Cneter. Bumping to high priority.

**Comment by laurenwalker** [comment]
@mbjones This issue is caused by NCEAS/metacat#1374. I'm pinging @taojing2002 so he is aware it is high priority. It looks like he has it slated for the 2.17.0 release anyway.

**Comment by robyngit** [comment]
Closing as this is a Metacat issue (https://github.com/NCEAS/metacat/issues/1374)
