### ISSUE TITLE
Routes to /edit/portals/new should work

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/metacatui#1050]
We use a temporary project name in the window location when a new project is being created (`new`). We should make sure those URLs always resolve to something useful. Right now if I navigate to /edit/portals/new, I get an infinite spinner (probably due to a JS error). I would expect a new blank editor to render, just like if I went to /edit/portals.

Navigating to a section with the 'new' name should work, too. Maybe we should just remove the section name and navigate to the default section (Settings).

**Comment by mbjones** [comment]
@laurenwalker @robyngit That URL path is not very *RESTful* with "new" in the path.  Generally, a REST path should generalize to either a collection endpoint (e.g., `/portals`), or to an item endpoint (e.g., `/portals/my-portal`).  In both cases, the HTTP operation would then determine the kind of operation requested:

- `GET /portals` to list all portal items in the collection
- `POST /portals` on the collection to create a new item
- `GET /portals/my-portal` to return the portal item listed
- `PUT /portals/my-portal` on an item is used to update the item
- `DELETE /portals/my-portal` to delete an item

Is there a reason we're not following this common design pattern?  Can we try to structure our routes to be more RESTful?  Reopening this issue to simply discuss this and come to some resolution.  Have you discussed the route design with @csjx?

**Comment by laurenwalker** [comment]
@mbjones -

This particular issue is regarding the URL for portals in MetacatUI. We haven't talked about creating a RESTful API for creating, updating, and deleting portals as you describe, since portals are objects in the DataONE network and use the DataONE MN API to GET, POST, PUT, and DELETE.

The `new` is added to the MetacatUI URL automatically when you navigate to `edit/portals` since we add the section name to the URL automatically, and without a portal name, the URL gets tricky to update. For example, if you navigate to Settings section of the portal editor for your `my-portal` portal, your URL path would be: `edit/portals/my-portal/settings`. If you have just created a new portal and haven't given it a label yet, your URL would be `edit/portals/new/Settings`. This particular issue was suggesting that if you navigate directly to `edit/portals/new/Settings`, you should go to a blank portal editor rather than get a 404.

Yes, @csjx has been in these discussions...

**Comment by mbjones** [comment]
@laurenwalker ok, thanks. Feel free to close again if you and @csjx are in agreement that there is no issue to be addressed here.

**Comment by csjx** [comment]
Yup, I agree with @laurenwalker  - we're not really designing a RESTful API set of endpoints since these are all client-side routes that we're trying to keep track of in the browser history.  Since we also don't have the HTTP verbs to discern between functions on the same path (like `GET /portals/:id` vs `POST /portals/:id`, which would fetch or create the portal respectively, I think using the `edit` prefix is pretty standard for client-side routes (or at least Google uses it). The same pattern applies with the `new` suffix when you don't have a generated `id` yet. I'll close this since it looks like @robyngit has already fixed the issue.
