### ISSUE TITLE
Navigating to a nonexistent project name doesn't work

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/metacatui#1051]
If I navigate to /edit/portals/test (test does not exist) - I get an infinite spinner. Going to the ProjectView ala /portals/test works, because it displays a "not found" message.

**Comment by robyngit** [comment]
The first step to fix this is to make sure that `models/DataONEObject.checkAuthority()` is called for non-existent projects (relates to issue https://github.com/NCEAS/metacatui/issues/983). When the project doesn't exist, `checkAuthority()` will set "notFound" to `true` in the project model, which we can then use to trigger the view to display a "not found" message.

**Comment by rushirajnenuji** [comment]
Update: we do call the `checkAuthority()` function for a label that doesn't exist. It looks to me that we just need to listen for the `notFound` trigger and a way to handle it. (may be add a `showNotFound` function.)

**Comment by rushirajnenuji** [comment]
Added a `showNotFound` function to the projectEditorView if the project with the given `label` does not exist.
