### ISSUE TITLE
Feedback from Jo Anna (intern)

### ISSUE THREAD

**Issue by amoeba** [NCEAS/metacatui#106]
I'm reposting this from Slack in here:

> - The save button is confusing. I think of 'save' to mean 'save as', not as 'submit'._

This is done.

> - Are coordinates in decimal degrees or dms?_
> - I like that I can add multiple locations_
> - "Not all your changes could be saved" - why?_
> - It is taking a very long time for the submission to fully go through (several minutes now)._

<img width="551" alt="screen shot 2017-05-01 at 4 29 53 pm" src="https://cloud.githubusercontent.com/assets/563/25633591/242cad3e-2f24-11e7-807a-5ab286ab5717.png">

**Comment by csjx** [comment]
So given the XML validation error, it looks like we need to validate our `N/S/E/W` bounding coordinates before sending the EML. Note that the schema restricts lons from `-180 to 180` and lats from `-90 to 90`.

**Comment by laurenwalker** [comment]
Created this ticket for the coordinate validation issue: https://github.com/NCEAS/metacatui/issues/115
