### ISSUE TITLE
Don't add portal section name to the URL until one is clicked

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/metacatui#1066]
In the portal view and portal editor view, we shouldn't automatically add the section name to the URL until the user has clicked on another section. This keeps the URL in the window as the direct portal URL (e.g. https://site.com/portals/my-portal) unless there is further navigation.

**Comment by rushirajnenuji** [comment]
Works for non-click events.

- TestCase 1: /portal/label
    - Previous behaviors: /portal/label/defaultSection
    - Current behavior: navigates to /portal/label

- TestCase 2: /portal/SID
    - Previous behaviors: /portal/SID/defaultSection
    - Current behavior: navigates to /portal/label

- TestCase 3: edit/portal/label
    - Previous behaviors: edit/portal/label/defaultSection
    - Current behavior: navigates to edit/portal/label

- TestCase 4: edit/portal/SID
    - Previous behaviors: edit/portal/SID/defaultSection
    - Current behavior: navigates to edit/portal/label

**Comment by laurenwalker** [comment]
Thanks Rushi, the section name is no longer being automatically added to the URL for me. There is an issue with navigating to the portal editor by sid, but I'll comment on that ticket
