### ISSUE TITLE
EditorView submit button says "Submit Dataset"

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/metacatui#1072]
The button text should be configurable in the inherited editor views
![Screen Shot 2019-08-23 at 6.52.19 PM.png](https://images.zenhubusercontent.com/5d152e12c27d0c306f021863/51a48603-ddb4-483b-9700-c3a7281fd126)

**Comment by robyngit** [comment]
I didn't see this bug. On my end, the submit button text said "save" for the portal editor, and "Submit Dataset" for the metadata editor. Each of these editors is using a different template (`portalEditor.html` and `editor.html` respectively), and the button text was set directly in these templates. I made the button text configurable for each of the templates, just in case we ever want to change this. @laurenwalker, is this still a bug on your end?

**Comment by laurenwalker** [comment]
It only seems to happen after I save once. See screencap:

![button.gif](https://images.zenhubusercontent.com/5d152e12c27d0c306f021863/f0e19d1a-138d-45c1-b48c-fa4f37734370)
