### ISSUE TITLE
When the collection is empty, the Metrics tab is blank

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/metacatui#1075]
The metrics tab doesn't render until there are search results. We should display a message or some kind of placeholder when the collection is empty.

![Screen Shot 2019-08-29 at 10.09.14 AM.png](https://images.zenhubusercontent.com/5d152e12c27d0c306f021863/05041907-efaa-483a-9c6a-0968573742be)

**Comment by robyngit** [comment]
We also need to improve the metrics page view in the portal editor by adding a 'preview' of what the user will see and by making the info text more positive (e.g. "you're all set!")
