### ISSUE TITLE
Add icon in search results indicating whether a result has annotations

### ISSUE THREAD

**Issue by amoeba** [NCEAS/metacatui#1078]
The search results currently show some nice icons that provide detail about each result:

<img width="706" alt="Screen Shot 2019-08-30 at 1 12 03 PM" src="https://user-images.githubusercontent.com/563/64051523-d806d400-cb27-11e9-9353-29feed85cfc0.png">

Steven made a good point in Slack that we could add an icon indicating the result has at least one annotation, like so:

<img width="579" alt="Screen Shot 2019-08-30 at 1 11 08 PM" src="https://user-images.githubusercontent.com/563/64051549-e94fe080-cb27-11e9-9acd-e955a367b693.png">

I used the same icon we use in the landing pages so the connection is as clear as possible. Any thoughts, objections?

**Comment by mbjones** [comment]
No major objections, but I don't see much benefit either.  The bottom row of icons is already a bit confusing with their diversity.

**Comment by laurenwalker** [comment]
I agree with Matt. Let's use a config option in the AppModel to turn that icon on/off.

**Comment by amoeba** [comment]
Thanks for the feedback. Maybe, since I'm not seeing a strong interest, it'd be better to not add it at all. Do you have a preference @laurenwalker 	?

**Comment by mpsaloha** [comment]
Some indication of whether an object is semantically enriched (or not)
might be valuable.  For example, it might be useful when triaging a large
result-set.  It also "advertises" an advanced feature of our repo.  But not
critical at this point.  It could be something, however, we could point out
at a demo, etc.

cheers,
Mark

**Comment by laurenwalker** [comment]
I don't have a strong preference either way, so let's go ahead and add it. Mark makes a good point that it might be a nice advertisement for a new feature.

**Comment by amoeba** [comment]
All done, for all themes. Hidden behind a feature flag on the AppModel `showAnnotationIndicator` which defaults to `false` in all themes. Will leave this issue open so it auto-closes on merge.

**Comment by laurenwalker** [comment]
THanks Bryce. I'm going to close it since it helps me with managing the work that's done for each milestone/release
