### ISSUE TITLE
Make the portal label editable only after clicking a "change" button

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/metacatui#1083]
Once a portal has been created, add a 'Change URL" button that prevents the user from editing the label until it is clicked.
The URL/label should be freely editable until the portal has been initially saved.

**Comment by rushirajnenuji** [comment]
Hi Lauren - Do we need an outlined button similar to the mockups?

Right now we have a simple button that makes the section editable.
![Screen Shot 2019-09-20 at 11 51 38 AM](https://user-images.githubusercontent.com/19696935/65351839-ef246900-db9d-11e9-947b-6fdd2f46c7f2.png)
![Screen Shot 2019-09-20 at 11 51 48 AM](https://user-images.githubusercontent.com/19696935/65351866-01060c00-db9e-11e9-9a33-a89e3d5529f6.png)

**Comment by laurenwalker** [comment]
You can leave the button as-is for now and we can style it later during the last MVP phase. Thanks!
