### ISSUE TITLE
Feedback from Sharis

### ISSUE THREAD

**Issue by amoeba** [NCEAS/metacatui#109]
Jesse sent this over Slack and I've re-formatted and cleaned it up:

- Simple to upload multiple files at a time.
- Something that could possibly be helpful since I feel like we see a lot of too short abstracts:
Including in parenthesis next to where you fill in the abstract this portion from the checklist,
“Abstract [Should provide an overview of the scientific context/project, how this data set fits into a larger project, a synopsis of the experimental or sampling design and a summary of the data contents]”
- I don’t understand the “Keyword Thesaurus” option
- Also don’t understand “Alternate identifier”. My guess is if you have the data published somewhere else so you give the DOI of that. Maybe I just don’t understand because I am not a scientist
- I like the bubbles that pop up when you hover over the usage rights options, I think that could be helpful for my previous confusions.
- Can’t tell if the locations entry still will create a box or if it is only a point.

- I hit save and it gave me an error that “Not all of your changes could be saved.”

```
<?xml version="1.0" encoding="UTF-8"?><error detailCode="1190" errorCode="500" name="ServiceFailure">
    <description>Error inserting or updating document: urn:uuid:db97419b-c5ef-4c4a-a032-fd634f80f1d6 since &lt;?xml version="1.0"?&gt;&lt;error&gt;cvc-complex-type.2.4.b: The content of element 'associatedParty' is not complete. One of '{individualName, organizationName, positionName, address, phone, electronicMailAddress, onlineUrl, userId, role}' is expected.&lt;/error&gt;</description>
</error>
```

- I closed the red error box and the saving icon has been swirling still for a long time
- I tried resubmitting because I thought maybe it was having trouble since I made up a fake funding number and alternate identifier. So I re entered everything and just left those boxes blank and I still got the same error.”

**Comment by laurenwalker** [comment]
THis was feedback during beta testing of the new editor. Some were old bugs and some feedback already has its own issue. Closing
