### ISSUE TITLE
serialize EML 2.2.0 from the editor

### ISSUE THREAD

**Issue by mbjones** [NCEAS/metacatui#1097]
Issue #694 is to generally add feature support for EML 2.2.0.  However, the ability to serialize and upload EML 2.2.0 to Metacat should be a much simpler start. So, this issue is to bascially switch the editor to use EML 2.2.0 before all of the features have been implemented.  This mainly involves 1) Changing the namespace of docs from 2.1.1 to 2.2.0, and 2) add any detection code to determine if features used in a doc can be edited (like annotations) and deal appropriately if they are detected.

**Comment by yvanlebras** [comment]
Hi @mbjones ,
Just a message as we are testing the use of metacat 2.7.0 and find that "edit" button is grey due to this metacat editor incompatibility if I'm not wrong

**Comment by laurenwalker** [comment]
@yvanlebras - EML 2.2.0 documents cannot be edited in MetacatUI yet, so the Edit button will be disabled/greyed-out. This Github ticket is for adding that capability to MetacatUI in the near future. We're still figuring out exactly which release it will be included in (likely 2.9.0).

**Comment by laurenwalker** [comment]
EML versions before 2.1.1 also need to be automatically converted to EML 2.2.0. That should be complicated at/around the same time as this issue, but should have its own issue. I'll create one.

**Comment by amoeba** [comment]
Implemented in https://github.com/NCEAS/metacatui/tree/feature-eml220-support and being tested right now on test.arcticdata.io.

**Comment by amoeba** [comment]
Merged onto `dev-2.13` in 793bbc55c818df28825c920b060b3536065840ce.
