### ISSUE TITLE
Decide on a default section name other than "new page"

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/metacatui#1099]
The team seemed to agree on "Untitled" or "untitled page"

**Comment by robyngit** [comment]
Whatever we decide, this is easily configurable here: https://github.com/NCEAS/metacatui/blob/c5e335af2f32649c25ae46a744522c86a712c843/src/js/models/portals/PortalModel.js#L1223

**Comment by robyngit** [comment]
Changed the default name to "Untitled" for now.
