### ISSUE TITLE
User can lose all their changes if they miss the drop target when adding files

### ISSUE THREAD

**Issue by amoeba** [NCEAS/metacatui#110]
I unintentionally did this:

![cast](https://cloud.githubusercontent.com/assets/563/25819508/a6169b24-33da-11e7-98e3-9fefd07e468b.gif)

You'll see I dropped my file I meant to upload outside the drop target and Chrome's default behavior 
 (and AFAIK many other browsers') is to view the file in the browser. This circumvents the `onbeforeunload` handler. 

Google + StackOverflow tell me that we can override two more events, `dragover` and `drop`, to prevent and/or change the behavior:

```js
window.addEventListener("dragover", function(e){
  e = e || event;
  e.preventDefault();
  }, false);
window.addEventListener("drop", function(e){
  e = e || event;
  e.preventDefault();
}, false);
```

I've tested this and it does work and it does not prevent uploading files using the current drop target. 

@csjx @laurenwalker shall make this change? Do we want another behavior other than doing nothing?

**Comment by csjx** [comment]
Hey Bryce @amoeba - Yes, I think we need to override the default from the browser.  This is related to #39.  Your implementation looks good - I'm thinking this would go into `EditorView.initialize()`.  Is that what you're thinking? While this basically sets up a no-op listener, we might think about having this override actually handle the drop by grabbing the UI component associated with the `MetacatUI.rootDataPackage` and add the files to it.  Might be a good catch all.

**Comment by amoeba** [comment]
Wow, how my brain aggressively removes memories. Good catch on #39. I lean toward having the entire window take the uploaded file, ala Slack, because I think it makes good UX sense because the only possible action the use would want would be to add the file once they've entered the browser window. If others agree, I guess I could fix this right now and we could work on that at a later date.
