### ISSUE TITLE
Open dataset links from portal in new tab

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/metacatui#1107]

**Comment by robyngit** [comment]
Dataset links from the portal editor now open in new tabs. Should we do the same for dataset links from the portal?

**Comment by laurenwalker** [comment]
No, I think links from the portal page can stay in the same tab. We may have to implement a way to save the search filters if someone clicks a dataset link and then comes back. The regular data catalog does this, so we could reuse that functionality.
