### ISSUE TITLE
authoriativeMemberNode is null when AppModel.nodeId is null

### ISSUE THREAD

**Issue by amoeba** [NCEAS/metacatui#111]
I encouraged @csjx to change this from being hard-coded to `null` but after doing that, the `authoritativeMemberNode` property on System Metadata the Editor generates is `null` instead of a valid node ID. I looked around the code and couldn't make heads or tails of a quick fix so for my current testing I've hard-coded the value back.

Could someone else take a look?

**Comment by laurenwalker** [comment]
When this happens, what is your baseUrl and cnBaseUrl set to?

**Comment by amoeba** [comment]
baseURL is dev.nceas and cnBaseUrl is cn-stage.test

**Comment by laurenwalker** [comment]
It is working as expected, then. You need to make sure you are pointing your app towards the CN environment that your MN is in. Otherwise, the app can't figure out the authMN. That is why Chris had his authMN hard-coded in his local AppModel - so he could use mixed environments.

**Comment by amoeba** [comment]
Ah, thanks. I'll make a mental note somewhere to remember that.
