### ISSUE TITLE
Show aggregated metadata quality scores in portals

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/metacatui#1116]
This issue may need to get broken down into actionable steps. I'll leave that to @gothub

**Comment by laurenwalker** [comment]
We need to display a message that states the quality charts might include scores about private datasets. See https://github.com/NCEAS/metadig-engine/issues/227

**Comment by gothub** [comment]
Here is a first pass for the text:
```
Metadata Quality

This graph shows the quality scores for all metadata viewable by this portal, based on
the DataONE FAIR Quality Suite. The FAIR suite evaluates metadata based on these
criteria: Finable, Accessible, Interoperable, Reusable.
```

**Comment by gothub** [comment]
This work is done, except for IE 11 testing as described in https://github.com/NCEAS/metacatui/issues/1200.

Initial commit e053b1705567b6d3362483de7eb6fc009d7bf462 in `feature-portals-agu-demo`, a branch of `dev-2.8`.
