### ISSUE TITLE
Add ability to remove freeform page image

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/metacatui#1122]
Right now, if you upload an image to a freeform section, there is no way to remove it. You can only replace it. Let's add a remove button, perhaps in the upper-right corner of the image.

**Comment by robyngit** [comment]
As of [this commit](https://github.com/NCEAS/metacatui/commit/6190e8738de617b483b2eeccc5aa42f97f1de9f7), there should be a remove button that shows in the lower right hand corner of the freeform section image on hover. Clicking this button should remove the image. Maybe it's too small/subtle, or is it just not showing for you at all @laurenwalker?
