### ISSUE TITLE
Create mockups for re-design of EditCollectionView

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/metacatui#1133]
We decided during our last meeting that we want to redesign the EditCollectionView, since it is not intuitive right now that the current search in the DataCatalogView is the collection search.

Let's design one or more quick mockups for a different layout. These don't need to be pixel perfect, just communicate the general idea

**Comment by robyngit** [comment]
The current version of the mockup can be view [here](https://invis.io/3WUGZ3Y82MZ).

**Comment by robyngit** [comment]
Version two of the mockup is now available [here](https://invis.io/6ZUIHUG3G4J). This mockup is simplified for the initial release and excludes the "add datasets manually" option. It includes two options for the "Edit saved search" view - one horizontal and one vertical.

**Comment by robyngit** [comment]
The [final version of the mockup is here](https://invis.io/DMUITLP2EZW). We reviewed this version today and decided to move forward with it as shown, except that the "saved search" part will appear as it does in the current version of the editor (at least for the beta release).
