### ISSUE TITLE
Reject image uploads that are invalid sizes

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/metacatui#1140]
Use dropzone library features to help with image upload sizes, rejection, etc.

For freeform pages, we want to reject images below a certain file size or image size (eg. at least 600px wide and 120px tall - those numbers might need some testing)

For logos, we want to reject images that are too large. They should be no bigger than 300px wide or ~16KB

**Comment by robyngit** [comment]
This could use some testing to determine the optimal values for `minWidth`, `minHeight`, `maxWidth`, and `maxHeight` for the three instances of the `imageEditView` (portal logo, partner logos, and markdown section image).

**Comment by laurenwalker** [comment]
I've tried out the image uploader and the min and max requirements look good to me. Do you need any further review or testing on this, @robyngit ?

**Comment by robyngit** [comment]
Thanks for testing! I am going to make the max sizes a little larger for logos, otherwise wider logo images (e.g. the SASAP logo) are reduced to a size smaller than their display size. Otherwise, I think this issue is closed.
