### ISSUE TITLE
Package w/o Spatial Coverage fails to store Temporal Coverage

### ISSUE THREAD

**Issue by FiannaOBrien** [NCEAS/metacatui#1145]
User tried to submit a package with start & end dates but without spatial data, but the submitted dataset did not contain temporal data.

When replicating the issue, I was only able to submit temporal coverage in conjunction with spatial coverage. Metadata submissions with only start & end date and no location did not store or display dates in landing page.

**Comment by FiannaOBrien** [comment]
This is important for datasets performed on a global scale or in laboratory conditions where the exact location isn't relevant.

**Comment by mbjones** [comment]
Did it submit but not save the temporal coverage, or did you get an error saying that you were missing required fields?  Either way, I agree with you that it should be possible.  EML doesn't require them to be paired.

**Comment by FiannaOBrien** [comment]
It submitted with no error message but didn't appear in the EML.

**Comment by FiannaOBrien** [comment]
This is a critical issue for all of our global dataset users. Currently, there's no way for them to submit their data the way they want. Relates closely to #423 & #700.

**Comment by laurenwalker** [comment]
I'll get this fixed in a patch release so it can get released ASAP
