### ISSUE TITLE
Issues with filtering datasets in the PortalView when there are `id` filters

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/metacatui#1168]
With the new way we are structuring collection queries, with the `id` filters "OR"ed to the end, the filters in the PortalView can never fully filter down the datasets. The datasets with the matching ids will always be included.
When a user is filtering the collection in the FIlterGroupsView, the query should be structured differently.

**Comment by helbashandy** [comment]
Hi @laurenwalken - Is this regarding the identifier filter not working or is that a separate issue?

**Comment by laurenwalker** [comment]
This particular issue is about the identifier filter in the PortalView only. The identifier filter in the regular data search page (e.g. /data) should be working correctly.

**Comment by helbashandy** [comment]
By PortalView only do you mean the portal editor as well in the data tab of a portal?

**Comment by laurenwalker** [comment]
Only the data tab of the portal, when viewing it outside of the editor. I'm not aware of any issues with the identifier filter in the PortalEditorView.
