### ISSUE TITLE
updating a dataset with a new version of a file results in two otherEntity entries

### ISSUE THREAD

**Issue by jeanetteclark** [NCEAS/metacatui#1172]
I reproduced this in response to this user feedback, but I have been seeing this behavior for a while now.

> I seem to be
encountering some glitches- Specifically, values showing up in the Data
Table/Other Entity sections that don't show up when I am in the editing
mode. It seems like some of these are referring to old versions, whereby I
was writing up metadata, realized my file had a mistake, and uploaded a new
file version. 

Steps to reproduce:

- Create a metadata record
- Add a file
- Submit
- Edit the record
- Replace the file with a new version that has the same file name
- Submit

The result is a record that includes two `otherEntities`, one for each version of the file, when I think there should only be one.

Here is the result of my reproduction of the error: https://dev.nceas.ucsb.edu/view/urn:uuid:aebcd8ad-d7b0-4b7d-b587-c0825cfdf60e

**Comment by laurenwalker** [comment]
These three related bugs: #1172, #1217, #1095 are all now fixed with the same commit referenced above.  Please let me know if you continue to see this behavior, since it's possible more than one set of steps cause this bug (but I was only able to find one, after LOTS of debugging).
