### ISSUE TITLE
Add citation to the top of the quality report page

### ISSUE THREAD

**Issue by JEDamerow** [NCEAS/metacatui#1180]
Usability Problem: Quality reports currently open in same tab as the dataset view, and must use back arrow to go back to dataset metadata. There is also no indication of what dataset the quality report is referring to within the quality report view. 

Proposed Solution: Quality report should automatically open in a new tab, and should contain the dataset citation at the top of the page.

**Comment by gothub** [comment]
@laurenwalker what are your thoughts on this?

**Comment by laurenwalker** [comment]
I agree that the dataset citation should be at the top of the page. It used to be displayed there. I'm not sure how that got removed. That might have happened when we started using the pre-generated reports.

I don't think the quality report should open in a new tab. We could display breadcrumbs like we do on the MetadataView.

**Comment by laurenwalker** [comment]
Oh, actually I just looked and there are already bookmarks. So there is another way to navigate back besides the browser back button.

**Comment by JEDamerow** [comment]
Hi @laurenwalker , I don't see any change to the quality report view, and still find it cumbersome to navigate back and forth between the quality report and the dataset metadata.  Especially since there is no citation for dataset that quality report is referring to on that page.  Am I missing something?

**Comment by laurenwalker** [comment]
I forgot that this GH issue included the request to show the dataset citation at the top of the page. I'll reopen that so we can get that worked in. Thanks for the heads up.
