### ISSUE TITLE
Download counts show some events from DataONE IPs and Subjects

### ISSUE THREAD

**Issue by csjx** [NCEAS/metacatui#1183]
Our metrics query against `logsolr` uses the `inPartialRobotsList:false` parameter, but not the `inFullRobotsList:false` parameter, which means that some events with CN `Subject` strings are being counted as reported downloads.  This is causing spikes in the download metrics when the replication auditor audits objects, as seen in the numbers for ESSDIVE in July and November 2019:

<img width="1041" alt="downloads" src="https://user-images.githubusercontent.com/1437565/69278249-2f549780-0b9f-11ea-838e-d31a13d3f3f0.png">
See the results from these two queries

```
https://cn.dataone.org/cn/v2/query/logsolr/?q=+nodeId:urn\%3Anode\%3AESS_DIVE+event:read+formatType:(METADATA%20OR%20DATA)+inPartialRobotList:false+isRepeatVisit:false&facet=true&facet.limit=-1&facet.mincount=1&facet.field=formatType&facet.range=dateLogged&facet.range.start=2012-07-01T00:00:00Z&facet.range.end=2019-11-03T06:00:00.000Z&facet.range.gap=%2B1MONTH&wt=json&rows=0
```
and
```
https://cn.dataone.org/cn/v2/query/logsolr/?q=+nodeId:urn\%3Anode\%3AESS_DIVE+event:read+formatType:(METADATA%20OR%20DATA)+inPartialRobotList:false+inFullRobotsList:false+isRepeatVisit:false&facet=true&facet.limit=-1&facet.mincount=1&facet.field=formatType&facet.range=dateLogged&facet.range.start=2012-07-01T00:00:00Z&facet.range.end=2019-11-03T06:00:00.000Z&facet.range.gap=%2B1MONTH&wt=json&rows=0
```
@gothub @laurenwalker : Is there a reason we are not using `inFullRobotsList`? I'm not familiar with the differences with full and partial.  Are those defined in the documentation somewhere?

**Comment by laurenwalker** [comment]
These download charts are getting replaced by the new metrics charts that @rushirajnenuji has made. We are going to update the metrics views on the portals and the MN profiles. 

I'm not sure about the User Profiles, since we may want to switch those to paid portals. I need some clarification on what we plan to do with user and user group profiles.

**Comment by csjx** [comment]
Yes, makes sense.  @rushirajnenuji - Does the `metrics-service` use the full or partial robots list when filtering out IPs and subjects?

**Comment by rushirajnenuji** [comment]
Hey @csjx  - we are not directly using either of the lists. Based on Counter recommendation, we have a separate list of IPs and robot agents (which I think is similar to both `full` or `partial` robot lists). 

> If the requesting IP is a DataONE CN or MN, then the tags `dataone_ip` and `ignore_ip` are set.
> 
> if the requesting IP is a known robot IP address, then the tags `robot_ip` and `ignore_ip` are set.
> 
> If the UserAgent of the requesting client matches an entry from the "Machines" list, then the record is tagged with `machine_ua`.
> 
> If the UserAgent of the requesting client matches an entry from the "Robots" list, then the record is tagged with `robot_ua`.

Right now, we're only filtering user agents and robot IPs. But it should be very easy to filter out DataONE IPs as well. Also - the DataONE IPs is a simple text file - so we can include additional IPs  if and when detected.

**Comment by mbjones** [comment]
@rushirajnenuji I think you completed this long ago. Could you update the ticket and close if it is completed, please?

**Comment by rushirajnenuji** [comment]
Update: Chris and I wrote up a script to add a new tag `d1_admin_subject` for all new and existing events in the ES `eventlog-*` index. We started filtering out events with `d1_admin_subject` from metrics aggregations starting  [v0.4.2](https://github.com/DataONEorg/metrics-service/releases/tag/v0.4.2) release. Closing this issue as completed.
