### ISSUE TITLE
Citation modal window is blank when count is 0

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/metacatui#1185]
We previously had a message displayed in the modal when there were no citations. Something must have broken in that flow, so let's fix it to get the message to display again.

Related: The modal window opens too far right in the window. It should be centered.

<img width="1213" alt="Screen Shot 2019-11-21 at 11 20 30 AM" src="https://user-images.githubusercontent.com/6643222/69360975-1f958b80-0c51-11ea-8d3b-5f02ebd234ce.png">

**Comment by rushirajnenuji** [comment]
Hi @laurenwalker  - I can fix this while I'm working on getting the portal metrics on the UI.

**Comment by laurenwalker** [comment]
Thanks Rushi. This is lower priority, so feel free to save it for the last step

**Comment by rushirajnenuji** [comment]
This has already been completed as part of #1214 and #1115. Closing this issue.
