### ISSUE TITLE
Michener on metacatui/about/sharing-your-data page

### ISSUE THREAD

**Issue by taojing2002** [NCEAS/metacatui#1191]
Hi NCEAS,

Looking at our metacat test server pages, I just see that there is a typo in the metacatui/about/sharing-your-datapage, as Michener is spelled Michner here.

Whishing you a good day,

Yvan

**Comment by taojing2002** [comment]
This ticket is transferred from a ticket on Metacat
https://github.com/NCEAS/metacat/issues/1411

**Comment by yvanlebras** [comment]
Thank you for moving the issue at the good place!
