### ISSUE TITLE
Allowing using several times the same entity for prov

### ISSUE THREAD

**Issue by yvanlebras** [NCEAS/metacatui#1192]
Hi amazing NCEAS team,

Testing deploying our own metacat, I just saw this amazing functionlity allowing metacatui document creator to eidt it from the web and notably adding provenance information. Unfortunately, clicking on "Add a program that used XXX" to select a R script entity using an entity Y make impossible to specify that this R script entity is also using entity Z. Not sure this is a normal behaviour and not sure that this is completely or in part related to this existing issue https://github.com/NCEAS/metacatui/issues/449 

Best,

Yvan

**Comment by laurenwalker** [comment]
If my understanding is correct, you want to specify that an R script `used` two objects? If so, that is possible by finding the entity details for the R script and adding the two input objects on the left side of the chart. E.g.:

<img width="1086" alt="Screen Shot 2019-11-27 at 1 46 57 PM" src="https://user-images.githubusercontent.com/6643222/69754816-6a654680-111c-11ea-896b-6c23bcac69f9.png">

**Comment by yvanlebras** [comment]
Thank you for your rapid feedback. Effectively, this works ! In fact I was trying to make the same but specifying for each datatable entity the same "script entity" output but this was not possible as selecting a script entity for one datatable make impossible to select the same script enityt for another datatable... But making as you mentionned is ok! Thank you very much
