### ISSUE TITLE
Remove buttons aren't working right on parties

### ISSUE THREAD

**Issue by amoeba** [NCEAS/metacatui#120]
Two issues cropping up:

- Remove buttons aren't placed on each party member as needed
- Remove button doesn't do anything

**Comment by amoeba** [comment]
At least partially caused by

```
Uncaught TypeError: Cannot read property 'splice' of undefined
    at n.handleRemove (EML211View.js?v=2.0.0:1802)
    at HTMLDivElement.dispatch (jquery.js?v=2.0.0:3)
    at HTMLDivElement.v.handle (jquery.js?v=2.0.0:3)
```

**Comment by amoeba** [comment]
I think I found the culprit in 841f4cfc430621d11a3d0122bc47d3028d183101. Now it's causing a second bug where I'm being added as a `creator` even when there is already a `creator` set. I'll ned to squash that one before I can verify this and close.

**Comment by laurenwalker** [comment]
Working on this now

**Comment by laurenwalker** [comment]
Related commit: be8f5ad9af6524984d511442cbe3c5d60f484da7

**Comment by amoeba** [comment]
I'll let you take this one and #231 if you're already rolling away on it.

**Comment by laurenwalker** [comment]
@amoeba I think this is fixed. I'm not experiencing any issues with the remove buttons now, are you?
