### ISSUE TITLE
Tooltip is not showing up correctly.

### ISSUE THREAD

**Issue by helbashandy** [NCEAS/metacatui#1206]
There's a minor issue found while editing a portal, where the hover-over tooltip for "Datasets added manually" search filter tile is cut off by the data list. See below.
<img width="461" alt="Screen Shot 2019-12-05 at 4 33 20 PM" src="https://user-images.githubusercontent.com/47407500/70300538-9fbd0480-17ac-11ea-9450-7dde996bc33f.png">

I tested it on both ESS-DIVE and KNB.

**Comment by robyngit** [comment]
Since we're using the query builder in the portal builder data page, and there is no side bar, this is no longer an issue
