### ISSUE TITLE
Add config param to enable/disable metadata quality assessment

### ISSUE THREAD

**Issue by gothub** [NCEAS/metacatui#1209]
Add a config parameter to all themes that can be used to disable/enable portal metadata quality assessment tab in the portal editor. This param should also prevent calling of `getMdqScores()` in Stats.js

In addition, a config param should be added for the dataset quality assessment to explicitly enable/disable dataset calculation and display of metadata quality assessment. Currently the param `mdqUrl` can be set to `""` to disable. This is a hack and should be replaced with a parameter named something like `enableDatasetQualityMetrics`.

**Comment by laurenwalker** [comment]
> Add a config parameter to all themes that can be used to disable/enable portal metadata quality assessment tab in the portal editor. This param should also prevent calling of getMdqScores() in Stats.js

This config was added in 25e45f859c6fb869826aaed1095816b79723b6ad. The config is called `showMetadataQualityInPortals`. So we only need to add a config for the latter use case -- turning off mdq features EVERYWHERE in the app.

Thanks Peter

**Comment by laurenwalker** [comment]
Moving this to the icebox since we decided it's a nice-to-have but not necessary
