### ISSUE TITLE
Remove buttons don't trigger appearance of Save dialog

### ISSUE THREAD

**Issue by amoeba** [NCEAS/metacatui#121]

**Comment by amoeba** [comment]
Looks like I'm running into a situation where editing even the title doesn't trigger showing of the Save dialog

**Comment by laurenwalker** [comment]
@amoeba - Is the title the only field that doesn't cause the Submit button to display? It has been working for me well, so it would be helpful to have a concise list of fields that aren't triggering a change.

**Comment by amoeba** [comment]
Ahhh! Lame job on my part filing this Issue. I'll re-verify this one and update.

**Comment by amoeba** [comment]
The Submit button is showing up fine when removing the following:

- title
- a data file
- a person
- a location

Didn't test on others.

**Comment by amoeba** [comment]
Also fine for:

- methods step
- taxa (individual classification and entire root classification)

I feel comfortable saying this is all fixed up. Re-open if anyone can find a case where removal of existing elements *does not* cause the Submit button to show up.
