### ISSUE TITLE
Move Citations to the bottom of the StatsView for empty citations list

### ISSUE THREAD

**Issue by rushirajnenuji** [NCEAS/metacatui#1213]
Move Citations to the bottom of the StatsView for empty citations list

**Comment by rushirajnenuji** [comment]
Additional TODOs for the same scenario:
- [ ] Add more explanation for citations when there are 0 citations (for all metrics displays)

**Comment by rushirajnenuji** [comment]
This issue is complete. The only part remaining is to add some explanation text on the citation list text area explaining when the citations are 0. 
@laurenwalker  @csjx  - could you please help me with the wording of the text.

**Comment by laurenwalker** [comment]
How about:

> We couldn't find any citations for [this dataset/these datasets].

Can we add citations manually? If so, then perhaps we want to provide a way for our users to report a citation - to start, we could just show our email address. That wording could look like:

> To report a citation of this [this dataset/one of these datasets], send the citation information to our support team at [MetacatUI support email]

Thoughts?

**Comment by rushirajnenuji** [comment]
Thanks for the feedback @laurenwalker. 

We still have to figure out a way to report back to DataCite, but we do have a small procedure in place to get the citations into our database and display them on the UI. So, I really like the second option. Thanks again!

**Comment by mbjones** [comment]
Yes, please, let's create a feature issue for letting users report publications that used or cited their data.  This might come in two phases, the first of which is as you say just a linked email to report citations to the data team, and the better phase would be a UI for getting the DOI/biblio info for the pub and then adding that into the citation database and report it to DataCite for DOIs that are maintained in Metacat.

**Comment by laurenwalker** [comment]
Hi Rushi, I just reviewed the changes from this issue. We need to make the font color a bit darker so that our users can actually read the message about reporting citations. I can barely read this message:

![Screen Shot 2020-01-20 at 6.22.39 PM.png](https://images.zenhubusercontent.com/5d152e12c27d0c306f021863/5300bf8d-dcad-45de-a026-59a0d2273b16)

It looks like you also left out the first sentence of the message which I suggested above. I think it's needed in order to fully explain that there are 0:

> We couldn't find any citations for [this dataset/these datasets].

Let's also make the support email an email link.

Thanks!

**Comment by rushirajnenuji** [comment]
Made the changes in the above commit. Updated the empty citation list and added the link. This issue is ready to be closed. 
![Screen Shot 2020-01-23 at 9 33 26 AM](https://user-images.githubusercontent.com/19696935/73008619-c5858380-3dc3-11ea-884c-5b4955623ab0.png)

**Comment by laurenwalker** [comment]
Perfect!
