### ISSUE TITLE
citation metrics view should include links to data set

### ISSUE THREAD

**Issue by mbjones** [NCEAS/metacatui#1214]
The current metrics view for citations shows the list of citations.  When this is on a dataset landing page, it is obvious that the citations are to that particular data set.  But when the citation list is for a collection (like the SASAP portal), there is no indication of which data sets are cited by each citation.  

Please add a link or button that allows users to navigate to the dataset that is cited in the paper.  Also, note that one citation might cite multiple data sets, so this may need to be a list of links or a menu of links, so I'm not sure how it should be displayed.  In addition, if we use a button, it would be nice to present a human readable label for the dataset, rather than an opaque DOI id.  So, here are some options:

- https://doi.org/10.xxxx/11111111
- [Go to Dataset](https://doi.org/10.xxxx/11111111)
- [Cites Dataset](https://doi.org/10.xxxx/11111111)
- [Cites Data: Hydrology data](https://doi.org/10.xxxx/11111111)
- [Cites Data: Smith et al. 2019](https://doi.org/10.xxxx/11111111)

Of these, I think I like the last the best, but it is still unclear what to do if a paper cites multiple data sets.  Thoughts on how to proceed @rushirajnenuji @csjx @laurenwalker @robyngit?

**Comment by laurenwalker** [comment]
This looks good on the portal view. I looked at the citation list on the dataset landing page, and I can see the "Cites Data:" header, but no link to the dataset.

![Screen Shot 2020-01-29 at 5.44.53 PM.png](https://images.zenhubusercontent.com/5d152e12c27d0c306f021863/2aa36d6a-e249-496c-98b1-bff4ee7a58ef)

**Comment by rushirajnenuji** [comment]
Hey @laurenwalker  - just wondering if the links should be removed from the modals of the dataset landing page. (if so - my above commit fixes the issue)

Thoughts?

**Comment by laurenwalker** [comment]
Rushi and I discussed this ticket today and the only thing left to do is add the links to the metrics service response for the user and repository views. It is completed for the portals view only, right now. Rushi is going to create a ticket in the metrics service repo for that task.
