### ISSUE TITLE
Preview doesn't always load markdown on portal editor 

### ISSUE THREAD

**Issue by helbashandy** [NCEAS/metacatui#1215]
To replicate:
1. Click on new portal on knb-dev (or data-dev.ess-dive.lbl.gov) instance. 
2. Click on the + button to add a new section then select freefrom. 
3. Without clicking into the text field of the markdown, click on preview, the markdown preview will not load.

Note that after putting the cursor back to the text field and then clicking preview it works.

**Comment by robyngit** [comment]
I think this bug is fixed with commit https://github.com/NCEAS/metacatui/commit/f2b77779fc0a5935173e2b3763472c923329dfc7
