### ISSUE TITLE
removing a data file does not remove description of file in the metadata

### ISSUE THREAD

**Issue by jeanetteclark** [NCEAS/metacatui#1217]
related to issue #1172, if a user removes a data file from a dataset via metacatUI, the otherEntity for that file is not removed from the metadata record.

came up in this ticket: https://support.nceas.ucsb.edu/rt/Ticket/Display.html?id=19427

**Comment by laurenwalker** [comment]
These three related bugs: #1172, #1217, #1095 are all now fixed with the same commit referenced above.  Please let me know if you continue to see this behavior, since it's possible more than one set of steps cause this bug (but I was only able to find one, after LOTS of debugging).
