### ISSUE TITLE
Configuring dataset added manually checkbox to be removed. 

### ISSUE THREAD

**Issue by helbashandy** [NCEAS/metacatui#1218]
If ESS-DIVE gives access to certain non-technical users to create portals, they might be confused with what would `datasets added manually` checkbox mean. I suggest to add a configuration in the AppModel.js that removes that checkbox in the portals filters.

**Comment by laurenwalker** [comment]
We can easily add that config option. An easy immediate solution may be to just hide that filter via CSS. We also are planning on redesigning that view in the next iteration of the Portal editor since people did find that confusing. So hopefully that redesign will help

**Comment by robyngit** [comment]
Whether the `isPartOf` filter is shown or hidden in the query builder is configurable with the `hideIsPartOfFilter` option in the AppModel, added in [this commit](https://github.com/NCEAS/metacatui/commit/4352d9f7410778b84b1ecbad49b55dee0df7b803)
