### ISSUE TITLE
Indicate to users if their submitted portal/data package is being indexed

### ISSUE THREAD

**Issue by helbashandy** [NCEAS/metacatui#1221]
<img width="1274" alt="Screen Shot 2019-12-17 at 8 04 38 AM" src="https://user-images.githubusercontent.com/47407500/71017817-1068f880-20ac-11ea-8ee2-411b0bf51927.png">

It can be confusing for users to see the portal or package not found error while it's being indexed. It would be nice if we could ask them to wait for a minute to see their portal or package being indexed if they just submitted it. Maybe by showing the wait message only if the indexing queue is not empty.

**Comment by laurenwalker** [comment]
This same feature should be added to the MetadataView

**Comment by laurenwalker** [comment]
Here is what the new message looks like when the portal is not found, but there is an indexing queue:

![Screen Shot 2020-01-28 at 12 47 24 PM](https://user-images.githubusercontent.com/6643222/73294947-61502e80-41cc-11ea-9918-6d4d05500763.png)

Note that we can't verify that the portal object is one of those in the queue, but it is more helpful than "not found" message.
