### ISSUE TITLE
Add code definition table to the attribute section

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/metacatui#124]

**Comment by csjx** [comment]
As we work on this, I have a few comments on usability. Given this current layout:
![domain](https://cloud.githubusercontent.com/assets/1437565/26129566/ee6e2fe4-3a4d-11e7-8d0e-2d3cc6b19cff.png)
I think we can make it more approachable with less EML-specific jargon.  I think `Domain Type` could be changed to `Possible Values`, `Enumerated Domain` could be `Code List`, and `Text Domain` could be divided into two radio buttons: `Text Pattern` and `Free Text`, potentially with `Free Text` being the default choice.  This would map to a `pattern` of `*`, whereas choosing `Text Pattern` would show a table with placeholders like:

Definition                                  | Pattern                                | Source
------------------------------|---------------------------|--------
Add a definition (required)      | Add a pattern (optional)     | Add a source (optional)

And if they choose `Code List`, we'd have a similar table with repeatable rows. Bottonm line is to avoid the tech jargon.

**Comment by laurenwalker** [comment]
Yes, thanks for that Chris. I've been wanting to get some better wording in there, so let's continue to revise as we go.
