### ISSUE TITLE
Change wording of message when there are 0 downloads/views

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/metacatui#1250]
![Screen Shot 2020-01-20 at 6.25.06 PM.png](https://images.zenhubusercontent.com/5d152e12c27d0c306f021863/eec97ceb-495f-4141-9b37-77077bc8be03)

Right now the message says, "This portal has no views to display". I think that's a bit vague and uses our DataONE lingo (i.e. so are there views, but they're just not displayed? And what's a portal?)

Let's change the wording to:

"This dataset/These datasets have not been viewed/downloaded yet."

**Comment by rushirajnenuji** [comment]
Fixed this in the above commit.
Updated message for 0 download / views
![Screen Shot 2020-01-23 at 9 42 28 AM](https://user-images.githubusercontent.com/19696935/73009129-c965d580-3dc4-11ea-9a77-eb0c8283139f.png)

**Comment by laurenwalker** [comment]
Looks great!
