### ISSUE TITLE
Links not working on feature-portals-agu-demo branch

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/metacatui#1251]
I'm having this issue only on the feature-portals-agu-demo branch. To reproduce:

- Go to a portals view, such as /portals/sasap
- Click on the Data tab
- Click on the link to the first dataset listed
- Bug: The page URL changes in the browser, but the page doesn't actually navigate to the MetadataView until after a significant delay.

I've never seen this before, so I'm not sure what is causing it, but there must be some change from either the recent metrics or metadata quality work that has caused this issue, since everything works fine on the dev-2.9 branch.

**Comment by rushirajnenuji** [comment]
Interesting bug - took a while to figure out. Since path Alias was already defined - requireJS was not importing MetricsChartView properly via the full path.

Found a relevant issue: https://github.com/requirejs/requirejs/issues/1630

This is now fixed and up for review.
