### ISSUE TITLE
adding one data file generates two otherEntities

### ISSUE THREAD

**Issue by jeanetteclark** [NCEAS/metacatui#1253]
Adding a data file on test.arcticdata.io results in two metadata entities for that file, one with attribute information and another with the download link. There should only be one entity.

steps to reproduce:

start a submission with one file
add attributes to that file
submit dataset

observe two entities. Example: https://test.arcticdata.io/view/urn:uuid:c866f36d-015f-4663-bc3d-f1367428664c

**Comment by laurenwalker** [comment]
I believe this issue was fixed with the other EML entity issues in to-be-released 2.9.0. (The MetacatUI version on test.arcticdata is 2.8.3). I was able to reproduce the issue on the 2.8.3 tag but not on the current dev-2.9 branch.
