### ISSUE TITLE
Ensure that quality metrics display in portals for member nodes

### ISSUE THREAD

**Issue by gothub** [NCEAS/metacatui#1265]
The member node profile view is being ported to the portal metrics tab. Currently the quality metrics are dependent on:
- a portal entry in Solr that is used by the offline quality metrics chart facility
- a collection id that is used in Stats.js (model) that is the key (with quality suite) to load the quality chart that is displayed in the portal view.

If these two items are not available in the changes used to migrate member node portals to the portals metrics tab, then updates need to be made so that quality metrics can be pre-generated, retrieved and display.

**Comment by laurenwalker** [comment]
Hi @gothub - I see that you assigned this to 2.9.0, but I was under the impression from our discussion Monday that we are not going to implement this for 2.9.0. The MN profiles will just have the same charts they do now, plus the new aggregated metrics charts. Quality charts will be on portals only, for now.
