### ISSUE TITLE
Citations in /profile loads forever

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/metacatui#1268]
To reproduce:
- Go to /profile, and see that the citations, views, and downloads display correcty
- Click on another MetacatUI link, such as to /data
- Click the browser back button to go back to /profile, and see that the views and downloads display correctly but after a significant wait time. And the citations just show a loading spinner forever.

**Comment by rushirajnenuji** [comment]
The render function for citation and usage metrics was looking for the selector before the template was inserted in the DOM. The following commits solve this issue partly. - https://github.com/NCEAS/metacatui/commit/823018366bef6790b133774145dff25ad2b145a5 and https://github.com/NCEAS/metacatui/commit/d1957af5cefe8f8da4dc3b79e493f2f0a15853b2

[WIP] - Still seeing issues with the width of the metrics chart.

**Comment by rushirajnenuji** [comment]
The original bug linked with this ticket has been solved. For additional enhancements, I've opened a new ticket to work on. The charts and citation lists are rendering correctly (on reload, back/forward button click events, etc).
