### ISSUE TITLE
/profile view is sending invalid metadata quality requests

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/metacatui#1269]
When I look at /profile, I see error messages for the metadata quality charts, because there is no collection/portal object for that PortalView. We should detect when there is no collection/portal, and not send the AJAX request to get the metadata quality chart.

For example, the metadata quality chart URL is the following, for /profile: 
https://docker-ucsb-4.dataone.org:30443/quality/scores/?collection=undefined&suite=FAIR.suite.1

When the collection is `undefined`, we should not send that request.

**Comment by rushirajnenuji** [comment]
Solved with the above commit : https://github.com/NCEAS/metacatui/commit/52e4f9d08ce316609d31d0850d1754e11aa5a46c

The flags are set as part of the AppModel per theme in the commit: https://github.com/NCEAS/metacatui/commit/71c853d286cf4f3d474d6568738acc863c57ed32

This issue seems complete.

**Comment by laurenwalker** [comment]
Looks great, let's just set the `hideMetadataAssessment` attribute on the Stats Model and then have the `getAll()` function check the value of the attribute on the model, rather than send the `hideMetadataAssessment` value as a parameter to `getAll()`

**Comment by rushirajnenuji** [comment]
Made the changes that Lauren suggested above in the commit linked to this ticket. This issue is not complete.
