### ISSUE TITLE
Use the `nodeId` configured on the AppModel for the /profile StatsView

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/metacatui#1270]
The StatsView should use the `nodeId` set on the AppModel (this is a configuration that already exists and is used elsewhere in the app). We should not set the nodeId in the router.

**Comment by rushirajnenuji** [comment]
Updated the /profile view to utilize the AppModel settings. Relevant commit: https://github.com/NCEAS/metacatui/commit/71c853d286cf4f3d474d6568738acc863c57ed32

**Comment by rushirajnenuji** [comment]
Actually, on additional testing, I think this needs better error handling. When pointed to `handy-owl` Metacat MN - the `nodeId` is null. 

Moving back to in progress.

[WIP] - error handling
