### ISSUE TITLE
Attribute info not resizing correctly

### ISSUE THREAD

**Issue by gothub** [NCEAS/metacatui#1272]
Here is a bug report from  @mpsaloha (Mark Schildhauer

Attached are 3 screen shots showing what I take to be a bug with the Web UI on both DataONE and the Arctic Data Center, which is that at "intermediate display widths"-- details about attributes are relocated below (rather than to the side) of the Attribute listing.  When the browser width is narrowed or widened, then the Attribute details are "properly" displayed to the right of the listing.

Here is a link to the data package where I discovered this issue, but it appears to hold for other (all?) data packages where attribute details are provided.

https://arcticdata.io/catalog/view/doi:10.18739/A28S4JP53

(Note that the images below show a narrow, medium and then wide browser window)

<img width="869" alt="Narrow width- attribute details at side" src="https://user-images.githubusercontent.com/6412946/74389851-70ca9c80-4db4-11ea-8e51-20b7524a8d02.png">
<img width="1093" alt="Medium width-- attribute details at bottom" src="https://user-images.githubusercontent.com/6412946/74389864-7627e700-4db4-11ea-9dfc-f181b998ccfb.png">
<img width="1335" alt="Wide width- attribute details at side" src="https://user-images.githubusercontent.com/6412946/74389870-7922d780-4db4-11ea-81b7-d3bfecd7b6fa.png">

**Comment by amoeba** [comment]
Thanks for writing this up @gothub and for the screenshots. This appears similar to the closed issue #916 and the open issue #1029. @laurenwalker wrote up a fix in dfd4808d4d17c6c5569e36fc7a5b4657c93e54c1 to close #916. It looks like the fix went in 2.8.4 which is deployed at both search.dataone.org and arcticdata.io.

I can take this and look into it.

**Comment by amoeba** [comment]
Okay, can confirm the bug exists on the dev-2.9 branch.

**Comment by amoeba** [comment]
I tried commenting out the above the change from dfd4808d4d17c6c5569e36fc7a5b4657c93e54c1 to see what the effect would be and the bug appears to go away. @gothub would you have a sec to confirm by checking the deployment at https://neutral-cat.nceas.ucsb.edu/view/doi:10.18739/A28S4JP53 when you get a chance?

**Comment by gothub** [comment]
@amoeba I tried the neutral-cat link and the resizing works correctly, thx!

**Comment by amoeba** [comment]
Thanks for checking, @gothub! 

Hey @laurenwalker, while my change seems to fix things, it'd be undoing your dfd4808d4d17c6c5569e36fc7a5b4657c93e54c1. I don't want to undo anything you were trying to do with that change so could you take a second look here and see if you're okay with changing this back?

**Comment by amoeba** [comment]
FYI the `netural-cat` demo has been switched out so the above link isn't an accurate representation of my patch.

**Comment by amoeba** [comment]
Hey @laurenwalker, I took another look at this just now and undoing https://github.com/NCEAS/metacatui/commit/dfd4808d4d17c6c5569e36fc7a5b4657c93e54c1 still works as far as I can see.  c162a247075f8b079180fb5834fd4b5203a73000 is deployed at https://neutral-cat.nceas.ucsb.edu/view/urn:uuid:0a409765-7519-4bef-a04d-dd0bf352fd37. I can't get the attributes pane to jump below the list at any browser width.

Do you wanna take a look or shall I just close this and #1029?
