### ISSUE TITLE
Offset witdth of chart element sets to 0

### ISSUE THREAD

**Issue by rushirajnenuji** [NCEAS/metacatui#1284]
To reproduce:

- Go to /profile, and see that the citations, views, and downloads display correctly
- Click on another MetacatUI link, such as to /data
- Click the browser back button to go back to /profile, and see that the width of the metrics chart is set to the default width.

Noticed this while working on #1268

**Comment by laurenwalker** [comment]
What's the status of this? Is this still an issue? @rushirajnenuji

**Comment by rushirajnenuji** [comment]
Solved by updating app view to perform rendering new view after the fading is complete. Relavant commit: https://github.com/NCEAS/metacatui/commit/4e6ff968b95537df91a64dc80296828167f2a4b4
