### ISSUE TITLE
Improvements to Citations display

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/metacatui#1292]
- [x] Improve explanation text to Citations display in StatsView - Explain that the citations are of datasets in the portal.
- [x] Display "Cites Data" on a new line
- [x] Add row background color to every citation row so the bg of the div isn’t shown
- [x] Citation text is light gray but should match the darker gray/black on rest of the page
- [x] Fix extra negative space below short citation list (likely a min-height is set on the containing div/stripe)
- [x] Just the citation title should be a link, not the entire citation.

**Comment by laurenwalker** [comment]
Hi @rushirajnenuji - I see this ticket is slated for tthe 2.10.0 release. I'm hoping to get that tagged bby the end of this week. Do you think this will be completed by then or should we move to 2.11.0?

**Comment by rushirajnenuji** [comment]
Hey @laurenwalker  - I think I'll be able to get this done by the Thursday. I'll let you know when completed.

**Comment by rushirajnenuji** [comment]
Completed this with few styling changes in the linked commit https://github.com/NCEAS/metacatui/commit/b56de9d51a1e8134f57b47b0fc7a01bb46e22d3c

**Comment by laurenwalker** [comment]
When can this be merged into a dev branch? 

I see you committed this to the feature-portals-agu-demo branch, but I'm having trouble keeping track of what is on that branch and if it is ready to be merged into a dev branch yet. I am about to tag 2.10.0, so I'll move this to 2.11.0. Please merge into dev-2.11.0 when it's ready.
