### ISSUE TITLE
Updates charts overlap at smaller widths

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/metacatui#1295]
They should move to a vertical display sooner

**Comment by rushirajnenuji** [comment]
Tasks: 
- [ ] Make the CSS responsive for updates chart

**Comment by rushirajnenuji** [comment]
Fixed this by re-rendering the svg.
reference commit: https://github.com/NCEAS/metacatui/commit/55abc86d82afda8ae4e244d7a648c377031e1519
