### ISSUE TITLE
Add portal pages to the Metacat/UI sitemap

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/metacatui#1302]
All portal objects in Metacat need to be added to the sitemap with the portal MetacatUI route (e.g. /portals/{label}). The route for portals can be configured differently for each MetacatUI instance. (e.g. ESS-DIVE may be using /projects instead of /portals), so the sitemap should reflect this. That may require a new Metacat config.

We will also have portals stored in a DataONE replica MN, so we need to determine if we need a sitemap for those MNs too.

**Comment by amoeba** [comment]
Hey @laurenwalker, thanks for writing this up. I've filed a companion issue over on https://github.com/NCEAS/metacat/issues/1432 so we can coordinate changes in both repos. I put a some detail in issue.
