### ISSUE TITLE
editor cannot handle datasets containing spatialVector

### ISSUE THREAD

**Issue by jeanetteclark** [NCEAS/metacatui#1303]
When editing a valid document that had a spatialVector element, I got the following error after editing some entity descriptions:

>Error inserting or updating document: urn:uuid:1f8c19c6-93cc-47db-a9b6-4a19dec72d9d since <?xml version="1.0"?><error>cvc-complex-type.2.4.a: Invalid content was found starting with element 'spatialreference'. One of '{geometry, geometricObjectCount, topologyLevel, spatialReference, horizontalAccuracy, verticalAccuracy}' is expected.</error>

I'm guessing this is a typo somewhere, note the non-camelcased "spatialreference"

**Comment by csjx** [comment]
Yes, because we parse the tree as HTML and not XML, we have a mapping from camel case to lowercase (for parsing, and vice versa for serializing.  I bet we just need to add this to the mapping, but would need to look.
