### ISSUE TITLE
Add app config for hiding the aggregated metadata assessment charts

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/metacatui#1304]
There is not a config option right now to hide the aggregated metadata assessment charts. It's already built into the StatsView, but there's no way to control it from the AppModel. This needs to be added for the next release.

**Comment by gothub** [comment]
@laurenwalker I think the following line is in the wrong place, but am not sure where it should be placed in StatsView.js:

    https://github.com/NCEAS/metacatui/blob/dev-2.10/src/js/views/StatsView.js#L66

Should this just be outside the `if ( options.nodeSummaryView ) {` block?

**Comment by gothub** [comment]
Fixed in commit 97f0b883973ad9beb0151aa69ad9ea4c17cb788f

Note: when the app config param `hideMetadataAssessment = true`, the chart displays for both profile view (i.e. url=".../profile") and portal view (i.e. url=".../portals/<portal name>/metrics".

**Comment by laurenwalker** [comment]
The changes you made to the Stats.js model are incorrect, in that the model should check the `hideSummaryMetadataAssessment` attribute on the Stats model, as well as the AppModel. With your change, it just checks the AppModel. This breaks the functionality of user and group profiles, because not the metadata assessment charts are displayed when `hideSummaryMetadataAssessment=true` on the AppModel. 
I'll push a fix for this.

**Comment by gothub** [comment]
@laurenwalker thanks for catching this & for the explanation -  I see now that StatsView has to be able to conditionally control the Stats model by passing the `hideMetadataAssessment` to it, potentially overriding the AppModel setting.
