### ISSUE TITLE
Considering deprecating IE11 support for all or part of MetacatUI

### ISSUE THREAD

**Issue by amoeba** [NCEAS/metacatui#1308]
_We had a short discussion about this on Slack today and I wanted to make an Issue for visibility's sake and continue discussion if needed._

While testing Drafts (#216, #1242, #1228) under IE11, I ran into a good number of JS errors under IE11, some behavior-breaking. The errors are various, from syntax errors, to syntax not supported, to missing JS API features other browsers have.

From a conversation with @mbjones, @laurenwalker , and @nickatnceas on Slack,

@mbjones said:

> unless there are objections, I’d say pull the plug, and just be clear that people need to use a modern browser. Upon detecting an outdated browser, maybe the main page for arcticdata.io could put up a warning banner (at the top) but that still let’s people read the page, and navigating to MetacatUI routes would trigger a modal that requires an upgraded browser version.

> the one thing I would avoid is whitelisting good browsers, because that prevents new good browsers from gaining traction.  So just blacklist common known-problematic browser versions, and let unknown user agents through

@laurenwalker pulled stats from the ADC's Google Analytics and noticed we have ~8% IE users app-wide, ~4% IE11, the rest using older versions. However, only about **four** of those users tried to use the Editor with IE11 and the Editor is the only thing I've seen that just doesn't load under IE11.

I think we can do two things:

1. Spend time fixing the existing IE11 bugs
2. Deprecate just the Editor under IE11, displaying a warning to users who load the Editor under IE11, that the Editor doesn't work and that they should upgrade to a newer browser. The search catalog still works on IE11 and a large portion of people still use IE11 so I think an app-wide deprecation may not be ideal

(1) and (2) would probably take roughly equal amounts of time but (1) will recur as we add new features and need to spend that extra time testing and bug-fixing on IE11. Testing on IE11 is slow since it requires a VM or a reboot and IE11 itself is significantly harder to debug under due to its poor tooling.

I think a good plan would be:

- [ ] Display a warning for IE11 who load the Editor about deprecation & upgrading. Since the Editor doesn't even load, we can just always display a notice
- [ ] Updates docs to indicate this change in browser support

Does anyone else having any thoughts on this, either for or against deprecation?

**Comment by laurenwalker** [comment]
For 2.10.0, I think we can start displaying a warning for IE11 and earlier on _every page_. (There might be issues beyond the editor).
I'll take a look at the error messages in IE11 and make sure it's not something that can be fixed really quickly. But I don't think we should delay the release of 2.10.0 for any of those compatibility issues.
So in general, I support deprecating support for IE11 and earlier.

**Comment by amoeba** [comment]
Sounds good, I'll let you have a go at that.
