### ISSUE TITLE
Add icon next to every DataONE Plus feature 

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/metacatui#1309]
Add an option for hiding these icons everywhere, which most hosted repositories will probably want to do. 

The icon could be the DataONE Plus icon or some variation of it. (The world with a + on it).

**Comment by robyngit** [comment]
There's a mockup of how this might look available [here](https://robyn437774.invisionapp.com/console/DataONE-Website-Redesign-2019-ck3g5wyvd0ot401aeho8jjoyx/ck80l7d1703t401xza069lzvk/play)
