### ISSUE TITLE
Add DataONE Plus "ad" to the header of DataONE theme

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/metacatui#1310]
The DataONE theme should display an "ad" for the DataONE Plus and hosted repo services in the header of MetacatUI. This could be something subtle. It should link to the DataONE Plus or hosted repo or signup page.
We may only want to show it on certain pages, like the profiles and dataset pages. 

Possibly several mockups should be designed to see what this ad would look like, both in style and placement.

Related to #1309

**Comment by robyngit** [comment]
The mockups related to this are available [here](https://robyn437774.invisionapp.com/console/DataONE-Website-Redesign-2019-ck3g5wyvd0ot401aeho8jjoyx/ck80l7d1703t401xza069lzvk/play)

**Comment by laurenwalker** [comment]
This will be completed when the entire navigation is changed to the new navigation style - #1419. Closing
