### ISSUE TITLE
Can't submit dataset after adding a file

### ISSUE THREAD

**Issue by amoeba** [NCEAS/metacatui#1313]
After adding a file to a package, I see no change after clicking "Submit Dataset". i.e., I can't submit my edit

Steps to reproduce:

1. Create a minimal package w/ no files, setting title, abstract, temporal and geo coverage.
2. Submit it
3. On the landing page, hit Edit
4. Add a file
5. Observe "Submit Dataset" pops up
6. Try to click "Submit Dataset", observe nothing happens

Reproduced on dev-2.10 branch using Chrome 80.0.3987.87.

**Comment by amoeba** [comment]
Odd, the Describe button also ends up broken. Still tinkering away on this before I get to #653.

**Comment by laurenwalker** [comment]
I encountered this bug while fixing another bug, and quickly figured out the issue so I went ahead and fixed it. Thanks for looking into it anyway Bryce!

**Comment by amoeba** [comment]
Great, thanks!
