### ISSUE TITLE
Add image uploader to the markdown sections

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/metacatui#1316]
Add easy way for people to upload an image and include it in the Markdown.

**Comment by robyngit** [comment]
Left to do:
- [ ] Move the markdown editor out of the `portEditorMdSection` view into its own view so that it can be used anywhere it's required (e.g. for EML editor)

**Comment by laurenwalker** [comment]
Yay, this is awesome! It was very easy to use and everything seemed to work great.

A couple improvements: 

- [ ] What do you think about changing the icon for "headings"? It wasn't obvious to me:
![Screen Shot 2020-06-15 at 4.24.14 PM.png](https://images.zenhubusercontent.com/5d152e12c27d0c306f021863/339e04a1-6f7f-4cf8-a12c-b01799150ed4)

Is there a way to change it to a dropdown list to select a heading? The way Evernote does it immediately came to mind:

![Screen Shot 2020-06-15 at 4.27.18 PM.png](https://images.zenhubusercontent.com/5d152e12c27d0c306f021863/2c30c24f-8f32-40f2-9538-b8fcb76444f3)

- [ ] I couldn't figure out a way to create a link using an image. I thought by highlighting the image markdown and clicking the link icon, it would wrap a link around the image, but it just replaced it.

Are there any other Markdown features we could easily add? (dividers, tables, etc.) - I think we can release a first version with the features you added here, though.

**Comment by robyngit** [comment]
Thanks for reviewing this! :)

> changing the icon for "headings"

Agreed, the `Tt` isn't so obvious. It looks like an `H` icon or `H1` / `H2` / `H3` icons are more common. The trouble is in part that FontAwesome 3.2.1 doesn't have anything appropriate. We could just use an entire word, like "Heading" or "Title". What do you think?

> dropdown list to select a heading

This seems much nicer, good idea! The heading button uses the default "add a header" function from woofmark, but I could make a custom button in the same way that I did for the image uploader. The drop down would take a little more time, a quicker option would be just to have separate buttons for each level of header (`H1` / `H2` / `H3`). Which do you think is better?

> create a link using an image

This is strange! If you highlight a link and press the link button, it also removes the link in the same way it removes the image. Just a guess, but I bet this button is supposed to also function as a "remove link" button, and it is detecting image markdown as links. I'll look into it and see if I can fix it.

> any other Markdown features we could easily add

Yes! Tables and dividers would be pretty easy to add I think. Also easy: strikethrough, footnotes, task lists, and emojis. More difficult: equation builder, dataset citations

**Comment by laurenwalker** [comment]
> a quicker option would be just to have separate buttons for each level of header (H1 / H2 / H3). Which do you think is better?

Let's make SVG icons for the `H1`, `H2`, `H3` icons and go that route. It would be great if each icon reflected the font size/style as much as possible (e.g. the `H1` icon would be the largest font, `H2` smaller, `H3` smallest, and all of them are bold).

If dividers, tables, and strikethrough are easy to add, let's get those in too. The equation builder and dataset citations can wait for another iteration.

Thanks!

**Comment by robyngit** [comment]
The last task for this issue was allowing the link button to make links from images. We decided in the meeting today that this is more involved than is worth it for now. It could be a future enhancement to the markdown editor.
