### ISSUE TITLE
"Copy" button for user token doesn't work

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/metacatui#1320]
In the user settings, the Copy button for the token doesn't work. The "Copy citation" button on the MetadataView does work, so it's something isolated to the UserView.

**Comment by amoeba** [comment]
Fixed in https://github.com/NCEAS/metacatui/commit/8e530a47ee8ca5536db0f99a182692e7bd1ed49c. Changed the usage of the Clipboard API to use an event delegate instead of DOM binding. Seems to work nicely now.
