### ISSUE TITLE
portal "url valid" message wraps incorrectly

### ISSUE THREAD

**Issue by mbjones** [NCEAS/metacatui#1329]
When editing a portal page for the first time on fancy-vulture, I added a short name to the field to set the URL, which was successful. However, the green success message "This URL is available" with a check mark wraps oddly, even if the browser window is resized.  This is FF 74.0 on Mac OS.  Screenshot:

<img width="719" alt="url-valid-message" src="https://user-images.githubusercontent.com/766407/79178903-e94cda00-7db2-11ea-90e0-c03e7f6f0b29.png">

**Comment by laurenwalker** [comment]
Ah yeah, that's odd. THanks
