### ISSUE TITLE
Add Dataset Contact (with ORCID) to Read Write Permissions

### ISSUE THREAD

**Issue by FiannaOBrien** [NCEAS/metacatui#1333]

**Comment by mbjones** [comment]
@FiannaOBrien I don’t understand under what contexts you want this to happen. Would it be a button to add them? Or automatically add them based on Metacat configuration? A description with what you expect would be really helpful. Could you edit the description and provide more context?

**Comment by FiannaOBrien** [comment]
@mbjones I'm so sorry. I added this issue to the wrong repo. This was meant for ESS-DIVE internally.
