### ISSUE TITLE
Routes to /profile should be case-insensitive

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/metacatui#1338]
Example:
https://handy-owl.nceas.ucsb.edu/profile/LTER and https://handy-owl.nceas.ucsb.edu/profile/lter should both resolve to the LTER MN profile view.

**Comment by rushirajnenuji** [comment]
Updated the search filters to perform case insensitive searches against already retrieved node model.
Relevant commits: https://github.com/NCEAS/metacatui/commit/c65c45ab3d3b29aaddab7e8dc16daec961ef232c
