### ISSUE TITLE
Fix colors in profile time period chart

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/metacatui#1339]
![Screen Shot 2020-04-20 at 1.50.05 PM.png](https://images.zenhubusercontent.com/5d152e12c27d0c306f021863/a00542d9-8ca9-461f-bb04-70efe8786279)

**Comment by rushirajnenuji** [comment]
Updated CSS rules in the above commit (https://github.com/NCEAS/metacatui/commit/94b5ebfd0bb2a442a6b777ee97e769f70e06dbef). Reverted the chart colors to default ones. 

![Screen Shot 2020-04-28 at 10.13.06 AM.png](https://images.zenhubusercontent.com/5d152e0511232d5ce5b3f588/104e5fe8-2028-4acf-8258-e707419b8e94)
