### ISSUE TITLE
Latest updates chart is not rendering

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/metacatui#1340]
![Screen Shot 2020-04-20 at 1.51.20 PM.png](https://images.zenhubusercontent.com/5d152e12c27d0c306f021863/13975e4c-e16e-4c32-a4dd-d13111a22216)

**Comment by rushirajnenuji** [comment]
This seems to have been fixed in earlier issue/commits. I've tested this and it looks like this is working.

**Comment by rushirajnenuji** [comment]
I cannot recreate this. I still see this bug in production, but not on the latest dev branch and as well as on my personal development branch.

I verified that this bug was fixed earlier in this commit: https://github.com/NCEAS/metacatui/commit/7240e054b670a23fcc15d009fdb29fe7a0b13670
