### ISSUE TITLE
Add "member since" stat to header of MN profile

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/metacatui#1341]

**Comment by rushirajnenuji** [comment]
Included the member since details above the description for repository profiles.

![Screen Shot 2020-04-28 at 9.29.58 AM.png](https://images.zenhubusercontent.com/5d152e0511232d5ce5b3f588/63471349-00fa-4813-812c-44c752b7335b)

**Comment by laurenwalker** [comment]
Look great! Can we change the term "Member Node" to "Member Repository"? That matches the new wording we've been using for DataONE. Thanks!

**Comment by rushirajnenuji** [comment]
Ah yes, we discussed this during our dev call. Sorry for the oversight! I've pushed the change:

![Screen Shot 2020-04-28 at 9.53.20 AM.png](https://images.zenhubusercontent.com/5d152e0511232d5ce5b3f588/e1f7083e-debf-4929-bdb3-accccb19aac8)
