### ISSUE TITLE
Add padding to portal view dataset list

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/metacatui#1344]
![Screen Shot 2020-04-20 at 1.57.44 PM.png](https://images.zenhubusercontent.com/5d152e12c27d0c306f021863/4873cbc6-a32d-41c1-b716-4a8363f46d72)

**Comment by rushirajnenuji** [comment]
Added some padding to the DataCatalog list for portals view

![Screen Shot 2020-04-28 at 3.14.29 PM.png](https://images.zenhubusercontent.com/5d152e0511232d5ce5b3f588/53eaff46-ed45-4636-a0e8-35e2bca2f68b)
