### ISSUE TITLE
Add mechanism to reserve node IDs as portal labels 

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/metacatui#1349]

**Comment by rushirajnenuji** [comment]
Hey @laurenwalker - this is complete and up for review. Could you please test the functionality whenever you get time.  Changes are pushed to the `patch-2.11.3` branch which is based on `dev-2.11`.

**Comment by laurenwalker** [comment]
Hey Rushi, this looks good! I merged your changes into the dev-2.11 branch.

However I do think we should populate the `portalLabelBlacklist` with all the node ids and names dynamically, by using all the node ids retrieved from the CN node service. What we could do is keep all the hard-coded node names in the AppModel like we have now, as a fast check, and then in `PortalModel.checkLabelAvailability()`, we send both a request to Solr to check for portal labels AND a request to the `/cn/v2/node` endpoint to fetch the list of node ids, too. Both of those checks have to pass for the "available" message to display.

I'll make a second ticket for that and close this one since it's good as a first pass
