### ISSUE TITLE
Test Attribute section of the Editor thoroughly

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/metacatui#135]
We need to do some testing of the attribute section by doing things like:

- loading an EML document with attribute info into the editor and making sure it was parsed correctly and is displaying correctly
- changing attribute info, then checking serialization and EML validation
- Adding an entity from scratch and adding new attributes,  then checking serialization and EML validation

etc....

**Comment by laurenwalker** [comment]
The only thing left here is to test serialization of the entity and attribute sections. I believe @csjx is still working on this.

**Comment by csjx** [comment]
Yup - it's a little tricky in `updateDOM()` to identify the exact DOM fragment for updating, but I've got a pattern for it.  Still working on it.

**Comment by csjx** [comment]
Testing this stuff now.

**Comment by laurenwalker** [comment]
Waiting to hear back from @amoeba about testing this on Windows, then we'll close this issue

**Comment by laurenwalker** [comment]
The testing of IE and Windows is covered with ticket #196, so I'm closing this ticket
