### ISSUE TITLE
Remove "replicas" stat from non-repo portals/profiles

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/metacatui#1351]

**Comment by rushirajnenuji** [comment]
Hi @laurenwalker  - This was an easy fix - but now that we have reduced the radius of the charts for summary metrics - (i.e. the number of datasets and total volume of content) - there is too much of extra space on for that section in portal views.

Moving this to review column for now.

**Comment by rushirajnenuji** [comment]
Added a flag to display replicas only for repository profiles. Also updated some CSS rules for the summary charts.
