### ISSUE TITLE
Saving portals on feature branch not working

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/metacatui#1359]
I tried to edit and save a portal on test.arcticdata.io (which currently uses the dev-2.11-encoding branch), and it failed due to this error:

`The series identifier urn:uuid:ccd1a03a-1e8a-40fa-a8b5-55e391e27bfe is already used by another object and therefore can not be used for this object. Clients should choose a new identifier that is unique and retry the operation or use CN.reserveIdentifier() to reserve one.`

It seems like during save(), the DataONEObject.isNew() function returns true, even though the object is not new.

This bug doesn't exist on the dev-2.11 branch.

**Comment by amoeba** [comment]
Interesting. I'll take a look.

**Comment by amoeba** [comment]
This was a quick fix and due to my bad assumption about how `encodeURIComponent` would work on a null value. Turns out it just returns "null" which is truthy in JS. Oops.

I looked at my other commits on this branch and I didn't make this same mistake anywhere else so I'll call this fixed.

**Comment by amoeba** [comment]
PS: @laurenwalker IIRC this was the last/only thing we found that needed fixing on this branch so I think this ready for a review and/or merge whenever you're ready.

**Comment by laurenwalker** [comment]
Awesome, thanks
