### ISSUE TITLE
My Portals menu wraps strangely

### ISSUE THREAD

**Issue by mbjones** [NCEAS/metacatui#1361]
When I view the menu in the arcticdata.io using Firefox 75.0 on MacOS I get a weird multiline wrap.  Here's a screenshot:

<img width="321" alt="portals-menu" src="https://user-images.githubusercontent.com/766407/80540338-9435ca00-8955-11ea-91b5-fe5da296f0ea.png">

**Comment by laurenwalker** [comment]
Yes this is fixed and should be deployed soon
