### ISSUE TITLE
OPC DOI URL doesn't resolve

### ISSUE THREAD

**Issue by gothub** [NCEAS/metacatui#1376]
For the OPC repository (opc.dataone.org), the 'publish DOI' button was pressed and the new package https://opc.dataone.org/view/doi:10.25494/P6QP4H was created with the corresponding registered DOI.

When trying to resolve this DOI from doi.org, the resolution url https://opc.dataone.org/metacatui/view/doi:10.25494/P6QP4H is returned, which doesn't display on OPC.

Should the URL include `metacatui`? 
Is this:
- a config issue and metacatui is passing an incorrect URL to metacat
- an apache issue and the url with `metacatui` should route to the dataset
- a metacat issue in not creating the correct URL for DOI registraction
- something else?

**Comment by amoeba** [comment]
Just looks like they haven't configured this section of Metacat. I think they wanna change https://github.com/NCEAS/metacat/blob/3c4a4109fa49e86969981901b8979d7214aa63d1/lib/metacat.properties#L728

**Comment by gothub** [comment]
@amoeba thanks for find the config for this, i'll close this now.

**Comment by mbjones** [comment]
@csjx was configuring this for them, so we need to update the configuration on metacat, and we need to update all of the already-registered DOIs so they point at the correct landing page URL.  @taojing2002 could you do this while chris is out? I'm not sure who has access....

**Comment by taojing2002** [comment]
There was still a missed configuration on the ezid part - `guid.ezid.uritemplate.metadata`. It should be `/view/<IDENTIFIER>` rather than `/metacatui/view/<IDENTIFIER>`. After I fixed the issue and re-registered the new datacite.xml,  it works.
