### ISSUE TITLE
Check node list for node ids when checking portal label availability

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/metacatui#1387]
We should populate the portalLabelBlacklist with all the node ids and names dynamically, by using all the node ids retrieved from the CN node service. What we could do is keep all the hard-coded node names in the AppModel like we have now, as a fast check, and then in PortalModel.checkLabelAvailability(), we send both a request to Solr to check for portal labels AND a request to the /cn/v2/node endpoint to fetch the list of node ids, too. Both of those checks have to pass for the "available" message to display.

**Comment by rushirajnenuji** [comment]
Performs a retrieval of node information while doing label checks. Relevant commit: 
- 2e4c8dc2d92668d2591bb61c4df33144f05a98d8
- 641f909802216d6673658a9f710d953031a93c2e
