### ISSUE TITLE
custom filters don't clear on Icecaps portal

### ISSUE THREAD

**Issue by mbjones** [NCEAS/metacatui#1391]
**Describe the bug**
When using the custom filters from the Icecaps portal (https://arcticdata.io/catalog/portals/icecaps/Data), the filters only clear for the Data Stream dropdown, and not for the Year dropdown.

**To Reproduce**
1. Go to https://arcticdata.io/catalog/portals/icecaps/Data
2. Click on the Year dropdown, and select a year (say 2014)
3. Note the Year is added as a pill showing the query constraint
4. Try to remove the pill by either clicking on the x or hitting "Clear All", and note that nothing changes

**Expected behavior**
When deleted, the query constraint should be removed.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS 10.14.6
 - Browser FireFox
 - Version 76.0.1

**Additional context**
None.

**Comment by jeanetteclark** [comment]
This got fixed I believe - combination of a SOLR syntax issue and a metacatUI issue where the search string was being wrapped in quotes
