### ISSUE TITLE
Update entity name on replace doesn't work sometimes

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/metacatui#1394]
When a user replaces a file and the file name has changed, I wonder if we want to update the entity name in the metadata as well? We *do* update the fileName in the system metadata. Typically, these file/entity names match, but they don't have to.
Thoughts?

**Comment by laurenwalker** [comment]
Actually, after testing some more, it seems that the entity name does get updated, but sometimes it doesn't work.  I haven't found the exact conditions under which it doesn't work, but I will update this if I find them.

**Comment by jeanetteclark** [comment]
I thought that I had opened an issue for removing the ability to edit the entityName entirely in metacatUI. Often users mis-interpret this field, and IMO it should be the same name as what exists in the system metadata.

Because of this, my vote is to update the entityName in the metadata to match the fileName in the sysmeta

**Comment by mbjones** [comment]
That is not the main intent of that field, although I agree it sometimes contains filenames.  The filename for an object in EML goes in e.g., `dataTable/physical/objectName`, and that should definitely match system metadata.  The entity name is meant to differentiate entities, sometimes in files that might contain multiple entities.  For example, in an excel file named with a physical `objectName` of "mydata.xls", one might have two entities representing two tabs in the spreadsheet, with the first `entityName` being "Population Abundance" and the second being "Taxon Codes", or somesuch. Or they might be multipole objects in a NetCDF single file.

In sum, while putting a filename in `entityName` is fine, it shouldn't be required.  I would however fully support that `objectName` always should properly reflect the same filename that is in sysmeta.

**Comment by laurenwalker** [comment]
Okay, so perhaps we should never update the entityName when replacing files.

I think we can keep the behavior where the entityName is set to the fileName upon initial upload, just to get the user started.
