### ISSUE TITLE
Add try, catches to replace file functions

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/metacatui#1398]
Add try, catches to the new replace functionality. These should catch errors and abort the replace so that if something goes wrong, the user can still submit the rest of their dataset, just without the new file.

**Comment by amoeba** [comment]
Hey @laurenwalker, could you help me understand what you had in mind here? Were you able to get the replace feature into any particular failure states?

About all I can imagine doing is try-catching the entire method body and having the catch block re-set the Model attributes to what they were before replace and re-render the DataItemView.

**Comment by laurenwalker** [comment]
> About all I can imagine doing is try-catching the entire method body and having the catch block re-set the Model attributes to what they were before replace and re-render the DataItemView.

This is what I was thinking. I didn't come across any errors, but I think we should be wrapping methods in try, catches as much as possible so that we catch unknown errors in the future.

**Comment by amoeba** [comment]
Sounds good, I'll get that added.

**Comment by amoeba** [comment]
Got this done and tested in c62eb059a5043b437a5ea564e14782088ffa43e4. To copy the pre-replace state, I went with a selective `_.clone` of only the attributes we change. I was able to test by tossing a `throw` in four or so different places inside the `try-catch` and making sure things got reverted correctly.
