### ISSUE TITLE
Complete the Entity and Attribute section of the editor

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/metacatui#14]
- [x] Design the Entity and Attribute UI
- [x] Implement the entity UI
- [x] Implement the attribute UI
- [x] Edit/Add an otherEntity section to the EML document
- [ ] Edit/Add attribute information to the EML document

**Comment by csjx** [comment]
This effectively depends on https://github.com/NCEAS/metacatui/issues/87

**Comment by laurenwalker** [comment]
The basic other entity view, shown in a modal window, is done. It is just the entity name, description, and type. 

The EditorView works as the controller for all the EMLEntityViews, since the data package table is outside the scope of the EML211View. 

If the data object is new or is not described in the EML yet, the EditorView will add the EMLOtherEntity model to the EML211 model "entities" attribute.

**Comment by laurenwalker** [comment]
Closing this ticket since the entity and attribute sections are largely done. Anything else that needs to be added or fixed should get its own ticket.
