### ISSUE TITLE
Invalid XML characters error

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/metacatui#1401]
The following characters were inserted into an EML doc and caused an XML validation error: `DÃ©partement de gÃ©ographie, UniversitÃ© de MontrÃ©al &#x26; Centre dâ€™Ã©tudes nordiques`

It looks like this is only an issue in Firefox. Chrome and Safari strip out these characters from form input fields, but it looks like FF doesn't.

**Comment by mbjones** [comment]
Stripping out the characters does not seem like a viable approach either.

Part of the problem could be that we don't seem to be setting the charset on the HTML page for MetacatUI.  The [W3C page on encoding declarations](https://www.w3.org/International/questions/qa-html-encoding-declarations) says to provide it as:

```html
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
```

When I run the ADC page through the W3C Validator, it spits back an immediate character encoding error, and says to assume the page is `windows-1252`. Check it out here: https://validator.w3.org/nu/?doc=https%3A%2F%2Farcticdata.io%2Fcatalog%2Fdata

<img width="748" alt="html-validation-errors" src="https://user-images.githubusercontent.com/766407/82507589-2f324780-9aaf-11ea-82b3-effd16cb8a5a.png">

Our pages should be valid HTML if at all possible.

**Comment by laurenwalker** [comment]
I added this to the HTML head:
`<meta http-equiv="Content-Type" content="text/html; charset=utf-8">`

and fixed a few other HTML and CSS validation errors.

I also added some code that strips the input of any Unicode characters that are not in the list of valid XML characters, per https://www.w3.org/TR/xml/#charsets
