### ISSUE TITLE
Metrics tab in MN portal is empty

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/metacatui#1410]
I navigated to the mnTestKNB portal and clicked on the Metrics tab, and the view is empty.

A caught error in the console:

`PortalMetricsView.js?v=2.10.0:232 Failed to render the metrics view. Error message: TypeError: Cannot read property 'includes' of undefined`

[Screen Shot 2020-05-28 at 2.57.04 PM.png](https://images.zenhubusercontent.com/5d152e12c27d0c306f021863/bc66117b-55c5-4e03-9d38-cb9b52a4af94)

To fix:
- [x] fix error listed above
- [x] When we `catch` an error there, we should display something to the user so they don't just see a blank screen. Using the standard `alert` template works fine, but maybe use the yellow (warning) styling instead of red (error), since it's not a fatal error

**Comment by rushirajnenuji** [comment]
Additional subtasks:

- [ ] Include better error handling before rendering the metrics. 

- [ ] Include check for object types before performing object-specific operations.
