### ISSUE TITLE
Redesign summary of holdings section

### ISSUE THREAD

**Issue by rushirajnenuji** [NCEAS/metacatui#1411]
Remove the circle badges from the summary of holdings and redesign the metrics making them more visually appealing. Chris and Lauren and I have finalized a design for this.

**Comment by rushirajnenuji** [comment]
- [ ] Make the helper text more `subtle` for this section.

- [ ] restructure the container to move the text below the metric count

**Comment by laurenwalker** [comment]
Here's the screenshot I took yesterday after we played around with the CSS a bit:

![Screen Shot 2020-05-28 at 4 27 41 PM](https://user-images.githubusercontent.com/6643222/83306725-b88cfc80-a1c8-11ea-868b-e4911bc6d17f.png)

**Comment by rushirajnenuji** [comment]
Hi @csjx  @laurenwalker  - here's the screenshot of the updated summary of holdings section. 

![Screen Shot 2020-06-16 at 7.53.11 PM.png](https://images.zenhubusercontent.com/5d152e0511232d5ce5b3f588/0d8b7e3f-3a3b-49ac-812c-79b9eb08e646)

This is deployed here: [.../**portals**/arctic](https://handy-owl.nceas.ucsb.edu/portals/ARCTIC)

**Comment by laurenwalker** [comment]
Hey Rushiraj, this looks really great! 🎉
