### ISSUE TITLE
Design and implement a way to add the custom search filters in the portal editor

### ISSUE THREAD

**Issue by robyngit** [NCEAS/metacatui#1415]
We don't have any mockups for this feature yet, so the first step is to create some options of how this will look & work.

**Comment by robyngit** [comment]
Two versions of mockups are required:
1. Search filters as they would look integrated in the current version of the portal editor data tab
2. Search filters as they would look with the planned update to the EditCollectionView (see https://github.com/NCEAS/metacatui/issues/1133 and https://github.com/NCEAS/metacatui/issues/1175)

**Comment by robyngit** [comment]
The first iteration of these mockups, along with feedback, is viewable [here](https://invis.io/3YYGWMY9B6M)

**Comment by robyngit** [comment]
Round two of mockups with feedback in the comments can be viewed [here](https://invis.io/X7YJ34C5DZT)

**Comment by robyngit** [comment]
We have mockups done already for a potential MVP version of the custom search filter builder [here](https://invis.io/MYZUFNFATQ7)

**Comment by robyngit** [comment]
The MVP version of this feature is ready to review on the `feature-search-filter-editor` branch.

Note that if a portal already has filter groups (tabs) or filter icons, like in the examples below, these elements will show in the editor, but will not yet be editable. Tabs and filter icons will not show up in the editor in portals without them.

I will make issues for the other features we discussed that are still missing. The most important might be preventing users from building filters with mis-matched solr fields. For example, this version allows a user to build a dateFilter with any non-date solr field, e.g. "title".

<img width="1863" alt="Screen Shot 2021-03-11 at 10 55 50" src="https://user-images.githubusercontent.com/26600641/110815614-998fc080-8258-11eb-86a3-9e337f6d100f.png">

<img width="500" alt="Screen Shot 2021-03-11 at 10 56 52" src="https://user-images.githubusercontent.com/26600641/110815607-985e9380-8258-11eb-858e-f56e629350d5.png">

<img width="500" alt="Screen Shot 2021-03-11 at 10 56 09" src="https://user-images.githubusercontent.com/26600641/110815617-998fc080-8258-11eb-8a31-59a7445dcf1e.png">

**Comment by mbjones** [comment]
Fantastic, @robyngit! Let's coordinate with @erinlynmclean about getting our documentation updated as well to go along with the MVP release. Let's discuss what steps are next needed on our dev call today.

**Comment by erinlynmclean** [comment]
Sounds great! Loop me in on the team call tomorrow :) yay!

**Comment by robyngit** [comment]
When it comes to reviewing this feature, just a note that it has been merged into the more up-to-date `feature-rule-groups` branch

**Comment by laurenwalker** [comment]
Thanks Robyn

**Comment by robyngit** [comment]
@laurenwalker, since this feature is in the same branch as #1582, could it be added to the [`2.16.0`](https://github.com/NCEAS/metacatui/milestone/89) release?
