### ISSUE TITLE
Can't go back when clicking link to search.dataone.org

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/metacatui#1417]
search.dataone.org redirects to /data, so when clicking the back button, the user can never get to the page before search.dataone.org. This seems to only happen in FF and Safari

**Comment by robyngit** [comment]
This bug happens for me in Chrome as well (Version 83.0.4103.61), but not in every circumstance. 

- If I click a [link to the search page](https://search.dataone.org), then I **cannot** navigate back.
- If I copy paste the search url (`https://search.dataone.org`) into my nav bar, I **can** navigate back to this page with the back button, but not every time.
