### ISSUE TITLE
Outdated KNB template

### ISSUE THREAD

**Issue by gothub** [NCEAS/metacatui#1432]
The template `themes/knb/templates/metadataControls.html` contains an outdated link that is used to navigate to the assessment report from the metadata view. Here is the different between the standard template and `knb`:
```
diff templates/metadataControls.html themes/knb/templates/metadataControls.html
25c25
< 		<a href="<%= MetacatUI.root %>/quality/<%=encodeURIComponent(model.id)%>" class="btn"><i class="icon icon-dashboard"></i> Assessment report</a>
---
> 		<a href="<%= MetacatUI.root %>/quality/s=knb.suite.1/<%=encodeURIComponent(model.id)%>" class="btn"><i class="icon icon-dashboard"></i> Assessment report</a>
```

The string `/s=knb.suite.1` is no longer necessary, and this hard-coded value will produce incorrect results when a new version of the KNB Suite is available.

Currently this outdated URL does not create an error or incorrect results, but should be fixed before the next release.

**Comment by laurenwalker** [comment]
It would be great if we could remove the knb-specific template and just rely on the default metadataControls.html template for all themes. I think it was only created to hard-code the knb suite in, but there may be other differences.
