### ISSUE TITLE
Update Dataset/DataCatalog JSON-LD to use https schema.org context

### ISSUE THREAD

**Issue by amoeba** [NCEAS/metacatui#1437]
Per Dave V, we should update the JSON-LD we generate to use the new https Schema.org context URI.

```
it would be helpful to change the @context to either:
"@context":"https://schema.org/"
or
"@context":{
  "@vocab":"http://schema.org/",
  "@import":"https://schema.org/version/latest/schema.jsonld"
}
that way the full schema.org context is referenced rather than just asserting the namespace. Then class inheritance etc is available for consumers.
8:16
the two are equivalent, though the later works for libraries that do not yet implement Link header processing (https://w3c.github.io/json-ld-api/#remote-document-and-context-retrieval )
```

**Comment by mbjones** [comment]
Note that our current context URI is also missing its trailing slash, which causes a validation error with Dave's validation parser (and doesn't create the correct SO class URIs. So, whichever way it gets represented, include the trailing slash.

**Comment by amoeba** [comment]
Done in https://github.com/NCEAS/metacatui/commit/6327bef703eb2f48d85eecf841be9703d72a5f2a on the dev-2.13 branch.
