### ISSUE TITLE
Issues with repository portals

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/metacatui#1439]
- [x] Testing with a Google Map API key - the map is pushed down the page. Looks like the width of the results container is set to 100% in the CSS. This was in the DataONE theme using the `cn-stage2.js` config file from https://github.nceas.ucsb.edu/walker/metacatui-config.

![Screen Shot 2020-06-29 at 4.38.26 PM.png](https://images.zenhubusercontent.com/5d152e12c27d0c306f021863/3460bee2-6b5d-4efc-a30c-a6474682a0c9)

-----

- [x] The text under the two summary numbers sometimes overlap:
![Screen Shot 2020-06-29 at 4.39.33 PM.png](https://images.zenhubusercontent.com/5d152e12c27d0c306f021863/a019e277-e50f-4e31-8a36-718295da75a4)

-----

- [x] The FAIR Assessment loading icon displays forever. This is on the /profile view in the DataONE theme, using cn-stage-2. (Use the `cn-stage2.js` config file from https://github.nceas.ucsb.edu/walker/metacatui-config)

-----

- [x] In StatsView, we added a listener to the `window` `resize` event. This is causing errors in other views when the window is resized:
https://github.com/NCEAS/metacatui/blob/05c94a1e9918888e63fd3e99f8d3f4aa3367c918/src/js/views/StatsView.js#L285-L293

We need to remove this listener when the StatsView is closed by removing it in the `StatsView.onClose()` function. Other views do this, if you need an example.

https://github.com/NCEAS/metacatui/blob/feature-repository-portals-view/src/js/views/StatsView.js#L861

-----

- [x] In the StatsView, display the node name rather than the nodeId in the subtitle/paragraph. For example, this profile should say "PPBio AmOc" rather than the less-readable nodeId of "mnTestPPBIO":

![Screen Shot 2020-06-29 at 4.54.21 PM.png](https://images.zenhubusercontent.com/5d152e12c27d0c306f021863/653b5f04-836c-47f6-ba54-cb0239cd057f)

-----

- [x] Use DataONE theme color for summary numbers in DataONE theme. This is when looking at /profile:

![Screen Shot 2020-06-29 at 4.57.32 PM.png](https://images.zenhubusercontent.com/5d152e12c27d0c306f021863/3ca90e37-a406-4320-ad23-6f4ed11c6a18)

-----

- [x] Change the "replicas" stat descriptions. 
    When viewing the CN profile at /profile in the DataONE theme, it says `The total number of data replicas hosted in this repository.` This is an inaccurate description for the CN, since it's not a repository. For the CN profile *only*, it should say `The total number of replica datasets hosted by DataONE Member repositories.` 

     For MN profiles, it should say `The total number of replica datasets hosted in this repository`
-----

- [x] Add `-obsoletedBy:*` filter to replica query. We should only count each replica dataset once.

- [x] Add `formatType:METADATA` filter to replica query. It would be nice to show a more detailed breakdown of the replica count, but I think since we are showing this stat next to the dataset/metadata count, it makes sense to keep it consistent with the replicas count too.

For example, on the KNB profile, there are about 27,000 datasets, but it says there are 77,000 replicas. This is confusing. If we filter to only unobsoleted metadata docs, the replica count changes to about 14,000, which makes more sense.

**Comment by rushirajnenuji** [comment]
Fixed all the changes in the above commits.
