### ISSUE TITLE
validation errors with schema.org 

### ISSUE THREAD

**Issue by mbjones** [NCEAS/metacatui#1440]
**Describe the bug**
Our schema.org entries do not validate using the in-progress validator by science on schema.org. While that is in flux, there are still some clear items that should be fixed:

- [x] Ensure the schema.org namespace includes its trailing slash
- [x] add the required `sameAs` property
- [x] add the required `version` property
- [x] add the required `isAccessibleForFree` property

**To Reproduce**
1. Copy the JSON-LD from any dataset (e.g.,  https://arcticdata.io/catalog/view/doi%3A10.18739%2FA2MG7FW5P)
2. Paste the JSON-LD into the validator at https://grbf0pbqz1.execute-api.us-east-1.amazonaws.com/dev/edit
3. See errors. The first error on the namespace hides the others. Once you fix the first one, the other errors will show up.

**Expected behavior**
The schema.org should validate without errors. For the document above, I changed the following and it validates:

```json
 "@vocab":"http://schema.org/"
 "sameAs":"https://doi.org/10.18739/A2MG7FW5P",
 "isAccessibleForFree": true,
 "version":"doi:10.18739/A2MG7FW5P",
```

Related to: Issue #1437

**Comment by amoeba** [comment]
Done in https://github.com/NCEAS/metacatui/commit/269d3a03db51d586be8b674d2380e215769568d3.

I added `sameAs` just for identifiers that appear to be DOIs, added `version` and `isAccessibleForFree ` for all.
