### ISSUE TITLE
multiple method steps cannot be removed

### ISSUE THREAD

**Issue by jeanetteclark** [NCEAS/metacatui#1447]
**Describe the bug**
When there are multiple method steps in a metadata record, editing the dataset and removing them using the X button doesn't seem to stick - the updated metadata still shows the same method steps.

**To Reproduce**
1. Upload a metadata record with multiple method steps
2. Edit the metadata document and remove 1 or more steps by clicking the gray X
3. Observe the published record still has all of the stems

**Expected behavior**
Method steps are removed

**Screenshots**
![Screen Shot 2020-07-13 at 12 59 51 PM](https://user-images.githubusercontent.com/24237074/87347935-d14b3a80-c508-11ea-9545-ae567359aace.png)
![Screen Shot 2020-07-13 at 1 00 09 PM](https://user-images.githubusercontent.com/24237074/87347944-d4462b00-c508-11ea-9a1d-7c9d5145b3e7.png)

**Desktop (please complete the following information):**
 - OS: Mojave
 - Browser: Chrome
 - Version: 83.0.4103.116

**Comment by laurenwalker** [comment]
This has been fixed when I worked on #1864
