### ISSUE TITLE
Design mockups for hierarchical package display and editing

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/metacatui#1454]
Design mockups/wireframes for how these will be displayed and edited in both the MetadataView and EditorView

**Comment by mbjones** [comment]
Note the existing mockups we have for hierarchical folder display and editing, which I linked to in issue #1452.

**Comment by robyngit** [comment]
Here are our two mockups so far:
[Edit-Metadata-View-Add-Nested-Folder.pdf](https://github.com/NCEAS/metacatui/files/7342122/Edit-Metadata-View-Add-Nested-Folder.pdf)
[Add-a-Folder.pdf](https://github.com/NCEAS/metacatui/files/7342124/Add-a-Folder.pdf)

Both show how a hierarchical package is _edited_ in the UI. We still need:
- [ ] a mockup of how a hierarchical package will be _displayed_ in MetacatUI

This is how packages with data objects are currently displayed:
<img width="80%" alt="display of files" src="https://user-images.githubusercontent.com/26600641/187967988-b7215d65-5cfb-47ad-8e78-7111d172e2be.png">

We should come up with a mockup that shows how we will display multiple nested directories. Note that there is currently no support for downloading all files from a single directory, so download buttons should only be paired with individual files or the entire data package (not for each sub-directory).

**Comment by robyngit** [comment]
@rushirajnenuji's mockup of how to display [Folders in MetacatUI](https://github.com/NCEAS/metacatui/files/9500111/Folders.in.MetacatUI._21.pdf)

**Comment by rushirajnenuji** [comment]
3rd round of mockups:
MetadataView:
[MetadataView_naviagte_by_path.pdf](https://github.com/NCEAS/metacatui/files/9824649/MetadataView_naviagte_by_path.pdf)
[MetadataView_move_up_arrow.pdf](https://github.com/NCEAS/metacatui/files/9824651/MetadataView_move_up_arrow.pdf)

Editor:
[Editor_navigate_by_path.pdf](https://github.com/NCEAS/metacatui/files/9824652/Editor_navigate_by_path.pdf)
[Editor_move_up_arrow.pdf](https://github.com/NCEAS/metacatui/files/9824653/Editor_move_up_arrow.pdf)

**Comment by rushirajnenuji** [comment]
The final iteration of the mock-ups before beginning development: [Invision prototype](https://invis.io/4Y1333IEMANF#/470700389_MDV_01)

**Comment by robyngit** [comment]
@rushirajnenuji , is this issue close-able now?

**Comment by rushirajnenuji** [comment]
Hey @robyngit  -- yes, we might have to revisit the mock-ups later, but we can close this issue for now. The mock-ups I'm following for development are linked in the above comment.
