### ISSUE TITLE
Randomly generate portal label for free trial portals

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/metacatui#1466]
- [x] Randomly generate labels for new portals if the Subscription/Usage is in free trial mode, according to Bookkeeper, or if `MetacatUI.appModel.get("dataonePlusPreviewMode")==true`.
- [x] Disable the portal label input 
- [x] Display a message next to the input that says, "Create a custom portal name for the URL when your free preview of DataONE Plus ends"

**Comment by mbjones** [comment]
it would be great if these were easy to type and remember. Which means not using a random number or uuid or that type of thing. One common things I've seen other projects do is to choose two or three random words from set lists, which provides quite a few permutations.  For example, docker uses names like 'furious_einstein' and 'awesome_newton', which generates about 25K random strings using the code here: https://github.com/moby/moby/blob/master/pkg/namesgenerator/names-generator.go

Depending on how many of these we need, we could tweak the algorithm by adding another word, or increasing the wordlist lengths. A more generalized version of this approach was done in python: https://github.com/jjmontesl/codenamize -- it gives more options for number of adjectives to control the size of the codespace.

**Comment by laurenwalker** [comment]
@rushirajnenuji - The code I pushed for #1465 paves the way for this issue. The PortalEditorView will fetch the subscription (for now, it just creates a Subscription model since Bookkeeper is not fully integrated in yet). When it has completed fetching, the view will insert free trial info. You can use this to hook in the changes to the `PortEditorSettingsView`.

https://github.com/NCEAS/metacatui/blob/3ba47b98fdab14a40315de244e55e5709075ce70/src/js/views/portals/editor/PortalEditorView.js#L738-L779

It would be great to have this done soon so we can test it before releasing to production on Aug 11. Let me know if you run into any issues.

**Comment by rushirajnenuji** [comment]
Hi Lauren - as discussed, I've added this support to generate random portal labels for portals in the preview mode. This is ready for review. 

![Screen Shot 2020-08-03 at 9.55.58 AM.png](https://images.zenhubusercontent.com/5d152e0511232d5ce5b3f588/c09f90f3-4b3b-4f46-ac41-3b4339f12165)

**Comment by laurenwalker** [comment]
Opening this back up because new portals are not able to be saved with random labels. I get a validation error when I click Save.

**Comment by laurenwalker** [comment]
Also, when you try to edit a free trial portal that already exists, I'm able to edit the label in the text input. 

We need to make sure when changes are made that they are tested at least at a minimum, to make sure things don't break. This caused a few breaking changes and isn't totally functional @rushirajnenuji . I am going to fix it up since I'm already in the code.

**Comment by rushirajnenuji** [comment]
Hey @laurenwalker - sorry I missed that. I'll keep in mind to perform thorough testing for new functionalities added.
