### ISSUE TITLE
Add ability to register citations as a logged-in user to track the user. 

### ISSUE THREAD

**Issue by rushirajnenuji** [NCEAS/metacatui#1473]
**Describe the feature you'd like**
Ability to register citations as a logged-in user to track the user. 

Extension of #1245

**Comment by laurenwalker** [comment]
I added this to the 2.13.1 milestone so we can get it into a patch release soon. I think we should also make this feature configurable because some MetacatUI users do not have their repo registered w/dataone. I'll create a ticket

**Comment by rushirajnenuji** [comment]
Sounds good. Thank you, Lauren!

**Comment by laurenwalker** [comment]
@rushirajnenuji - ANy updates on this? I'd like to release a patch version of MetacatUI with this feature soon

**Comment by csjx** [comment]
The citations database will need to track a `reporter` ORCID and a `reviewer` ORCID, along with a `status` that shows if the reported citation was verified or is still in review.

**Comment by rushirajnenuji** [comment]
Only authenticated users can submit the citation registration request/s to the metrics service. Unauthenticated user is redirected to DataONE Sign In.
