### ISSUE TITLE
Include Google Analytics to track errors - PortalMetricsView

### ISSUE THREAD

**Issue by rushirajnenuji** [NCEAS/metacatui#1480]
**Describe the feature you'd like**
Include Google Analytics to track errors - PortalMetricsView

**Comment by laurenwalker** [comment]
Here's an example thatt you can copy/paste and just change tthe message: https://github.com/NCEAS/metacatui/blob/ba47712e155b9dc2a7ead81b60919fc56f0aa4c7/src/js/models/NodeModel.js#L91-L97

**Comment by rushirajnenuji** [comment]
Added ga reporting for portal metrics loading in [this](https://github.com/NCEAS/metacatui/commit/51a5539a30b84c3f7af4c858955579af3e37573d) commit.
