### ISSUE TITLE
portals display and other issues in prep for rollout

### ISSUE THREAD

**Issue by mbjones** [NCEAS/metacatui#1481]
**Describe the bug**
Several display issues and metrics appear incorrect on the fancy-vulture deploy of the portals. I will list the issues I am seeing below with a quick review for some of the portals that we plan to highlight next week:

- https://fancy-vulture.nceas.ucsb.edu/portals/ARCTIC
    - [x] Citation for "Chelsea Wegner Koch" repeats 4 times (**Rushi** update metrics service)
    - [x] Citation for "Chelsea Wegner Koch" missing links to datasets that it cites (maybe 4?) (**Rushi** update metrics service)
    - [ ] Citation for "Chelsea Wegner Koch" has mis-formatted citation text: `PLOS} {ONE}`, and many others have formatting problems (`{\textquotedblleft}rotten{\textquotedblright}`, `K{\k{e}}dra`) (**Rushi** to fix after community meeting)
    - [x] Quality report graph missing (**Lauren** to create portal document)
    - [x] Missing link to FAIR quality report on dataset landing pages (e.g., https://fancy-vulture.nceas.ucsb.edu/view/doi%3A10.5063%2FF1BG2MB2) (**Peter** to look into this and fix - please update on what needs to be done to complete this) 
    - [x] Related: Improve messaging when dataset landing page report is not ready (**Lauren** to file ticket - doesn't necessarily have to be done by community mtg)
 - https://fancy-vulture.nceas.ucsb.edu/portals/KNB
    - [x] repeating citations (same as above) missing links to data **(Rushi)**
    - [x] Quality report graph missing (**Lauren** to create node portal doc, **Peter** to ensure chart is generated after)

- [x] OPC portal missing (https://fancy-vulture.nceas.ucsb.edu/portals/CA_OPC) (**Lauren** to create OPC portal doc. **Chris** to coordinate finishing registration and sync with Dataone CN. **Peter** to ensure assessment charts generated) 
- [x] Sync issues with OPC (38 datasets on MN, 24 on CN)
- [x] Turn on metadata assessment chart in OPC MN profile (**Lauren**)

- [X] Dangermond Portal missing (https://fancy-vulture.nceas.ucsb.edu/portals/dangermond) (Will not be ready for Tuesday)
- https://fancy-vulture.nceas.ucsb.edu/portals/toolik
    - [X] Metadata Assessment graph shows only placeholder 
    - [x] Add explanation of Metadata Assessment charts to portal view (StatsView) - See #1288 (**Lauren** to add)
    - [x] Polish up metadata assessment chart titles and Metrics tab title (Metrics vs Stats and Figures)(**Lauren**)
    - [ ] 0 citations shown (can we find at least one to register for our exemplar portals?) (**Rushi** to talk to Jeanette to find a citation to register.)
    - [x] People Tab seems to revert to DataONE CSS colors, rather than portal colors
    - [x] DataONE header and footer are prominent (is this what we planned, rather than minimizing them?) (**Lauren** to fix this)
- https://fancy-vulture.nceas.ucsb.edu/portals/ecoblender
    - [x] Data tab missing search results for "Lortie" from Dryad and ONEShare
    - [ ] similar Metrics issues as above, including 0 citations (despite some data on Dryad) (**Rushi** to talk to Amber, Chris about finding citation to register)
- https://fancy-vulture.nceas.ucsb.edu/portals/SASAP
    - [x] Similar CSS color issues and header/footer issues as above (**Lauren** fixed colors issue already. Lauren to fix header navigation)
    - [x] On Data search, Year sliders start at Year 0 (rather than something reasonable like 1900 or 1950)
    - [x] Search for Identifier `doi:10.5063/F14B2ZMJ` returns 140 hits, many with other identifiers, some without titles (**Lauren** to file bug, may not get fixed by Monday but will look into it - #1168  )

### Metadata assessment other tasks
- [ ]
- [ ]

I found these issues with only a few minutes on each portal. There are probably other latent issues with a more careful inspection. Fixing as many of these as possible would present a more polished product, although none of them are deal-breakers. Let's discuss how to triage these.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Firefox
 - Version 78.0.2

**Comment by robyngit** [comment]
> DataONE header and footer are prominent (is this what we planned, rather than minimizing them?)

Note that we have a ticket for that, see https://github.com/NCEAS/metacatui/issues/1448

**Comment by laurenwalker** [comment]
I fixed the issue with CSS colors:
>  People Tab seems to revert to DataONE CSS colors, rather than portal colors

> OPC portal missing (https://fancy-vulture.nceas.ucsb.edu/portals/OPC)
Dangermond Portal missing (https://fancy-vulture.nceas.ucsb.edu/portals/dangermond)

The OPC and Dangermond portals do not show up because they are not registered nodes in DataONE. They cannot have portals on the CN because they have no content in the CN.

**Comment by laurenwalker** [comment]
>  On Data search, Year sliders start at Year 0 (rather than something reasonable like 1900 or 1950)

Fixed. Set to 1800

>  Data tab missing search results for "Lortie" from Dryad and ONEShare

Fixed. By default, we were wrapping text searches in wildcards, but that seems to cause less flexible searches, so I removed it.
