### ISSUE TITLE
Markdown editor toolbar missing from some freeform pages in the portal editor

### ISSUE THREAD

**Issue by robyngit** [NCEAS/metacatui#1484]
**Describe the bug**
In the portal editor, the markdown editor toolbar only appears on the first new freeform page. On subsequent freeform pages, the `MarkdownEditorView` throws an error and the toolbar doesn't appear.

**To Reproduce**
1. Create a new portal
2. Add a new freeform page
3. Add a second new freeform page
4. See error: There's no toolbar in the second freeform page

**Expected behavior**
All freeform pages should show the markdown editor toolbar

**Desktop:**
 - OS: MacOS
 - Browser: Chrome
 - Version: 84.0.4147.105

**Comment by laurenwalker** [comment]
Adding this to the MVP release so we can get it fixed for the community meeting. People will be watching live demos and following along, and will be confused if they dont see the markdown toolbar
