### ISSUE TITLE
Improve messaging when the assessment report isn't ready

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/metacatui#1486]
Right now we show a generic green alert. Replace with loading illustration from portals view.

**Comment by robyngit** [comment]
Here's how the assessment report page looks now when the report is not ready (in the `develop` branch):

<img width="1367" alt="Screen Shot 2021-03-17 at 20 12 52" src="https://user-images.githubusercontent.com/26600641/111555510-f14d9080-875e-11eb-9218-5e0e2e33d60f.png">

**Comment by laurenwalker** [comment]
Saw this during testing this week and it looks really good!
