### ISSUE TITLE
checksum algorithm is changed for data files on unrelated updates

### ISSUE THREAD

**Issue by jeanetteclark** [NCEAS/metacatui#1489]
**Describe the bug**
Some of the R libraries upload data files with SHA-1 checksums as opposed to MD5. When data packages with these files are edited in metacatUI (even if only the metadata is changed), the checksum algorithm is changed from SHA-1 to MD5, but the checksum itself is not changed. This results in object validation errors on sync to the cn.

**To Reproduce**
1. Create a dataset using metacatUI
2. Run the following R code
```
library(dataone)
library(arcticdatautils)

cn <- CNode("PROD")
mn <- getMNode(cn, "urn:node:mnTestARCTIC")

ids <- get_package(mn, "resource_map_urn:uuid:8b4168fa-a21d-4a43-8960-31cb00ab867c")

new_pid <- publish_object(mn, path = "~/funding_summary.csv", format_id = "text/csv")

# check algorithm after create call
sys <- getSystemMetadata(mn, new_pid)
sys@checksumAlgorithm
# [1] "SHA1"

publish_update(mn, metadata_pid = ids$metadata,
               resource_map_pid = ids$resource_map,
               data_pids = new_pid)

# check algorithm after resource map modification
sys <- getSystemMetadata(mn, new_pid)
sys@checksumAlgorithm
# [1] "SHA1"

```
3. Make an update on metacatUI unrelated to the data file (I added a sentence to the abstract)
4. Check the checksum algorithm again
```
# check algorithm after metacatUI update
sys <- getSystemMetadata(mn, new_pid)
sys@checksumAlgorithm
# [1] "MD5"
```

**Expected behavior**
MetacatUI shouldn't change the checksum algorithm unless the file itself is changed, and then the checksum and algorithm can be changed.

**Comment by csjx** [comment]
Thanks for writing this up @jeanetteclark 👍 

And note that the `checksum` remains the same, but the `checksumAlgorithm` has changed:

```
$ curl -s "https://test.arcticdata.io/metacat/d1/mn/v2/meta/urn%3Auuid%3A36319436-ebb0-4980-b5d9-cf0a6d626ec3" | xmlstarlet sel -t -v "//checksum" -n
78e66b83d0a867d30660fe9b418e228ffdb04147
$ curl -s -o funding_summary.csv "https://test.arcticdata.io/metacat/d1/mn/v2/object/urn%3Auuid%3A36319436-ebb0-4980-b5d9-cf0a6d626ec3"
$ shasum -a 1 funding_summary.csv
78e66b83d0a867d30660fe9b418e228ffdb04147  funding_summary.csv
```

**Comment by laurenwalker** [comment]
Thanks Jeanette. This is a critical bug that I will try to get fixed for a patch release asap. Thanks
