### ISSUE TITLE
Collect user feedback on assessment graphs

### ISSUE THREAD

**Issue by gothub** [NCEAS/metacatui#1491]
Collect feedback from the DataONE Community Meeting, developers, etc. regarding the display of metadata assessment graphs that appear in the portal metrics tab.

Some current ideas
- include graph with 5 month rolling average
- include a graph for each supported metadata format
   - i.e one graph for EML, one for ISO, ...
- cumulative vs monthly graphs?
- add drill down graphs
- add interactive features to the graph ( from @robyngit )
  - e.g. https://www.investopedia.com/articles/technical/052201.asp

**Comment by laurenwalker** [comment]
We collected feedback during the meeting and via a couple Google Form surveys
