### ISSUE TITLE
Add support to send the portal collection query to the Metrics Service

### ISSUE THREAD

**Issue by rushirajnenuji** [NCEAS/metacatui#1494]
**Describe the feature you'd like**
Add support to send the portal collection query to the Metrics Service

Metrics Service has support for portals collection query, for cases when the portal object is not synced. Sample query:
```json
"filterBy": [
    {
      "filterType": "portal",
      "values":["DBO"],
      "interpretAs": "list"
    },
    {
        "filterType": "month",
        "values": [
            "01/01/2000",
            "08/07/2020"
        ],
        "interpretAs": "range"
    },
    {
        "filterType": "query",
        "values": [
            "(((readPermission:CN=DBO,DC=dataone,DC=org) AND (formatType:METADATA)))"
        ],
        "interpretAs": "list"
    }
]
```

**Additional context**
From Slack conversation with @laurenwalker : 
> I think we will want to do a POST as a last resort, since the response won’t be cached. Perhaps we could only send a POST if we can detect that 1.) the portal isn’t synced and 2.) The query length is too long to send with GET. That way, portals with long queries can still take advantage of cached responses if they are synced. We might have to work this into an iterative release.

**Comment by laurenwalker** [comment]
I imagine the flow would look something like:

1. When rendering the metrics for a portal document, construct the collection query within MetacatUI.
2. Check the collection query string length.
    - If the query length is too long to send with GET (e.g. 1000+ characters), then send a GET request to the metrics service with only the portal label.
        - If the metrics service responds with the error `Operational Error: ... colelction Query not found...`, indicating that a  portal with that label was not found, then send a POST to the metrics service with the collectionQuery. Log a Google Analytics exception event so we can be notified when this error occurs.
    - If the query length is short, send a GET request to the metrics service with the portal label AND collectionQuery.

This essentially uses POST as a last resort - only for portals with long/complex collection queries that also haven't been synced. 

However we should do some benchmarking to see which is faster -- sending the request as a POST with the collectionQuery (uncached response), or sending the request with only the label (cached, but the metrics service may have to retrieve the collectionQuery on the fly). The above flow is assuming that the latter is faster.

**Comment by rushirajnenuji** [comment]
Implemented this support in: https://github.com/NCEAS/metacatui/commit/63ee3dd6f072e51059aaaae7b0c2a179510a2243

Deployed on : `https://handy-owl.nceas.ucsb.edu`

- Testing config: 
1. copy [`search-stage` config](https://github.nceas.ucsb.edu/walker/metacatui-config/blob/master/search-stage.js)
2. Set metricsUrl to point to MS test instance (i.e. `metricsUrl:'https://logproc-stage-ucsb-1.test.dataone.org/test/metrics'`) in this config

- Testing example: https://handy-owl.nceas.ucsb.edu/portals/9073552/Metrics

- Testing mechanism: 
1. created a portal from portal editor
2. set appropriate filters for this portal (in this example I simply searched for `carbon flux` text)
3. saved the portal

- Test result: The Metrics Service responds with metrics for the `collectionQuery` forwarded by MetacatUI.

**Comment by rushirajnenuji** [comment]
Hi @laurenwalker  - since we're making some changes to the `MetricsModel`, it would be great if you could review this [commit](https://github.com/NCEAS/metacatui/commit/63ee3dd6f072e51059aaaae7b0c2a179510a2243) whenever you get a chance. 

Moving this to testing column. Thank you!
