### ISSUE TITLE
Highlight the markdown help in the Portal Builder freeform pages

### ISSUE THREAD

**Issue by robyngit** [NCEAS/metacatui#1499]
**Describe the feature you'd like**
Some users reported that they didn't notice the link for markdown help that's just above the markdown editor. We may want to emphasize this help text somehow, and/or move it closer to the textarea.

**Is your feature request related to a problem? Please describe.**
Some users will be new to markdown when they create their first freeform page, so this help text is really important. The example text in the textarea is another source of guidance, but isn't helpful anymore once the user replaces it with their own content.

**Additional context**
This is how it currently looks:

- _Collapsed (default):_

<img width="1175" alt="Screen Shot 2020-08-11 at 17 39 22" src="https://user-images.githubusercontent.com/26600641/89951810-1773e680-dbfa-11ea-959a-0fe406237490.png">

- _Expanded:_

<img width="1175" alt="Screen Shot 2020-08-11 at 17 39 44" src="https://user-images.githubusercontent.com/26600641/89951807-1642b980-dbfa-11ea-82f4-f95806586f51.png">

**Comment by laurenwalker** [comment]
I like it collapsed. Perhaps we could just improve the text that the link is set on? ("See Markdown Cheatsheet" with a caret icon?)
