### ISSUE TITLE
Add ability to OR filters together in EditCollectionView

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/metacatui#1505]

**Comment by robyngit** [comment]
In the `feature-rule-groups` branch, it's now possible to edit the Portal definition's `exclude` and `operator` attributes in the Query Builder:

<img width="1382" alt="Screen Shot 2021-02-10 at 17 49 36" src="https://user-images.githubusercontent.com/26600641/107583069-69f18800-6bc8-11eb-966d-a873b3c5237f.png">

This could use some review, though I'll keep testing as I work on #1582
