### ISSUE TITLE
On-the-fly search fields using Solr field descriptions for EditCollectionView 

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/metacatui#1510]
Use the Solr API that lists all search fields and their descriptions to allow users to build a specific search filter for their collection definition. This could take advantage of the same views that are used when creating a custom search field in the portal data tab. The user would be presented a list of all the Solr fields, and then would provide a value for that field. This filter would get added to the search like any other search field that is used in the EditCollectionView now.

**Comment by laurenwalker** [comment]
Let's do another review of this during our next portals call, and then close this. We can always update the field names and descriptions in additional patch releases.

**Comment by laurenwalker** [comment]
@Robyn - Checking on this, is this done? I think we've decided on names and descriptions for the MVP at least

**Comment by robyngit** [comment]
Yes, I think the MVP at least is ready!
