### ISSUE TITLE
Newer version banner fails to send user to most recent version

### ISSUE THREAD

**Issue by laijasmine** [NCEAS/metacatui#1515]
**Describe the bug**
The `View it now` does not forward the user to the most recent dataset

**To Reproduce**
1. Open Safari
2. Go to https://arcticdata.io/catalog/view/doi:10.18739/A2JH3D23R
2. Click on `View it now`

The link sends you to: https://arcticdata.io/catalog/view/urn%3Auuid%3A044cfffb-e7ca-4a69-8ead-18ef7508e2f5

This is *not* the most recent version.

**Expected behavior**
It should send you to the most recent version (this works fine in Chrome): https://arcticdata.io/catalog/view/doi%3A10.18739%2FA26D5PB2S

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS Mojave
 - Browser safari
 - Version 13.1.2

**Comment by jeanetteclark** [comment]
@laijasmine did you check to see if there were private intermediate versions? this can interfere with the banner

**Comment by laijasmine** [comment]
ah ok there are some private intermediate versions. thanks!
