### ISSUE TITLE
Add attribute button in file "Describe" gets duplicated.

### ISSUE THREAD

**Issue by helbashandy** [NCEAS/metacatui#1528]
**Describe the bug**
The add attribute button the's listed on the left panel of the uploaded file describe modal gets duplicated.

**To Reproduce**
1. Go to https://dev.nceas.ucsb.edu/submit
2. Click on add files and upload a file.
3. Open attributes panel.
4. Click on Add attribute multiple times. 
5. Select the first added attribute and start writing anything. 
6. Notice the left panel
7. Also notice that you can no longer add an attribute. 

**Screenshots**
<img width="1680" alt="Screen Shot 2020-09-21 at 6 32 38 PM" src="https://user-images.githubusercontent.com/47407500/93836838-db8c6200-fc38-11ea-8a46-e7f999bc5702.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: chrome
 - Version : 2.12.0

**Comment by laurenwalker** [comment]
Thanks for the detailed report. I think this is the same bug from #799 which I've never managed to reproduce. I'll try your steps, thanks.

**Comment by laurenwalker** [comment]
Fixed, but after some testing I think this is different than #799, so we still need to figure out how to fix that bug.
