### ISSUE TITLE
Expand the editor's validation routine for funding info to cover award and funding elements

### ISSUE THREAD

**Issue by amoeba** [NCEAS/metacatui#1533]
When an EML 2.2.0 record containing structured funding information (`awward`) but not the old-style `funding` information _and_ the editor config specifies funding information as a required field, users get a validation error which stops them from saving.

This really only affects the data team right now as they do their typical ticket processing. The current workaround they use is to enter a throwaway value in the field tied to the `funding` element and remove it programatically after they save in the editor.

As discussed in https://github.com/NCEAS/metacatui/issues/1403 and on Slack, prior to getting full structured funding support in, we can relax validation for the presence of funding information in order to prevent users from having to put in throwaway values to get around validation. This quick fix will probably still be useful after structured funding information is put in.

**Comment by amoeba** [comment]
Okay, this is in and moved to the Review/QA column on ZenHub. I ended up having to query the project's objectDOM since the project model doesn't currently parse award. We'll wanna revisit this when we put in support for structured funding in #1403. I'll drop a note over there too.

**Comment by laurenwalker** [comment]
Works great, thanks
