### ISSUE TITLE
Generate portals for nested datasets

### ISSUE THREAD

**Issue by robyngit** [NCEAS/metacatui#1540]
**Describe the feature you'd like**
Replace parent datasets with portal pages on the Arctic Data Center

**Additional context**
This issue was transferred from https://github.com/DataONEorg/collections-portals-schemas/issues/75

**Comment by laijasmine** [comment]
I wanted to note that we might need to check with the authors before replacing all the parent datasets. There are some cases that I have encountered where the researcher prefers the nested datasets. For example: https://arcticdata.io/catalog/view/doi%3A10.18739%2FA2319S373

The data team can help keep track of those if that helps!

**Comment by laurenwalker** [comment]
Since this is more of an Arctic Data Center data management task, I'm going to close this issue here. @laijasmine and @jeanetteclark can track this work elsewhere if they decide to do this
