### ISSUE TITLE
Register Citation button accessibility issue - CSS fix on Safari

### ISSUE THREAD

**Issue by MayaSamet** [NCEAS/metacatui#1541]
@aebudden ran into this issue, Macbook pro running mojave 10.14.5 using safari 13.1.1. 

She was viewing a dataset with existing citation & needed to scroll to the bottom of the citation pane to register a new citation. She was only able to scroll all the way done briefly, then the scroll bar would bounce back up. So she was able to briefly view the button but not click it. When she continued scrolling it would just scroll on the pane behind. Screen recording included. @mbjones suggested that a CSS fix is needed on Safari to adjust the window pane height.

[Screen Recording 2020-10-14 at 2.35.25 PM-1.mov.zip](https://github.com/NCEAS/metacatui/files/5381000/Screen.Recording.2020-10-14.at.2.35.25.PM-1.mov.zip)

**Comment by amoeba** [comment]
Thanks for the report @MayaSamet and for the video especially. For anyone who looks at this bug:

- I can confirm the behavior on Safari (not Chrome, for example)
- The dataset showing the behavior is https://arcticdata.io/catalog/view/doi%3A10.18739%2FA2RN3081R
- From a quick look at the CSS, it doesn't look like we need a fix for Safari. Safari may actually be doing the correct thing here. The element that's not showing jumps out of its box with a `position: fixed` so I think the fix should focus on changing that

**Comment by laurenwalker** [comment]
I fixed this particular issue but also noticed that the metric modal windows were displaying pretty terribly on mobile, so I fixed those issues as well (related to #660).
The metrics  charts are still at high widths, so I will fix that in a later commit tied to #660
