### ISSUE TITLE
Standard Unit list for describing attributes not inclusive of all the pre-defined units.

### ISSUE THREAD

**Issue by BrennieDev** [NCEAS/metacatui#1544]
**Description**
In the arcticdata.io UI, the Standard Unit list present in the UI when describing an attribute with category set to "Numeric" is evidently missing one or more values. The issue was specifically noticed by the standard unit "percent" missing from the list, but it is possible that others are missing as well.

**To Reproduce**
1. Go to https://test.arcticdata.io/submit/urn%3Auuid%3Af631978d-a23e-45ee-a984-52cc1e163c1f (or any data package with attribute data).
2. Next to some data file, click on Describe -> Attributes to enter the modal to describe attribute data.
3. For any attribute, set category to "Numeric".
4. Observe that the list of standard units to choose from does not contain "percent".

**Expected behavior**
The list of standard units here is expected to contain "percent".

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 86.0.4240.75 (Official Build) (64-bit)

**Comment by amoeba** [comment]
Thanks for finding this and writing up a bug for it @BrennieDev!

I can confirm the same behavior and can see that this is something we missed in the editor's transition from EML 2.1.1 to EML 2.2.0. The units list is pulled from a GitHub tag:

https://github.com/NCEAS/metacatui/blob/dev-2.13/src/js/collections/Units.js#L20:L20

I'll update this to point to the 2.2.0 unit dictionary.
