### ISSUE TITLE
"Contains data files" query rule

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/metacatui#1548]
The `documents:*` filter is used to find metadata docs that document another object, which effectively means finding only data packages that contain data objects in addition to metadata objects. This now shows up in the query builder as this:

![Screen Shot 2020-10-22 at 2.20.12 PM.png](https://images.zenhubusercontent.com/5d152e12c27d0c306f021863/32eaf81f-1489-4de6-88ab-b09eb5699c10)

We should build a special rule/filter View for this particular rule

**Comment by robyngit** [comment]
Note that we want both a special UI for users to build a "Contains data files" true/false rule, _and_ to keep the `documents` field in the list of metadata fields a user can select from.
