### ISSUE TITLE
Organize Rule files into subfolders

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/metacatui#1551]
Let's create folders in the 'models' 'views' and 'templates' directories of the Metacatui repo and put all the new Query builder files in those folders, even if it's only one. I've been starting to organize things more this away and it's helped me during development find the file I need faster.

**Comment by robyngit** [comment]
Some of the new views and models could be used outside of the Query Builder. For example, we'll probably use the `QueryFields` collection, and the `QueryFieldSelectView` when we eventually build the custom search filter editor. Should these files go in the Query Builder directory?

**Comment by laurenwalker** [comment]
Name the directories whatever makes sense for the files
