### ISSUE TITLE
For the formatId field in the Query Builder, show a list of possible format IDs

### ISSUE THREAD

**Issue by robyngit** [NCEAS/metacatui#1565]
When a user selects the `formatId` field in the Query Builder, show a dropdown list of format IDs that have the raw format ID and the name of that format ID (this is already retrieved by MetacatUI)

**Comment by robyngit** [comment]
Added this with the commit: https://github.com/NCEAS/metacatui/commit/4da659a11271573b9c9a0c273b8da01630727ae3

I limited the options to formats that were also type METADATA, since the collection query has a `formatType: METADATA` rule automatically applied

**Comment by laurenwalker** [comment]
I constructed a query for this EML format and got a Solr syntax error. It looks like we aren't properly escaping the formatID

![Screen Shot 2020-11-24 at 12.09.37 PM.png](https://images.zenhubusercontent.com/5d152e12c27d0c306f021863/37b6fb9a-9534-4ffc-947c-ccf54c8af9a4)

**Comment by robyngit** [comment]
Fixed the Solr syntax error by escaping dashes positioned at the beginning of search terms for all queries built by the Filter model. Also found and fixed another error where sometimes the ObjectFormats collection wasn't fetched before the formatId select interface rendered, causing an error to show in the query builder. With these two issues fixed, I believe this UI is ready to use.
