### ISSUE TITLE
Change "Submit Dataset" Button on Web Upload Form UI to "Save Dataset"

### ISSUE THREAD

**Issue by mburrus** [NCEAS/metacatui#1575]
**Describe the feature you'd like**
Change the "Submit Dataset" button on the web data upload form UI. Our suggested change is "Save Dataset". Many users have given the feedback that "submit dataset" is easily confused with publishing their data set. 

**Is your feature request related to a problem? Please describe.**
Since users don't see the publish button until after they hit submit dataset, they don't know that a publish button exists at first.

This becomes frustrating when troubleshooting user issues because multiple users have reported "submitting their dataset for publishing" and it is difficult for us to understand their problem if we can't tell whether they have hit the publish button or the submit button.

**Comment by laurenwalker** [comment]
I can make the text of the button configurable so each repository can set it to what they'd like, since some repositories do make the dataset publicly available once it's initially submitted

**Comment by mbjones** [comment]
We repeatedly have this same request for Arctic Data Center, and so we might want to use this feature as well. Let's talk about the publishing lifecycle models in use by different repos and try to come up with a way for them all to be configurable. Here's a first stab at a couple of ways we do these things across Metacat repos:

1) ADC: a) User Save and revise loop; b) curator feedback and revise loop (R and MetacatUI); c) curator publish with DOI
2) KNB: a) User Save and revise loop; b) User Publish with DOI
3) ESS:DIVE: 2) User Dave and revise loop; b) user notifies curator with 'Publish' button?; c) curator review and revise loop; .... not really sure what happens next
4) OPC/Dangermond: a) User Save and revise loop; b) curator publish with DOI (is this right?)

**Comment by laurenwalker** [comment]
We can configure all repos/themes to use "Save dataset" instead of "Submit dataset" and see how that goes. We've been hesitant to use the word "Save" in the past because it may imply that a private or draft version will be saved. "Submit" clarifies that the repository data management team will be notified of a submission. But we change it and monitor how it goes.
