### ISSUE TITLE
Test the Query Builder in IE11 and Edge

### ISSUE THREAD

**Issue by robyngit** [NCEAS/metacatui#1576]
- [x] Tests in IE11
- [x] Test in Edge

**Comment by robyngit** [comment]
I tested a few portals in all themes in Edge, and the Query Builder looks good and seems to work as it should

**Comment by robyngit** [comment]
I was unable to load the Query Builder in IE11. I believe that getting it to work in this browser would take quite a lot of time. Some of the components that we use commonly throughout MetacatUI, such as underscore.js, throw syntax errors in IE11. This prevents a number of other views from loading as well. Based on the conversation in our meeting Tuesday, I believe it is sufficient that the "Your browser is out of date" message appears in these cases. I will close this issue for now, but perhaps a new issue should be opened if it's decided that we should invest time into getting MetacatUI compatible with IE11.

**Comment by mbjones** [comment]
I agree it is probably time to deprecate IE11 support altogether, and just put up a message to not use an obsolete browser.

**Comment by laurenwalker** [comment]
Agreed, we have already been doing this for a while. Thanks Robyn for helping with a polyfill issue though so that message can display in the first place.
