### ISSUE TITLE
Support rule groups in the Query Builder

### ISSUE THREAD

**Issue by robyngit** [NCEAS/metacatui#1582]
Once the schema [supports more complex definition filters](https://github.com/DataONEorg/collections-portals-schemas/issues/70), the Query Builder will need to support adding and editing rule groups, as depicted below. Users will be able to add a group using an "Add a Rule Group" button next to the "Add a Rule" button.

Although we plan to allow unlimited nested groups in the schema, in the editor we are not planning to support groups within groups. That means we'll need to show a warning when a user tries to open a portal with groups nested within groups.

![Screen Shot 2020-10-28 at 14.15.36.png](https://images.zenhubusercontent.com/5d2377a81799422cc7d89f1d/64927c1a-d438-4da2-b332-3f29d93974da)

**Comment by robyngit** [comment]
Definitions with nested rule groups can be created on the `feature-rule-groups` branch:

<img width="1420" alt="Screen Shot 2021-02-12 at 18 45 42" src="https://user-images.githubusercontent.com/26600641/107833912-b7096180-6d62-11eb-9f53-608b9dceea45.png">

This feature will need some final testing once we're ready to save 1.1.0 portal documents.

Note that in the UI, the user is only able to create 1 level of nested rule groups. However, if a portal document is opened in the editor that has multiple levels of nested rule groups, the Query Builder is able to render these.

**Comment by laurenwalker** [comment]
After review, there are no show-stopping issues with  the  rule groups feature. I created some issues that should be addressed, but they  shouldn't stop a release.
