### ISSUE TITLE
MetacatUI doesn't load in IE11 due to unsupported Object.assign() method in config files

### ISSUE THREAD

**Issue by robyngit** [NCEAS/metacatui#1592]
**Describe the bug**
MetacatUI won't load at all in IE11. The console gives the error message: `SCRIPT438: Object doesn't support property or method 'assign'` `config.js (4,1)`. The issue appears to be with the `MetacatUI.AppConfig = Object.assign({...` line in the config files. Apparently the `Object.assign()` method is [not supported in IE11](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign#Browser_compatibility).. There is, however, [a polyfill](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign#Polyfill).

**To Reproduce**
1. In IE11, navigate to  https://search.dataone.org, https://knb.ecoinformatics.org/data, or https://arcticdata.io/catalog/
2. See endless spinner & errors in console

**Expected behavior**
MetacatUI should load or should show a warning and *suggestion to use a modern browser*

**Desktop (please complete the following information):**
via BrowserStack:
 - OS: Windows 10
 - Browser: Internet Explorer 11
 - Version 11.785.16299.0

**Comment by laurenwalker** [comment]
Could you add that polyfill to app.js and see if that works?
I think we want to support IE 11 to a basic extent, but its ok if some features need to be disabled for IE11 users. We should be dispalying a warning message once the AppView loads, via the [`AppView.checkIncompatibility()`](https://nceas.github.io/metacatui/docs/AppView.html#checkIncompatibility) function which uses a user-agent RegEx matching via the [`unsupportedBrowsers` config](https://nceas.github.io/metacatui/docs/AppConfig.html#unsupportedBrowsers)

**Comment by robyngit** [comment]
I see that the `Object.assign()` polyfill is already in loader.js. I guess the problem is that the config.js file needs to run first. I tried adding the polyfill straight to one of the scripts in index.html, but now I'm getting a strange `SCRIPT1002: Syntax error` in `jquery.js (9597,5)`.. I'll keep working on it and see if I can resolve it..
