### ISSUE TITLE
The Portal Builder mobile menu is improperly positioned

### ISSUE THREAD

**Issue by robyngit** [NCEAS/metacatui#1599]
**Describe the bug**
The editor footer with save button now only appears in the Portal Builder when changes have been made to the portal (🎉). However, on small screens, before any changes have been made, the portal pages menu is still positioned 73px above the bottom of the page. This positioning is meant to leave room for the footer, but looks strange when the footer is hidden.

**To Reproduce**
1. Create a brand new portal on the ADC on a narrow screen
2. Before you make any changes, notice that the blue "Pages" bar is floating above the bottom of the screen.

**Expected behavior**
The div with class `section-links-toggle-container` should be set to `position: 0px` before the editor footer is displayed.

**Screenshots**
<img width="492" alt="Screen Shot 2020-11-04 at 10 46 29" src="https://user-images.githubusercontent.com/26600641/98133851-19151980-1e8c-11eb-9a75-59e3c29648e8.png">

**Additional context**
- The menu is currently positioned assuming that the height of the editor footer is always exactly 74px. However, there are some issues with this absolute height, see https://github.com/NCEAS/metacatui/issues/1596. The solution to that issue, depending on what it is, could have an impact on this one.
- For other issues with the portal builder mobile menu, see https://github.com/NCEAS/metacatui/issues/1597

**Comment by laurenwalker** [comment]
Hmm I feel like I fixed this one already. Perhaps only on the feature-dataone-portals branch?

**Comment by robyngit** [comment]
Just tried the `feature-dataone-portals` branch, same issue for me

**Comment by laurenwalker** [comment]
Okay, thanks for testing
