### ISSUE TITLE
Warn users when capitalization matters in the Query Builder

### ISSUE THREAD

**Issue by robyngit** [NCEAS/metacatui#1602]
**Describe the feature you'd like**
It would be nice to have some extra help text to indicate to users that capitalization will influence the data search results when they are building a collection.

**Is your feature request related to a problem? Please describe.**
When testing the Query Builder, results are sometimes different that I expected because I forgot that capitalization matters for some (all?) text filters.

**Comment by robyngit** [comment]
I found that only solr fields that are type `text` are case-sensitive. If a user has selected one of these fields in the query builder, a message will now appear when they focus on the value input:

<img width="1453" alt="Screen Shot 2021-02-16 at 18 07 12" src="https://user-images.githubusercontent.com/26600641/108134680-9f90e800-7084-11eb-9054-3308df6a5aba.png">

**Comment by laurenwalker** [comment]
That looks really good, thanks
