### ISSUE TITLE
Upload of large files prevents files from being associated with Data Package

### ISSUE THREAD

**Issue by vchendrix** [NCEAS/metacatui#1603]
**Describe the bug**
We now have two known occurrences of this happening with our users.  One happened in Metacatui 2.8.5 and the other in 2.12.0.  This issue is when users upload large files > ~3gb and  <= 10GB (our limit is 10GB) that take a long time to upload.  The resource map is never created and the files do not get associated with the new metadata file.  We were able to fix this by generating a resource map for the uploaded files for the metadata file. However, we do not find out about this particular problem if a user does not tell us.  

@FiannaOBrien may have some additional context.

**To Reproduce**
1. Create a metadata file
2. Save
3. Edit data package
4. Upload several large files that take many hours
5. not sure what happens next..maybe save?

**Expected behavior**
A user should be able to upload large files without loosing the association with their data package.

**Additional context**
If it helps, here are the data packages that this happened to. 

Private data package (you need to be an essdive-admin to see)
https://data-sandbox.ess-dive.lbl.gov/view/ess-dive-bde245f960c5e39-20201104T141345101

Public data package ( need to essdive-admin to see the private obsoleted packages)
https://data.ess-dive.lbl.gov/view/doi:10.15485/1682304

**Comment by laurenwalker** [comment]
Thanks Val, this may be related to #662, if the issue is that someone is clicking Save before the files are done uploading.

**Comment by laurenwalker** [comment]
I think this issue should be solved from the changes in MetacatUI 2.18.0 via #662, where the Save/Submit button is disabled until files are done uploading.

However #1897 should also help with this, by providing a warning when the user starts to upload a large file. This can be an opportunity to tell users there are other upload options (e.g. FTP) for huge files.
