### ISSUE TITLE
Static map showing wrong location

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/metacatui#1606]
The bounding box here should be in Greenland:

![Screen Shot 2020-11-18 at 11.46.29 AM.png](https://images.zenhubusercontent.com/5d152e12c27d0c306f021863/a7d949fe-3fb2-4476-9a36-d1aa447925f2)

**Comment by laijasmine** [comment]
seems like a reoccurring issue specifically for Greenland. Another dataset with the same [issue]( https://arcticdata.io/catalog/view/urn%3Auuid%3A14f26c17-8fb4-4bd8-885b-280733e7d7c7)

**Comment by laijasmine** [comment]
another ticket with this issue at the ADC - [dataset](https://arcticdata.io/catalog/view/urn%3Auuid%3A1122ee46-21c5-4aed-8b0a-55006ac5bbf5)

**Comment by amoeba** [comment]
Maybe I'm missing something, but from the coordinates above, it looks like the map is "correct" and that the person who entered the metadata entered things backwards. For a bounding box in Greeland, the eastern boundary will be a _larger_ number than the western boundary but, in this case, the eastern boundary is _smaller_. It's a bit of a head scratcher and maybe I have it wrong? Thoughts, @laijasmine?

**Comment by laijasmine** [comment]
Thanks for catching that @amoeba! I think you are right that the east west coordinates just need to be swapped. I have tested it here for my own sanity: https://test.arcticdata.io/view/urn%3Auuid%3A1f3e4a22-5c59-4cc1-9e87-e74db6226172

The way it is laid out it is a lot easier for me to spot if there is a swap in the North South coordinates but not so much in the east west coordinates. I'm wondering if anything can be changed i the UI to help make entering the information more accurate?

**Comment by amoeba** [comment]
I think we can do a lot better, yeah. We already have a ticket, https://github.com/NCEAS/metacatui/issues/425, describing adding an interactive map to the editor so users can verify their coordinates on a map. I think that'd make any mistakes very obvious.

**Comment by laijasmine** [comment]
sounds good. In the meantime I'll look into correcting those datasets

**Comment by laurenwalker** [comment]
Closing as this looks to be resolved.
