### ISSUE TITLE
Interface for accessing different structured citation formats

### ISSUE THREAD

**Issue by vchendrix** [NCEAS/metacatui#1608]
**Describe the feature you'd like**
In order to support different bibliography tools used be researchers, it would be nice to provide an interface for accessing different structured citation formats (bitex etc) 

**Is your feature request related to a problem? Please describe.**
It is difficult to ingest text citations into bibiliography databases.

**Comment by mbjones** [comment]
I think this would be covered by and is highly related to an earlier ticker #973 to support different CSL styles, including export in bibtex format. @rushirajnenuji this has been in your court. @vchendrix do you think the proposal in #973 would work for your case?

**Comment by rushirajnenuji** [comment]
Hi @mbjones  - yes, this was on the back burner for a while. I noticed that Lauren bumped this issue to the next pipeline. I'll actively start working on this.

**Comment by laurenwalker** [comment]
Closing as it sounds like a duplicate of #973. We can reopen if there's clarification on how it's different. Thanks
