### ISSUE TITLE
Render schema.org /  Google Structured Data Dataset tags in HTML display?

### ISSUE THREAD

**Issue by cboettig** [NCEAS/metacatui#162]
Migrated from https://github.com/NCEAS/eml/issues/274.

**Comment by laurenwalker** [comment]
@amoeba Do you think this issue can be closed? I think the schema.org tags are pretty complete by now?

**Comment by amoeba** [comment]
ah yep, thanks for picking this issue out @laurenwalker

**Comment by amoeba** [comment]
For anyone following along, all MetacatUI landing pages expose schema.org compatible metadata for all metadata formats (not just EML) and Google can see it. See https://search.google.com/test/rich-results?url=https%3A%2F%2Fsearch.dataone.org%2Fview%2Furn%3Auuid%3Aeb9d45be-f3d8-4300-af12-5668efe4f69a&user_agent=1.
