### ISSUE TITLE
Consider revisiting the implementation of DataONEObject.hasUpdates() method

### ISSUE THREAD

**Issue by amoeba** [NCEAS/metacatui#1623]
The `DataONEObject` Backbone model has a `hasUpdates` method that determines whether the associated DataONE Object needs updating (either because the sysmeta has been mutated on the client, or because the object bytes have changed, triggering a mutation of the file's checksum and size attribute in the sysmeta). It's mainly called when `DataONEObject.save()` is called as part of the logic of determining _what_ to save. See:

https://github.com/NCEAS/metacatui/blob/1d5f538f2df255a06eede3403ee7da95a0585114/src/js/models/DataONEObject.js#L1249-L1259

The way it currently works essentially relies on a string comparison between a string version of last copy of the sysmeta from the server and a string version of the current copy of the sysmeta the client holds. This can work in some scenarios but won't work when the method used to serialize the copy on the server differs from the way MetacatUI serializes sysmeta. This can be reproduced by creating a package in R and opening it with the editor. When I ran into this issue today, I saw differences between indentation (tabs, spaces, number of tab stops) and trivial whitespace despite the data contained in the sysmeta being otherwise equivalent.

This can cause what I would superfluous calls to update sysmeta and has negative impacts that scales with the number of members in a data package: If your package has 1000 data files and you edit it with the editor but only update the metadata, the editor still makes 1000 `updateSystemMetadata` calls. And (I'm not why yet), MetacatUI can't really keep up with these updates and eventually breaks.

I see a few options here:

1. Do nothing right now as it's not necessarily breaking anything that we know of at the moment
1. Try to make MetacatUI's sysmeta serialization routine serialize XML w/o insignificant whitespace. Downside is ugly XML.
1. Rewrite the current comparison method to be serialization-independent or at least less finicky about it
1. Look into changing how we track whether an object's sysmeta needs updating

I'm most interested in (3) and I think we could do it by converting each copy of the sysmeta from XML to a JS Object (which we've already got a helper for) and using `_.isEqual()` which does a deep object comparison.

What do others think?

**Comment by mbjones** [comment]
You make great points, and I totally agree that (3) is promising. Comparing XML as strings is highly unreliable. At a minimum, both copies would need to be canonical (see https://www.w3.org/TR/xml-c14n11/) for that to work, and even then it would be unreliable I think. Some tools have been developed that do tree-diffs of the XML content nodes, which is far more reliable and removes the problems with the flexibility in XML serialization. But it requires invoking an XML parser (which I might argue we need anyways, but that's another discussion...)

Serializing in JSON can have similar issues, as it also has much flexibility in how models are serialized. One reliable way could be to convert to JSON-LD, then compact and then expand the model and see if the resultsets are the same on the outgoing side. We do this for unit testing with CodeMeta JSON-LD documents. This last one might be the most tractable in the JS world. Case insensitivity might still bite you though.

**Comment by amoeba** [comment]
Thanks, and I realize I made a mistake in my description of (3): The method is named `toJson` but actually creates a plain old JavaScript Object which is what the comparison would be done on. Similar to `_.isEqual({"a": 1, "b": 2}, {"b": 2, "a": 1}) # => true`. I'll update the above bullet point too.

**Comment by robyngit** [comment]
I ran into the exact problem you described while working on issue #1418. I tried to fix it in commit 0831d6d7a37281c861f4dedd6788ef87565045ea like so (still in a WIP feature branch):

https://github.com/NCEAS/metacatui/blob/0831d6d7a37281c861f4dedd6788ef87565045ea/src/js/models/DataONEObject.js#L1255-L1271

**Comment by amoeba** [comment]
Right on, thanks for chiming in @robyngit. Parsing the second copy of the sysmeta-as-a-string into a duplicate Backbone Model is a slick approach too and might be better than using our `.toJson` helper.

**Comment by laurenwalker** [comment]
I tested this today and it looks to be working well. I'm going to close, but if there are other improvements to make related to this issue, feel free to push a commit and reopen.

**Comment by amoeba** [comment]
Sounds great, thanks @laurenwalker
