### ISSUE TITLE
Add some help text in the Register Citation Button for selecting the Type of Citation

### ISSUE THREAD

**Issue by laijasmine** [NCEAS/metacatui#1626]
**Describe the feature you'd like**
Add some help text in the `Type of Citation` in Register Citation button to make it clear when to use `cites` and when to use `uses`

**Is your feature request related to a problem? Please describe.**
I've been finding that I get confused sometimes when to use `cites` and when to select `uses`. This has also come up more than once with the datateam.

[Maya's blog post](https://arcticdata.io/blog/2020/10/getting-credit-for-data-creation-and-curation/) has been super useful to make sure I have everything straight:

> CITES the dataset (that is, the dataset is explicitly identified or linked to somewhere in the text or references) or USES the dataset (that is, uses the dataset but doesn’t formally cite it)

**Comment by laurenwalker** [comment]
Thanks Jamine. Rushiraj, we could probably implement this is a simple `title` alt text or a Bootstrap popover (with a slight delay)

**Comment by rushirajnenuji** [comment]
Thanks, Lauren and Jasmine. I'll try to squeeze this into the current patch release.

**Comment by rushirajnenuji** [comment]
Added `alt title` to the drop-down options.

![Screenshot.png](https://images.zenhubusercontent.com/5d152e0511232d5ce5b3f588/a9cb2f7d-4643-4c27-b7d7-694fc7c39851)
