### ISSUE TITLE
Prov charts don't show when version chain is patchy

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/metacatui#1627]
Example on ADC, per @jeanetteclark and @gothub: view/doi:10.18739/A2P55DH4M

The prov chart is not displaying because the MetadataView is only condisering the first PackageModel in the array set on the view, which in this case is an obsoleted package. Only the newer version of the package contains the provenance relationships.

The long-term solution is to use the proposed/in-progress version chain API: https://github.com/NCEAS/metacat/issues/1429 to determine if the packages are in the same version chain, and then parse prov from the most recent package in the chain that aggregates the given metadata object.

The short-term solution is to either:
A. Fetch the sysmeta of (almost) every package in the version chain that aggregates the given metadata object to determine that the packages are in the same version chain
B. Just assume the packages are in the same version chain and parse prov from the most recent one.

I'm going to go with B since this is an edge case and the version chain API will make things like this much easier.

**Comment by gothub** [comment]
Here is the obsolescense chain for the resmap for this dataset (urn:uuid:7e05fd08-c9f3-471a-9144-d296cdd9a200):

| resmap pid | obsoleted by | comment |
|-|-|-|
| resource_map_urn:uuid:59acb192-163d-480b-8b7a-614984d16e57 | resource_map_urn:uuid:618b3aba-1d23-4d83-bf7c-528e86f0fb86 ||
| resource_map_urn:uuid:618b3aba-1d23-4d83-bf7c-528e86f0fb86 | resource_map_doi:10.18739/A2P55DH4M  | this was the resmap that was selected, which btw doesn't contain any prov, and does not have a solr entry, i.e. it was not indexed |
| resource_map_urn:uuid:273164c8-0423-4fbd-8237-3ebde440b65c | resource_map_urn:uuid:bf77f7be-09b4-4e94-8c16-29b1be2e18aa ||
| resource_map_urn:uuid:bf77f7be-09b4-4e94-8c16-29b1be2e18aa | resource_map_urn:uuid:1acb3fcf-7440-43c4-85a1-1c2127f2b744 ||
| resource_map_urn:uuid:1acb3fcf-7440-43c4-85a1-1c2127f2b744 | resource_map_urn:uuid:3cc3861a-0899-4b10-96e7-10c6295bda6a ||
| resource_map_urn:uuid:3cc3861a-0899-4b10-96e7-10c6295bda6a | urn:uuid:7e05fd08-c9f3-471a-9144-d296cdd9a200 ||
| urn:uuid:7e05fd08-c9f3-471a-9144-d296cdd9a200  || this was the latest resmap that should have been selectd, that did contain the desired prov relationships |
