### ISSUE TITLE
Portal editor's query builder isn't handling special characters completely

### ISSUE THREAD

**Issue by amoeba** [NCEAS/metacatui#1629]
**Describe the bug**
Jasmine found this while working on the Arctic Report Card portal: When a semantic term IRI is entered into the value field such as:

> `http://ecoinformatics.org/oboe/oboe.1.2/oboe-core.owl#MeasurementType`

you end up with malformed Solr queries being sent.

**To Reproduce**
1. Go to test.arcticdata.io
2. Create a portal
3. In one of the Rules, select Semantic Annotation (this probably doesn't matter at all, Text works too)
4. Enter `http://ecoinformatics.org/oboe/oboe.1.2/oboe-core.owl#MeasurementType` for  the value
5. Notice the invalid queries being sent

**Expected behavior**

The portal editor needs to allow content like the above.

**Desktop (please complete the following information):**

macOS 11.1, Chrome 87.0.4280.88

**Additional context**

You can see the malformed query here:

> `https://test.arcticdata.io/metacat/d1/mn/v2/query/solr/?q=((isPartOf:urn\:uuid\:b39f6bf5-b089-4683-8970-f5a226ca3d09)%20OR%20(sem_annotation:http\://ecoinformatics.org/oboe/oboe.1.2/oboe-core.owl`

It kinda looks like the `#` is the problem. See how the query is truncated? I'd have to look at the Lucene docs again but I know we handle this case in the Data Catalog by urlencoding the value, like:

> `sem_annotation:%22http%3A%2F%2Fecoinformatics.org%2Foboe%2Foboe.1.2%2Foboe-core.owl%23MeasurementType%22%20AND%20`

**Comment by mbjones** [comment]
We should be fully encoding wrt [RFC3986](https://tools.ietf.org/html/rfc3986#section-2.2). That URL encoding, however, differs from XML escaping, so I would argue that, in the editor, the term URI should probably not be escaped -- it should only be escaped when data is being embedded inside a URL, as it is being prepared to be sent to SOLR. This is true of all data being embedded in the URL, and so we should be careful to be consistently doing it only when serializing our URL string for retrieval. If data are encoded and stored earlier that way, we run the risk of double-encoding.

**Comment by robyngit** [comment]
>  it should only be escaped when data is being embedded inside a URL, as it is being prepared to be sent to SOLR.

This is exactly what the `Filter` model does with the [escapeSpecialChar function](https://github.com/NCEAS/metacatui/blob/aca0de3ecd3355b728d0ef83350fd52fc739c924/src/js/models/filters/Filter.js#L429-L450). It was not escaping `#` characters though, so I added it to the list. With that fix, searching for `http://ecoinformatics.org/oboe/oboe.1.2/oboe-core.owl#MeasurementType` in the query builder now works, so I'm closing this issue. If there are other characters that need to be escaped or other annotation searches that are problematic, feel free to re-open!
