### ISSUE TITLE
Saving datasets with spatial entities

### ISSUE THREAD

**Issue by laijasmine** [NCEAS/metacatui#1633]
**Describe the bug**
Unable to save datasets with spatial entities. The following error is generated:
```
Error inserting or updating document: urn:uuid:15efb248-cff7-4109-b59c-9e2f285e1b50 since <?xml version="1.0"?><error>cvc-complex-type.2.4.a: Invalid content was found starting with element 'spatialRaster'. One of '{annotation, purpose, introduction, gettingStarted, acknowledgements, maintenance, contact}' is expected.</error>
```
**To Reproduce**
1. Go to a dataset with a spatial entity: https://test.arcticdata.io/view/urn%3Auuid%3Ac2fb00ab-8291-408f-b6a9-b253a6bfdf3b
2. Edit the dataset (eg. edit something in the abstract)
3. Click submit

**Expected behavior**
The dataset to be submitted successfully

**Screenshots**
<img width="839" alt="Screen Shot 2020-12-18 at 5 42 40 PM" src="https://user-images.githubusercontent.com/13112379/102817685-165f7c80-4385-11eb-928e-14962a7b632e.png">

**Desktop (please complete the following information):**
 - OS: Mojave
 - Browser: chrome

**Additional context**
The message also says that it will send an email to the support team with the draft but I don't believe this step happens at the moment.

**Comment by laijasmine** [comment]
wanted to check in on this issue as it still is a blocker in editing datasets of this kind

**Comment by laurenwalker** [comment]
Another researcher came across this error today. Added High priority label. Will try to get into the next release.
