### ISSUE TITLE
Files removed from package when user doesn't have write or changePermission

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/metacatui#1638]
**To reproduce:**

Opena  package in the editor with two data files. The first data file should have an access policy that grants you read, write, and changePermssion. THe second data file only grants you read permission. Edit part of the EML and save. Notice that only the first data file is in the package.

**Expected behavior:**
Even if someone does not have write or changePermission on a data object, it should remain in the aggregation.

**Comment by robyngit** [comment]
Hey @laurenwalker, I think this issue might be a duplicate of #1418, which is fixed but still in the `develop` branch

**Comment by laurenwalker** [comment]
Thanks Robyn, I just tested this and it does seem to be fixed with the changes on the develop branch. Thanks
