### ISSUE TITLE
Dropdown menu blocked by edit portal button

### ISSUE THREAD

**Issue by laijasmine** [NCEAS/metacatui#1649]
**Describe the bug**
The dropdown menu is blocked by the Edit portal button when trying to navigate away from the portal page.

**To Reproduce**
1. Login using your ORCiD
2. Go to any portal page
2. Click your name on the top right corner
3. Try to select one of the options in the dropdown menu

**Expected behavior**
Be able to click on one of the options to navigate away.

**Screenshots**
<img width="1279" alt="Screen Shot 2021-01-15 at 9 34 18 AM" src="https://user-images.githubusercontent.com/13112379/104760136-c79fcb00-5715-11eb-9a01-3ad3299b3723.png">

**Desktop (please complete the following information):**
 - OS: Mojave
 - Browser chrome and firefox
 - Version 7.0.4280.88  and 83.0

**Comment by robyngit** [comment]
Thanks, @laijasmine ! We also have this issue documented in #1598, though not with the helpful details you've provided here.

**Comment by laijasmine** [comment]
Ah thanks @robyngit!

**Comment by laurenwalker** [comment]
Closed with #1725
