### ISSUE TITLE
Attribute editing form doesn't show on re-editing

### ISSUE THREAD

**Issue by csjx** [NCEAS/metacatui#166]
When re-editing entity or attribute information, the attribute form is not being shown on the second time editing.  Steps to reproduce:

1) Choose an existing package to edit in the search list
2) Edit the entity or attribute information (pane switching works)
3) Close the modal dialog
4) Choose `Submit`
5) Open the modal dialog again
6) Click on the `Attributes` tab.

At this point, any calls to `showTab()` are only showing the `Overview` tab form, even though the attributes tab will be highlighted.

**Comment by laurenwalker** [comment]
I changed EMLEntityView.showTab() so that the tabs are switched manually instead of with Bootstrap, which seemed to be unreliable.
