### ISSUE TITLE
Verify injected JSON-LD in MetadataView matches SOSO 1.2.0

### ISSUE THREAD

**Issue by amoeba** [NCEAS/metacatui#1662]
SOSO 1.2.0 was [released](https://github.com/ESIPFed/science-on-schema.org/releases/tag/1.2.0) yesterday and we should run through it and see if we should make any tweaks.

**Comment by amoeba** [comment]
The structure of the SOSO Dataset recommendation is pretty similar to what I've seen before and everything we have here looked good. I did see one place for improvement in the identifier property: SOSO [strongly recommends](https://github.com/ESIPFed/science-on-schema.org/blob/master/guides/Dataset.md#identifier) using the [PropertyValue](https://schema.org/PropertyValue) pattern when possible so I've added support for using that pattern for DOIs:

```json
  "identifier":
      {
        "@id": "https://doi.org/10.5066/F7VX0DMQ",
        "@type": "PropertyValue",
        "propertyID": "https://registry.identifiers.org/registry/doi",
        "value": "doi:10.5066/F7VX0DMQ",
        "url": "https://doi.org/10.5066/F7VX0DMQ"
      }
```

Done in 68be09b9ce2f6fcc291a41af04858cc67c6383a7.

There are more ways we can improve our JSON-LD (funder, variableMeasured) but those are already tracked in other tickets and need more work.

**Comment by mbjones** [comment]
Thanks, @amoeba for getting right on these

A couple of other things that I think would be useful, although these likely could be in distinct tickets:

- ensure that our Provenance traces from our ORE docs are represented (following the SOSO Guide: [Dataset - Provenance Relationships](https://github.com/ESIPFed/science-on-schema.org/blob/1.2.0/guides/Dataset.md##provenance-relationships)). this will be helpful to provide real-world examples.
- ensure we have `schema:dateModified` represented following the [Guide: Dataset - Time of resource modification](https://github.com/ESIPFed/science-on-schema.org/blob/1.2.0/guides/Dataset.md#howmodification_times)
    - I see `datePublished` but often not `dateModified` in our records
    - I think `dateModified` should be derived from the most recent `dateSystemMetadataModified` value from the system metadata from the metadata document or the package. Thus, if either the metadata document content or the ORE content (like prov relationships) changes, it would get a regenerated JSON-LD and reharvested. This probably also applies to our sitemap lastMod date.
    - For example, it appears to be missing from this record: [doi:10.18739/A2JM23H1J](https://search.dataone.org/view/doi%3A10.18739%2FA2JM23H1J)

**Comment by amoeba** [comment]
Nice catches @mbjones. I'll make a ticket for the prov suggestion and make the `dateModified` change now.

Right now, I think all of the info in our JSON-LD comes from _just_ the metadata record + its sysmeta so using the metadata records' sysmeta datemodified value seems like the right thing to do at the moment.

You make a great point about possibly using the datemodified value from the ORE's sysmeta in the future. And the sitemap date has the same problem, mainly because we don't store packaging information in an easily queryable form in the database (yet? ;)).

**Comment by amoeba** [comment]
Okay, [ticket](https://github.com/NCEAS/metacatui/issues/1663) made. Thanks again.
