### ISSUE TITLE
Instance of endless spinner when Editor is saving

### ISSUE THREAD

**Issue by amoeba** [NCEAS/metacatui#1665]
I think I finally found a situation which I can reproduce that causes the editor's Save button to spin endlessly.

It looks like a copy paste error that got introduced at some point. It's in DataPackage.save and is an unhandled exception that gets thrown when the save request fails. It's due to using a variable `errorMsg` that was never defined.

https://github.com/NCEAS/metacatui/blob/a328f00edf75636839c752fbbbcf1f770689ae11/src/js/collections/DataPackage.js#L1350-L1356

Changing this to, for example, `$(data.responseText)` instead fixes things.  Given where the error is, I think it's reasonable that this could be the issue others have been running into.

Thoughts @laurenwalker, @csjx?

**Comment by laurenwalker** [comment]
Good catch, Bryce, that sounds like a good fix to me

**Comment by amoeba** [comment]
Change made in 9cbfbc2528a7abf586262b0c74138daa1f042b20 and issue moved to Review/QA on ZenHub.
