### ISSUE TITLE
duplicate citations shown in citation view

### ISSUE THREAD

**Issue by mbjones** [NCEAS/metacatui#1673]
**Describe the bug**
When looking at the citation view for a specific data set, two identical citations are listed for the same dataset.

**To Reproduce**
1. Go to https://knb.ecoinformatics.org/view/doi:10.5063/F1891459
2. Click on 'Citations'
3. View the duplicated citations

**Expected behavior**
Only one citation should be listed. Two citations with the same DOI should not be shown, and/or should not be possible in the metrics DB.

**Screenshots**
<img width="1510" alt="citation-list" src="https://user-images.githubusercontent.com/766407/109592685-1f26aa00-7abc-11eb-826a-33586ed8a931.png">

**Desktop (please complete the following information):**
 - OS: Mac OS 10.14.6
 - Browser: Firefox
 - Version 86.0

**Comment by laurenwalker** [comment]
@rushirajnenuji Could you look into why this bug is happening?

**Comment by rushirajnenuji** [comment]
Hi Lauren - yes, I'll get this resolved asap. Thanks!

**Comment by rushirajnenuji** [comment]
Solved this issue from within the Metrics Service. No action steps are required on here.
