### ISSUE TITLE
DOI and File Name Search on the SASAP Portal is not filtering data packages

### ISSUE THREAD

**Issue by samanthacsik** [NCEAS/metacatui#1676]
**Describe the bug**
Typing a DOI or File Name into either of those search fields on the SASAP portal does not apply any filter to the collection of datapackages (i.e. it returns 121 out of 121 total data packages contained in the portal)

**To Reproduce**
1. Go to https://knb.ecoinformatics.org/portals/SASAP/Data 
2. Click on the 'Identifier' tab 
3. Type any DOI into the DOI or ID search field (I just grabbed the first DOI that appears in the SASAP corpus: doi:10.5063/F1891459)
4. See error: Returns "Datasets 1 to 25 of 121" and does not filter specifically for "doi:10.5063/F1891459"

**Expected behavior**
The DOI filter should return just one datapackage (e.g. just doi:10.5063/F1891459), not all 121.

**Screenshots**
![Screen Shot 2021-03-02 at 11 57 32 AM](https://user-images.githubusercontent.com/43836046/109707509-1af79c80-7b4f-11eb-9d24-a6a16fe3aad6.png)

**Desktop (please complete the following information):**
 - OS: iOS version 10.14.6 (Mojave)
 - Browser: chrome
 - Version: 88.04324.192

**Smartphone (please complete the following information):**

**Additional context**

**Comment by robyngit** [comment]
Thanks @samanthacsik, these details are helpful! I believe this might the same as this issue: https://github.com/NCEAS/metacatui/issues/1168.

**Comment by amoeba** [comment]
Might be, @robyngit, thanks for the link. I checked out the Solr query and it definitely has the wrong structure because it `OR`s on the filter value instead of `AND`ing. But looking at the Portal doc I see that the filter is specifying an `OR`. I wonder if we can't just change that here and elsewhere?

```xml
<filter>
  <label>DOI or ID</label>
  <field>id</field>
  <field>documents</field>
  <field>resourceMap</field>
  <operator>OR</operator>
  <filterOptions>
    <placeholder>doi:10.5063/F18P5XTN</placeholder>
    <description>unique ID of data package or object</description>
  </filterOptions>
</filter>

```

**Comment by amoeba** [comment]
I just checked and it looks like changing the operator to AND doesn't change the resulting Solr query.

**Comment by robyngit** [comment]
@amoeba , normally we `OR` ID filter queries onto the rest of the portal solr query, see [this comment](https://github.com/NCEAS/metacat/issues/1494#issuecomment-802110627) for details. There is however a `mustMatchIds` option that can be set to make sure the ID filters are `AND`ed on in certain cases. I switched this for the PortalView filters, where clearly we want to search *within* the portal collection.

**Comment by amoeba** [comment]
Thanks @robyngit
