### ISSUE TITLE
Portal query builder doesn't escape special characters

### ISSUE THREAD

**Issue by jeanetteclark** [NCEAS/metacatui#1677]
**Describe the bug**
Adding a special character (& in my case) to the query builder text causes an error

**To Reproduce**
1. Add a query rule
2. Select "Creator Full Names and Organizational Names"
3. Add "ADF&G" to the text

**Expected behavior**
Seems that we should be able to escape the `&`

**Screenshots**
<img width="1188" alt="Screen Shot 2021-03-02 at 2 38 51 PM" src="https://user-images.githubusercontent.com/24237074/109719067-5a30e800-7b65-11eb-9e85-ce2cffe23a93.png">

**Desktop (please complete the following information):**
 - OS: Mojave
 - Browser: Chrome
 - Version: 88.0.4324.192

**Comment by robyngit** [comment]
Good catch! Thanks for finding this. Fixed in the `develop` branch: <img width="1129" alt="Screen Shot 2021-03-02 at 18 15 42" src="https://user-images.githubusercontent.com/26600641/109727987-5d3ad100-7b83-11eb-8c55-3be6e53da6d0.png">
