### ISSUE TITLE
Rename "site" filter field in query builder

### ISSUE THREAD

**Issue by jeanetteclark** [NCEAS/metacatui#1678]
**Describe the feature you'd like**

I think just "site" is a bit confusing and doesn't quite match what the field actually looks at. To me, site means like "HAW-003", some arbitrary site name). I think "site description" or "place description" would be a little more intuitive if you wanted to constrain your search to the Arctic Ocean, for example, but don't want to enter a bounding box.

Definitely open to other suggestions on the replacement name but I definitely think it should contain the word "description"

The feedback that triggered this was a user in our training trying to constrain dataset results to the San Francisco bay area using text - they were trying do it using "place keyword" which yielded few/no results since that is only for FGDC metadata

**Comment by robyngit** [comment]
I like "place description" - I think people might be more likely to search for "place" over "site", what do you think?

Also, do you think it would help to come up with another name for the "place keyword" field as well?

**Comment by amoeba** [comment]
I think it makes sense to think about a rename in the context of the UI where it shows up:

<img width="354" alt="Screen Shot 2021-03-04 at 5 40 40 PM" src="https://user-images.githubusercontent.com/563/110059465-c1d76680-7d10-11eb-9bea-0e627db352b1.png">

I'd remove Geoform and Place keyword and rename Site to "Geographic Description". Maybe instead, make this section look like:

![redesign](https://user-images.githubusercontent.com/563/110059388-9bb1c680-7d10-11eb-9f79-878d193ad638.png)

> they were trying do it using "place keyword" which yielded few/no results since that is only for FGDC metadata

I'd say that not all Solr fields are worth exposing in the UI. Might be worth a review?

**Comment by mbjones** [comment]
👍 I agree a further review is needed. There are many SOLR fields which are holdovers from our Mercury/FGDC roots, and many of those are not populated by our current indexer, and therefore not useful for the UI and portals. We should exclude those, or, if we decide they are needed, then figure out to make sure the index is properly populated. @laurenwalker and @robyngit did a first pass at this review through the spreadsheet that Lauren developed -- maybe that would be a good place to revisit this with another pass.

**Comment by robyngit** [comment]
There have been some changes made in the query builder since we made that spreadsheet, so [here's an updated version](https://docs.google.com/spreadsheets/d/1op1aBpNVzH51u4Q7l6IrPUWM5SHLtn7dSkeUXgeCvGk/edit?usp=sharing) that lists the fields in the order and category they are currently displayed. Please feel free to make comments or changes directly in that spreadsheet.

**Comment by amoeba** [comment]
Thanks @robyngit. I took a look and made some comments.

**Comment by laurenwalker** [comment]
I changed it to 'Site description' for now, to at least get some kind of improvement out the door. These names are very simple to change, so we can discuss a better name and change it again easily.
