### ISSUE TITLE
Prevent users from building custom search filters with search fields that are mis-matched to the filter type

### ISSUE THREAD

**Issue by robyngit** [NCEAS/metacatui#1687]
Currently, a user can build a custom search filter that will result in invalid or nonsensical searchers. For example, they could create a `dateFilter` that uses `submitter` as the solr search field:
<img width="500" alt="Screen Shot 2021-03-16 at 14 14 32" src="https://user-images.githubusercontent.com/26600641/111359688-34760980-8662-11eb-81a0-eed2237edd2d.png">

We should limit the available filter types based on which metadata field(s) have been selected, and vice versa, like so:

<img width="722" alt="Screen Shot 2021-03-16 at 14 18 51" src="https://user-images.githubusercontent.com/26600641/111359968-933b8300-8662-11eb-9494-12c27e90c441.png">

**Comment by laurenwalker** [comment]
I found this issue too, and (accidentally)  created some duplicate but more precise GH issues. I think these should be fixed before we release this feature. I think it would be bad form to allow users to create filters that will result in errors. 

I'm going to close this issue so  we can focus on specific bugs/tasks of this kind that may be released iteratively. (see #1855 #1854)
