### ISSUE TITLE
The portal metrics page shows the wrong values if you searched on the data page first

### ISSUE THREAD

**Issue by robyngit** [NCEAS/metacatui#1695]
**Describe the bug**
If the metrics page is rendered following a search on the data page, metrics are shown for the search results rather than for the entire portal collection.

**To Reproduce**
1. Go to the SASAP portal data page: https://knb.ecoinformatics.org/portals/SASAP/Data. Note that there are 121 datasets in that collection.
<img width="1046" alt="Screen Shot 2021-03-16 at 19 47 29" src="https://user-images.githubusercontent.com/26600641/111394172-8b92d300-8690-11eb-86f2-7ced4730fb35.png">

2. Search for something using the search filters, like "Bethel" under community. Note that there are 17 results:
<img width="1046" alt="Screen Shot 2021-03-16 at 19 47 45" src="https://user-images.githubusercontent.com/26600641/111394188-977e9500-8690-11eb-89ab-e73039faa3a4.png">

3. Click on the "Metrics" tab, see that the Metrics shows there are only 17 datasets in the collection and 2GB of content.

<img width="1046" alt="Screen Shot 2021-03-16 at 19 47 49" src="https://user-images.githubusercontent.com/26600641/111394511-402cf480-8691-11eb-9271-3ae55f257fde.png">

4. Do a hard refresh (`Cmd` + `Shift` + `R`) and see that now Metrics shows 121 datasets and 9GB of content.

<img width="1046" alt="Screen Shot 2021-03-16 at 19 53 49" src="https://user-images.githubusercontent.com/26600641/111394569-60f54a00-8691-11eb-9c98-ccb801e0ee44.png">

The trick to reproduce this is to search for something before the Metrics page is rendered. If you were to navigate to the Metrics page *and then* search for something on the Data page, then there correct metrics will always be shown.

**Expected behavior**
The metrics should be based on the collection and not the search results

**Comment by mbjones** [comment]
@laurenwalker do you think this is a metrics service issue, or a MetacatUI issue with how it is requesting metrics for the portal?

**Comment by robyngit** [comment]
This was just a MetacatUI issue with how the metrics page was creating its query (it included all the search filters, instead of just the definition filters). Fixed on the `feature-rule-groups` branch so that the metrics page uses the 1.1.0 definition query construction.
