### ISSUE TITLE
500 error if request is too large

### ISSUE THREAD

**Issue by helbashandy** [NCEAS/metacatui#1698]
**Describe the bug**
Portals that are associated with a large number of PIDS sends a large request through the [getRequestType](https://github.com/NCEAS/metacatui/blob/master/src/js/models/Stats.js#L964) which resolves it to be sent as a POST request. Metacat responds with 500 error when requesting data package summary, latest updates, file formats, and time period of data in portal.

Example response: 

```
<?xml version="1.0" encoding="UTF-8"?><error detailCode="2821" errorCode="500" name="ServiceFailure">
<description>Solr server error: org.apache.solr.client.solrj.SolrServerException: org.apache.solr.common.SolrException</description>
</error>
```

**To Reproduce**
1. Go to https://data.ess-dive.lbl.gov/portals/CDIAC/Metrics 
2. Notice the metrics loading.

**Screenshots**
<img width="1440" alt="68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3565343266343264376437653266623934386566356330392f35326533643865312d613832642d343762382d393761632d313335656566306539363230" src="https://user-images.githubusercontent.com/47407500/112297748-79e29a00-8c53-11eb-9c8a-8fe09726289f.png">

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser: Chrome
 - Version: 2.12.0

**Additional context**
For more information on the bug and the request details, here's the [original logged bug on ESS-DIVE.](https://github.com/ess-dive/ess-dive-catalog/issues/462#issue-800851389)

**Comment by mbjones** [comment]
@helbashandy we noticed this problem last year and it was fixed in MetacatUI under issue #1346, along with improvements to the metrics service itself. I think ESS-DIVE is behind on the deployed Version so you are still seeing the issue. @laurenwalker what release was that in?

**Comment by vchendrix** [comment]
> @helbashandy we noticed this problem last year and it was fixed in MetacatUI under issue #1346, along with improvements to the metrics service itself. I think ESS-DIVE is behind on the deployed Version so you are still seeing the issue. @laurenwalker what release was that in?

ESS-DIVE is on 2.12.0 but we will be upgrading to 2.13.4 soon.  Will that fix it?

**Comment by mbjones** [comment]
Based on the release notes, I think the fix was in 2.13.2. So probably good, but hopefully @laurenwalker can clarify -- I think there were some related fixes later as well, but those might have been mainly in the metrics service and not metacatui.

**Comment by laurenwalker** [comment]
@helbashandy - I tried to look at the original bug log that you linked to (https://github.com/ess-dive/ess-dive-catalog/issues/462#issue-800851389) but I am getting a 404. Do I need access to that repo?

It's hard for me to tell exactly what the error from Metacat is. The fix to the 'too many clauses' Solr issue from #1346 was introduced in 2.12.0 and requires Solr `join` support. What version of Metacat and Solr are you using?

**Comment by laurenwalker** [comment]
Per the release notes for 2.12.0, if you are using a Solr version that supports `join`s (later than 4.0.0, I believe), you need to configure your MetacatUI to `enableSolrJoin`:

![Screen Shot 2021-04-14 at 10.11.30 AM.png](https://images.zenhubusercontent.com/5d152e12c27d0c306f021863/8a6ef881-bf06-4338-a737-0ed562370cb0)

It is disabled by default to be on the safe side for backwards compatibility with Metacat.

When I look at your configuration on https://data.ess-dive.lbl.gov in the console, it looks like you have Solr joins disabled:

![Screen Shot 2021-04-14 at 10.10.13 AM.png](https://images.zenhubusercontent.com/5d152e12c27d0c306f021863/7c74e2d1-f5d5-4c45-b2ea-e73126108cb2)

**Comment by helbashandy** [comment]
@laurenwalker - We're still on Metacat `2.12.3` which uses a Solr version less than v4 so we didn't enable that in configs yet. Thanks for the pointers.

**Comment by laurenwalker** [comment]
@helbashandy Ok, gotcha. yeah unfortunately there's no fix to this particular issue without a Solr upgrade. Although the forever spinner should be replaced with an informative message, at least.
