### ISSUE TITLE
Prefer D1 resolve URIs in replaceEcoGridLinks

### ISSUE THREAD

**Issue by amoeba** [NCEAS/metacatui#17]
Hey @laurenwalker, last night @mbjones made a call to switch to D1 resolve URIs from using MN object service URIs for the EML Online Distribution URLs. I took a look at the code and it looks like it's a simple fix. I'll take a stab at it but could use a quick review.

**Comment by amoeba** [comment]
Committed in fd5fc361a9628641d1622d35bf63a0de0cfc82cb

Is there anyone else to make this change?

**Comment by laurenwalker** [comment]
Thanks, I think that's the only place
