### ISSUE TITLE
Replace Google maps with Cesium

### ISSUE THREAD

**Issue by robyngit** [NCEAS/metacatui#1720]
Replace the Google map that is currently used in the `DataCatalogView` and `DataCatalogViewWithFilters` with a Cesium map

Related issues: https://github.com/NCEAS/metacatui/issues/1436, https://github.com/NCEAS/metacatui/issues/1514, https://github.com/NCEAS/metacatui/issues/1520

**Comment by mbjones** [comment]
Sounds good. I think for a while at least this should be a configurable choice, not outright removal of the Google Map options. If most themes move to using Cesium, then we could deprecate the google maps support and remove it in a later release, but not without sufficient notice and discussion with various MetacatUI deployments.

**Comment by laurenwalker** [comment]
Let's do the development for this on a separate branch than the Cesium work for portals and PDG. Keeping that development work on different branches will prevent us from having to delay releases until both are done.

**Comment by robyngit** [comment]
The development for this issue is now in the branch named [`feature-#1720-cesium-data-catalog`](https://github.com/NCEAS/metacatui/tree/feature-%231720-cesium-data-catalog), and the choice of whether to use Google maps or Cesium in the search catalog is now configurable.

**Comment by laurenwalker** [comment]
I converted this to an Epic since this work will likely happen in stages. @robyngit Feel free to add issues for individual steps, such as planning, design, and the coding/implementation steps.
