### ISSUE TITLE
Cesium for data portals MVP

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/metacatui#1724]
This Epic contains all the issues related to releasing an MVP version of Cesium for data portals, specifically for the Permafrost Discovery Gateway. We need to build a basic interface in Cesium for the user to pick data layers and view metadata about those layers. Each portal instance may have configurations for different data layers and tile services. For the MVP, we might not support direct editing of those configs in the portal editor, but the PortalView should be able to parse those configs and display those layers in a Cesium viz section.

**Comment by robyngit** [comment]
@laurenwalker, all of the changes from the `feature-cesium-portals` branch are now merged into the `develop` branch
