### ISSUE TITLE
ADC theme portals header buttons are overlapped and un-clickable at times

### ISSUE THREAD

**Issue by helbashandy** [NCEAS/metacatui#1725]
**Describe the bug**
The ADC css have an overlap layer that dis-allow the user to click on their username link and select any of the dropdown menu items. Also, the ADC logo is not clickable when a temporaryMessage banner is set. 

**To Reproduce**
Go to the portals page of ADC with a temporaryMessage and see the header.

Few issues will reveal:

1. The temoroaryMessage banner overlays near the portal title.
2. The edit portal button overlays on top of the username link with the dropdown when the temporaryMessage banner is set. 
2. If edit portal button is hidden, note that the username link is no longer being clickable unless the temporaryMessage banner is removed. 
3. After the banner is removed, the dropdown menu out of the username is no longer clickable and it is overlayed by the portals tabs. 

**Screenshots**

<img width="1676" alt="Screen Shot 2021-04-28 at 1 10 01 AM" src="https://user-images.githubusercontent.com/47407500/116369963-cd01bc80-a7be-11eb-93ad-b6afee377ba7.png">
<img width="1680" alt="Screen Shot 2021-04-28 at 1 10 16 AM" src="https://user-images.githubusercontent.com/47407500/116369974-cf641680-a7be-11eb-8df0-3132d7504194.png">
<img width="1677" alt="Screen Shot 2021-04-28 at 1 10 28 AM" src="https://user-images.githubusercontent.com/47407500/116369978-d0954380-a7be-11eb-9c06-4f27bb91a642.png">
**Desktop (please complete the following information):**
 - OS: [e.g. iOS] iOS
 - Browser [e.g. chrome, safari] chrome 89.0.4389.114 
 - Version [e.g. 22] 2.15.1

**Additional context**

**Comment by robyngit** [comment]
Note: The same issue is documented in #1649, though it doesn't include the issues with the temporary message banner. Also see #1598.
