### ISSUE TITLE
Show coordinates of the mouse and a scale bar in CesiumView

### ISSUE THREAD

**Issue by robyngit** [NCEAS/metacatui#1727]
Update the longitude, latitude, elevation as a user moves their mouse, and update the scale bar when a user zooms in or out.

For example:
<img width="487" alt="long-lat-elevation" src="https://user-images.githubusercontent.com/26600641/116588532-ae4c1480-a8e9-11eb-9027-4f8ae23f06d4.png">

**Comment by robyngit** [comment]
There is a now a scale bar that updates as you zoom and pan, and coordinates that update as you move your mouse:

<img width="551" alt="Screen Shot 2021-10-01 at 15 53 25" src="https://user-images.githubusercontent.com/26600641/135678798-e080408f-c4c3-49f9-b04a-25284936f29a.png">

Adding an elevation measurement that isn't wildly inaccurate is a challenge, so I'll create a separate issue for that.

Also, since the scale bar is referencing an area at the bottom of the screen (and the scale at the top of the screen could be very different depending on how the camera is tilted/position), I think we should consider moving it to the bottom of the Cesium canvas. We can make a separate issue for this if we find it's necessary.

**Comment by mbjones** [comment]
Yay! 🎉
