### ISSUE TITLE
Determine how a CesiumView section will be configured in portals

### ISSUE THREAD

**Issue by robyngit** [NCEAS/metacatui#1729]
- [ ] Determine how a portal document will configure a CesiumView for a section. In development, we are currently using `<option>` elements in `<section>` elements, as shown below:
```
<option>
  <optionName>sectionType</optionName>
  <optionValue>visualization</optionValue>
</option>
<option>
  <optionName>visualizationType</optionName>
  <optionValue>cesium</optionValue>
</option>
```
- [ ] Determine how a portal will configure layers for Cesium

Things to consider:
- In addition to configuring data layers, will we also allow configuration of the terrain layer (DEM), and the base layers?
- When support is added for 1.1.0 portal sections (#1701), we could consider including the Cesium layer configuration in a section's `<content>` element, since in 1.1.0 it will allow any element.

**Comment by laurenwalker** [comment]
Is there any more work to be finished with this or can this issue be closed?
