### ISSUE TITLE
Add the ability to visualize data within the portal

### ISSUE THREAD

**Issue by erinlynmclean** [NCEAS/metacatui#1735]
**Describe the feature you'd like**
Add the ability to visualize data within the portal

**Additional context**
Requested from the portals focus groups

**Comment by robyngit** [comment]
Related to #1383

**Comment by laurenwalker** [comment]
I'm not sure exactly what this feature request is - is this referring to maps and graphs of data in the portals? (#1383) I think this may also refer to the ability to browse data files (#1758)

Or something different?

I will close as a duplicate for now unless this is a different feature than the two mentioned above.
