### ISSUE TITLE
Add more functionality to the Markdown editor for freeform pages

### ISSUE THREAD

**Issue by erinlynmclean** [NCEAS/metacatui#1737]
**Describe the feature you'd like**
Add more functionality to the Markdown editor for freeform pages

**Additional context**
Requested from the portals focus groups

**Comment by laijasmine** [comment]
Continue to hear this from researchers. Reference [ADC RT ticket](https://support.nceas.ucsb.edu/rt/Ticket/Display.html?id=21981) specifying the following:
- "Project Gallery" where multiple photographs could be displayed
- a way to upload videos

**Comment by laurenwalker** [comment]
Let's create GH issues for each individual feature that is requested by researchers. Thanks for the specific examples, @laijasmine.
