### ISSUE TITLE
Notification system for portals MVP

### ISSUE THREAD

**Issue by erinlynmclean** [NCEAS/metacatui#1744]
**Describe the feature you'd like**
Create an email notification system for when new datasets are added to the portal via the rules, and as a reminder to update, with the option to turn that off if it’s not relevant or needed

**Additional context**
Requested from the portals focus groups

**Comment by robyngit** [comment]
These notifications should be available for both portal owners/editors and the community. From #1845:

> Add the capability for the community to 'follow' portals so that users are aware when there have been updates...

> This request came in from David Allen (NOAA) via Sandy Starkweather (NOAA) in response to the portals focus group update email.

**Comment by robyngit** [comment]
Duplicate of #1761
