### ISSUE TITLE
Support search functionality within the portal, e.g. a search box that queries all the text content in a portal.

### ISSUE THREAD

**Issue by erinlynmclean** [NCEAS/metacatui#1754]
**Describe the feature you'd like**
Support search functionality within the portal, e.g. a search box that queries all the text content in a portal.

**Additional context**
Suggestion from the portals focus groups.

**Comment by laurenwalker** [comment]
Is this a request for a way to search for portals?

**Comment by aebudden** [comment]
I believe this is a within portal search, akin to a website search. The ability to search the freeform pages within a portal.

**Comment by laurenwalker** [comment]
Okay, thank you

**Comment by erinlynmclean** [comment]
That's kind of right - there was the feedback that there's no way to search for datasets within the collection but that feature exists after i just looked at it....so maybe this one is actually resolved.

**Comment by laurenwalker** [comment]
Okay, I'm going to close since that sounds about right and we probably won't ever implement a portal text search (browsers can already search text on a page, I'm not sure we want to rebuild that wheel)
