### ISSUE TITLE
Combine the Funding Description and Award Number fields in the portal query builder

### ISSUE THREAD

**Issue by laijasmine** [NCEAS/metacatui#1757]
**Describe the feature you'd like**
Combine the `Funding Description` and `Award Number` fields in the portal query builder to one field called `Funding`

**Is your feature request related to a problem? Please describe.**
[Portal](https://arcticdata.io/catalog/edit/portals/beavers) that uses the Funding Description field. As we move datasets to use the EML 2.2.0 awards format, it will remove the Funding Description section. I anticipate this might (1) break some of the queries if people set it up initially using Funding Description or (2) cause confusion for people who have a mix of datasets that have metadata in EML 2.1.1 and 2.2.0 . 

The support team can guide users to select both Funding Description and Award Number in the query but it isn’t very intuitive and requires some knowledge about the differences in EML 2.1.1 and 2.2.0.

**Comment by robyngit** [comment]
This can easily be implemented by adding it to the list of `collectionQuerySpecialFields` in the repository-level configuration:

https://github.com/NCEAS/metacatui/blob/f64c80af2a99c6e477a65d3249e6f376578b0d67/src/js/models/AppModel.js#L1431-L1459

The new field would look something like this:
```
{
  name: "funding-text-number",
  fields: ["fundingText", "awardNumber"],
  label: "Funding",
  description: "The award number for funding associated with a dataset or the description of funding source",
  category: "Awards & funding"
}
```

This could either be added as a default in the `AppModel`, or configured only for certain repositories.

**Comment by laurenwalker** [comment]
@robyngit That sounds like a good solution to me. Could we use `Award number` as the label and hide the default `Award number` field? 

Can you add this to the arctic theme in the develop branch and test that it works ok?

**Comment by laurenwalker** [comment]
Looks great. Point 1 sounds good to me. Point 2 is problematic, since we don't want to have to update that config with  MetacatUI upgrades. It would be nice to have some sort of merge feature instead for those sorts of configuration options (like `extend`ing the JS object rather than overwriting it completely). For now, let's just update this default behavior for all themes since it could be an issue for any repo that is upgrading from EML 2.1.1 to EML 2.2.0
