### ISSUE TITLE
Notification system MVP

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/metacatui#1761]
Develop a notification system for datasets and portals for events such as downloads, views, citations, derived products, new datasets added to a portal, reminders to update a portal, etc.

This Epic is specifically for the MVP of this feature. (CI-18 in ADC proposal)

**Comment by robyngit** [comment]
This issue was duplicated twice. Here are details provided in other issues.

From #1744:

> Describe the feature you'd like
> Create an email notification system for when new datasets are added to the portal via the rules, and as a reminder to update, with the option to turn that off if it’s not relevant or needed

> Additional context
> Requested from the portals focus groups

From #1845:

> Add the capability for the community to 'follow' portals so that users are aware when there have been updates...

> This request came in from David Allen (NOAA) via Sandy Starkweather (NOAA) in response to the portals focus group update email.

Note that there notifications should be available for both portal owners/editors and the community (when the portal/dataset is public)

**Comment by robyngit** [comment]
The tasks described here have been broken down into small steps in issues #213, #1762, #2250. These steps are grouped together in [the CI-18 tab of the ADC Deliverables project](https://github.com/orgs/NCEAS/projects/7/views/12).
