### ISSUE TITLE
Show 3D tiles as data layers in the Cesium layer picker

### ISSUE THREAD

**Issue by robyngit** [NCEAS/metacatui#1778]
Support adding [`3DTilesets`](https://cesium.com/docs/cesiumjs-ref-doc/Cesium3DTileset.html) in the Cesium View. Show the tileset as a data layer in the layer picker. Allow configuration of the various 3DTilesets options.

**Comment by laurenwalker** [comment]
Related to https://github.com/PermafrostDiscoveryGateway/pdg-portal/issues/8 and https://github.com/PermafrostDiscoveryGateway/pdg-portal/issues/9
