### ISSUE TITLE
Add a button that navigates to the full extent of the data layer when clicked

### ISSUE THREAD

**Issue by robyngit** [NCEAS/metacatui#1785]
Each data layer in the Cesium view should have an easy option to show the complete dataset across the area of the globe that it covers

**Comment by robyngit** [comment]
Here's an example of how the new button looks with the sample ice wedge polygon layer:

https://user-images.githubusercontent.com/26600641/135920149-84e63b2a-8e67-45ea-999a-f7bf3633f244.mp4

**Comment by laurenwalker** [comment]
Woohoo! Looks awesome!
