### ISSUE TITLE
Support customization of the Feature Info Panel for each data layer in Cesium

### ISSUE THREAD

**Issue by robyngit** [NCEAS/metacatui#1797]
In Cesium, clicking on a data entity (e.g. on a LEO Network marker) shows an "info box" containing the description property or attribute table of that entity. Make the information shown in that info box configurable (e.g. for the LEO Network data, we show the date, an image, a link, logo, etc, but this is currently hard-coded in the app.)

**Comment by robyngit** [comment]
This is how the default Feature Info Panel looks now:

<img width="165" alt="Screen Shot 2021-11-29 at 12 44 42" src="https://user-images.githubusercontent.com/26600641/143917239-d5242086-196d-4908-9869-905348eaf07e.png">

**Comment by robyngit** [comment]
Completed in the `feature-cesium-portals` branch, which includes the addition of a "story" template:

<img src="https://github.com/NCEAS/metacatui/raw/feature-cesium-portals/docs/screenshots/views/maps/FeatureInfoView.png" width="600">

Which properties are used in the each part of the template are configured in a `featureTemplate` property: 
https://github.com/NCEAS/metacatui/blob/451d93e6db058d1f673b698615ee49a54380d763/src/js/models/maps/assets/MapAsset.js#L172-L211

The content of a `FeatureInfoView` is rendered within an iframe.

**Comment by mbjones** [comment]
Nice, @robyngit ! 🎉
