### ISSUE TITLE
When an array attribute OR model attribute in the EML211 model is changed, flag the EML content as changed

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/metacatui#18]
We are in a bit of a dilemma. When a nested EML model (e.g. EMLParty) or an array in an EML211 model attribute is changed, the EML211 model does not recognize the change unless the `change` event is manually fired.

We currently have a `change` listener on the EML211 model with EML211.handleChange() as a callback. This function essentially checks if the change was made on the EML211 content, or on an attribute that doesn't get serialized into the content (such as the `synced` attribute or an attribute from the system metadata.)

The way Backbone works, if you trigger the change event for an attribute via `model.trigger(”change:alternateIdentifier”)`, it does not trigger the general `change` event too - so our `EML211.handleChange()` callback is not called. If you just `model.trigger("change")`, then `EML211.handleChange()` does get called, but it decides that no specific attribute was changed and does nothing.

There are a few choices to solve this issue, and I'd like to get feedback on which to choose since it will affect the way we handle every single array or nested model change in the Editor:

- [ ] Customize the Backbone library to trigger the general `change` event whenever the `change:attribute` event is triggered. 
CON: We need to update the Backbone library code with this customization anytime the library is updated. We may need to check if it would negatively affect other parts of the app.
PRO: We only need to call `trigger("change:attribute")` for it to work. 

- [ ] Send the changed attribute in the `options` parameter of the `trigger` function, and check for it in the `handleChange()` function. 
CON: Anytime we update an array or nested model in the Editor, we need to have a line like this: `model.trigger("change", null, {changed: ["alternateIdentifier"] });` which is a bit tedious to remember.
PRO: It works exactly as needed.

- [ ] Only trigger the `change` event, and in `EML211.handleChange()`, assume that the EML content has changed when no specific attribute is given. 
CON: We may end up updating the EML at times when it has not been changed (if the user clicks Save) - I'm not sure how likely this would happen, but there is a risk.
PRO: We only need to call `trigger("change")` for it to work, and it uses the Backbone library as-is

I am leaning towards the third choice.

**Comment by amoeba** [comment]
1. No way
2. Not bad but you're right: I know I'd forget.
3. My preference. If the user clicks save after may-not-making-a-change that's fine.

**Comment by laurenwalker** [comment]
After some discussion, we decided on option #3. I've implemented it now, so the "change" event needs to be triggered after arrays or objects set on the EML are updated. The "parentAttribute" doesn't need to be set on nested EML models anymore.

**Comment by laurenwalker** [comment]
I've been encountering some related issues to this and am considering that at least for the Editor 1.0, we should just show the Save button at all times. 

Even after making the suggested change above, there is still an issue with determine which attribute on the EML model has changed when its value is an object, such as another Backbone model (e.g. EMLParty model). When `changedAttributes()` is called, Backbone will return an array of the attributes that we last `set()`. This will not work when tracking submodel changes. Example:

The user changes the address of a creator in the editor.
The EMLPartyView updates the address of the EMLParty model.
The EMLParty model triggers the change event on the EML model.
The EML model will get the `changedAttributes()`, which will NOT include the creator attribute, since `EML.set("creator", model)` was never called.

The only reason why we've tracked content changes is to:
- prevent a user from saving the package when there are no edits to save
- When a user does save, we only want to update the objects that have content changes - for example, a user might just update the data files and not touch the EML. When they save, we might want to leave the EML alone.

I am considering just leaving the Save button visible at all times, and allowing the user to save the full package at any time, since it is looking to be a fairly complicated process to track changes on submodels.

Thoughts?

**Comment by csjx** [comment]
I agree Lauren - I'm also seeing the `Save` button when I don't expect it (like when the editor is reloaded), so for this first round, I think having it consistently there is better than unexpectedly there, and not there when you need it!  I think we should just visually change it to `Saving ...`, then to maybe `Saved` (with a check mark), and then time out back to `Save`, or some sort of obvious sequence like that.

**Comment by amoeba** [comment]
That sounds really reasonable to just allow the user to Save always. Let's do that for now.

**Comment by laurenwalker** [comment]
Seems like we have an agreement!
