### ISSUE TITLE
Entity description is not saved to the model

### ISSUE THREAD

**Issue by csjx** [NCEAS/metacatui#182]
When documenting a data file, we add the file using the `Add Files` button, and then click on the `Edit` pencil icon to edit the entity and attribute information.  On the `Overview` tab of the modal dialog, we can enter an entity description.  On the `focusout` event, this value should get saved to the backing `EMLOtherEntity.entityDescription` attribute in the model, but doesn't.  This results in the field not being serialized in the EML. Track this down.

**Comment by amoeba** [comment]
Working on this this afternoon
