### ISSUE TITLE
Deploy the 2.0.0-RC1 editor to beta.arcticdata.io

### ISSUE THREAD

**Issue by csjx** [NCEAS/metacatui#183]
After talking with Lauren, we've decided to install a release candidate tag of the `2.0.0` code to beta.arcticdata.io.  This will allow arcticdata.io to continue with the `1.4.x` deployment and the Registry Editor.

- [x] Get beta.arcticdata.io registered in DNS
- [x] Configure the beta.arcticdata.io virtual host on the arcticdata.io VM
- [x] Enable SSL support via LetsEncrypt 
- [x] Merge `master` back into the `2.0.0` branch
- [x] Cut a `2.0.0-RC1` tag from the `2.0.0` branch
- [x] Deploy `2.0.0-RC1` to beta.arcticdata.io

**Comment by csjx** [comment]
I've deployed `2.0.0RC1` to beta.arcticdata.io.  The configuration still needs testing, but it's up, and the new editor is accessible.

**Comment by amoeba** [comment]
Hey @csjx, beta.arcticdata.io just redirects me to arcticdata.io. Just an FYI

**Comment by amoeba** [comment]
```
~> curl -v https://beta.arcticdata.io
* Rebuilt URL to: https://beta.arcticdata.io/
*   Trying 128.111.84.81...
* TCP_NODELAY set
* Connected to beta.arcticdata.io (128.111.84.81) port 443 (#0)
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate: beta.arcticdata.io
* Server certificate: Let's Encrypt Authority X3
* Server certificate: DST Root CA X3
> GET / HTTP/1.1
> Host: beta.arcticdata.io
> User-Agent: curl/7.54.0
> Accept: */*
>
< HTTP/1.1 301 Moved Permanently
< Date: Sun, 20 Aug 2017 20:42:42 GMT
< Server: Apache/2.4.7 (Ubuntu)
< X-Frame-Options: SAMEORIGIN
< X-Powered-By: PHP/5.5.9-1ubuntu4.22
< Location: https://arcticdata.io/
< Access-Control-Allow-Origin:
< Access-Control-Allow-Headers: Authorization, Content-Type, Origin, Cache-Control
< Access-Control-Allow-Methods: GET, POST, PUT, OPTIONS
< Access-Control-Allow-Credentials: true
< Content-Length: 0
< Content-Type: text/html; charset=UTF-8
<
* Connection #0 to host beta.arcticdata.io left intact
```

**Comment by csjx** [comment]
Yeah, I noticed that too, but if you go to https://beta.arcticdata.org/catalog directly it doesn't. It's probably because I copied the WordPress site over, and probably didn't config it right.

**Comment by amoeba** [comment]
Oh cool. Thanks!

**Comment by csjx** [comment]
But yes, I'll also check the virtual host config, I might have missed something there too. thanks for the heads up.
