### ISSUE TITLE
Submit data sensitivity and ethics

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/metacatui#1844]
We want to add two new questions to the dataset editor to capture whether or not incoming datasets contain any sensitive data (e.g. about human subjects) and/or whether any ethical research practices were adhered to when collecting this data. This effects the data management process.

Here's a first pass at what these questions could look like:

## Data sensitivity question
![Data Sensitivity](https://user-images.githubusercontent.com/6643222/128081958-d20c7d0d-17c0-4243-ae60-6098d798a210.png)

### Implementation details
- This question is configurable in MetacatUI. It can be enabled/disabled and required or optional.
- Option for metadata storage: [EML `licensed` element](https://eml.ecoinformatics.org/schema/eml-resource_xsd.html#ResourceGroup_licensed)
- No option will be selected when the editor first loads. The user will need to read the question and make a choice. This could be configurable as well.

## Data governance question
![Data Governance](https://user-images.githubusercontent.com/6643222/128081956-c3f3fb60-97b7-48ae-90d1-c045808b7190.png)

### Implementation details
- This question is configurable in MetacatUI. It can be enabled/disabled and required or optional.
- Option for metadata storage: [EML `methodStep` and `description` elements](https://eml.ecoinformatics.org/schema/eml-methods_xsd.html#MethodsType_methodStep). We may want to consider storing references to specific ethical research principals (e.g. CARE) via a method `citation` or `protocol` (which may require a separate input to select the principals used).

**Comment by karlbenedict** [comment]
With the increasing visibility and traction that the CARE Principles [https://www.gida-global.org/care](https://www.gida-global.org/care) are receiving in the data management community, and the emerging work around being able to provide local context labels (i.e. [Traditional Knowledge](https://localcontexts.org/labels/traditional-knowledge-labels/) and [Biocultural Knowledge](https://localcontexts.org/labels/traditional-knowledge-labels/) labels) capacity for capturing this type of information would be useful as a complement to the more commonly thought of human subjects/PII/PHI/sensitive species considerations.

**Comment by mbjones** [comment]
@karlbenedict thanks for the input. We agree, and have been holding a working group that has been discussing these issues, including for example the [DataTags](https://datatags.org) classification system, the TKLabels and BC Labels approach from localcontext.org, and related initiatives. Our current pass for the metadata editor takes a DataTags-driven approach to tagging data and then provides a narrative context around CARE and ethical research practices. We will be continuing iterations on this via discussions with our SS working group and others in the Arctic.  All of this is at the member repository level (e.g., Arctic Data Center), as that is where data are stored and curated. I'm not as clear what role the DataONE infrastructure can or should add on the infrastructure side, other than properly displaying any of this information that the curators at member repositories might provide. That would be a useful discussion.

**Comment by laurenwalker** [comment]
(Converted to Epic and individualized the two separate tasks)
