### ISSUE TITLE
Allow users to 'follow' portals for updates

### ISSUE THREAD

**Issue by aebudden** [NCEAS/metacatui#1845]
Add the capability for the community to 'follow' portals so that users are aware when there have been updates. Possible related to issue #1744 

This request came in from David Allen (NOAA) via Sandy Starkweather (NOAA) in response to the portals focus group update email.

**Comment by laurenwalker** [comment]
Thanks Amber. Were any specific kinds of updates mentioned? (updates to the content of the portal or the datasets in the portal)?

**Comment by aebudden** [comment]
No, no more details. I followed up via email talking about different types of updates (portal features(MetaCatUI), datasets in the portal, knowing about new portals)

**Comment by robyngit** [comment]
Duplicate of #1744
