### ISSUE TITLE
Data files disappear at times on refresh.

### ISSUE THREAD

**Issue by helbashandy** [NCEAS/metacatui#1847]
**Describe the bug**
When refreshing the page, data files does not show up consistently. 

**To Reproduce**
1. Go to https://data.ess-dive.lbl.gov/view/ess-dive-bb4d81681f10854-20210805T222147794
2. Refresh the page multiple times
3. Note the data files.

**Expected behavior**
Data files should always show up. 

**Screenshots**
<img width="1676" alt="Screen Shot 2021-08-06 at 1 37 36 PM" src="https://user-images.githubusercontent.com/47407500/128568747-1c48a267-ad90-4837-b62f-e0110bcbd82a.png">
<img width="1671" alt="Screen Shot 2021-08-06 at 1 37 44 PM" src="https://user-images.githubusercontent.com/47407500/128568760-8506f480-71f2-4a36-bcf6-2ca384da4346.png">

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] OSX
 - Browser [e.g. chrome, safari] Chrome
 - MetacatUI Version: 2.14.1

### **Note:**

 The reviewer will have to be an ESS-DIVE admin to be able to debug the package. Contact me if you need to be added.

**Comment by laurenwalker** [comment]
@helbashandy - Thanks for the report. Is this happening for newly submitted datasets? If so, it's probably due to an indexing delay. (The messaging could be improved for those cases. See #569). If the datasets have been submitted some time ago, then this is a new bug. Thanks

**Comment by robyngit** [comment]
Hey @helbashandy, I'm going to close this issue but please feel free to re-open it if the issue occurred with an already-indexed dataset, or if the problem persists.
