### ISSUE TITLE
Chrome/Chromium on Linux Mint 18.1 cannot properly login to the Arctic Data Center

### ISSUE THREAD

**Issue by j00sr** [NCEAS/metacatui#185]
If one is not already logged in, then they can go to the ORCid login screen and enter login details as normal. Once they get back to the ADC search it doesn't seem like they are in fact logged in (can't see private datasets, still being prompted to log in on the top right). 

Clicking the log-in button again will just 'refresh' the page as if being sent there again after having logged in, which is something you can no longer attempt to do unless you clear cache again to 'log out'. 

Speaking of which, clearing the cache and disabling extensions is not a workaround, so resorting to Firefox to use the Arctic Data Center.

*Only one reported case so far* (myself on Linux MInt 18.1 Serena) so it could be a issue on my side of things, but I did enjoy a long period of time where this was not a problem on either Chrome or Chromium so I don't know what change precipitated this for me. 

@csjx tested with Chromium on Ubuntu and faced no problems.

**Comment by amoeba** [comment]
Have you tried creating a new profile in Chromium and trying again? (Does Chromium have profiles?)

**Comment by j00sr** [comment]
That actually did the trick!

**Comment by amoeba** [comment]
Glad to hear it! If you don't want to nuke your usual Chrom(ium) profile, I would troll through your settings looking for content settings that may block something involved in this sign-in process.

**Comment by j00sr** [comment]
The issue was one of blocking third party cookies in Chrome/ium.
The setting to toggle this can be found in `chrome://settings/content/cookies`.
Or, one can add exceptions for *arcticdata.io*, *cn.dataone.org*, and *orcid.org* and keep the blocking on.
