### ISSUE TITLE
Date search filters result in errors if not a slider

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/metacatui#1854]
Related to #1853.

I was able to create a "free text" search filter with a Date search field, e.g. `dateUploaded`. This resulted in a custom search filter where as a portal visitor, I was creating invalid Solr query strings because I was  searching for strings (e.g. `2018`) on a Date Solr field.

 ![screencast.gif](https://images.zenhubusercontent.com/5d152e12c27d0c306f021863/6eeff73e-8681-4723-9b5c-a1f7a81d0498)

We should either:

1. format search values as valid ISO datetimes when the search field is a date
2. Restrict date filters to the slider filter type
3. Support a new year filter type that uses a date or number input element and formats the search values as valid ISO datetimes

For now, I think Option 2 is the way to go, with Option 3 as an iterative step  in the future, if there is demand for it.

**Comment by robyngit** [comment]
> We should either:
> 
> 1. format search values as valid ISO datetimes when the search field is a date
> 2. Restrict date filters to the slider filter type
> 3. Support a new year filter type that uses a date or number input element and formats the search values as valid ISO datetimes
> 
> For now, I think Option 2 is the way to go, with Option 3 as an iterative step in the future, if there is demand for it.

The Filter Editor now prevents users from matching Date fields with text-type interfaces and vice versa, for example:

https://user-images.githubusercontent.com/26600641/132930979-0eb1e980-e327-4bea-917d-cadb065ab807.mov

**Comment by laurenwalker** [comment]
Looks great, thanks!

**Comment by robyngit** [comment]
I'm not sure if the search filters in the DBO portal were built using the filter editor view, but I just came across this problem again. There is a `<choiceFilter>` that uses the `endDate` solr field, with improperly formatted dates, resulting in search errors:

https://user-images.githubusercontent.com/26600641/140962968-43d00994-edf5-40e3-b28e-3454144f8ee1.mov
