### ISSUE TITLE
Year Slider filters should be restricted to datetime fields only

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/metacatui#1855]
Related to #1853 and #1854

The `Year Slider` filter type only works properly with datetime Solr fields. But I am still able to  choose it as a  filter type when I have a non-datetime search field selected. In the below screenshot, you can see that I am able to create a slider on the `keywordsText` Solr field.

This doesn't result in a Solr error, but it isn't a good user experience because it's not a helpful query. 

![Screen Shot 2021-08-19 at 11.47.30 AM.png](https://images.zenhubusercontent.com/5d152e12c27d0c306f021863/823ce9d7-8b22-4616-860e-fb76305101c0)

## Solr query snippet
`keywordsText:[1930-01-01T00:00:00Z TO 2021-12-31T23:59:59Z]`

**Comment by robyngit** [comment]
See https://github.com/NCEAS/metacatui/issues/1854#issuecomment-917308662
