### ISSUE TITLE
Portal editor "searching for data..." forever

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/metacatui#1873]
I am experiencing an intermittent issue where the portal editor Data tab  will show "Searching  for data..." forever, even though the Solr request  is sent and completed successfully, via the developer Network tab.

This seems to only happen when not doing a  fresh page load - e.g. Click on "Edit" from the My Portals page and click on the "Data" tab.

Saw this issue  on FF, on the Dataone  theme, pointing to cn-sandbox

**Comment by robyngit** [comment]
@laurenwalker, I've experienced this issue as well, but only when there's a problem with the Google Map failing to load at the same time - e.g. if you configure an invalid map key (I thought I had made an issue for this but can't find it at the moment). Do you remember if you got this endless search bug even when the map loaded successfully?

**Comment by laurenwalker** [comment]
Ah ok, I  was not using a correct gmaps key. If that  is the underlying issue, i think we can close this ticket
