### ISSUE TITLE
Sign in under arctic them not working in 2.17.0

### ISSUE THREAD

**Issue by amoeba** [NCEAS/metacatui#1893]
While testing @taojing2002 's upgrade of Metacat on arctic today, I noticed that signing in wasn't quite working. After clicking it and logging in to orcid.org, I would get redirected to a blank page at https://cn.dataone.org/portal/oauth and not getting the last redirect back to arcticdata.io.

I noticed the "Sign in with ORCID" button had an `href` of `https://cn.dataone.org/portal/oauth?action=start&target=`. In my experience, the sign in button usually has an `href` where the `target` query param is set to `window.location.href` which enables the CN Portal to redirect back to MetacatUI.

I noticed a recent commit that was included in 2.17.0 (which is also the deployed version of MetacatUI on arctica): https://github.com/NCEAS/metacatui/commit/16bcc1d1f23e7eaa8115ad2ee7b7bd51ef036551. It mentions fixing a bug in full page sign in (which arctica uses; ie no modal like the KNB) though it wasn't clear what that bug was from the commit message. I tested whether that commit introduced this behavior by locally reverting the commit, testing locally with the arctic theme, and the bug went away.

This makes sense because the commit changes the template from using a view-local variable for the `href` to using the value of AppModel's `signInUrlOrcid` attribute which is set to a value without a value in the `target` query param:

https://github.com/NCEAS/metacatui/blob/da1b6d188700bf38ec06a08be430beafad252d99/src/js/models/AppModel.js#L1834-L1835

I manually reverted the `loginButtons.html` template on arctica and bumped the `cachebuster` config and sign in began working as expected again. @taojing2002 was able to confirm the breakage and the fix on his end too.

@laurenwalker did I break something I was unaware of here? I figured not being able to log in via the big button at the top was a big enough issue to warrant fixing so I went ahead with my fix above. Let me know.

**Comment by laurenwalker** [comment]
Thanks @amoeba for fixing the deployment! I figured out where I went wrong with that commit and pushed a working solution. Thanks
