### ISSUE TITLE
Enhance FilterEditorView to properly support semantic annotation

### ISSUE THREAD

**Issue by amoeba** [NCEAS/metacatui#1900]
This is a continuation of https://github.com/NCEAS/metacatui/issues/1653, which:

1. Lets people editing their Collection Query to use our current BioPortal tree widget (AnnotationFilterView)
2. Lets people searching for data inside portals use our current BioPortal tree widget (AnnotationFilterView))

But we don't yet let them build out (2) to really support semantic annotation well. A user should be able to build out custom filters that use our semantic annotations entirely from within the portal editor UI and without having to go to other references to find what they need.

This issue wasn't possible to consider until very recently when we landed [MetacatUI 2.17.0](https://github.com/NCEAS/metacatui/releases/tag/untagged-4dc7ebf4016a34ddee9b) which includes support for building filters from the UI.

Here's the current UI:

<img width="809" alt="Screen Shot 2021-10-13 at 6 31 50 PM" src="https://user-images.githubusercontent.com/563/137240701-07eb2838-ea39-4904-99c5-f033fdb34fb7.png">
 
There are some limitations here:

- If you pick FREE TEXT, you can't customize which ontology or ontologies you can search. I think many portals _need_ to customize this.
- If you pick DROPDOWN, you still have to enter values and labels manually. It'd be a lot more convenient to be able to show our BioPortal tree widget and automatically fill in values and labels based upon a selection

So the first change, we could disable FREE TEXT for Semantic Annotations and show another type, "TREE":

![image](https://user-images.githubusercontent.com/563/137242250-b830b6cc-7fdd-41f4-afb9-a4cd41f2863b.png)

When you pick TREE, we'd also show a field to pick an ontology (autocompleted from BioPortal) and a tree widget to (optionally) pick your startingRoot).

Then, for DROPDOWN, we could show a tree here:

![image](https://user-images.githubusercontent.com/563/137242234-02fd9c63-a7f2-4b94-9dda-a9ff954308a0.png)

These are just some quick mockups so let me know if you have any questions or thoughts on direction.

**Comment by amoeba** [comment]
I have this working but I'm not totally sure of my approach as I don't think I've fully wrapped my head around every moving piece here. My first take was to to extend UIBuilderOptions to specify the restriction,

```diff
-              if (uiBuilder.filterTypes.includes(type)) {
+              if (
+                uiBuilder.filterTypes.includes(type) &&
+                !uiBuilder.isNotAllowed(selectedFields)
+              ) {

```

But that would have required specifying the restriction on every blocked UIBuilderOption and making sure we add the restriction to new UIBuilderOptions we create in the future. Instead, I built the rules and the logic into `FilterEditorView` like below:

<details>
<summary><code>FilterEditorView</code> patch (expand me)</summary>

```diff
diff --git src/js/views/filters/FilterEditorView.js src/js/views/filters/FilterEditorView.js
index d6bb17399..2715e501d 100644
--- src/js/views/filters/FilterEditorView.js
+++ src/js/views/filters/FilterEditorView.js
@@ -314,6 +314,25 @@ define(['jquery', 'underscore', 'backbone',
           }
         ],
 
+        /**
+         * The list of restrictions on which UI builders should be allowed for a
+         * particular field.
+         *
+         * Values for "fieldName" should be QueryField names. Members of the
+         * key "allowedModelTypes" should be modelTypes from UIBuilderOptions
+         * and may repeat.
+         *
+         * @type {UIBuilderRestriction[]}
+         */
+        uiBuilderRestrictions: [
+          {
+            "fieldName": "sem_annotation",
+            "allowedModelTypes": [
+              "Filter"
+            ]
+          }
+        ],
+
         /**
          * Executed when this view is created
          * @param {object} options - A literal object of options to pass to this view
@@ -705,7 +724,10 @@ define(['jquery', 'underscore', 'backbone',
             var type = MetacatUI.queryFields.getRequiredFilterType(selectedFields)
 
             this.uiBuilders.forEach(function (uiBuilder) {
-              if (uiBuilder.filterTypes.includes(type)) {
+              if (
+                uiBuilder.filterTypes.includes(type) &&
+                view.isBuilderAllowedForFields(uiBuilder, selectedFields)
+              ) {
                 view.allowUI(uiBuilder)
               } else {
                 view.blockUI(uiBuilder)
@@ -1108,6 +1130,47 @@ define(['jquery', 'underscore', 'backbone',
           }
         },
 
+        /**
+         * Determine whether a particular UIBuilder is allowed for a set of
+         * search field names. For use in handleFieldChange to enable or disable
+         * certain UI builders using allowUI/blockUI when the user selects
+         * different search fields.
+         *
+         * @param {UIBuilderOption} uiBuilder The UIBuilderOption object to
+         * check
+         * @param {string[]} selectedFields A set of search field names to look
+         * for restrictions
+         */
+        isBuilderAllowedForFields: function (uiBuilder, selectedFields) {
+          var view = this;
+
+          var hasRestriction = _.map(selectedFields, function (field) {
+            var restrictions = _.findWhere(view.uiBuilderRestrictions, {
+              "fieldName": field,
+            });
+
+            if (typeof restrictions === "undefined") {
+              return false;
+            }
+
+            var isAllowed = _.find(
+              restrictions.allowedModelTypes,
+              function (mt) { return mt === uiBuilder.modelType; }
+            );
+
+            if (typeof isAllowed === "undefined") {
+              return true;
+            }
+
+            return false;
+          });
+
+          if (_.some(hasRestriction)) {
+            return false;
+          }
+
+          return true;
+        },
       })
     return FilterEditorView
   });
```
</details>

Is that something like what you were thinking @robyngit? Any help would be appreciated.

**Comment by robyngit** [comment]
@amoeba 

> ... that would have required specifying the restriction on every blocked UIBuilderOption and making sure we add the restriction to new UIBuilderOptions we create in the future.

I see what you're saying here. I didn't think about the fact that you would need to restrict some of the `UIBuilderOptions` when the sem_annoation field is selected. Wouldn't you just need to add the restriction to two of the options: "Free text" and "Toggle"? (Since you still want to use a version of the "Dropdown" option for sem_annotations, and the other one requires a `<dateFilter>`.)

> Is that something like what you were thinking @robyngit? 

Considering that you would need to restrict based on field, I was thinking something like this:

<details>
 <summary>Expand!</summary>

```javascript
uiBuilderOptions: [
  {
    label: "Free text",
    // ... 
    restrictedQueryFields: ["sem_annotation"],
    // ...
  },
  {
    label: "Dropdown",
    // ...
    uiFunction: function(model) {
      if (model.get("fields").includes("sem_annotation")) {
        // special dropdown UI builder for semantic annoations maybe?
      } else {
        return new ChoiceFilterView({
          model: model,
          mode: "uiBuilder"
        });
      }
    }
  },
  {
    label: "Year slider",
    // ... (nothing here changes because sem_annotation is not a date filter ) ...
  },
  {
    label: "Toggle",
    // ...
    restrictedQueryFields: ["sem_annotation"],
    // ...
  },
  {
    label: "Tree",
    modelType: "Filter",
    iconFileName: "tree.svg",
    description: "Let people use a tree widget to select a semantic annotation",
    filterTypes: ["filter"],
    queryFieldTypes: ["sem_annotation"], // == only use this builder if filterType is filter and queryField is sem_annotation
    modelFunction: function (attrs) {
      return new Filter(attrs)
    },
    uiFunction: function (model) {
      return new SemanticAnnotationFilterView({
        model: model,
        mode: "uiBuilder"
      });
    }
  }
]
```
</details>

But I see that your solution, specifying the restriction in just one place rather than two, is DRYer. It makes sense. I think if it works, then go for it!

BTW, here are some other things I thought of while looking through this:

1. If I understand your code correctly, the `uiBuilderRestrictions` property specifies which `UIBuilderOption`s to use by looking at the list of `modelTypes` and matching to the `modelType` property in the `UIBuilderOption`s. However, `modelType` won't always be unique to each `UIBuilderOption`. For example, if you add a "Tree" option, it may also use the "Filter" `modelType`. It might be better to add a unique ID to each `uiBuilderOption`? (Or use the index, or label...?)
2. There are plans to eventually support other types filter builder UIs based on the query field selected (see https://github.com/NCEAS/metacatui/issues/1693). If the solution you come up makes it easy to add new UIs in the future, all the better! 
3. What should happen if a user selects sem_annoation AND some other field in the fields input?
