### ISSUE TITLE
Show list of validation errors in the Editor

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/metacatui#1915]
The current validation error message:

![Screen Shot 2021-11-14 at 1.24.44 PM.png](https://images.zenhubusercontent.com/5d152e12c27d0c306f021863/a9b8b265-b6b7-4ee1-8d98-408710dd7da8)

says to fix the validation error messages below. This is fine, but there have been a few instances where users have not been able to find the validation error in the editor sections (possibly due to an issue with the editor not displaying the red validation styling correctly) and it also makes the user go on a bit of a treasure hunt.

It should be easy to display each validation error in a bullet point list in addition to displaying the errors inline with the inputs.

**Comment by laurenwalker** [comment]
The new error message looks like:

![Screen Shot 2021-11-14 at 1 32 11 PM](https://user-images.githubusercontent.com/6643222/141701411-1c83ca82-5e65-43cc-9984-8090b788bbf3.png)

**Comment by amoeba** [comment]
This is a really nice improvement, thanks @laurenwalker.
