### ISSUE TITLE
Create FooterView.hide() function

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/metacatui#1924]
https://github.com/NCEAS/metacatui/blob/4fab314c4f8d6e3f6ba56f23d9ef39a3af8bab9e/src/js/views/portals/PortalView.js#L703-L704

When reviewing this part of the portal view code, I thought it might be useful to give the FooterView this functionality rather than subviews controlling the footer directly. We have at least one other space in the app then the footer is minimized or hidden (data catalog view in map mode), so this would be convenient.

**Comment by robyngit** [comment]
Added to the `develop` branch
