### ISSUE TITLE
bad hyperlink on the metacatui news page ?

### ISSUE THREAD

**Issue by yvanlebras** [NCEAS/metacatui#1925]
in the Amazing [last MetacatUi release note](https://github.com/NCEAS/metacatui/releases/tag/2.18.0), I see this URL http://localhost:4000/guides/maps/cesium.html as hyperlink in this sentence "See the full documentation for Cesium " who seems to be maybe wrong isn't it ?

Thank you so much, amazing release, Amazing cesium !!!!!

**Comment by laurenwalker** [comment]
Ah, thank you for catching that Yvan. Fixed!
