### ISSUE TITLE
Enable Cesium Widget to measure the bounding box of the currently visible map area

### ISSUE THREAD

**Issue by robyngit** [NCEAS/metacatui#1939]
To eventually support searching by geographic area, the `CesiumWidgetView` will need to be able to find the coordinates of the currently visible area. The View should update the the Map model with these coordinates, in the same way it updates the Map model with the longitude and latitude to show in the ScaleBarView. The visibile area coordiantes could be updated each time a user zooms or pans (i.e. on `camera.changed`).

**Comment by mbjones** [comment]
@robyngit Doesn't the current Google Map view already update the model with its current map extent? If so, it seems like the cesium view should update that same model element so that the other views can continue to depend on it. Maybe this was already your plan?

**Comment by robyngit** [comment]
> Doesn't the current Google Map view already update the model with its current map extent?

The `DataCatalogView` gets the bounding box directly from the Google Map then updates the Search Model directly:

https://github.com/NCEAS/metacatui/blob/90cb7e217308bfdeea1576c55cf775356998b764/src/js/views/DataCatalogView.js#L1953-L1966

So it looks like the bounding box is not added to the (Google) Map model.

> it seems like the cesium view should update that same model element so that the other views can continue to depend on it.

Agreed that the Cesium View should also update the search model. But perhaps it should do this via the DataCatalogView, similar to how it currently works for Google Maps. Exactly how this works might depend on issues https://github.com/NCEAS/metacatui/issues/1940 and https://github.com/NCEAS/metacatui/issues/1520
