### ISSUE TITLE
Create a Cesium layer type to display search results from the Data Catalog

### ISSUE THREAD

**Issue by robyngit** [NCEAS/metacatui#1942]
Create an extension of the base `MapAsset` model to use alongside the `DataCatalogView`, which can be updated to display the location of datasets from search results. This layer may create Geohashes or clustered entities, depending on the outcome of #1941

**Comment by robyngit** [comment]
Some notes about this issue:
- When I first experimented with this, adding/removing so many rectangle entities at once was crashing Cesium
- [Suspending events](https://cesium.com/learn/cesiumjs/ref-doc/EntityCollection.html#resumeEvents) during the creation/removal process, then resuming events after, might speed things up
- Alternatively, using [primitives](https://cesium.com/learn/cesiumjs/ref-doc/Primitive.html?classFilter=primitive) directly rather than entities is less memory-intensive, and might be more appropriate for creating the geohash layer
- As another option, the geohash layer could be created as an imagery layer using a canvas, the way Cesium does for it's [GridImageryProvider](https://github.com/CesiumGS/cesium/blob/2d74054e54625f9c4d7e645abeb1afc5bcfb91e0/Source/Scene/GridImageryProvider.js) - though we would need another mechanism to make each geohash square clickable

**Comment by laurenwalker** [comment]
> As another option, the geohash layer could be created as an imagery layer using a canvas, the way Cesium does for it's [GridImageryProvider](https://github.com/CesiumGS/cesium/blob/2d74054e54625f9c4d7e645abeb1afc5bcfb91e0/Source/Scene/GridImageryProvider.js) - though we would need another mechanism to make each geohash square clickable

I also wondered if we could create a geohash 3D tileset which simply displays the geohash rectangles. This would depend on the ability for MetacatUI to tell Cesium to hide or make transparent the geohash rectangles that are not populated with datasets. I'm not sure how performant that would be. It would be simple to create and assign geometricErrors based on the well defined geohash levels and geohash box sizes.

**Comment by robyngit** [comment]
That's an interesting idea! Would we ship the tileset with MetacatUI, or host it externally? Do you have an idea of how large the tileset would be? We would still need to create (or update?) the [labels](https://cesium.com/learn/cesiumjs/ref-doc/Label.html) that give the count per geohash on the fly.

**Comment by robyngit** [comment]
I've been looking at alternatives to the Entity API to render the GeoHash layer on the map and for reference will add some notes and ideas here. This builds on discussion from https://github.com/NCEAS/metacatui/issues/1941

## Requirements (and limitations with current approach):
- Limit geohashes to the current view extent (https://github.com/NCEAS/metacatui/issues/2076)
- Remove/update geohashes quickly on zoom/pan (https://github.com/NCEAS/metacatui/issues/2063)
- Number labels must be drawn on the map, sized relative to the current zoom position (https://github.com/NCEAS/metacatui/issues/2066)
- Need to be able to drape the geohashes over the surface/terrain (https://github.com/NCEAS/metacatui/issues/2070)
- Need to show outlines or otherwise be able to distinguish geohashes that are next to one another.
- Individuals geohashes must be clickable (https://github.com/NCEAS/metacatui/issues/2067) and highlightable (https://github.com/NCEAS/metacatui/issues/2068)

## Other options:

### vector
- Create a custom data source ([example](https://sandcastle.cesium.com/?src=Custom%20DataSource.html))
- Model the geohash layer with CZML ([example](https://sandcastle.cesium.com/?src=CZML%20Billboard%20and%20Label.html))
  - can specify labels and rectangles in JSON
- Draw [GroundPrimitives](https://cesium.com/learn/cesiumjs/ref-doc/GroundPrimitive.html) instead of entities. This would [presumably be faster](https://cesium.com/blog/2016/03/02/performance-tips-for-points), but I believe that outlines wouldn't work. We could draw the geohashes a little smaller such that there is some padding between geohashes and users could distinguish between side-by-side rectangles.
- Create a geohash 3D tileset (see https://github.com/NCEAS/metacatui/issues/1941#issuecomment-1099677899)
### raster
- Create a custom imagery source, similar to the [GridImageryProvider](https://cesium.com/learn/cesiumjs/ref-doc/GridImageryProvider.html) and [TileCoordinatesImageryProvider](https://cesium.com/learn/cesiumjs/ref-doc/TileCoordinatesImageryProvider.html).
  - [here](https://github.com/CesiumGS/cesium/pull/8280) is an example of an implementation of a custom imagery grid, discussion [here](https://github.com/CesiumGS/cesium/issues/8282)
  - ideal since there is built in logic in Cesium to update imagery tiles based on zoom/position, and they can be updated very quickly.
  - The one disadvantage is that this would lack the vector features: not clickable, or highlightable. We could draw a single rectangle entity when a user clicks or highlights a geohash; or create something similar to a [SingleTileImageryProvider](https://cesium.com/learn/cesiumjs/ref-doc/SingleTileImageryProvider.html)

**Comment by robyngit** [comment]
Here are some notes from my investigation into creating a custom imagery provider to display geohashes in Cesium.

### How we could implement a `GeohashImageryProvider`

- The first step would be to create a custom [`TilingScheme`](https://cesium.com/learn/cesiumjs/ref-doc/TilingScheme.html) that represents the geohash pattern (e.g. `GeohashTilingScheme` ). The [`GeographicTilingScheme`](https://github.com/CesiumGS/cesium/blob/main/packages/engine/Source/Core/GeographicTilingScheme.js) is an example of a Cesium tiling scheme that we can model our `GeohashTilingScheme` off of. We can essentially extend this with a few minor changes:
  - The most important part of a Cesium tiling scheme is the `positionToTileXY` function. It takes a position (long/lat) and a level and returns an x and y index for the tile located there. Although geohashes do not use indices, I believe we could calculate indices for geohashes anyways. We can use the same function that is in the `GeographicTilingScheme`, but only change the underlying `getNumberOfXTilesAtLevel` and `getNumberOfYTilesAtLevel` methods;
  - To calculate the number of x/y tiles at each level, we can make use of the fact that geohashes are [divided into 32 new geohashes](https://www.pubnub.com/learn/glossary/what-is-geohashing/) at each increase in precision.
- Next we need to create our own Imagery Provider (e.g. `GeohashImageryProvider`), that implements functionality similar to both the [GridImageryProvider](https://cesium.com/learn/cesiumjs/ref-doc/GridImageryProvider.html) and [TileCoordinatesImageryProvider](https://cesium.com/learn/cesiumjs/ref-doc/TileCoordinatesImageryProvider.html). We would pass it the `GeohashTilingScheme`.
  - The `GeohashImageryProvider` needs to be connected to the Search results, such that it has access to the number of results for each geohash, and that it updates the search model with the level/precision Cesium is displaying (it can use the [`GeohashSearchConnector `](https://github.com/NCEAS/metacatui/blob/main/src/js/models/connectors/Geohash-Search.js).
   - The Search model gives the number of results for each encoded geohash, but the Imagery Provider must be able to provide an image for a given x, y, z coordinate. Therefore, the imagery provider will need to be able to convert an x, y, z index (as calculated in the `GeohashTilingScheme`) to an encoded geohash string.
   - As long as a given tile has > 0 search results, then the `GeohashImageryProvider` would draw a rectangle (like [this](https://github.com/CesiumGS/cesium/blob/828d6799916196a6f9c79dd8e5b001d58305e093/packages/engine/Source/Scene/GridImageryProvider.js#L331-L344)) and add text with the number of search results (like [this](https://github.com/CesiumGS/cesium/blob/828d6799916196a6f9c79dd8e5b001d58305e093/packages/engine/Source/Scene/TileCoordinatesImageryProvider.js#L332-L357)).
   - We might be able to make use of the Imagery Provider's `pickFeatures` function to implement the [click to zoom behaviour](https://github.com/NCEAS/metacatui/issues/2067)
- Finally, we could add the Geohash Imagery Provider to the [`CesiumImagery` model](https://github.com/NCEAS/metacatui/blob/main/src/js/models/maps/assets/CesiumImagery.js) similar to how we do for other imagery providers.

### Advantages
- It would render faster than a vector-based layer
- Cesium has internal logic that we can make use of for deciding a zoom/precision level. This is especially useful when users are viewing the map at an angle, where we could be showing high precision tiles in the foreground, and lower precision tiles in the background.
- We don't have to worry about manually adding and removing tiles - Cesium decides when to request tiles and which tiles to request given the camera position and Tiling Scheme

### Disadvantages
- Complicated to implement
- Even more complex to change the style of a tile on hover

### Open questions
- Can we force Cesium to update tiles when the search changes (when the precision and view extent will stay the same, but the number of results per tile changes), or will it always use a cached version of a tile for a given x, y, z?
