### ISSUE TITLE
Add Project Backbone Model to access project rest api 

### ISSUE THREAD

**Issue by vchendrix** [NCEAS/metacatui#1945]
**Describe the feature you'd like**
Add Project Backbone Model to access project rest api. 

**Is your feature request related to a problem? Please describe.**
We need to be able to view and manage projects in metacat UI.

**Additional context**
The current project JSON is as follows.  We will definitley need to have a identifier that is resolvable 

```json

{
       "url": "https://mule-stage.ess-dive.lbl.gov/project/1/",
        "id": 1,
        "project_title": "Soil Carbon Biogeochemistry",
        "sponsor_program": "TES",
        "project_type": "Lab Awards",
        "short_name": "",
        "pis": [
            {
                "last_name": "Bailey",
                "first_name": "Vanessa",
                "institution": "Pacific Northwest National Laboratory",
                "email": "Vanessa.Bailey@pnnl.gov"
            }
        ]   
 }
```

**Comment by vchendrix** [comment]
Test version of api: https://mult-stage.ess-dive.lbl.gov/projects

**Comment by mbjones** [comment]
@vchendrix that URL isn't working for me -- gives a 404. Maybe a typo?

**Comment by vchendrix** [comment]
> @vchendrix that URL isn't working for me -- gives a 404. Maybe a typo?

@mbjones yes a typo. I just corrected it

**Comment by vchendrix** [comment]
@gothub A mule release candidate with the discussed endpoint and response body changes has been deployed to https://mule-stage.ess-dive.lbl.gov/api/v1/.  You will need to pass in the following query arguments to get the JSON output: `https://mule-stage.ess-dive.lbl.gov/api/v1/project/?format=json`

**Comment by vchendrix** [comment]
@gothub To get JSON data you can also user the Accept Header. See the curl command below

```json
curl  -H "Accept: application/json"  \
    "https://mule-dev.ess-dive.lbl.gov/api/v1/project/"
```

**Comment by vchendrix** [comment]
@laurenwalker in our tech meeting yesterday we discuss with @mbjones that @helbashandy would submit a PR for the Project model and collection and maybe the view that we created already for this.  That way the theme could extend the project model with repository specific logic. This way if/when dataone implements a project API the base code is there.
