### ISSUE TITLE
EMLAttributeList instances are duplicated across EMLEntity instances

### ISSUE THREAD

**Issue by csjx** [NCEAS/metacatui#195]
We have a serialization issue that is similar to #181. With multiple entities added into the data package table, editing the attribute list on one of those entities will result in a serialized EML document where every entity is assigned the same `attributeList`, which results in repeated `id` values and an invalid XML document.  Still tracking this down.

**Comment by laurenwalker** [comment]
This should be fixed with the same code change as #181 since the underlying issue was that new EMLOtherEntity models were using object references as the default attributes rather than instantiating new objects.

**Comment by csjx** [comment]
Thank you @laurenwalker - I definitely wasn't seeing that in the `defaults` attribute. Good to get your fresh eyes on it.
