### ISSUE TITLE
Cross-browser UX Testing

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/metacatui#196]
We need to test the Editor in:

- [x] IE 10, 11, Edge
- [x] Firefox 45+
- [x] Chrome 52+
- [ ] Safari 9, 10

This list is based on our most frequent users via Google Analytics from the past year.

**Comment by laurenwalker** [comment]
Starting Firefox 45 testing now

**Comment by amoeba** [comment]
I am not having any luck adding a file to a package in MS Edge on Win10. Everything looks good so I'm not sure what's up. I do see this in the Console:

<img width="593" alt="screen shot 2017-08-17 at 4 11 06 pm" src="https://user-images.githubusercontent.com/563/29438970-e4546afc-8366-11e7-8839-633ffb5af333.png">

That JS error we'll need to address (whatever is causing it)

**Comment by amoeba** [comment]
Added Edge to list as it's the default browser in Win10

**Comment by laurenwalker** [comment]
We just need some Safari testing at this point

**Comment by laurenwalker** [comment]
Safari 10 seems to work well. Just need to get a VM of Mac OS X 10.11 up so I can test with Safari 9

**Comment by laurenwalker** [comment]
I tested the Editor in Safari 9 and saw no Safari-specific errors. Closing this ticket as it looks good.
