### ISSUE TITLE
Hook up CI with tests

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/metacatui#1966]
Use CI tools to run test suites automatically with every commit

**Comment by laurenwalker** [comment]
I created a Node JS test script (`npm test`) that runs an Express server to execute the in-browser Mocha tests and parse the test results from the generated HTML. I created a GitHub Action to run this script on every push. So we now have automated tests for MetacatUI!

The README has a handy badge with the pass/fail status and failure messages can be viewed either on GitHub Actions or by running the tests locally via `npm view-tests` and viewing the test results on localhost.

**Comment by amoeba** [comment]
This is great, thanks @laurenwalker.
