### ISSUE TITLE
feature requests from 2017 training event

### ISSUE THREAD

**Issue by mbjones** [NCEAS/metacatui#197]
During the 2017 training event, we demonstrated the existing editor, and the following issues were raised as high-value improvements and/or bug fixes.  These need to be triaged with respect to the new editor, and bugs created for each describing how to handle it. 

- [ ] Efficiently enter names and addresses (see #175)
- Quality engine
    - [ ] change error messages to natural, readable language (too cryptic)
    - [ ] Have quality errors link to navigate back to proper form fields
- [ ] Units should be from a controlled list, with ability to create new as needed
- [ ] Add ability to save drafts before submission (guard against browser crashes and session timeouts)
- [ ] Use a template text file as an alternative to web form (see, [emldown](https://github.com/ropenscilabs/emldown))
- [ ] Support Paleo and other time scales in metadata
- [ ] Make a larger title box, appropriate for the desired title length
- [ ] Add subscribable notifications to be emailed when a data set is updated
- [ ] Make the 'role' dropdown extensible with custom roles
- [ ] Checkbox if temporal coverage isn't important
- [ ] Support multiple, discontinuous temporal coverages
- [x] Support multiple, discontinuous spatial coverages 
- [ ] Support inclusion of detailed spatial reference info for spatial objects (raster and vector) (see #218)
- [ ] Support use of FIPS codes and other vocabularies for spatial coverage
- [ ] TAR support (not sure exactly what was meant here, @amoeba may remember more)
- [ ] Ability to revise unit definitions (see earlier unit item)
- [ ] Ability to export to other metadata standards, particularly ISO 19115 and FGDC BDP
- [ ] Support controlled vocabularies everywhere with lookahead data entry widgets
- [ ] Support adding custom thesaurus beyond GCMD
    - [ ] Fix links and documentation for GCMD, which is more or less unuasble
    - [ ] Use the GCMD API to do lookahead matching for GCMD keywords

**Comment by amoeba** [comment]
Thanks for collating these!

**Comment by laurenwalker** [comment]
We've created issues for each of these bullet points and have skipped over a couple that we don't intend to implement/change.
