### ISSUE TITLE
Identifier search fails when reserved characters "{" or "}" appear in search term

### ISSUE THREAD

**Issue by datadavev** [NCEAS/metacatui#2]
Searching the DataONE search UI for identifier "{412470CB-9F67-4831-B8DC-E0FC1BE36D36}" fails to return.

Escaping the braces with "\" works. e.g.: `\{412470CB-9F67-4831-B8DC-E0FC1BE36D36\}` when the value is used in the identifier search field.

**Comment by laurenwalker** [comment]
Fixed
