### ISSUE TITLE
fix scroll position

### ISSUE THREAD

**Issue by mbjones** [NCEAS/metacatui#201]
When navigating from page to page, one can end up on screens with nothing visible.  This happens when I am on a screen with a lot of sections and therefore have scrolled far down the page.  If I then click a link to another page that is short, the content area goes blank because the content is scrolled off the screen.  It would be more understandable if navigation set the scrollbar to the top of new pages or sections when one navigates there.

**Comment by laurenwalker** [comment]
I believe this was fixed already
