### ISSUE TITLE
Refactor UserView with group management separated into a new view

### ISSUE THREAD

**Issue by vchendrix** [NCEAS/metacatui#2024]
In order to support Project Spaces team management,  it is necessary to refactor MetacatUI [`views/UserView`](https://github.com/NCEAS/metacatui/blob/main/src/js/views/UserView.js) to separated out the group management functionality so that it can be used outside of the user settings page.

This will require us to make copy of [`views/UserView`](https://github.com/NCEAS/metacatui/blob/main/src/js/views/UserView.js) and then create a subview  `js/views/UserGroupView` that  encapsulates all of the group logic from the UserView.

**Proposed New ESS-DIVE Theme Views**
+ `src/js/views/UserView` (refactored)
+ `src/js/views/UserGroupView` (new)

The outcome of this will not have any functionality changes it will merely replace the MetacatUI view with the new ESS-DIVE theme views above. Additionally, try to change as little logic as possible except where the GroupView interacts with the UserView.

**Comment by vchendrix** [comment]
In order to support Project Spaces team management,  it is necessary to refactor MetacatUI [`views/UserView`](https://github.com/NCEAS/metacatui/blob/main/src/js/views/UserView.js) to separated out the group management functionality so that it can be used outside of the user settings page.

This will require us to make copy of [`views/UserView`](https://github.com/NCEAS/metacatui/blob/main/src/js/views/UserView.js) and then create a subview  `themes/essdive/views/UserGroupView` that  encapsulates all of the group logic from the UserView.

**Proposed New ESS-DIVE Theme Views**
+ `themes/essdive/views/UserView` 
+ `themes/essdive/views/UserGroupView` 

The outcome of this will not have any functionality changes it will merely replace the MetacatUI view with the new ESS-DIVE theme views above. Additionally, try to change as little logic as possible except where the GroupView interacts with the UserView.

**Comment by laurenwalker** [comment]
This would be really useful for other repositories as well, so if this refactor and new view can be done in the main MetacatUI codebase, we would certainly take advantage of it.

**Comment by laurenwalker** [comment]
@vchendrix No, it's something that's on my "Wish List" but I haven't started any development yet.

**Comment by vchendrix** [comment]
@laurenwalker thanks for the clarification.  Should @mamelara branch off main?

**Comment by laurenwalker** [comment]
Yes, main would be best to branch from. Thanks!

**Comment by laurenwalker** [comment]
Hi @mamelara - Thanks for reaching out! I don't remember the original case for `UserGroupView`, it was likely going to be the start of a refactor similar to what you are doing now, but never materialized out of lack of sprints to work on this. I'd say go ahead and reuse it however you'd like (or even remove it).
