### ISSUE TITLE
add support for pubDate

### ISSUE THREAD

**Issue by mbjones** [NCEAS/metacatui#205]
EML should include a `pubDate` field to record when a particular version of the data set was released.  This should generally be a year of publication (e.g., 2017). It probably would be fine to set it automatically, but it should be editable to allow it to be changed to reflect when a data set version was actually released (even if the metadata entry we are gathering is done much later).  Let's discuss how to best handle this.

Note that without this, the Quality check fails for this data set with the following error:

    A publication date is not present.

**Comment by amoeba** [comment]
This is a great time for me to increase my understanding of this element in EML. From the spec, as well as your comment above, it appears `pubDate` (when used on an EML `dataset)` describes the date the dataset was published. What does that actually mean? I don't know what "publishing a dataset" means. Is this distinct from when the metadata record was "published" (whatever that means)?

**Comment by mbjones** [comment]
Yep, the spec says:

> The 'pubDate' field represents the date that the resource was published.

As publication is a nebulous term, we have generally intended it as the date on which the repository or other institution that is responsible for the data package considers it to be published, in that they have made it accessible and commit to its continued existence.  Also, the publication date for two different versions of a data package can be and often are different, and they are typically much later than the temporal coverage for the data set.

**Comment by amoeba** [comment]
Since, in DataONE terms, 'dataset' most closely maps to "Data Package" and the Data Package is defined by its ORE, any modification of the ORE would imply we've re-"published" the dataset?

So changes such as adding, removing, or updating `Object`s of `formatType` `METADATA`, `DATA`, or `RESOURCE` `Object`s would **all**  imply a re-"publication" or the dataset? If that's the case, then the field shouldn't be user-editable as it should always match the creation date of the ORE containing the EML record.

Would there ever be a case where the two would be out of step?

**Comment by mbjones** [comment]
Well, as it has traditionally been an EML field, and EML was the descriptor for a data package, the `pubDate` was usually tied to the publication of an EML document, not an ORE document.  Most scientists think of it as the release date for the data set, and so many have asked us to retroactively post-date the field so that the data set is 'published' when they released it (i.e., the year that shows in the citation makes sense to them).  This has happened many times.  Also, not all versions are created equal.  Given a released data set with an EML `pubDate` set to 2010, an update to the EML record that only changed access control rules or did something inconsequential in 2015 that didn't really change the data might not have the pubDate updated at all, and it would stay at 2010.  So, that's the history of the `pubDate` field.  Its messy.  And I'm not sure one-size-fits-all will work here.  So yes, I think there are many cases when the two will be out of step.

**Comment by amoeba** [comment]
Okay thanks, that helps clarify the problem a ton. Though I'm not seeing a way forward.

**Comment by amoeba** [comment]
Doing this now. Just finishing up the view validation routine.

**Comment by amoeba** [comment]
I've got a first-pass implementation done. I think it's all working nicely. Need to figure out what to do about updateBasicText still.

**Comment by laurenwalker** [comment]
Closing this issue for now - basicText refactoring can be in a separate ticket.
