### ISSUE TITLE
Errors when editing data package not generated by metacatui

### ISSUE THREAD

**Issue by yvanlebras** [NCEAS/metacatui#2053]
**Describe the bug**
When Editing a data package created by EML Assembly Line / MetaShARK through the metacatui editor, a message is saying that saving the modification is not possible due to errors.

![image](https://user-images.githubusercontent.com/7910679/188075754-f44b12d8-96f5-42d8-b510-64a31832381a.png)

Looking at errors, it appears that errors are coming from the "taxa" part, where every classification row should have a rank value, we see some classification rows don't have!

![image](https://user-images.githubusercontent.com/7910679/188075968-1a45d861-f271-472d-8d80-659e51684414.png)

And we have these rank informations on the EML file (and data package view from metacatui)
![image](https://user-images.githubusercontent.com/7910679/188076825-7fb49163-50b0-4731-b898-39a47bba2e60.png)

Maybe this is only due to the fact we are using particular authorities to infer these classifications? But as it seems the metacatui editor don't recognize some elements already specified (for example for "Usage Rights", licence already specified, CC-BY 4.0 here, but in the editor nothing is marked) on the EML file, maybe this is a real "bug" ?

**To Reproduce**
1. Go to '[this data paackage](https://data.test.pndb.fr/view/urn%3Auuid%3A47936173-2f77-4408-9824-1e4e6f31f52e)'
2. Click on 'Edit'
3. Change something then click 'Save'

**Expected behavior**
Edit a data package, save and all is ok ;)

**Desktop (please complete the following information):**
 - OS: [windows]
 - Browser [chrome]
 - metacatui 2.21

**Comment by robyngit** [comment]
Thanks for reporting this error with thorough details, @yvanlebras! :)

I uploaded a copy of your EML document [here](https://test.arcticdata.io/view/urn%3Auuid%3Aec1e9e85-ba7f-4937-9215-3b6318f415b8) for testing and also saw the `Every classification row should have a rank and value` error when trying to save a change.

After inspecting your EML, I see that there is in fact a taxonomic classification that has a value but no rank. On line 1729:
```
<taxonomicClassification>
  <taxonRankValue>non_renseigne</taxonRankValue>
</taxonomicClassification>
```
This is reflected in the editor at the bottom of the Taxa page:
<img width="979" alt="Screen Shot 2022-09-02 at 15 35 24" src="https://user-images.githubusercontent.com/26600641/188225540-73bacfcc-490a-4083-b9ba-65280caa0dc0.png">

Clicking the `X` to remove this row in the editor fixes the save error for me. @yvanlebras, could you try removing that row and seeing if the error is resolved?

**Comment by yvanlebras** [comment]
Thanks for your rapid answer Robyn !

And what an eagle eye! Very nice catch!!! THANK YOU ! Effectively, removing this row allows me to edit and save the data package, AMAZZIIINGGGG ! So no real issue with the possibility to upload a data package not written from metacatui editor and then edit it with this metacatui editor! Too cool !! THANK YOU !!!!

**Comment by robyngit** [comment]
Great that it works now, @yvanlebras! I think the real issue here is that the editor doesn't indicate _which_ classification is causing the error. I've made an issue for that here: https://github.com/NCEAS/metacatui/issues/2054
