### ISSUE TITLE
entity list disappears when returning to edit

### ISSUE THREAD

**Issue by mbjones** [NCEAS/metacatui#206]
I created a data package with 4 CSV files, and filled out all of the metadata overall, plus attribute info for two of the CSV files.  Everything saved and displayed fine.  I then clicked 'Edit' to return to editing the document, but when I did none of the 4 CSV files was listed in the package, instead it showed a blank white box.  See attached screenshot.  

<img width="1892" alt="entity-list-missing" src="https://user-images.githubusercontent.com/766407/29342971-82dc4f7a-81da-11e7-8c04-01df6ff04fb2.png">

**Comment by amoeba** [comment]
Got that screenshot?

**Comment by mbjones** [comment]
Just added it.  Also, I just reloaded the page, and noticed that one of the four entities now shows up.  So maybe this is an indexing delay?

**Comment by laurenwalker** [comment]
This is a bug I discovered yesterday and am already working on.
