### ISSUE TITLE
File sizes in the package table are actually in MiB, but are displayed in MB

### ISSUE THREAD

**Issue by robyngit** [NCEAS/metacatui#2094]
There was some confusion recently when someone noticed that the size of a data file as measured by the OS did not match the file size displayed in MetacatUI. This issue was caused by the fact that the numbers we display in MetacatUI are actually [Metibytes (MiB)](https://simple.wikipedia.org/wiki/Mebibyte) but we show them as [Megabytes (MB)](https://simple.wikipedia.org/wiki/Megabyte).
![Screenshot 2023-02-07 at 4 43 30 PM](https://user-images.githubusercontent.com/26600641/217549121-f9341182-251c-48a0-a94c-0ccc978ba7e0.png)

**Comment by dvirlar2** [comment]
Robyn, you're so quick! I was going to make an issue for this, and it's already made. Thank you! 😁  I do want to point out that the same issue (MB == Mebibyte, not Megabyte) also occurs in the submission form. In the following screenshot, the underlined file size in _megabytes_ is 992.5. So confirmed that it's doing the same thing there as well.
<img width="1589" alt="Screen Shot 2023-02-08 at 12 26 59 PM" src="https://user-images.githubusercontent.com/98365096/217645651-39464a59-5139-4b51-9a08-222cd920a460.png">

I'm not sure how much easier/harder it is to change things in the submission form than the landing pages, but just wanted to let y'all know! Thanks y'all!

**Comment by robyngit** [comment]
@dvirlar2, thanks that's useful! @rushirajnenuji is actually working on making the package table on the submission page the same as the package table on the landing page - which means it's just one update to make! 🎉
