### ISSUE TITLE
Enforce JS formatting standards to improve readability and encourage collaboration

### ISSUE THREAD

**Issue by robyngit** [NCEAS/metacatui#2096]
**Describe the feature you'd like**
Select a code formatting standard, and enforce it using a shared JS formatter tool / linter. Reformat all JS files in MetacatUI to align with this standard. Consider also implementing a pre-commit hook to prevent unstyled code from being committed.

**Is your feature request related to a problem? Please describe.**
Code in MetacatUI uses a combination of tabs and spaces for indenting, and has many other stylistic inconsistencies. The result is that the code tends to be difficult to read, understand, and update. I believe these challenges are a barrier to onboarding new developers and discourage contributions from external developers.

**Additional context**
Given that this will cause major merge conflicts for users who have extended MetacatUI, and that any code that doesn't follow the new standard will not be valid, this should be considered a breaking change. This was discussed as part of the the [3.0.0 release](https://github.com/NCEAS/metacatui/discussions/2028).

**Comment by robyngit** [comment]
There are plenty of formatters, linters, and standards to choose from. I haven't done a deep dive into what's available, but [standardJS](https://standardjs.com/) looks really nice. Here are some highlights:
- No config required: "At the end of the day you have to 'just pick something', and that's the whole philosophy of standard -- its a bunch of sensible 'just pick something' opinions."
- Supports extensions for Atom, VSCode, Vim, Emacs, Brackets & Webstorm
- Can use in pre-commit hooks
- Has an automatic formatter
- Widely used (27.9K stars on GitHub)

**Comment by robyngit** [comment]
We should also consider [prettier](https://prettier.io/). From @ianguerin:
> I usually opt for prettier because it has very little configuration, it makes a lot of its own style decisions rather than letting me make them

**Comment by ianguerin** [comment]
Prettier also plays nicely with eslint with projects like [eslint-config-prettier](https://github.com/prettier/eslint-config-prettier) that ensure there are not conflicting rules with having both configured. 

Eslint seems to be more extensible, it lets you define your own rules, so you can enforce things like property name ordering, or import ordering, the possibilities are great. 
I was playing around with eslint's playground to try to restrict a specific property from Backbone.View declarations, and it even provides [a shareable link](https://eslint.org/play/#eyJ0ZXh0IjoiY29uc3QgQmFja2JvbmUgPSB7Vmlldzoge2V4dGVuZCgpe319fTtcblxuY29uc3QgTXlHb29kVmlldyA9IEJhY2tib25lLlZpZXcuZXh0ZW5kKHtcbmNsYXNzTmFtZTpcImdvb2RcIixcbn0pO1xuXG5jb25zdCBNeUJhZFZpZXcgPSBCYWNrYm9uZS5WaWV3LmV4dGVuZCh7XG4gIGNsYXNzTmFtZTpcImJhZFwiLFxuICBjbGFzc05hbWVzOntcbiAgICBcInNvbWV0aGluZ1wiOlwidGhpcyBzaG91bGQgYmUgZmxhZ2dlZFwiLFxuICB9XG59KTtcblxuLy9lc2xpbnQtZGlzYWJsZS1uZXh0LWxpbmUgbm8tdW5kZWZcbmNvbnNvbGUubG9nKHtjbGFzc05hbWVzOnt9fSk7XG5cbi8vIGVzbGludC1kaXNhYmxlLW5leHQtbGluZVxuY29uc29sZS5sb2coe015R29vZFZpZXcsIE15QmFkVmlld30pOyIsIm9wdGlvbnMiOnsicnVsZXMiOnsiY29uc3RydWN0b3Itc3VwZXIiOlsiZXJyb3IiXSwiZm9yLWRpcmVjdGlvbiI6WyJlcnJvciJdLCJnZXR0ZXItcmV0dXJuIjpbImVycm9yIl0sIm5vLWFzeW5jLXByb21pc2UtZXhlY3V0b3IiOlsiZXJyb3IiXSwibm8tY2FzZS1kZWNsYXJhdGlvbnMiOlsiZXJyb3IiXSwibm8tY2xhc3MtYXNzaWduIjpbImVycm9yIl0sIm5vLWNvbXBhcmUtbmVnLXplcm8iOlsiZXJyb3IiXSwibm8tY29uZC1hc3NpZ24iOlsiZXJyb3IiXSwibm8tY29uc3QtYXNzaWduIjpbImVycm9yIl0sIm5vLWNvbnN0YW50LWJpbmFyeS1leHByZXNzaW9uIjpbImVycm9yIl0sIm5vLWNvbnN0YW50LWNvbmRpdGlvbiI6WyJlcnJvciJdLCJuby1jb250cm9sLXJlZ2V4IjpbImVycm9yIl0sIm5vLWRlYnVnZ2VyIjpbImVycm9yIl0sIm5vLWRlbGV0ZS12YXIiOlsiZXJyb3IiXSwibm8tZHVwZS1hcmdzIjpbImVycm9yIl0sIm5vLWR1cGUtY2xhc3MtbWVtYmVycyI6WyJlcnJvciJdLCJuby1kdXBlLWVsc2UtaWYiOlsiZXJyb3IiXSwibm8tZHVwZS1rZXlzIjpbImVycm9yIl0sIm5vLWR1cGxpY2F0ZS1jYXNlIjpbImVycm9yIl0sIm5vLWVtcHR5IjpbImVycm9yIl0sIm5vLWVtcHR5LWNoYXJhY3Rlci1jbGFzcyI6WyJlcnJvciJdLCJuby1lbXB0eS1wYXR0ZXJuIjpbImVycm9yIl0sIm5vLWVtcHR5LXN0YXRpYy1ibG9jayI6WyJlcnJvciJdLCJuby1leC1hc3NpZ24iOlsiZXJyb3IiXSwibm8tZXh0cmEtYm9vbGVhbi1jYXN0IjpbImVycm9yIl0sIm5vLWZhbGx0aHJvdWdoIjpbImVycm9yIl0sIm5vLWZ1bmMtYXNzaWduIjpbImVycm9yIl0sIm5vLWdsb2JhbC1hc3NpZ24iOlsiZXJyb3IiXSwibm8taW1wb3J0LWFzc2lnbiI6WyJlcnJvciJdLCJuby1pbnZhbGlkLXJlZ2V4cCI6WyJlcnJvciJdLCJuby1pcnJlZ3VsYXItd2hpdGVzcGFjZSI6WyJlcnJvciJdLCJuby1sb3NzLW9mLXByZWNpc2lvbiI6WyJlcnJvciJdLCJuby1taXNsZWFkaW5nLWNoYXJhY3Rlci1jbGFzcyI6WyJlcnJvciJdLCJuby1uZXctbmF0aXZlLW5vbmNvbnN0cnVjdG9yIjpbImVycm9yIl0sIm5vLW5vbm9jdGFsLWRlY2ltYWwtZXNjYXBlIjpbImVycm9yIl0sIm5vLW9iai1jYWxscyI6WyJlcnJvciJdLCJuby1vY3RhbCI6WyJlcnJvciJdLCJuby1wcm90b3R5cGUtYnVpbHRpbnMiOlsiZXJyb3IiXSwibm8tcmVkZWNsYXJlIjpbImVycm9yIl0sIm5vLXJlZ2V4LXNwYWNlcyI6WyJlcnJvciJdLCJuby1zZWxmLWFzc2lnbiI6WyJlcnJvciJdLCJuby1zZXR0ZXItcmV0dXJuIjpbImVycm9yIl0sIm5vLXNoYWRvdy1yZXN0cmljdGVkLW5hbWVzIjpbImVycm9yIl0sIm5vLXNwYXJzZS1hcnJheXMiOlsiZXJyb3IiXSwibm8tdGhpcy1iZWZvcmUtc3VwZXIiOlsiZXJyb3IiXSwibm8tdW5kZWYiOlsiZXJyb3IiXSwibm8tdW5leHBlY3RlZC1tdWx0aWxpbmUiOlsiZXJyb3IiXSwibm8tdW5yZWFjaGFibGUiOlsiZXJyb3IiXSwibm8tdW5zYWZlLWZpbmFsbHkiOlsiZXJyb3IiXSwibm8tdW5zYWZlLW5lZ2F0aW9uIjpbImVycm9yIl0sIm5vLXVuc2FmZS1vcHRpb25hbC1jaGFpbmluZyI6WyJlcnJvciJdLCJuby11bnVzZWQtbGFiZWxzIjpbImVycm9yIl0sIm5vLXVudXNlZC1wcml2YXRlLWNsYXNzLW1lbWJlcnMiOlsiZXJyb3IiXSwibm8tdW51c2VkLXZhcnMiOlsiZXJyb3IiXSwibm8tdXNlbGVzcy1iYWNrcmVmZXJlbmNlIjpbImVycm9yIl0sIm5vLXVzZWxlc3MtY2F0Y2giOlsiZXJyb3IiXSwibm8tdXNlbGVzcy1lc2NhcGUiOlsiZXJyb3IiXSwibm8td2l0aCI6WyJlcnJvciJdLCJyZXF1aXJlLXlpZWxkIjpbImVycm9yIl0sInVzZS1pc25hbiI6WyJlcnJvciJdLCJ2YWxpZC10eXBlb2YiOlsiZXJyb3IiXSwibm8tcmVzdHJpY3RlZC1zeW50YXgiOlsiZXJyb3IiLHsibWVzc2FnZSI6IkJBRCIsInNlbGVjdG9yIjoiQ2FsbEV4cHJlc3Npb25bY2FsbGVlLnByb3BlcnR5Lm5hbWU9J2V4dGVuZCddW2NhbGxlZS5vYmplY3Qub2JqZWN0Lm5hbWU9J0JhY2tib25lJ10gUHJvcGVydHlba2V5Lm5hbWU9J2NsYXNzTmFtZXMnXSJ9XX0sImxhbmd1YWdlT3B0aW9ucyI6eyJwYXJzZXJPcHRpb25zIjp7ImVjbWFGZWF0dXJlcyI6e319fX19)!

**Comment by robyngit** [comment]
Released in 2.29.1
