### ISSUE TITLE
Metrics displayed in the modal should be in the same order as the the metrics buttons in the dataset landing page

### ISSUE THREAD

**Issue by robyngit** [NCEAS/metacatui#2100]
Originally pointed out by @dvirlar2 I think - the order of the metrics on the dataset landing pages do not match the order of the metrics when you scroll through them in the modal:

The buttons (Downloads, Citations, Views)
![image](https://user-images.githubusercontent.com/26600641/219138113-16c6c76f-fde9-4754-9a23-26fadaf5ba9d.png)

The modal (Views, Citations, Downloads)
![image](https://user-images.githubusercontent.com/26600641/219138245-05b62dbf-46b5-43c4-8d44-c209944a0399.png)

This has been momentarily confusing for me, since it's intuitive that they should be in the same order.

**Comment by robyngit** [comment]
Fixed in https://github.com/NCEAS/metacatui/commit/23f8e18ec43b65e1d3bf5b4d2e27d211684a904e

**Comment by dvirlar2** [comment]
Thank you @robyngit!!!

**Comment by robyngit** [comment]
Thanks for pointing it out, @dvirlar2 !! 🎉
