### ISSUE TITLE
Add "information icon" to "Alternate Identifier" field

### ISSUE THREAD

**Issue by dvirlar2** [NCEAS/metacatui#2103]
Recently, a user was having issues understanding the data in a dataset. I helped troubleshoot this error by going to the original copy of the dataset, found in the "Alternate Identifier" field, and finding the relevant information that hadn't been transferred over to our copy of the dataset. I think the user could have found this information on their own if they knew what the Alternate Identifier field contained, and how it could be helpful to them. As such, I think it would be helpful to include an information icon that explicitly details what the field is. 

Here is a rough sketch of where I think the icon should go: 
![image](https://user-images.githubusercontent.com/98365096/220473690-7e30f5f0-284f-4e43-b367-fff9a3d33c5d.png)

The explanation should be something along the lines of:

> _"This field contains a link to the original copy of this dataset. The dataset you are currently viewing is a copy of this record. Due to differences in archival methodology between repositories, this copy may not contain all information present within the original record."_

I know it's not great to say "hey we may not have everything" because that might make us look bad, but I think it's important to somehow signify that there might be more content in the original record, and why that is, so people have more incentive to check out the original.

**Comment by robyngit** [comment]
Thanks for including a figure and some explanatory text, @dvirlar2 ! That's super helpful.

**Comment by mbjones** [comment]
Yeah, thanks for the great feature request.

One comment -- Alternate Identifiers are used for more than just "original" copies -- there are many different use cases for alternate IDs, and many groups use them differently. I thin the most we can say for certain is that the alternate identifier was at some point used to identify **some** version of this dataset, which might be the same or different, and may or may not be currently accessible. The field is often used for old identifers that used to be the main identifier for a data set but were later replaced (e.g., going from a UUID to a DOI). While your suggested taxt is good for the one case you outline, it will be misleading in the other cases. So we'll need to be clear about all of that.

**Comment by robyngit** [comment]
Thanks for the clarification, @mbjones!

**Comment by robyngit** [comment]
Now fixed in the develop branch, I used the text:

> An identifier used to reference this dataset in the past or in another system. This could be a link to the original dataset or an old  identifier that was replaced. The referenced dataset may be the same  or different from the one you are currently viewing, and its accessibility may vary. It may provide additional context about the history and evolution of the dataset.

The text is configurable in the MetadataView and is easy to update.

<img width="475" alt="Screenshot 2023-08-03 at 15 29 52" src="https://github.com/NCEAS/metacatui/assets/26600641/468a4e1e-3b98-457d-a550-87c6e54cc84e">
