### ISSUE TITLE
Add metatags to portals for better SEO

### ISSUE THREAD

**Issue by robyngit** [NCEAS/metacatui#2150]
Here is how our portals show up in search results:

![Screenshot 2023-06-26 at 10 35 21](https://github.com/NCEAS/metacatui/assets/26600641/2ab877b3-0125-4d28-814b-3485968a0b2d)

We should include a title, description, etc. for portal pages so that search results give useful information about what each portal is.

Currently, we don't update meta tags dynamically in MetacatUI (see https://github.com/NCEAS/metacatui/issues/1723). At a minimum, we need to add meta tags when a portal is loaded, and remove them when someone navigates away from the portal.

**Comment by mbjones** [comment]
Wow, yes, great catch @robyngit

**Comment by robyngit** [comment]
It was Jen Moss and two teachers who work with her who caught this! :)

**Comment by robyngit** [comment]
This is now fixed in the `develop` branch - both the document title and description meta tags are updated for all portal pages. I'm curious to see if this will fix how the portals show up in searches.

Part of the issue may be that when someone navigates to e.g. `arcticdata.io/catalog/portals/permafrost`, the app needs time to look up the most recent portal document that has the `permafrost` label, then to parse it and get the portal name & description. During that time, the website shows the "loading..." text, which is also the text that currently appears in search results.

If this update does not fix how portals are displayed in search results, then we should open a new issue, as this might require a more complex fix like coming up with new ways to find the portal document.
