### ISSUE TITLE
Clicking back button too many times makes start parameter negative

### ISSUE THREAD

**Issue by datadavev** [NCEAS/metacatui#2155]
**Describe the bug**
When browsing DataONE search and using the browser back button to go back to the index page, hitting the back button too many times causes an error:

**To Reproduce**
1. Visit search.dataone.org
2. click on the a dataset
3. use the browser back button to go back to the index
4. Hit the back button again

**Expected behavior**
An error should not appear

**Screenshots**
See also https://app.screencast.com/U5XaleOOx1y5K

<img width="654" alt="image" src="https://github.com/NCEAS/metacatui/assets/605409/405ae2c0-6cbe-45ca-a8b3-f88042973536">

**Desktop (please complete the following information):**
 - OS: OSX
 - Chrome
 - Version 114.0.5735.198 (Official Build) (x86_64)

**Comment by robyngit** [comment]
I and others were not able to reproduce this. It seems Dave had `/page/0` in his browser history for some reason. Navigating to that page of the catalog does in fact give this error. Though it's unlikely to happen for most users, MetacatUI should just autocorrect any page numbers <1 to 1.

**Comment by robyngit** [comment]
@rushirajnenuji pointed out that the query that leads to the error is:

```
https://search.dataone.org/cn/v2/query/solr/?q= -obsoletedBy:* AND -formatId:*dataone.org\/collections* AND -formatId:*dataone.org\/portals* AND formatType:METADATA&fl=id,seriesId,title,origin,pubDate,dateUploaded,abstract,resourceMap,beginDate,endDate,read_count_i,geohash_9,datasource,isPublic,documents,sem_annotation,northBoundCoord,southBoundCoord,eastBoundCoord,westBoundCoord&sort=dateUploaded desc&rows=25&start=-25&facet=true&facet.sort=index&facet.field=geohash_2&facet.mincount=1&facet.limit=-1&wt=json
```
