### ISSUE TITLE
Prevent users from entering impossible geographic coordinates in the editor

### ISSUE THREAD

**Issue by robyngit** [NCEAS/metacatui#2159]
**Describe the feature you'd like**
Build some logic In the geographic coverage section of the editor that prevents users from entering in coordinates that don't make sense, like a bounding box that has the south point further north than the north point.

**Additional context**
A [dataset](https://arcticdata.io/catalog/view/urn%3Auuid%3A35ccd85f-8168-40b4-bc67-44c5946811d4) seems to have reversed the north and south coordinate of the bounding box, and this prevented it from being indexed properly in Solr. As a result, the dataset did not appear on the catalog search map:
![Screen Shot 2023-07-13 at 9 34 45 AM](https://github.com/NCEAS/metacatui/assets/26600641/7d6da8d1-a096-4a04-83c0-afb35c785af3). See https://github.com/NCEAS/metacatui/issues/2158.

Related to: https://github.com/NCEAS/metacatui/issues/303

**Comment by mbjones** [comment]
In addition to inverted coordinates, another thing to check for may be bounding boxes that attempt to traverse the international dateline or tries to contain the north or south poles, which don't really work.

**Comment by robyngit** [comment]
We now have a `GeoBoundingBox` model with its own validation rules (in the `feature-2180-draw-on-map` branch at the time of writing). We can use this in the EML editor to make sure coordinates are valid.

**Comment by robyngit** [comment]
In the develop branch, we now check for and show validation errors for all the scenarios discussed above:

<img width="737" alt="Screenshot 2023-11-01 at 20 38 33" src="https://github.com/NCEAS/metacatui/assets/26600641/d58b9c7d-8861-49c0-9d63-ce7757ba8871">

These validation rules are included in new tests for the EMLGeoCoverage model:

<img width="459" alt="Screenshot 2023-11-01 at 20 41 30" src="https://github.com/NCEAS/metacatui/assets/26600641/7961c3c4-214b-4d61-b5f5-df0399e5bf54">

**Comment by mbjones** [comment]
These are great. Could the errors also include solutions? For example, something like:

`The bounding box cannot cross the anti-meridian. Please use multiple bounding boxes that meet at the anti-meridian instead.`

Maybe it could be shorter, but that's the idea.

**Comment by robyngit** [comment]
Yes, good idea!

**Comment by robyngit** [comment]
✅ Done! (@mbjones please let me know if any of these should be tweaked)

<img width="862" alt="Screenshot 2023-11-02 at 09 13 07" src="https://github.com/NCEAS/metacatui/assets/26600641/370da3b6-b535-4e15-ad11-359365fb5ca9">


```js
errorMessages: {
  "default": "Please correct the geographic coverage.",
  "north": "Northwest latitude out of range, must be >-90 and <90. Please correct the latitude.",
  "east": "Southeast longitude out of range (-180 to 180). Please adjust the longitude.",
  "south": "Southeast latitude out of range, must be >-90 and <90. Please correct the latitude.",
  "west": "Northwest longitude out of range (-180 to 180). Check and correct the longitude.",
  "missing": "Latitude and longitude are required for each coordinate. Please complete all fields.",
  "description": "Missing location description. Please add a brief description.",
  "needPair": "Location requires at least one coordinate pair. Please add coordinates.",
  "northSouthReversed": "North latitude should be greater than South. Please swap the values.",
  "crossesAntiMeridian": "Bounding box crosses the anti-meridian. Please use multiple boxes that meet at the anti-meridian instead.",
  "containsPole": "Coordinates include a pole. Latitudes should be >-90 and <90."
}
```

**Comment by mbjones** [comment]
:shipit:
