### ISSUE TITLE
After adding user to a group user does not show up on page refresh

### ISSUE THREAD

**Issue by vchendrix** [NCEAS/metacatui#2171]
**Describe the bug**
Adding a user to a group seems to work successfully, however when the page is refreshed the user does not appear to be there.  This was discovered when trying to add a user and then make them the owner.  

**To Reproduce**
You will need to use two different browsers to reproduce. I started with Chrome (browser 1) and then
switched to Firefox (browser 2).  However, you could use any two browsers and the result should be the same.  I have also reproduced this using Firefox and Safari.

1. Using broswer 1, Go to https://dev.nceas.ucsb.edu/ 
2. Click on [Username] > My Profile > Settings > Groups
3. Add a user to a group
4. Refresh the page
5. Navigate to [Username] > My Profile > Settings > Groups
6. Look at the group and see that the user is not there
7. Using broswer 2, navigate to [Username] > My Profile > Settings > Groups
8. Look at the group and see that the user is indeed in the group

**Expected behavior**
A user should be able to use one browser to add user to  a group and set them as the owner of that group.  

**Desktop (please complete the following information):**
Browser 1:
 - OS: Mac OS
 - Browser: Chrome
 - Version: 114.0.5735.248 (Official Build) (x86_64)

Browser 2:
 - OS: Mac OS
 - Browser: Firefox
 - Version: 115.0.2 (64-bit)

**Additional context**
This seems to be a caching issue of some sort

**Comment by mburrus** [comment]
Additional context: The issue was first noticed around 10:30am on 08/02. The last time a user was added to a group before this issue appeared was on 07/26.

**Comment by robyngit** [comment]
I was able to reproduce the issue by following these very clear steps, thanks @vchendrix. It definitely requires checking in another browser to see that the user you added is in fact in the group. I tried a hard refresh and even clearing my cache and it appears as though the group is not updated.

**Comment by taojing2002** [comment]
This issue may be related to the new setting on the cn Apache cache mechanism for the account requests. The account requests have a 60 ~ 120 seconds cache mechanism. So I am wondering if MetacatUi just gets a cache copy, which doesn't reflect the changes user just made.

The Apache configuration looks like:
```
<LocationMatch "/cn/v1/accounts*">
      CacheEnable disk
      CacheIgnoreNoLastMod On
      #not allowed - CacheIgnoreCacheControl On
      CacheMinExpire 60
      CacheMaxExpire 120
      CacheStoreExpired On
      #ExpiresActive On
      #ExpiresDefault "access plus 60 seconds"
    </LocationMatch>

    <LocationMatch "/cn/v2/accounts*">
      CacheEnable disk
      CacheIgnoreNoLastMod On
      #not allowed - CacheIgnoreCacheControl On
      CacheMinExpire 60
      CacheMaxExpire 120
      CacheStoreExpired On
      #ExpiresActive On
      #ExpiresDefault "access plus 60 seconds"
    </LocationMatch>
```
We need to figure out the best value for the cache.

**Comment by robyngit** [comment]
@taojing2002 changed the new cache mechanism for accounts API and this resolved the issue! 🎉
