### ISSUE TITLE
Map imagery disappears when navigating back to search page

### ISSUE THREAD

**Issue by iannesbitt** [NCEAS/metacatui#2172]
**Describe the bug**
After using the search page (e.g. [drp.dataone.org/data](https://drp.dataone.org/data)) navigating to a dataset, then using the "< Back to search" button, the imagery layer does not load correctly. Similarly, navigating to the About page and back to the Search causes a layer error. A full page refresh is needed to re-load the layer.

**To Reproduce**
1. Go to [drp.dataone.org/data](https://drp.dataone.org/data) or similar search page that uses Cesium map (perhaps just one that uses a Bing maps imagery layer
2. Click on a dataset
3. Click on "< Back to search"
4. See blue globe and imagery layers error in console

**Expected behavior**
The Bing Maps imagery should be displayed on the globe.

**Screenshots**
![image](https://github.com/NCEAS/metacatui/assets/18689918/4ad3ab53-0e4d-46c8-9381-16e28ebdad63)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Firefox, Safari
 - Version: 114.0.2, 15.4

**Additional context**
Have not tried with other imagery layers. I suspect it's something to do with a one-time object or session going stale and being re-requested somehow, which gets fixed on full refresh because a new object/session is requested.

**Comment by robyngit** [comment]
This was a bug caused by the fact that we were directly modifying the `cesiumOptions` (config) object while setting up the imagery layer. I fixed all map asset models so that we're only working with clones of the `cesiumOptions` object while setting up layers. Good catch @iannesbitt! 🎉
