### ISSUE TITLE
Cesium map navigation help/tool tips

### ISSUE THREAD

**Issue by iannesbitt** [NCEAS/metacatui#2173]
**Describe the feature you'd like**
There are several modes of movement that are necessary when navigating a Cesium scene. For example, left mouse is pan, scroll wheel rotation is zoom in/out, right mouse click/drag is zoom in/out, scroll wheel click/drag is rotate. Users who are not familiar with these modes of navigating a 3-dimensional map may have trouble doing so. Having a little question mark that brings up a navigation tool tip to explain the modes of navigation for mouse and/or trackpad would be useful for those users. It would be especially useful for trackpad users, who will likely have to modify their clicks and drags with a keypress in order to use all of the modes of navigation available (and required) to explore 3D data on a Cesium map.

**Is your feature request related to a problem? Please describe.**
n/a

**Additional context**
Cesium does have a tooltip on some of their [example maps](https://cesium.com/learn/cesiumjs-learn/cesiumjs-quickstart/) that does this (see below). However, I'm not sure all users are able to take advantage of this, as it doesn't exactly work with my Mac trackpad.
![image](https://github.com/NCEAS/metacatui/assets/18689918/b7e2488f-ddd2-4752-b5a0-822563f088e0)

![image](https://github.com/NCEAS/metacatui/assets/18689918/a9321faf-b6ef-40f7-a94e-f094557d1222)

**Comment by robyngit** [comment]
This came up today when Emily, who is new to the PDG team, couldn't figure out how to zoom in on the map with her mouse. Her initial instinct was to be able to use the two expand gesture like on the trackpad like you would on a touch screen, then looked for [+/- navigation buttons](https://github.com/NCEAS/metacatui/issues/2043). She ended up only being able to zoom using the "Zoom To" buttons. She even tried multiple browsers and devices! We need to ensure that basic navigation is intuitive, and if it's not, that instructions are readily available.

**Comment by robyngit** [comment]
Complete in the develop branch:

![map help panel preview](https://raw.githubusercontent.com/NCEAS/metacatui/develop/docs/screenshots/views/maps/MapHelpPanel.png)

Whether or not to show the help panel & navigation instructions is configurable. The option to show/hide the feedback section and the associated text is also configurable. By default the navigation panel is shown but the feedback section is not.
