### ISSUE TITLE
Error on missing googleAnalyticsKey

### ISSUE THREAD

**Issue by vchendrix** [NCEAS/metacatui#2183]
**Describe the bug**
Just brought up MetacatUI 2.26.0 and am getting an error about a missing googleAnalyticsKey.  We do not use this  google API.

```
VM505:54 Uncaught ReferenceError: googleAnalyticsKey is not defined
    at n.eval (eval at m.template (underscore.js:1454:20), <anonymous>:54:2)
    at n.c [as appHeadTemplate] (underscore.js:1461:21)
    at n.render (AppView.js?v=20230724T0903:150:18)
    at app.js?v=2.26.0:208:23
    at Object.execCb (require.js:1635:33)
    at Module.check (require.js:871:51)
    at Module.<anonymous> (require.js:1112:34)
    at require.js:129:23
    at require.js:1155:21
    at each (require.js:57:31)
```

**To Reproduce**
1. Go to http://wfsidata.org/
2. Look at http://wfsidata.org/config/config.js to confirm there is no analytics key
3. Open JS console

**Expected behavior**
The application should load seamlessly with or without a googleAnalyticsKey

**Screenshots**
<img width="1411" alt="Screenshot 2023-08-17 at 3 42 45 PM" src="https://github.com/NCEAS/metacatui/assets/1558129/f9cd41fb-d40c-4df5-befb-25329ae63918">

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser Chrome, Safari and Firefox

**Additional context**
The application is extending the default theme with very minor modifications.

**Comment by vchendrix** [comment]
I think I figured it out.  the appHead.html that I copied has changed.   Any advice on what I am supposed to do?

**Comment by robyngit** [comment]
@vchendrix nice work finding the fix! 🎉 

> Just wondering if there is a way to document changes to the root templates that are copied as a part of customization of themes.

This was an oversight on my part. I updated the `AppView` to no longer pass the `googleAnalyticsKey` to the `appHead` template, but this is clearly a breaking change for themes that are using the `googleAnalyticsKey` in their custom appHead template. I should have made this change in a way that's backwards compatible, or at the very least, documented the need for external themes to update the appHead template in the release notes. I'll keep this in mind for future releases. Sorry for the trouble!! Other than the release notes, is there anywhere else you'd want to see these types of changes documented?

**Comment by vchendrix** [comment]
Hey @robyngit!  That is a good question.  Since there is no way to know which templates a custom theme overrides, I think the release notes are probably the best place for it.  At least, that is all I can think of, for now.  Thanks for following up!

**Comment by robyngit** [comment]
Okay, then that is where any of these types of changes will be documented moving forward. Added it to my release checklist. Thanks!
