### ISSUE TITLE
Add more config options for layers in the Map Config

### ISSUE THREAD

**Issue by robyngit** [NCEAS/metacatui#2187]
The layers that show in the Cesium map are configured with JSON. We would like to add a few more configuration options to the layer config:

- [x] `clickFeatureAction`: This is currently set at the map level, to either "showDetails" or "zoom". With show details, a layer panel pops up with additional info about the feature. With zoom, the map zooms into the bounding sphere for that feature. There are cases where some layers should zoom on click(geohashes) and others should show details on click (other vector layers in a data catalog). If no action is set, it should default to the map-level behaviour.

- [x] `showOpacitySlider` a boolean that determines whether to show an opacity slider for the layer in the layer details panel

- [x] `showInLayerList`: Set to false to hide this layer in the layer list. Defaults to true. This will be used for issue #2180, because we don't want to show the layer that we create that stores the polygon a user draws on the map. It could also be useful for any layers a portal wants shown all the time - e.g. a base layer.

**Comment by robyngit** [comment]
`showInLayerList` has been implemented in https://github.com/NCEAS/metacatui/pull/2204

**Comment by robyngit** [comment]
- See [this guide](https://nceas.github.io/metacatui/guides/maps/cesium.html#configuration) for how we configure Cesium maps in MetacatUI portals, and see the [MapConfig](https://nceas.github.io/metacatui/docs/MapConfig.html) for all configuration options.
- The [`MapAssetConfig`](https://nceas.github.io/metacatui/docs/MapConfig.html#MapAssetConfig) shows the configuration options for each layer in a Cesium map (configured as `layers` in the `MapConfig`).
- The goal of this issue is to be able to add two more options to that `MapAssetConfig`:
  - `showOpacitySlider` - a boolean that determines whether to show an opacity slider for the layer in the layer details panel
  - `clickFeatureAction` - a string that determines what action to take when a feature is clicked on the layer. Options are `showDetails` or `zoom`.
  
  e.g.
  ```js
  {
    "label": "Local Stories",
    "layerId": "ls",
    "type": "GeoJsonDataSource",
    "opacity": 0.75,
    "showOpacitySlider": false,
    "clickFeatureAction": "zoom",
    "cesiumOptions": {
                        "data": "https://www.leonetwork.org/en/explore/posts?query=&type=TWEET&type=POST&type=ARTICLE&mode=geojson_compact&region=&polygon=&bbox=&minlat=&maxlat=&near=&radius=&categories=PERMAFROST%7cPermafrost+Change&categories_anyOrAll=ANY&fromdate=&todate="
                    }
  }
  ```
- The `MapAsset` model (src/js/models/maps/assets/MapAsset.js) handles the majority of the configuration for each layer in a Cesium map.
- Other models in the `src/js/models/maps/assets/` directory are just extensions of the `MapAsset` model for specific types of layers.
- The `LayerDetailsView` (src/js/views/maps/LayerDetailsView.js) is responsible for rendering the panel that shows info and controls for each layer, including the opacity slider.
  <img src="https://nceas.github.io/metacatui/screenshots/views/maps/LayerDetailsView.png" width="300" />
- A quick way to test changes to the map config during development is to directly modify the map config options that are passed to the Map model in the `initialize` method. For example, you could add the following to [the very top of `Map.initialize`](https://github.com/NCEAS/metacatui/blob/develop/src/js/models/maps/Map.js#L275):
   ```js
       config.layers = [
      {
        "label": "Local Stories",
        "layerId": "ls",
        "type": "GeoJsonDataSource",
        "opacity": 0.75,
        "showOpacitySlider": false,
        "clickFeatureAction": "zoom",
        "cesiumOptions": {
          "data": "https://www.leonetwork.org/en/explore/posts?query=&type=TWEET&type=POST&type=ARTICLE&mode=geojson_compact&region=&polygon=&bbox=&minlat=&maxlat=&near=&radius=&categories=PERMAFROST%7cPermafrost+Change&categories_anyOrAll=ANY&fromdate=&todate="
        }
      }
    ]
   ```
   Now any Cesium map you load locally will be overridden to show just one "Local Stories" layer with the two new configuration options that we want to use!

**Comment by alonakos** [comment]
`showOpacitySlider` implemented in [2482](https://github.com/NCEAS/metacatui/pull/2482)
