### ISSUE TITLE
Small bounding boxes are hard to understand

### ISSUE THREAD

**Issue by vchendrix** [NCEAS/metacatui#2198]
Dataset map bug: if bounding box is really small then give bigger sized map for reference, when opens bigger map include pin

**Proposed Solution**
+ Change how the larger map is display by padding 3 decimal degress
  around the center lat/lon.
+ Also, add a marker to the large map.

_Change this code_
https://github.com/NCEAS/metacatui/blob/ee44f2f6e77dd6bcb2e9dba8f9434fb513d3899d/src/js/views/MetadataView.js#L1039-L1042

to

```diff
            var url = "https://maps.google.com/?ll=" + latLngCEN.lat() + "," + latLngCEN.lng() +
-              "&spn=0.003833,0.010568" +
-              "&t=m" +
-              "&z=5";
+              "&q=" + latLngCEN.lat() + "," + latLngCEN.lng() +
+              // Pad 3 decimal degrees around the latlon center
+              "&spn=3,3" +
+              "&t=m";
```
**Examples of a small bounding**
from https://arcticdata.io/catalog/view/doi%3A10.18739%2FA29P2W73Z
![Screenshot 2023-09-29 at 1 39 30 PM](https://github.com/NCEAS/metacatui/assets/1558129/9958aa0d-596e-43e8-8381-eacec2decda1)

**Example of large map with no pin**
The is the result from clicking the map above

![Screenshot 2023-09-29 at 1 41 05 PM](https://github.com/NCEAS/metacatui/assets/1558129/7d75a5dc-edda-4d72-b770-1a20fa882c80)

**Comment by mbjones** [comment]
Thanks for the suggestion, @vchendrix and I'll `+1` that as something I have also thought should be improved. 

One thing to think about is how to handle multiple, small bounding boxes that are closely arranged. Some researchers submit detailed, small bounding boxes for their sampling units (e.g., 5 sq m plots), and they want them to show up in context of one another. Such small features can't be differentiated on a larger map, and the main purpose of the current view is to allow reasearchers to validate the details of the provided bounding box. One suggestion we have discussed is to combine all of the bounding boxes into a single interactive map for the dataset, and show them at a higher zoom level, but allow people to zoom in to see the specifics of any of the fine-scale boxes. I think that could be a good solution and would likely be quite feasible with current interactive map libraries.

**Comment by robyngit** [comment]
@vchendrix - I just finished working on this issue and want to share some observations:
- We are not using the [official Google API](https://developers.google.com/maps/documentation/urls/get-started#introduction) for creating links to maps, and I had a hard time getting the parameters we're using to work as expected.
- There's no way (that I can find) to add a marker to the map with these url parameters. If we use the official API, the best we can do is search for the centroid coordinates, but the result is then _too_ zoomed in for larger bounding boxes.
- I think the best bet is to calculate an appropriate z level based on the bounding box, which I did in https://github.com/NCEAS/metacatui/commit/c82c15c34e0ad7959955a17b0441cb086b1cba95, the results of which are shown below.
- An alternative is to use OSM, which allows you to set a bounding box and a marker directly in the url, e.g. ```const osmUrl = `https://www.openstreetmap.org/export/embed.html?bbox=${w},${s},${e},${n}&amp;layer=mapnik&amp;marker=${mapLat},${mapLng}`;```
- Obviously if we switch to using Cesium in the MetadataView, we'll have a lot more control.
- I think this solution fixes the problem of small bounding boxes, so I'll close this issue for now. The fix will be included in the upcoming release. Of course, we can always re-open it if more discussion is needed!

**Before** (@vchendrix example above)
<img width="1140" alt="Screenshot 2023-11-02 at 18 21 07" src="https://github.com/NCEAS/metacatui/assets/26600641/39ee3c47-bca1-4aa8-8ec1-8b7685132afd">

**After**
<img width="1140" alt="Screenshot 2023-11-02 at 18 20 27" src="https://github.com/NCEAS/metacatui/assets/26600641/a5249316-798f-40e7-8a0c-06838a07c298">
