### ISSUE TITLE
Support enlarging the legend on mouseover or click

### ISSUE THREAD

**Issue by iannesbitt** [NCEAS/metacatui#2239]
**Describe the feature you'd like**
The legend should be larger and should support more than 6 colors. I think the way to do that is to expand the entire legend in a tooltip-like object rather than one color at a time, which would allow more than 6 to be defined in categorical color palettes, and would increase the visibility of the colors.

**Is your feature request related to a problem? Please describe.**
We got some strong feedback at the DRP meeting that the legends are hard to read. I think this may be partially attributable to the fact that the DRP project has heavy Cesium utilization and that we have several layers whose color palettes are not well defined. But given the discussion @mbjones @robyngit and I had a few weeks back, I think we generally agree that they need to be larger or more readable somehow. 

**Additional context**
I realize that this is not a trivial problem to solve, but I do think it is important for the platform's usability going forward.

**Comment by iannesbitt** [comment]
Related to
- #1784

**Comment by robyngit** [comment]
@iannesbitt this looks like a duplicate of #1784 to me, what do you think? Also, why is this labelled as an "Epic"?

**Comment by iannesbitt** [comment]
> this looks like a duplicate of https://github.com/NCEAS/metacatui/issues/1784 to me, what do you think?
Yes, sorry for making all of these duplicates. I will go ahead and close them.

> Also, why is this labelled as an "Epic"?
Because I misclicked on the labels tab 😅 

Closing as duplicate.
