### ISSUE TITLE
Allow point sampling raster values from Cesium map

### ISSUE THREAD

**Issue by iannesbitt** [NCEAS/metacatui#2240]
**Describe the feature you'd like**
Vector features are already selectable and bring up a box with attribute information. The same should happen when the user clicks on a visible raster layer.
Probably the way this should work is that all visible raster layers will report sample values at the chosen point. This way, the user (and the developer) avoids having to work around the problem of "visibility" which may complicate their understanding of sampling just the "top" layer. Plus, until TOC layers are reorderable (#1769), this would be a way of reporting cell values that are unbiased by their ordering in the TOC, which is largely arbitrary.

**Is your feature request related to a problem? Please describe.**
Feedback from the DRP meeting is that people don't know what to do with the raster layers that have been added. They look good and behave in the way they expect, but generally they are only good for visualization at the moment. They should instead be useful as "decisionmaking tools" as well, i.e. they should be able to convey some quantitative data when the user selects certain locations.

**Additional context**
Similar to this view but with one value per visible raster layer, separated by layer name, perhaps with a lat/lon sample location at the top.
![Screen Shot 2023-12-21 at 15 40 55](https://github.com/NCEAS/metacatui/assets/18689918/6f529656-1c2f-4b5e-a351-c74334e44beb)

**Comment by robyngit** [comment]
> Probably the way this should work is that all visible raster layers will report sample values at the chosen point.

To obtain point information from our raster layers, we will need some sort of backend service. The service will need to be queryable for a given location, and will need to return actual data values from the raster datasets. The browser currently only has access to the PNG representation of the raster data.

There is a standardized approach to this outlined in WMS: the 'GetFeatureInfo' request can be used to retrieve information about particular points on a raster layer. When a user clicks a point on the map, the coordinates are sent to the server via a GetFeatureInfo request, and the server returns information about the raster cell at that location.

@iannesbitt do you think that issue #2190 is a duplicate of what you are describing here, or are there additional/different features DRP is requesting that are not covered there?

**Comment by iannesbitt** [comment]
Yes, it is! Sorry, thank you for pointing that out. Should I close as duplicate?

**Comment by iannesbitt** [comment]
Closing as duplicate.

**Comment by robyngit** [comment]
Thanks @iannesbitt! I transferred your comments over to that issue for additional context
