### ISSUE TITLE
Fly to coordinates in Cesium map

### ISSUE THREAD

**Issue by iannesbitt** [NCEAS/metacatui#2246]
**Describe the feature you'd like**
DRP team members have requested a way to fly to specific coordinates in the Cesium map. This could exist as a button that reveals a `lat, lon` text entry field (or two separate fields), which is then used to change the map focus location in a fly to manner similar to that of the behavior after pressing the Home button.

**Is your feature request related to a problem? Please describe.**
Researchers may be interested in a specific area of the map, which may be easiest to find with a copy/paste of coordinates. This would help researchers and other users zoom to areas of interest quickly.

**Additional context**
n/a

**Comment by robyngit** [comment]
I think this would be one of the more straight forward features to implement. Here are some pointers:

- The Map Model already has [a "zoomTo" method](https://github.com/NCEAS/metacatui/blob/758ff8e3710637d9fdf406a9c2383e56ff5be877/src/js/models/maps/Map.js#L269-L280) that this widget could call when the coordinates are entered into the entry field
- We could potentially make use of the [GeoPoint model](https://github.com/NCEAS/metacatui/blob/main/src/js/models/maps/GeoPoint.js) to validate the inputted coordinates.
- The widget should be its own independent view that interacts with the Map Model (e.g. see the [ToolbarView](https://github.com/NCEAS/metacatui/blob/main/src/js/views/maps/ToolbarView.js))
- The [MapView](https://github.com/NCEAS/metacatui/blob/main/src/js/views/maps/MapView.js) should do the work of creating an instance of this widget and inserting it into the map interface.
- We should design this feature with https://github.com/NCEAS/metacatui/issues/1796 in mind. For example, the widget we build here could eventually be extended to navigate to not only specific coordinates, but also place names or addresses.

**Comment by iannesbitt** [comment]
Thanks Robyn! I agree that it would be good to include place names as part of the search functionality. I will take a look at this when I have the opportunity.

**Comment by ianguerin** [comment]
Here's a demo of what I have built so far: https://drive.google.com/file/d/1Sukzcv3BjcxH3Pi2fNHLd1g2Oii7LNu7/view?usp=drive_link

I'm working on some unit tests now, but figured I'd share this in case it doesn't match expectations

**Comment by robyngit** [comment]
Looks great @ianguerin! @iannesbitt any comments from the DRP perspective?
