### ISSUE TITLE
Better display page for data quality runs with a status other than success

### ISSUE THREAD

**Issue by jeanetteclark** [NCEAS/metacatui#2264]
**Describe the feature you'd like**

Not sure if this is a feature request or a bug report but currently, if a dataset has a status of "processing" in metadig, the quality page says there was an error retrieving the report. I think we should be able to display some information in XML returned by the API which shows the status of the run instead.

Here is the current display:

<img width="798" alt="Screen Shot 2024-02-07 at 2 48 39 PM" src="https://github.com/NCEAS/metacatui/assets/24237074/a0e7a548-1cae-474d-976e-d9de10f45e1a">

The API (example query [here](https://api.test.dataone.org:30443/quality/runs/arctic.data.center.suite-1.2.0/urn:uuid:7d354557-0618-47a6-9ea6-02fe496f35da?_=1707261030663)) is returning this:

```
<ns0:run>
<timestamp>2024-02-06T22:57:27.237Z</timestamp>
<objectIdentifier>urn:uuid:7d354557-0618-47a6-9ea6-02fe496f35da</objectIdentifier>
<suiteId>arctic.data.center.suite-1.2.0</suiteId>
<nodeId>urn:node:mnTestARCTIC</nodeId>
<runStatus>processing</runStatus>
<errorDescription/>
<sequenceId>urn:uuid:261e1784-169d-4b13-bc5a-042361e4f02b</sequenceId>
<runCount>1</runCount>
</ns0:run>
```

So if we could grab the run status and display that, the timestamp, and maybe the error description if there is one, that would give a lot more info to the user.

**Comment by mbjones** [comment]
+1

**Comment by robyngit** [comment]
There are actually more appropriate status messages already coded in this view, so it appears to be a bug with when or how they are displaying.
