### ISSUE TITLE
Update PDG font and color scheme

### ISSUE THREAD

**Issue by yvonnesjy** [NCEAS/metacatui#2278]
Mock: https://www.sketch.com/s/eea6a4f3-5c59-40e6-bf7f-64edc511e4cb

Ideally apply to whole site. If color changes become tricky, panel only is acceptable

**Comment by robyngit** [comment]
Colors can be configured in the portal document, as can a "layout" and a "theme". Let's implement these changes as a new "theme" such that it doesn't impact any of the existing portals.

**Comment by yvonnesjy** [comment]
Documenting the following fixes that we will implement as a part of the April release (R1):

- Enable weights on Barlow font
- Remove text-transform treatments
