### ISSUE TITLE
Fix GCMD keyword link in submission form

### ISSUE THREAD

**Issue by jeanetteclark** [NCEAS/metacatui#2284]
**Describe the bug**
User of the KNB reported that the link in the keywords section of the editor goes to the wrong place for GCMD keywords. 

![image](https://github.com/NCEAS/metacatui/assets/24237074/f7531e46-97f4-4b99-9c67-0f94812b3b63)

"This link doesn’t go where its suppose to- the underlying link is http://gcmd.arcticlcc.org/, but the current site is here https://www.earthdata.nasa.gov/learn/find-data/idn/gcmd-keywords...The new GCMD keyword API is actually here, sorry — https://gcmd.earthdata.nasa.gov/KeywordViewer/scheme/Earth%20Science?gtm_scheme=Earth%20Science" (pasting the whole message as I don't have time to investigate at the moment)

**Comment by robyngit** [comment]
@justinkadi I think you reported this as well! It will be fixed in the next release.
