### ISSUE TITLE
EML Parties are removed from the EML model but are not removed from the XML during serialization

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/metacatui#231]
Steps:
Open an EML document with a metadataProvider
Remove the metadataProvider via the remove button and see that it is successfully removed from the EML model
Click Submit and view the EML serialization, and see that the metadataProvider is still in the XML

**Comment by amoeba** [comment]
Oh, I'm already working on this one in #120. Are you far along on fixing this? I found the issue last night before I headed out.

**Comment by laurenwalker** [comment]
Hey @amoeba - I just pushed a fix for this. Sorry, this particular bug was not described in #120 so I didn't know you were already fixing it.
