### ISSUE TITLE
Idea: Support webhooks when a new package is created

### ISSUE THREAD

**Issue by amoeba** [NCEAS/metacatui#238]
The data team currently makes use of a bot I wrote that runs on a `cron` job which queries the `listObjects` endpoint for new Objects. This is clunky and inefficient. MetacatUI could instead send a JSON payload to a webhook URL which would then trigger the Slack bot (#arcticbot) to reactively announce the new submission.

**Comment by laurenwalker** [comment]
I like that the bot checks the `/objects` endpoint since that will catch submissions and edits from any client. If we rely on only MetacatUI, submissions could fall through the crack.

**Comment by amoeba** [comment]
Ah yes. Great point. Maybe this feature doesn't have broad enough appeal.

**Comment by mbjones** [comment]
Or, its a Metacat notification feature, not MetacatUI.  We had other recent requests for other people to be notified when new datasets arrive or are changed, so this could be part of a general notification service feature, and would be independent of the client tools used to submit or access data.

**Comment by amoeba** [comment]
Yeah, it depends. Probably better as a Metacat feature. Though, it's easier to code as a MetacatUI feature because the data required to generate the webhook payload are already used by MetacatUI to generate the Package and its related Objects itself.

I'd say if we can't find any particular reason to do webhooks in MetacatUI over Metacat, I'll close this Issue in short order.

**Comment by mbjones** [comment]
All of the information used by MetacatUI originates in Metacat, as it implements the /object service and other services used by MetacatUI, including the services to get packages and query SOLR.  So, the info is already local in Metacat.  And it has an event subsystem that already is dispatching and logging every CRUD action as it comes in. So my guess is the implementation would be both easier and more complete in Metacat than in the client tool.

**Comment by amoeba** [comment]
> And it has an event subsystem that already is dispatching and logging every CRUD action as it comes in.

I've never heard of this. Are there docs somewhere about this subsystem?

**Comment by laurenwalker** [comment]
I'm going to go ahead and close this ticket since it looks like we need to listen to objects via Metacat and not MetacatUI, since it is only one client tool. Feel free to reopen if further discussion is needed.
