### ISSUE TITLE
Requests to view service are not properly encoding identifiers

### ISSUE THREAD

**Issue by datadavev** [NCEAS/metacatui#239]
All requests to DataONE services *must* properly URL path encode identifiers that are included with GET requests.

For example, when viewing a search result for the identifier:

`http://dx.doi.org/10.5061/dryad.j1828/2?ver=2017-08-19T07:36:06.033-04:00`

the view request fails with a 404 error since the identifier is not being encoded:

`https://search.dataone.org/cn/v2/views/metacatui/http://dx.doi.org/10.5061/dryad.j1828?ver=2017-08-19T07:35:55.841-04:00`

Properly encoding the request:

`https://search.dataone.org/cn/v2/views/metacatui/http%3A%2F%2Fdx.doi.org%2F10.5061%2Fdryad.j1828%3Fver%3D2017-08-19T07%3A35%3A55.841-04%3A00`

yields the expected HTTP 200 response.

**Comment by laurenwalker** [comment]
This is a Metacat issue, not MetacatUI. I created a ticket in the Metacat project for this. https://projects.ecoinformatics.org/ecoinfo/issues/7207

**Comment by datadavev** [comment]
I do not believe your assessment is correct. When following requests being made by the Search UI, the aforementioned request is being made by the UI client. Because the PID is not properly encoded by the Search UI, the CN is not able to find the entry, and so returns an error.

**Comment by laurenwalker** [comment]
Ah I see what you are saying. Reopening and will get this in a patch release
