### ISSUE TITLE
DataPackage table doesn't show data objects in alpha order

### ISSUE THREAD

**Issue by amoeba** [NCEAS/metacatui#24]
I just noticed that, in the image below the DataPackage table shows the data objects in a seemingly random order. I expected them to be in descending order by `fileName`.

![image](https://cloud.githubusercontent.com/assets/563/23227331/078119ec-f8e5-11e6-9edc-3ef696d5ee6b.png)

Is there a reason this particular query doesn't add `&sort=fileName+desc` or we don't sort them in JS before rendering? I think this would be a good change.

**Comment by laurenwalker** [comment]
They are sorted in the table first by the order of appearance in the metadata. That gives the user the ultimate control over the order of the table, and is helpful when matching the table rows with the "otherentity" sections in the EML.

If there are no otherEntity sections in the EML, they are sorted by type, then alpha order.

If you see a package that is not behaving in either of those ways, let me know.

**Comment by amoeba** [comment]
Oh you're awesome. I didn't know we could use the EML to order the DataPackage table. Right on, thanks!
