### ISSUE TITLE
Update themes that reference Morpho

### ISSUE THREAD

**Issue by jeanetteclark** [NCEAS/metacatui#2402]
**Describe the feature you'd like**

The release of Metacat 3.0.0 means that Morpho will no longer work on any node. We need to update the themes to at a minimum remove references to Morpho. We could also consider whether we want/need to include warnings in FAQ pages or the like about how Morpho no longer works.

From [this search](https://github.com/search?q=repo%3ANCEAS%2Fmetacatui%20morpho&type=code) it doesn't seem like there are too many references to remove so shouldn't be too bad.

**Comment by artntek** [comment]
related to https://github.com/NCEAS/metacat/issues/1914#issuecomment-2101623919

**Comment by robyngit** [comment]
Thanks @artntek !!
