### ISSUE TITLE
Allow user to link to their current location, heading, pitch, roll, and enabled layers via a URL

### ISSUE THREAD

**Issue by ianguerin** [NCEAS/metacatui#2426]
**Describe the feature you'd like**
- Support loading a position in a Cesium widget view from the URL
- Update the browser window's URL as the user pans around the map
- Support changing a layer's initial visibility based on URL parameters
- Update the browser window's URL as the user shows or hides layers

**Comment by mbjones** [comment]
Closely related to the following existing issues:

- #1806: Save the current Cesium config as a link for sharing
- #2410: Allow configuration of a camera angle for preset views in the Cesium Viewfinder 
-
