### ISSUE TITLE
Tooltip fix for Metadig Assessment report

### ISSUE THREAD

**Issue by rushirajnenuji** [NCEAS/metacatui#2514]
**Describe the bug**
Tooltip for question sign icons needs a fix for the Metadig Quality Assessment report.

**To Reproduce**
Related to #2506  and #2507 (occurs for this branch, not merged with `develop` yet):

1. Visit any dataset assessment report
2. Hover over the `?` icon on the checks performed

**Expected behavior**
Tooltip appears for items in the check.

**Screenshots**
<img width="1007" alt="Screenshot 2024-09-09 at 13 04 30" src="https://github.com/user-attachments/assets/bedd2099-10cc-4b09-8b8e-03527d71bb56">

**Comment by robyngit** [comment]
This was a good catch! Fixed in the nick of time in https://github.com/NCEAS/metacatui/commit/da6c788c6d8f6707c317603bded7dc16b332c8b2
