### ISSUE TITLE
The lat and long input borders turn red when the value is valid

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/metacatui#254]
Sometimes when typing in the lat and long inputs, the borders turn red to indicate an error even though the value is a valid lat or long value. When focusing outside the input, the red border goes away.

**Comment by ThomasThelen** [comment]
I'm not sure if I'm properly reproducing this, but here's how I turned the borders red with valid numbers.

It looks like the Lat and Long fields have maximum values of 90, and anything over will turn the field red, but will not issue an error (Each coordinate must include a latitude AND longitude.). If this is an issue it looks like we have two paths:

   1. Allow the user to enter Lat/Long greater than 90 and less than -90. This would get rid of the red       
      border, and we would probably want to change the arrows to allow further increments/decrements
   2. The 90/-90 restrictions are correct, and we should make the error more explicit

+ Click "Submit Data"
+ Click "Locations" on the left
+ Enter a description
+ Enter a Northwest coordinate greater than 90 (like 120)
$ See red box around Lat input
+ Click away
$ See red box disappear

Bonus Points
+ Click back in the Lat box
+ Click the up arrow that appears
$ Notice Lat isn't incremented
+ Click the down arrow
$ See the Lat get reset to 90 (the upper limit)


Side note:
Chrome and Safari also restrict input differently. Chrome only allows the character 'e', while Safari allows all characters, and if the character is different than 'e', turns the field red.

**Comment by laurenwalker** [comment]
Your assessment of the problem looks good. Path 2 - giving more explicit errors - is the way to go. We should keep the red borders and we'll want to display an error message immediately to the user when the value is over the maximum.

I believe that the red border that appears now is added automatically by the browser because we have a `max` attribute. But we'll want to add our own validation logic to make sure the error message and red border displays even after focusout.

For red borders, you can add the `error` class to the number input.

Error notifications should go in the div with the `notification` class inside that `geoCoverage` row and also get the `error` class.

**Comment by laurenwalker** [comment]
There are still some issues with the lat and long error messaging:

**Multiple errors should display at once**
<img width="900" alt="screen shot 2017-10-27 at 2 45 39 pm" src="https://user-images.githubusercontent.com/6643222/32120192-ab49b856-bb25-11e7-87e2-f04127006665.png">
When both the latitude and longitude values are invalid, the error message for both should be displayed. It looks like the validation function is returning only the first error found. The error messages can just be concatenated.



**Refer to values as latitude and longitude coordinates, not North,West,South,East coordinates**
We are asking users to enter a bounding box by supplying the coordinates of the Northwest corner of that box and the Southeast corner. So if the Northwest latitude value is wrong, the error message should word it as the "Northwest latitude", not "North bounding coordinate." I think this will keep wording consistent and avoid confusion.

**The red border error styling should not display when a user enters a negative sign**
<img width="894" alt="screen shot 2017-10-27 at 2 57 04 pm" src="https://user-images.githubusercontent.com/6643222/32120679-9a432a68-bb27-11e7-96ef-1bfd1a67b669.png">
When the negative sign is typed in the input, we see a red border, indicating an error, on the input. This should not be displayed unless the user focuses away from the input without continuing with a valid numerical value.

**Comment by ThomasThelen** [comment]
As for concatenated error messages, the default style has the errors spanning the locations table width. A screenshot of how it looks is attached below. 

Is this acceptable or should they be stacked?

It might also be worthwhile to note that the geographic description error takes precedence over the missing lat/long error along with the out of bounds lat/long errors (See the fourth and fifth location in the image).

The missing coordinate error takes precedence over the lat/long errors as well.

Out of Bounds Err < Missing Lat/Long Err < Missing Description Err

Is this order okay or would we like to display all of them at the same time?

<img width="1314" alt="screen shot 2017-10-30 at 2 02 31 pm" src="https://user-images.githubusercontent.com/9289652/32196098-bd69c9d2-bd7c-11e7-9189-0b145843e60d.png">

**Comment by ThomasThelen** [comment]
As for fixing the red box that appears when the user enters the negative sign.

The first solution is to stop validating the input each time a character is entered, and only when focus is lost from the edit box.

The other solution would be to check, for each character,
   1. Is the character a '-'?
   2. Is it the first character in the box?
   3. Is there a '-' after it? (We would want to invalidate the case where the user enters '-1', then clicks in  
       front of the existing '-' and enters '-'.

We also have an issue where if the user is entering in engineering notation (ie 10e10) and they haven't had a chance to fill out the exponent, we display a red box. We also get a red box with a value like (10e1), although I'm not sure if we should. If we validate on focus loss, this should also get fixed at the same time.

Writing a custom rule would be something similar to the '-' one, but will be more messy (we have to make sure we have numbers before and nothing after).

<img width="850" alt="screen shot 2017-10-30 at 2 54 29 pm" src="https://user-images.githubusercontent.com/9289652/32197644-44775ab6-bd82-11e7-990c-fda7d070d88b.png">

**Comment by csjx** [comment]
@ThomasThelen 
For concatenated error messages, I agree that they would be much more readable as a stacked list.  As the user fixes issues in the list (on focus out events), the list should be updated to remove fixed items.
For the precedence issue, I think you're right, all issues should show as a list at the same time after validation.  It's best for us to inform the researcher with what we know from the validation. The difficulty is to not highlight fields red when they just haven't gotten there yet.  One suggestion is to use row-level validation; if the parent row id of the previously focused field is equal to the parent row id of the current field, hold off on validation.  Then, when the researcher moves to another section of the form (not in the row any more), do the validation for the row.  This is tricky - we want to minimize red highlights until we're sure they're done.  We might need to just test it with people to see what the tolerance level is.

I think I'm in favor of validation after focus is lost more than validation per character (regarding your second comment).

**Comment by ThomasThelen** [comment]
@csjx 

After looking at the error notification container (just a <p></p>-it looks like we use it in other places. It also looks like we could be stacking errors in the dates section too.

Do you think it would be worth while to create a second error container (like <ul></ul>) for stacking, and leave the original paragraph container in for the traditional messages?

<img width="1399" alt="screen shot 2017-10-30 at 3 34 49 pm" src="https://user-images.githubusercontent.com/9289652/32199048-35ae340e-bd88-11e7-9445-4556e094245c.png">

As for validating based on rows. I labeled the screenshot below with what I think you mean by row.
![screen shot 2017-10-30 at 3 46 51 pm](https://user-images.githubusercontent.com/9289652/32199739-28b75ef8-bd8b-11e7-9dce-331ee908de0f.png)

The green circles are examples of places that validation occurs when the user clicks.
Are you saying that we should give the user the chance to fill out the entire row before running validation (which we do about half way)? Currently, if the user enters a latitude, clicks into the longitude box and gives a value, and then clicks into the description field and gives a description, the validation process is not run until they click outside one of the fields. However, if the user enters a latitude and clicks outside the field(but still in that row)-we throw an error that they need a longitude and description.

The image below is kind of what I have in my head. The user fills out the top row, with correct or incorrect values and then clicks anywhere where there is a green circle. Then validation is performed. This will of course change validations on character/on focus loss.

![screen shot 2017-10-30 at 3 52 38 pm](https://user-images.githubusercontent.com/9289652/32199904-fdd671dc-bd8b-11e7-8988-37916c2b0b6f.png)

**Comment by csjx** [comment]
@ThomasThelen I do like the idea of having a message `<p>` and an error `<ul>`, and both could be part of a single `<div>`. @laurenwalker might have an opinion on that. It sounds like each row validates after focus goes out of all fields, so that was the behavior I was describing. But I see what you mean that we can't remove single error messages if we don't validate each field independently. So yeah, maybe that's the way to go - follow what is done in the Dates section.  I agree with the _Done_ state definition. So yes, I'm down with option two. 👍

**Comment by laurenwalker** [comment]
I am ok with validating each temporal coverage after the users focuses out of the `EMLTempCoverageView` (which is a single row). The only validation that would be nice to have before the user leaves the `EMLTempCoverageView` is validation of single latitude or longitude values (for example, we can show an error message for a latitude of `91` before the user starts typing the longitude). So validation should happen like this:

- When the user focuses out of a latitude number input, validate that latitude value
- When the user focuses out of a longitude number input, validate that longitude value
- When the user focuses out of the `EMLTempCoverageView`, validate the entire `EMLTemporalCoverage` model and show all error messages

For the error message display -- I agree that stacked is more legible, but I worry about creating a vertical list that when displayed, will shift all elements below it down, which is kind of jarring. That can happen a bit when the concatenated error messages are long enough to create a second line, but I doubt that will happen often. I tried to set up all the editor sections so that the error message container is an empty white space when there is no message, so that when one appears, the elements below it do not shift down, or at least shift only a few pixels.

**Comment by laurenwalker** [comment]
Oops, in my previous comment I meant to say `EMLGeoCoverage` model and `EMLGeoCoverageView`

**Comment by ThomasThelen** [comment]
Fantastic-I'll implement that validation scheme now. 

Good point about the error messages shifting the rest of the content down; I've definitely run across that behavior on other websites and forgot there was anything below-it wasn't user friendly. 

It sounds like I should leave the error message formatting alone for now. The most extensible path is probably to have an expandable/collapsible error box, triggered by an icon click. That way, the user sees one error, and if they want to see more they have the option. It also allows us to add/remove content and not have to worry about how the errors are formatted in the future. If anyone manages to get all the fields wrong and complains about the error display we can bring it back up!

**Comment by ThomasThelen** [comment]
Actually, if we validate lat/long independently when they click to and from, the 'Submit' button will be displayed. Disregard the stuff about the picture.

**Comment by laurenwalker** [comment]
> Validating everything by clicking outside the EMLGeoCoverage area means that if someone is editing, they'll have to click in one of the red areas for 'Submit' to appear.

I'm not sure what you mean by this. The Submit button will display anytime the content of the `EML211` model changes. The `EML211` model changes when the `change` event is fired, which is fired when someone changes a value of a form element in the `EMLGeoCoverageView` and focuses outside of that element.

**Comment by laurenwalker** [comment]
@ThomasThelen - Your recent changes look really good. Thanks for your help on this.

I noticed the only thing left to do is make sure that the number inputs have a red border when there is an error for that value. 

For example, I have an error message about the Southeast latitude and longitude, but neither of the inputs have a red error border. The border just helps with directing the user to the necessary input element.

<img width="1163" alt="screen shot 2017-11-03 at 12 27 06 pm" src="https://user-images.githubusercontent.com/6643222/32384834-9058a3d2-c092-11e7-8cf8-2da0492ff301.png">

I think after that change is made, we are done with this issue. Thanks

**Comment by ThomasThelen** [comment]
The only part left is allowing '-' before any numbers in the lat/long input fields.
Unfortunately, the "number" input type for the html definition does not support regex. When the input type is set to "text", we can change the validation method to follow a regex pattern. The following regex would look like `(^[+-]?(?:\d+\.?\d*|\d*\.\d+)$)|(-)`, which allows for all real numbers with a negative sign at the beginning.

The downside to doing this is that we lose our upper and lower value restrictions when changing values by the up and down buttons. We also lose the feature of restricting user input to numbers and allow for characters (because our input type is no longer number). The characters of course don't match the regex pattern, but can be typed in nonetheless. 

Should I go ahead and switch over to text inputs with regex validation or do we want to keep our number restriction and treat leading negative signs that are missing numbers as errors?
