### ISSUE TITLE
DataONE portal default text includes reference to old site

### ISSUE THREAD

**Issue by maggieklope** [NCEAS/metacatui#2544]
Default Markdown markdown text in DataONE portals includes logo image that has link directs to the old.dataone.org site causing login request

Default portal text:
![image](https://github.com/user-attachments/assets/fbc1ac82-c11f-4d4d-b838-1551948e493b)

Link to image::
https://www.dataone.org/sites/default/files/d1-logo-v8_aligned_left.png

which references old.dataone.org:
![image (1)](https://github.com/user-attachments/assets/7d9593cb-9962-4c68-bdcc-aff5589958b5)

Causing popup to login to old.dataone.org:
![image (2)](https://github.com/user-attachments/assets/b528facc-61b6-457f-8e98-948769a73518)

**Comment by mbjones** [comment]
@robyngit this is hopefully a quick change to remove the default markdown that points at the old.dataone.org site and instead points at a more reliably available image. This affects all example Freeform pages in portals so would be a nice change for the next release.

**Comment by robyngit** [comment]
Thanks for the wonderfully detailed issue description @maggieklope! This is now fixed and will be included in the next release.
