### ISSUE TITLE
Add a message to the arctic editor that indicates the submission is under review

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/metacatui#258]

**Comment by rushirajnenuji** [comment]
Does this mean that when the user clicks on Submit (after filling all the metadata fields), this message should be displayed on the screen?
Also does this have to be specific to the ARCTIC theme?!

**Comment by rushirajnenuji** [comment]
Added a property `contentIsModerated` in the `AppModel.js`. Based on this boolean value, the success message displays appropriate text. For now, only the Arctic theme has `contentIsModerated = true`.

**Comment by rushirajnenuji** [comment]
Hey @laurenwalker, regarding the **contentIsModerated** attribute, Chris suggested that if it is present in the `main AppModel` then we don't need to add that to each theme's individual `AppModel`. But, I'll make that change. And regarding the success alert, the `insertProgress.html` looks more formal and informative. I'll start working on these changes asap. Thanks!

**Comment by laurenwalker** [comment]
Unfortunately the theme AppModels do not use the default AppModel as a prototype to build upon. We have plans in the future to make the MetacatUI configuration easier in that way, but as of now each theme has it's own AppModel completely independent of the default AppModel, so there is some redundancy.

**Comment by rushirajnenuji** [comment]
Ah, I get that. Sure, no problem. I'll add the attribute and set it to `false` for the remaining themes.

**Comment by laurenwalker** [comment]
This is looking really good!

After testing it out, I think we should show the message until the user clicks the "X" button to remove it. Otherwise, it only displays a few seconds and it is difficult to read it that fast.

The showAlert() function should have an option to remove the timeout and add an "X" remove button.

Also, let's reduce the size of the font a bit. That may be done by increasing the header level from `h1` to `h2`, `h2` to `h3`, etc.

**Comment by csjx** [comment]
Ah, yes, I forgot we are not extending `AppModel`.  Thanks for catching that @laurenwalker

**Comment by laurenwalker** [comment]
Fixed in 79734d649740550298a38896c598148742dd66c6
