### ISSUE TITLE
Excessive request to solr when rendering profile view

### ISSUE THREAD

**Issue by datadavev** [NCEAS/metacatui#262]
When rendering the profile page on DataONE search such as `https://search.dataone.org/#profile`, a request is made to solr:

```
https://search.dataone.org/cn/v2/query/logsolr/
?q=+event:read+formatType:(METADATA%20OR%20DATA)+inPartialRobotList:false+isRepeatVisit:false
&facet=true
&facet.limit=-1
&facet.mincount=1
&facet.field=formatType
&facet.field=pid
&facet.range=dateLogged
&facet.range.start=NOW-20YEARS
&facet.range.end=NOW
&facet.range.gap=%2B1MONTH
&wt=json
&rows=0
```

The request includes facet on PID which is completely unnecessary and is a very expensive operation which results in a **52MB download for each request** that takes about 22seconds to complete. 

Removing the PID facet results in a 5.6KB download that completes in about 8 seconds.

**Comment by datadavev** [comment]
Replacing the `facet.range.start` with a specific date rather than a calculated date appears to result in a further reduction in query time to about 6 seconds, with subsequent requests in the order of 0.8 seconds.

**Comment by datadavev** [comment]
Furthermore:

1. The `facet.field` parameter appears to be unused. It should be removed from the request.
2. Replacing NOW with a specific date further reduces the time for Solr to respond.

**Comment by datadavev** [comment]
Replacing the first few lines of `getDownloadDates` in `Stats.js` with the following:
```javascript
		getDownloadDates: function(){
			if(!appModel.get("d1LogServiceUrl")) return;
			
			var model = this;
				
			var today = new Date();
			today.setDate(today.getUTCDay() + 1);
			today.setHours(0);
			today.setMinutes(0);
			today.setSeconds(0);
			today.setMilliseconds(0);
			
			var logSearch = new LogsSearch();
			logSearch.set("event", "read");
			logSearch.set("formatType", ["METADATA", "DATA"]);
			logSearch.set("facetRanges", ["dateLogged"]);
			logSearch.set("facets", ["formatType"]);
			logSearch.set("facetRangeStart", "2012-07-01T00:00:00Z")
			logSearch.set("facetRangeEnd", today.toISOString());
```

resulted in a Profile display in the order of a second or so compared to 20+ seconds.

**Comment by laurenwalker** [comment]
Thanks for looking into this, Dave. I've assigned this to our next patch release, 1.14.6, to be released as soon as possible.
