### ISSUE TITLE
Taxa validation error appears after reopening an existing dataset

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/metacatui#269]
During UX testing with Jeanette, we discovered the following bug:

- We submitted a dataset successfully
- We viewed the dataset via the #view URL
- We clicked edit, and edited a non-taxa part of the EML (I believe we edited an attribute)
- When we clicked submit, a validation error for the taxa appeared that said "Every taxa classification should have a rank and value." - even though all taxa tables were complete. We were only able to fix it by deleting 2 of the 3 taxa tables (even though they were valid)

Something must be off about the EMLTaxonCoverage validate() function

**Comment by ThomasThelen** [comment]
We're reliably dying during the validation of the second taxa.
`taxonomicClassification.taxonRankName` is returning undefined however, there is clearly an appropriate value in the `taxonomicClassification` object (See picture 2). 
`taxonomicClassification.taxonRankValue` also exhibits the same behavior.


<img width="971" alt="screen shot 2017-10-25 at 3 44 28 pm" src="https://user-images.githubusercontent.com/9289652/32027068-df90b21c-b99b-11e7-8b62-50805d59136a.png">
<img width="952" alt="screen shot 2017-10-25 at 3 44 52 pm" src="https://user-images.githubusercontent.com/9289652/32027069-dfacff26-b99b-11e7-8b4b-9e1c16aa666b.png">

**Comment by ThomasThelen** [comment]
Fixed this in commit 2091fb9. The issue had to do with accessing elements of taxonomicClassification
