### ISSUE TITLE
Test the editor in other themes

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/metacatui#278]
The editor should display and function properly in the following themes (besides arctic), listed in order of importance:

For the 2.0.0 release:
- [ ] KNB
- [ ] Default

For the 2.1.0 release:
- [ ] DataONE
- [ ] GOA
- [ ] NCEAS (less critical)

**Comment by mbjones** [comment]
Added DataONE to the list of themes.

**Comment by laurenwalker** [comment]
@mbjones - The DataONE theme is a little more complicated because it would only work for content from Tier 3 nodes that also use ORCID authentication. (I think that is just KNB, GOA, and Arctic, right?) 

I think for time's sake, maybe we can make sure the Editor works in the DataONE theme for a 2.1.0 release. Thoughts?

**Comment by mbjones** [comment]
Yes, that would be fine, but lets keep in mind that we will want it working in DataONE as well. But I agree it is lower priority than the others.  For that matter, the highest priority ones are KNB, Arctic, and Default, and then everything else is secondary.  GOA is unlikely to use it much if at all.  It will become more of a priority for DataONE than GOA.

**Comment by laurenwalker** [comment]
Ok, I'll update the ticket and save GOA and NCEAS for a 2.1.0 release. They
can still use the old editor in the meantime.

**Comment by rushirajnenuji** [comment]
Being new to waffle.io's interface, I closed this issue by mistake. I have re-opened it and self-assigned it.

**Comment by laurenwalker** [comment]
I've tested the editor in other themes and fixed a few styling issues. But everything seems to work smoothly.
