### ISSUE TITLE
Design display of metadata quality scores time series

### ISSUE THREAD

**Issue by gothub** [NCEAS/metacatui#280]
The metadata quality score section of the user profile page should show how metadata quality has changed over time. Currently the quality score is shown for the currently calculated value
<img width="306" alt="screen shot 2017-09-26 at 1 23 01 pm" src="https://user-images.githubusercontent.com/6412946/30885490-5b95a952-a2c8-11e7-86ba-9905d6ba9f2e.png">

We need to consider how this affects the quality graph that shows 
the quality scores for metadata formatId, repository, check suite, etc.:

<img width="999" alt="screen shot 2017-09-26 at 2 41 55 pm" src="https://user-images.githubusercontent.com/6412946/30885679-0ca86464-a2c9-11e7-8a59-1aa3e9ccea2f.png">

**Comment by laurenwalker** [comment]
See design in #309
