### ISSUE TITLE
Write proper documentation for MetacatUI

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/metacatui#282]
There should be two different kinds of documentation:

1. For data managers / non-technical users:
-  An appealing HTML presentation of MetacatUI features with screenshots.
- This documentation should live in a Github pages branch and be accessible via Github pages
2. For developers implementing MetacatUI:
- Technical documentation on how to install and configure MetacatUI
- Technical documentation on how to create a custom theme
- Brief explanations of the following technologies:
     - Require.js and Backbone.js
     - Authentication via DataONE API and how tokens are used in MetacatUI
     -  An overview of the major views of the app and what they do at a basic level - DataCatalogView, ProfileView, MetadataView, and EditorView.
- This documentation should be in the master branch so it is included in the .zip for each release

Others, please add any other ideas to this list

**Comment by laurenwalker** [comment]
The documentation should be written after the following issue is complete:

#281 (Overhaul of the app configuration)

**Comment by csjx** [comment]
When documenting MetacatUI, we need to include the CORS configuration for Apache, like
```
Header set Access-Control-Allow-Headers "Authorization, Content-Type, Origin, Cache-Control"
Header set Access-Control-Allow-Methods "GET, POST, PUT, OPTIONS"
Header set Access-Control-Allow-Credentials "true"
```

**Comment by laurenwalker** [comment]
- [X] I built the JSDoc documentation for MetacatUI developers and pushed it to https://github.nceas.ucsb.edu/walker/metacatui-docs.

- [X] A user-facing presentation of MetcatUI features now lives at products.dataone.org

- [X] Instructions on installation have since been included in the README for this repository.

- The following docs need to be added to `metacatui-docs` before this issue can be closed:
    - [ ]  Technical documentation on how to create a custom theme
    - [ ] Brief explanations of the following technologies: Require.js and Backbone.js
    - [ ] Authentication via DataONE API and how tokens are used in MetacatUI

**Comment by laurenwalker** [comment]
Going to close this since the remaining tasks are sufficiently covered by other documentation:
- RequireJS and BackboneJS -- have their own documentation
- DataONE authentication -- already detailed in the DataONE API docs
