### ISSUE TITLE
Quality report lists unneeded/invalid suites

### ISSUE THREAD

**Issue by gothub** [NCEAS/metacatui#283]
Quality reports displayed on KNB contain a 'Suite' dropdown menu that contains unneeded quality suites to be selected, for example, for https://knb.ecoinformatics.org/#quality/s=knb.suite.1/doi%3A10.5063%2FF12R3PSC:

<img width="679" alt="screen shot 2017-09-27 at 10 51 11 am" src="https://user-images.githubusercontent.com/6412946/30929106-512d687e-a372-11e7-8a7e-52ceaa357ff7.png">

The unneeded quality suites should be removed from the list.

**Comment by mbjones** [comment]
I think we should hide the dropdown altogether, the same way we hide it on Arctic Data.

**Comment by gothub** [comment]
Addressed in #741 and commit cb49add70deae92b1205e41dffe6f8f7f9c4d4f0
