### ISSUE TITLE
Title cannot be edited after "no title" error

### ISSUE THREAD

**Issue by jeanetteclark** [NCEAS/metacatui#291]
If a user submits a dataset with no title, an error pops up explaining that a title is needed. After clicking the "x" to get rid of the error banner, the title box is red and un-editable. 

I also suspect that titles are not showing up at all in registry submissions, after submission, on the landing page

<img width="1728" alt="screen shot 2017-10-05 at 2 42 44 pm" src="https://user-images.githubusercontent.com/24237074/31254167-6e31bc84-a9dc-11e7-9826-974759c2a96a.png">

**Comment by amoeba** [comment]
Thanks for submitting an Issue for this. I'm also seeing this behavior.

Could you please elaborate on this? I'm not sure quite what you mean:

> I also suspect that titles are not showing up at all in registry submissions, after submission, on the landing page

**Comment by jeanetteclark** [comment]
I also just noticed that I cannot find this submission in the "My Datasets" page, nor can Jesse view it even when logged in

https://test.arcticdata.io/#view/urn:uuid:407aed7f-3f52-4946-978b-4c618c0ebc65

<img width="1289" alt="screen shot 2017-10-05 at 4 38 09 pm" src="https://user-images.githubusercontent.com/24237074/31257115-a3b79324-a9eb-11e7-9955-63ce72285127.png">

**Comment by jeanetteclark** [comment]
Note: the second part of this issue was an index backlog. the inability to edit title after the "no title" error is still a problem AFAIK
