### ISSUE TITLE
 Confusion about the Submit button

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/metacatui#304]
In UX testing, users didn't know that the Submit button would submit the entire dataset. Some users attempted to click Submit after only completing the Overview section. To make this more clear, we could change the button text to "Submit dataset". We could also add a "Next section" button that moves the user to the next section in the left-side table of contents. This would only be an alternate way of moving through the sections. It might help users notice the multiple sections AND better understand the function of the Submit button.

**Comment by laurenwalker** [comment]
Also, another idea is to only show the Submit button after the EML document is valid. This would require some refactoring of the validation process since clicking the Submit now is what triggers it. But that may prevent users from clicking it right after completing the Overview section.

**Comment by laurenwalker** [comment]
For now, I'm going to change the button text to "Submit dataset" and we will see if that helps in the next UX testing.

**Comment by csjx** [comment]
This was originally `Save`, and I'd like to get back to that, but I don't think we can until we support Drafts (with `Save Draft` too). I'm not excited about `Submit dataset` for a button.  I see the `Submit` paradigm as Web 1.0 webpage construct, and `Save` as a Web 2.0 application construct. So, I still think this needs work.

**Comment by laurenwalker** [comment]
Absolutely, as soon as draft saving is a feature, having a `Save` button that can be used frequently totally makes sense.
