### ISSUE TITLE
Metadata View doesn't seem to work with SIDs

### ISSUE THREAD

**Issue by amoeba** [NCEAS/metacatui#314]
The data team just ran into this on https://arcticdata.io/catalog/#view/doi:10.18739/A2WD4W

That DOI is a SID that points to an EML211 Object,

https://arcticdata.io/metacat/d1/mn/v2/query/solr/?q=seriesId:%2522doi:10.18739/A2WD4W%2522&fl=identifier,title,formatId,seriesId,dateUploaded,resourceMap

We expected the Metadata View to render the normal View Service page for the EML but what was shown instead is just the Solr-only View. From the Network tab in Chrome I see that the query being sent to find the appropriate Metadata Object to render into the View returns zero results. This looks to be because the query is only querying for PIDs and not SIDs, see:

```https://arcticdata.io/metacat/d1/mn/v2/query/solr/?q=id:%22doi%3A10.18739%2FA2WD4W%22```

instead of

```https://arcticdata.io/metacat/d1/mn/v2/query/solr/?q=id:"doi%3A10.18739%2FA2WD4W" or seriesID:"doi%3A10.18739%2FA2WD4W"```

**Comment by laurenwalker** [comment]
Fixed in 78ef0f4423de872e6a7f84783f5d2d6479d26fe1
