### ISSUE TITLE
Show feedback after user clicks "Download" or "Download All" and an AJAX request is sent

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/metacatui#32]
There currently is no feedback for the Download buttons in the DataPackageTableView. We've had the KNB disk space filled up before after someone clicked the Download All button repeatedly, which implies people are not understanding that a download has started (which is understandable since it can take several seconds to minutes).

There should be some kind of progress bar and the button should be disabled so users don't click it twice.

**Comment by laurenwalker** [comment]
The download button will now show the user the download has started with a loading icon.

<img width="1053" alt="screen shot 2017-04-13 at 2 14 36 pm" src="https://cloud.githubusercontent.com/assets/6643222/25017985/af87d53c-2053-11e7-86c2-ebe57a2aa78e.png">

And when the download is complete:
<img width="1060" alt="screen shot 2017-04-13 at 2 15 08 pm" src="https://cloud.githubusercontent.com/assets/6643222/25017984/af7b12b6-2053-11e7-9c9c-5161ddc5a926.png">

While the download is in progress, we prevent the user from starting another download.

**Comment by amoeba** [comment]
This addition is ♠ ♠ ♠.
