### ISSUE TITLE
Consider changing citations to use full URL links

### ISSUE THREAD

**Issue by csjx** [NCEAS/metacatui#323]
I ran across [this recommendation](https://www.crossref.org/display-guidelines/) in the CrossRef documentation about DOIs.  The point is to display full links in online usage rather than the identifier alone (like `https://doi.org/10.XXXX/XXXXXXX` rather than `doi:10.XXXX/XXXXXXX`).  While this is a fairly short URL for DOIs, for objects that have UUID identifiers and links to, say, the DataONE resolve service or even the local repository, the link can get pretty long, so may not be as readable/usable.  This is low priority, but I thought I'd raise it from a best-practices point of view.

**Comment by amoeba** [comment]
Great catch. I agree wholeheartedly that IRIs should be hyperlinked when shown in hypermedia viewers. This also dovetails nicely with the discussions we've had about GeoLink and producing IRIs for DataONE content (instead of just #view URLs)

**Comment by mbjones** [comment]
Well, that's what CrossRef says, but not the DOI Foundation, which is the authority that we have followed.  The DOI foundation still recommends `doi:10.xxxx/yyyyyyy` for screen and print display, and that they should be linked to the HTTP resolvable version:  https://www.doi.org/doi_handbook/2_Numbering.html#2.6

If we were to use the URL version, then those should be properly encoded following [RFC 3986](https://tools.ietf.org/html/rfc3986), so a doi like `doi:10.xxxx/knb/foo:22` should be linked to the URL `https://doi.org/knb%2Ffoo%3A22`, which is fairly cumbersome for display.  Unicode characters also must be escaped.  As the DOI Handbook states, DOIs allow a much broader range of characters than URIs, and these need to be escaped in URI format.  This is the reasoning behind my continuing argument that we should keep using the doi: form for display.  

Section 2.6.5 goes so far as to say:

    So while it may be awkward, we recommend some convention of showing both the plain DOI name and a way to resolve it online

That said, I agree we should add links to our display that point to the properly escaped DOI URI.

**Comment by mbjones** [comment]
I think this issue has been resolved and now links to the DOI. Can it be closed?

**Comment by laurenwalker** [comment]
Yes, we display the DOI without the `https://doi.org` prefix, but we link the doi string to the full DOI URI. I'll close.
