### ISSUE TITLE
Taxa Species & Taxa Error Are Competing For Space

### ISSUE THREAD

**Issue by ThomasThelen** [NCEAS/metacatui#325]
The species number was added the the UI in issue #255 however, it is competing for space with any error messages. See screenshot below.

<img width="1411" alt="screen shot 2017-10-31 at 1 41 43 pm" src="https://user-images.githubusercontent.com/9289652/32247973-5e8820ec-be41-11e7-84f7-4456dd2b2689.png">

**Comment by rushirajnenuji** [comment]
Solved with commit code [fffc663](https://github.com/NCEAS/metacatui/commit/fffc6635560b2b610419b8ff81b26a418dd519fd) and [b1a43d5](https://github.com/NCEAS/metacatui/commit/b1a43d56052f05374c4a72fee94ee8eb28509981) for all the themes.
