### ISSUE TITLE
Persistant Data File Tooltip

### ISSUE THREAD

**Issue by ThomasThelen** [NCEAS/metacatui#327]
This is definitely an edge case, but might be worth documenting.

Steps:
1. Navigate to the Search page
2. Click on a data set
3. Before the new page loads, mouse over on the data file icon
4. You'll see that the tooltip persists throughout the UI

I can reproduce this in Chrome and Safari.

![screen shot 2017-10-31 at 4 47 52 pm](https://user-images.githubusercontent.com/9289652/32254015-78316e76-be5b-11e7-88a8-facbed1a208f.png)

<img width="1116" alt="screen shot 2017-10-31 at 4 09 06 pm" src="https://user-images.githubusercontent.com/9289652/32253023-f0a87990-be55-11e7-8a47-f7e20e36d500.png">
<img width="1669" alt="screen shot 2017-10-31 at 4 09 15 pm" src="https://user-images.githubusercontent.com/9289652/32253024-f0c18e80-be55-11e7-8790-aa1c6b90afa2.png">

**Comment by laurenwalker** [comment]
We've switched to just using the built-in browser alternative text "tooltip" so this is effectively fixed
