### ISSUE TITLE
Species Number Incorrect When Editing Package

### ISSUE THREAD

**Issue by ThomasThelen** [NCEAS/metacatui#329]
When editing the taxa section of a dataset which started with taxa information, the second taxa species will display "Species 1".

<img width="1442" alt="screen shot 2017-11-01 at 10 39 23 am" src="https://user-images.githubusercontent.com/9289652/32288388-f650c500-bef0-11e7-8043-a826695fd554.png">

To reproduce:
Create a new dataset and provide taxa information for one species.
Upload the dataset
Open the new dataset and edit it
Navigate to the 'Taxa' section
Notice that the second species is labeled 'Species 1'

**Comment by rushirajnenuji** [comment]
Hey @ThomasThelen, I was able to reproduce this issue as you suggested. I'm working on it. Thanks!

**Comment by rushirajnenuji** [comment]
Solved with commit code [b6c0ac1](https://github.com/NCEAS/metacatui/commit/b6c0ac106f2c4548a507128a67b00588329601fa).
