### ISSUE TITLE
Move the "Authentication Token" to an menu item under the user's name

### ISSUE THREAD

**Issue by taojing2002** [NCEAS/metacatui#333]
Now the "Authentication Token" is hard to find since it is hidden under My Profile/Settings.  And it seems that "Authentication Token" is not suitable for Settings. I am wondering if it is possible to add it as a menu item like "My Profile". Maybe we can name it as "My Tokens".

**Comment by csjx** [comment]
I think this needs discussion, in that this is a more technical feature, and we need to decide if it should be exposed in the user's menu.  Either way, if we do decide to support it, I suggest we make it configurable for the MetacatUI administrator to expose or not.  Also, I wouldn't "move" it per se to this location, but rather add a `My Token` menu item would just be a quick link to `Profile --> Settings -- Authentication Token`.

**Comment by laurenwalker** [comment]
I agree that it seems more like a technical feature than one most scientists will use.

**Comment by amoeba** [comment]
I'm okay with this being behind a few clicks. Even GitHub, a site for fairly technical users, hides their API tokens behind three clicks, under a "Settings" menu item. I like @csjx 's idea to be able to customize the menu though.
