### ISSUE TITLE
Don't serialize parties that are only space characters

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/metacatui#335]
The Editor will serialize EMLParty models that have nothing but space characters for a name. When I entered a space for a last name, and clicked Submit, I got this error:

`error updating EML:  <?xml version="1.0" encoding="UTF-8"?><error detailCode="1310" errorCode="500" name="ServiceFailure">
    <description>Error inserting or updating document: urn:uuid:ec06afda-b8b8-43af-97ff-0f83173a087b since &lt;?xml version="1.0"?&gt;&lt;error&gt;cvc-complex-type.2.4.b: The content of element 'individualName' is not complete. One of '{salutation, givenName, surName}' is expected.&lt;/error&gt;</description>
</error>`

The offending EML is:
`<associatedParty id="1378827558480322"><individualName></individualName><role>principalInvestigator</role></associatedParty>`

**Solution:** Trim (`trim()`) any string entered into any person input element before saving to the model. The model should not save empty strings.

**Comment by ThomasThelen** [comment]
If the user enters a space and triggers validation, should we flag it as an error?
It looks like we're also allowing special characters for almost all field inputs in the 'Dates' section. 
We're also not validating email formats, complete & valid phone/fax numbers, and website formats.

Would it be best to implement the trim method for this issue, and move all of the validation issues to a new issue? My thoughts are that it will be easier to add error flagging associated with blank strings when the rest of the validation work is done.

**Comment by laurenwalker** [comment]
If there are only space characters in the entire EMLParty model and view, then I don't think we should flag an error. I think we should assume the use is trying to remove the person from the metadata and just remove the EMLParty model for the EML211 model.
