### ISSUE TITLE
Error during EMLNumericDomain.updateDOM()

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/metacatui#340]
I opened an EML doc and edited the People section and clicked Submit. I got a red error message that the save was cancelled because of a JS error during save(). Here is the callstack:

<img width="559" alt="screen shot 2017-11-06 at 4 55 00 pm" src="https://user-images.githubusercontent.com/6643222/32465967-571a7248-c313-11e7-995f-1cc068c0b647.png">

It just looks like the code is trying to access a jQuery function when the variable is just a DOM object, not a jQuery object.

<img width="374" alt="screen shot 2017-11-06 at 5 02 39 pm" src="https://user-images.githubusercontent.com/6643222/32466283-67d92e5c-c314-11e7-9738-446e7b23712b.png">

**Comment by amoeba** [comment]
@gothub asked me to take a look at this. I'll see what I can come up with!

**Comment by amoeba** [comment]
Thanks for the detailed report @laurenwalker . I agree with your assessment and went ahead and made that change. I didn't see a set of steps to reproduce the error but I'm confident this change is (1) safe and (2) the right change.
