### ISSUE TITLE
EMLParty errors should not display on new EMLParties

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/metacatui#341]
Error messages and styling should not appear on new EMLParty rows. I keep getting error messages on the new, blank EMLParty rows as I fill out the People section. It even prevented me from Submitting once:

<img width="1224" alt="screen shot 2017-11-06 at 5 08 36 pm" src="https://user-images.githubusercontent.com/6643222/32466592-6aa1b1f8-c315-11e7-9e31-a0588ee5994f.png">

When this happens there is no way for me to fix the error. When I enter another (unnecesary) person in that new row, another new blank row appears and gives me the same error.

This was happening in Safari 10, but may be happening in other themes too.

**Comment by ThomasThelen** [comment]
I can reproduce this by adding a new person/role. Upon addition, it looks like the validation routine is firing and complaining about incomplete values.

<img width="1634" alt="screen shot 2017-11-13 at 2 06 04 pm" src="https://user-images.githubusercontent.com/9289652/32751850-fb828736-c87b-11e7-8ee0-f8b87c7d426a.png">
