### ISSUE TITLE
Title in DataPackage table is not editable after Submit

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/metacatui#349]
I opened an existing package in the Editor
I changed several parts of the metadata
I clicked Submit
The Editor submitted successfully
I changed some more values and had another successful save
The title row in the table is not editable.

This issue might occur after the first save too, but I wanted to write down the conditions this bug occurred in initially.

**Comment by ThomasThelen** [comment]
It looks like the problem is that the div isn't getting set to `contenteditable` after we finish saving. The if statement on line 672 fails.

![screen shot 2017-11-07 at 5 01 58 pm](https://user-images.githubusercontent.com/9289652/32526305-6e5cc94a-c3dd-11e7-8ed8-86ace1e4583a.png)

**Comment by laurenwalker** [comment]
The `DataItemView.rename` function can be removed. We already do that in `DataItemView.updateName`. The `DataItemView.emptyName` function needs to stay that way - we only want to empty the name when it is untitled. After it is given a title, we don't want to empty it when the user clicks or they will never be able to edit the title without totally retyping it each time.

**Comment by laurenwalker** [comment]
I think the real fix is what you had first commented about line 672. 

> It looks like the problem is that the div isn't getting set to contenteditable after we finish saving. The if statement on line 672 fails.

**Comment by csjx** [comment]
Looks good to me!
