### ISSUE TITLE
Correcting the error does not remove the corresponding error message in Overview publication date.

### ISSUE THREAD

**Issue by rushirajnenuji** [NCEAS/metacatui#356]
Correcting the error does not remove the corresponding error message in Overview publication date of the editor.
This error happens in both the themes: Default and KNB.
**Error**
![overview](https://user-images.githubusercontent.com/19696935/32570286-9300d3f4-c478-11e7-8ddd-a42cd28b18cf.png)
Even **after correction of date**, the message still appears (in normal font-color)
![overview 2](https://user-images.githubusercontent.com/19696935/32570332-afa45364-c478-11e7-8215-b69247bc6a88.png)

**Comment by ThomasThelen** [comment]
Fixed in a06413271fc856cfa21e011cc8d4288aa6f744f3

The error text was not getting set to "".
