### ISSUE TITLE
Prov editor needs to display save status

### ISSUE THREAD

**Issue by gothub** [NCEAS/metacatui#358]
The prov editor needs to save and display the status of DataPackage.save().

- implement functions in MetadataView triggered by
  - DataPackage.save() "successSaving" trigger
  - Datapackage.save() "error" trigger

Once these are received a message should be printed, as does the EditorView mechanism for
save, or similiar.

**Comment by laurenwalker** [comment]
There needs to be something that shows the package is in the process of saving, too. (See #363)

**Comment by gothub** [comment]
Implemented in these commits:

dd579dd5a6ee64f478dcbda38a5e6e8f01ae2db7
0f44001406a6b41c06e3bee37a18240606b7a81c
f80be7f88687fb7f1a7d1d2104620ad94d05eca1
