### ISSUE TITLE
Test Character encoding correctness under Mac, Windows, and Linux

### ISSUE THREAD

**Issue by csjx** [NCEAS/metacatui#36]
Test copy/paste from multiple environments and known disparate encodings (from Word, for instance Windows 1252 encoding) and other non-UTF-8 encodings.

**Comment by amoeba** [comment]
I copied some special characters

> ¥ÓďŋƇǃǿѠۊ۷

from a Word 97 doc running on Windows 10 inside Parallels into the editor Abstract and 👍

**Comment by laurenwalker** [comment]
I tested in Ubuntu 16, Windows 7, and Mac OSX Sierra with ASCII characters and direct copy/pasting formatted text from MS Word, MS Excel, and LibreOffice (Linux). There were no issues.

Added a function to remove MS Office hidden formatting text from the DataItemView content-editable cell. Inputs seem to automatically remove the hidden formatting text.

**Comment by mbjones** [comment]
@laurenwalker @csjx @jeanetteclark  I just noticed another example of the character encoding issues where characters are mangled somehow coming in from MetacatUI: https://search.dataone.org/view/urn:uuid:8b7db2b0-0d12-4a8f-9b9c-7c4650a55489  

So, while we don't seem to be able to reproduce this bug with the steps listed above, it is still happening.  So I am reopening this issue.

**Comment by amoeba** [comment]
I think it'd be good+useful to reach out to Tiff to see if she can shed some light on this. I'm happy to do that since I know her personally.

**Comment by csjx** [comment]
That'd be great if you could @amoeba - we'd at least know how the copy/paste happened and would give us a direction to look into.

**Comment by amoeba** [comment]
Talked to Tiff today. https://search.dataone.org/view/urn:uuid:8b7db2b0-0d12-4a8f-9b9c-7c4650a55489 came from the registry and not the new editor. She's been happily copying and pasting from Word into the editor on KNB and hasn't had any issues with garbled characters. She uses Windows and Chrome.

**Comment by laurenwalker** [comment]
Awesome, that's good to hear. Is she still accessing the registry somewhere? Or was that done a long time ago?

**Comment by amoeba** [comment]
She's using the new editor now. The object in question in this Issue is new (only 4d old) but the garbled characters were inserted in the first version, http://cn.dataone.org/cn/v2/object/knb.92401.2, which musta been a registry upload and was created `2018-05-08T23:00:00.000+00:00`.
