### ISSUE TITLE
Prov editor icons need tooltips

### ISSUE THREAD

**Issue by csjx** [NCEAS/metacatui#361]
In the provenance editor, hovering over the `+ Add` icons for sources, programs, and derivations.  While it's obvious to us, we need it to be explicit what each button adds.  For each input circle, add a tooltip of "Add a source input dataset".  For the derivation circle, add "Add a derived output dataset". For the program arrows, add tooltips with "Add a input processing program" and "Add an output processing program".

**Comment by laurenwalker** [comment]
I think tooltips would be a good idea too. I would suggest we say something like `Add source data that was used to create X` with X being the `fileName` of the current object.

**Comment by gothub** [comment]
The tooltips are displaying for prov icons that have been assigned, and should only display
for icons that have not been assigned:

<img width="343" alt="screen shot 2017-11-18 at 3 20 19 pm" src="https://user-images.githubusercontent.com/6412946/32985638-49e0dd32-cc74-11e7-9d9f-c9dd16b0ba2c.png">

**Comment by laurenwalker** [comment]
Another issue with the tooltips that needs fixed: The tooltip is only initialized on first hover. So the user has to hover to create the tooltip, then mouseout, then hover again to actually see the tooltip.

**Comment by laurenwalker** [comment]
Fixed in e896e4efc5707e25290ac891511d6d53ddeedb43
