### ISSUE TITLE
During save, change the submit button text to "Submitting..." rather than "Saving..."

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/metacatui#362]
To keep the text consistent.

**Comment by laurenwalker** [comment]
Also, the success message should use the word "submitted"  instead of "saved"

**Comment by rushirajnenuji** [comment]
In the `EditorView.js` changed the submit button text from "Saving" to "Submitting" and changed the corresponding alert messages.

**Comment by laurenwalker** [comment]
Perfect :+1:
