### ISSUE TITLE
Make prov editor configurable in AppModel

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/metacatui#364]
Let's add a flag to the AppModel so that the prov editor can be turned off/on. This will help us get the 2.0.0 release out without waiting for thorough testing and fixes to the prov editor.

**Comment by gothub** [comment]
The check for this flag could be made in MetadataView.drawProvCharts() where 'editModeOn' is set based on authentication, and controls whether or not the prov edit icons are displayed.

**Comment by laurenwalker** [comment]
We decided to release the prov editor in RC3, so closing.
