### ISSUE TITLE
Copying EMLParty Fails to Show First Name in New Entries

### ISSUE THREAD

**Issue by ThomasThelen** [NCEAS/metacatui#368]
When copying people in the EMLParty section, the first name is not carried over in the UI. Upon submission, you can see that the first name was added to the EML in the correct locations.

To Reproduce:
Navigate to EML Editor
Fill out required information
Go to 'People' section
Fill out data in every field
Copy the user to all the different user types
Note that the first name is empty on all new types
Submit data
View the dataset
Note that the first name is present in the appropriate locations

**Comment by laurenwalker** [comment]
Fixed in e42405b4dd5c2a2b72a35bdf4528a1d5581e49d8
