### ISSUE TITLE
Remove prov_instanceOfClass relationship from prov popovers

### ISSUE THREAD

**Issue by ThomasThelen** [NCEAS/metacatui#378]
When clicking the `purl.dataone.org` link, I receive the following errors

```
AppView.js?v=2.0.0RC2:418 Uncaught TypeError: Cannot read property 'top' of undefined
    at n.scrollTo (AppView.js?v=2.0.0RC2:418)
    at n.previewData (MetadataView.js?v=2.0.0RC2:1970)
    at HTMLElement.dispatch (jquery-1.9.1.min.js?v=2.0.0RC2:3)
    at HTMLElement.v.handle (jquery-1.9.1.min.js?v=2.0.0RC2:3)
```

![screen shot 2017-11-17 at 10 09 48 am](https://user-images.githubusercontent.com/9289652/32962098-0c8ce7d6-cb80-11e7-9de7-67dd71ad8599.png)

The line in question follows,
```
$("body,html").stop(true,true) //stop first for it to work in FF
   .animate({ scrollTop: $(pageElement).offset().top - 40 - offsetTop}, 1000);
```

`$(pageElement).offset()` is returning `undefined`, which is why the `top` property can't be read. 
`scrollTo` is called from `MetadataView.previewData`. We call `previewData` to scroll to an element on the page to avoid refreshes. Inside previewData, we pass the container of the element into `scrollTo` with
`MetacatUI.appView.scrollTo(this.findEntityDetailsContainer(id));`
`this.findEntityDetailsContainer(id)` returns `false`, and we end up with an empty `pageElement`.

The *real* question might be how I ended up with that link. If you look at the link heading, you'll see 
`prov_instanceOfClass` which is the name of a provenance field (see DataPackage.js) which raises further questions.

This issue might be an edge case issue, but we might want to check if 
`this.findEntityDetailsContainer(id)` returns an object before calling `scrollTo`.

**Comment by laurenwalker** [comment]
I noticed this the other day too, and I wonder if we should just hide the `prov_instanceOfClass` relationships. It's fairly technical and doesn't impart any additional information that isn't already displayed in the prov charts (i.e. activities are displayed as programs with an arrow and code icon. Data is displayed with a data icon or image, etc.).

**Comment by csjx** [comment]
I agree we should hide that relationship. A better use of it would be to,
say, change the icon type based on the class instance, but for now I would
drop the written statement.
