### ISSUE TITLE
Removing a data object from the table did not remove the corresponding otherEntity node

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/metacatui#384]
After getting a validation error detailed in #382, I removed one of the data files and clicked Submit. The EML did not change and I got the same validation error. 

When I checked the EML211 model in the JS console, I saw that the EMLEntity did not get removed from the `EML211.get("entities")` array.

**Comment by csjx** [comment]
Now that #382 is closed, this may not be an issue. Although let's still test if removing a file from the table removes the EML entity.

**Comment by laurenwalker** [comment]
I believe this may have been happening because the EMLEntity was not parsing the identifier correctly, so the DataONEObjects were not matching to their corresponding EMLEntity.
