### ISSUE TITLE
For Solr queries, replace HTTP GET with POST

### ISSUE THREAD

**Issue by gothub** [NCEAS/metacatui#392]
For packages with a large number of members, Solr queries to retrieve package info can 
fail due to GET limitations (entire query is in the URL). Refactor Solr queries that could
be very large to use POST instead, as the query is transferred in the request body and
does not have a size limit.

An example of a query that failed due to GET size limits
[err-msg.txt](https://github.com/NCEAS/metacatui/files/1492602/err-msg.txt)

**Comment by laurenwalker** [comment]
The Stats model now uses HTTP POST when the query is over a certain length. Added in 92e724a190578736d1d2283f47e54326e4b558f0

Added a new config option, `disableQueryPOSTs` to the AppModel in 92e724a190578736d1d2283f47e54326e4b558f0 and 569f8b2ac7e1a11498f42ad7528a096987cb99fd that allows MetacatUI to be deployed with POSTs turned off. The DataONE theme will likely have this off for a while until POST is supported on the CN.

The Stats model can still send GET requests when the query is short or `disableQueryPOSTs` is set.

**Comment by laurenwalker** [comment]
The provenance query sent in the DataCatalogView to draw the prov icons in the search result rows may also use POST now.

Closing this issue for now and all other queries to be sent via POST can have their own issue.
