### ISSUE TITLE
Clean up the default theme a bit

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/metacatui#395]
The default theme needs a little bit of updating and cleaning up. Some views are difficult to read with the background image. I'm going to spend a little bit of time making sure the default theme is attractive for the 2.0.0 release

**Comment by laurenwalker** [comment]
Here is the new look for the default theme. Instead of a complete background image with a semi-transparent content area, I minimized the background-image to just the navbar background. It still changes with each view change.

![default-theme](https://user-images.githubusercontent.com/6643222/33143491-0714c4ac-cf88-11e7-8aa1-ad0119a4a270.gif)

**Comment by amoeba** [comment]
That looks really good @laurenwalker!
