### ISSUE TITLE
Add the Taxonomic Reference field into the Taxa section

### ISSUE THREAD

**Issue by csjx** [NCEAS/metacatui#40]
We didn't mock up the Taxonomic Reference field as we see it in the current 1.x Registry.  Add this in.

**Comment by amoeba** [comment]
As a note for myself, this is just a free-text field at the XPATH taxonomicCoverage/generalTaxonomicCoverage which is defined as

> A description of the range of taxa addressed in the data set or collection.
> Example(s): 
> "All vascular plants were identified to family or species, mosses and lichens were identified as moss or lichen."

Is this not quite the right place for a taxonomy reference? I would have guessed: `classificationSystemCitation`.

**Comment by amoeba** [comment]
I followed up with @csjx on this and he thought the `taxonomicSystem` subtree wasn't the right fit. I agreed. I'll implement the this field as `generalTaxonomicCoverage`.

**Comment by amoeba** [comment]
Okay this is done in a254fee93224e0f8acb05fc61f29f5d487293459. Each EMLTaxonCoverage model can have one `generalTaxonomicCoverage`.
