### ISSUE TITLE
Download buttons don't work on IE11

### ISSUE THREAD

**Issue by amoeba** [NCEAS/metacatui#409]
We ran into this last week during our workshop. Clicking the Download buttons next to data items in the package table view does not work.

Steps to reproduce:

1. Open IE11
2. Browse to https://knb.ecoinformatics.org/#view/urn:uuid:9366b8e0-020d-47e5-bf55-204e7f9d33ff
3. Click "Download" on `permits_by_community_and_type.csv`
4. Observe endless spinning of spinner / no download happening

Reproducing environment:

- Win 10 in Vbox
- IE 11.0.15063.0

Notes:

IE11's console produces a warning in SolrResult.js (InvalidStateError) which looks like its an HTML5 Blob API compatibility issue.

**Comment by laurenwalker** [comment]
This was fixed by:

1. Setting the `xhr.responseType` after the `xhr` status is set to `OPENED`
2. Use the `navigator.msSaveOrOpenBlob()` function in IE instead of creating an `a` element and `click()`ing it

**Comment by amoeba** [comment]
You're a pro, thanks @laurenwalker!
