### ISSUE TITLE
Prov editor doesn't recognize some valid program formatIds

### ISSUE THREAD

**Issue by gothub** [NCEAS/metacatui#410]
When a prov editor `program` edit icon is clicked, only package members that have
a formatId for a program type should be in the selection list (i.e. "application/R", "application/MATLAB", ...). The list of valid DataONE formatIds that correspond to
programs that the prov editor uses is incorrect. This list is in `DataONEObject.js` `isSource()`
function, and needs to be corrected. The result of this bug is that some valid
package members are not available in the selection list for `program` edit icons.

**Comment by amoeba** [comment]
Nice catch. What do you think about relaxing the restrictions on this list, too? There are many filetypes that would conform to the "program" name that are not (and likely never will be) registered in DataONE. And rather than playing whack-a-mole when users ask us to add new format IDs to DataONE when their scripts aren't in the list, we could relax the restriction to any object. To help the user find the appropriate object, we could show a sorted list (perhaps with icons) to help differentiate.

**Comment by csjx** [comment]
Yeah, agreed - the restriction seemed a little too, umm, restrictive, to me 😄. I like the idea of sorting the list. We may also consider adding a filter input box that will match a filename pattern to cull the list if it's super long.

**Comment by amoeba** [comment]
A filteable list sounds 👌

**Comment by gothub** [comment]
For `program` edit icons (not data icons), first a check is made if the `formatId` is recognized as 
one of the DataONE listed formatIds that correspond to a program, then it is included in the list. If that doesn't  match, then if it's  recognized as a data type, then it is excluded from the list . If still no match (i.e. unknown), then it is included in the list. 

The checks for being a program or data are in `DataONEObject` `isSoftware()`, `isData()`, which have a list of the formatIds, which of course could be expanded beyond the DataONE list.

The intent is to allow new, unknown formatIds to be selected as programs, but to not clutter the list
with package members that are known to be data types.

Does this sound sufficient?

**Comment by gothub** [comment]
hmm, the filter input box idea maybe requires more discussion, as the list is already a subset of all package members. Would the filter box filter the filtered list, or would it start from scratch and filter the complete set of package members?

**Comment by amoeba** [comment]
Yeah that sounds good enough for now, @gothub, thanks.

**Comment by laurenwalker** [comment]
We discussed on #892 the need to have a "Show All" link that expands the list of identifiers to include all identifiers in the package. This way any formatId can be chosen as a program without a MetacatUI update.

**Comment by laurenwalker** [comment]
This issue has since been fixed. I think we need to improve the UI of file selection tool so that certain file types are listed first, or add sorting and filtering mechanisms. Maybe display as a table rather than a multi-select input. But for now, this is working, so I'm going to close this issue.
