### ISSUE TITLE
Border around Sign in with ORCID button is broken

### ISSUE THREAD

**Issue by amoeba** [NCEAS/metacatui#411]
I just visited https://dev.nceas.ucsb.edu/#share and saw this:

<img width="621" alt="screen shot 2017-12-06 at 12 13 21 pm" src="https://user-images.githubusercontent.com/563/33685708-eeee2f6a-da7e-11e7-98c5-43355381ed84.png">

Browser: Firefox Quantum 57.0.1 (Mac OS 10.13.1)

Doesn't appear to affect Chrome, Safari

**Comment by laurenwalker** [comment]
This was fixed in master and 2.0 branch
