### ISSUE TITLE
Locations validation not working correctly

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/metacatui#412]
I'm experiencing several issues with the Locations validation. The error borders are not displaying, and error messages are showing that are not correct. I think the entire locations validation code needs to be reviewed.

**Comment by laurenwalker** [comment]
Example:

<img width="1054" alt="screen shot 2017-12-08 at 1 34 54 pm" src="https://user-images.githubusercontent.com/6643222/33779864-9ee2e4c6-dc1c-11e7-87b5-c628cee28ae3.png">

**Comment by ThomasThelen** [comment]
May be related to #351

**Comment by laurenwalker** [comment]
I did a complete rehaul of the EMLGeoCoverage validation process. It was a little complication before and didn't take advantage of the EditorView validation process, which will automatically call `showValidation()` on any view that has a model with an error.
