### ISSUE TITLE
Disable Edit button if metadata format is not EML

### ISSUE THREAD

**Issue by vchendrix** [NCEAS/metacatui#418]
**MetacatUI Version:** 2_0_0RC1-52-gccbc63e

Dataset Edit button should be disabled if the dataset metadata is not EML

We are uploading datasets that use FGDC metadata format.  The edit button is available but when clicked the edit form hangs.

**FGDC format dataset metadata**
<img width="1109" alt="screen shot 2017-12-20 at 8 13 19 am" src="https://user-images.githubusercontent.com/1558129/34216789-37fc15de-e55e-11e7-9c8f-f8a603404531.png">

**After clicking "Edit"** the balls spin forever
<img width="1180" alt="screen shot 2017-12-20 at 8 16 32 am" src="https://user-images.githubusercontent.com/1558129/34216776-2d731a04-e55e-11e7-9920-7731ea68d645.png">

**Comment by laurenwalker** [comment]
I noticed this the other day, too. Should be fixed for the 2.0.0 release.

**Comment by laurenwalker** [comment]
The Edit button now only works on the MetadataView when the format is in the list of editable formats in the AppModel (only EML 2.1.1 for now). Otherwise, the edit button is disabled with a tooltip note.

**Comment by vchendrix** [comment]
Thanks! I have updated to the latest Metacat UI commit and tested that this works!
