### ISSUE TITLE
Dataset Edit: Title not indexed after save 

### ISSUE THREAD

**Issue by vchendrix** [NCEAS/metacatui#419]
**Metacat UI Version:** 2_0_0RC1-52-gccbc63ec

Dataset Edit: Title not indexed on save - There is no error indicated in the Metacat UI javascript console.  The error seems to be in indexing the obsoleted document. Also, every time the *title* is updated and saved the title immediately previous is finally updated in the index. So, the indexer is always one document behind. However, I just tested this on the *author first name*.  That field does get indexed immediately on save.

If this needs to be logged to Metacat Member Node instead of Metacat UI, I can do so there.

**Comment by laurenwalker** [comment]
I'm not sure what the exact issue is that you are describing. It sounds like you are opening a dataset in the editor and changing the title, but the EML title is not correctly updated?

**Comment by mbjones** [comment]
Yes, the symptom was that the title was updated in the XML, but was not displaying properly, and always seemed to be one version behind in display.  What would be helpful @vchendrix would be to have a reproducible example that shows the problem not just on your server, but also on one of our testing servers such as https://test.arcticdata.io.  What are the exact steps needed to make the problem appear, and can you show a screenshot of the erroneous display?  Thanks.

**Comment by vchendrix** [comment]
closing this.  Not an issue anymore
