### ISSUE TITLE
User Profile Access Policy

### ISSUE THREAD

**Issue by vchendrix** [NCEAS/metacatui#424]
It is not always desired to allow any user to have access to the authentication token or to create and manage groups.  It would be nice to have a way to limit access to these UI features based on an access policy.

**Comment by laurenwalker** [comment]
DataONE will allow any authenticated user to access their token and create groups. Only the owner of a group can manage that group.

A certain theme could possibly restrict those UI features to users within a certain user group (like an admin group).

**Comment by vchendrix** [comment]
This is no longer an issue for ESS-DIVE.
