### ISSUE TITLE
Allow selecting any file as a program in prov relationships

### ISSUE THREAD

**Issue by gothub** [NCEAS/metacatui#428]
When editing provenance relationships, allow for selecting package members that are
.zip files as scripts. Currently the prov entity selection dialog types ZIP archives as
data, and so doesn't include them in the selection list when prov 'programs' are selected.

Either we need to update the way ZIP archives are typed, or modify the way package members
are selected, so that 'data' members can be selected as 'programs'.

**Comment by laurenwalker** [comment]
I think we should improve the "choose program" dialog so that any file in the dataset can be selected as a program, regardless of file type. But it is helpful to have files that are identified as likely programs filtered so they are easy to find. Maybe we could have the list of likely programs, as it is now, but add a "See more" link that expands the list to show all the other files?

**Comment by gothub** [comment]
Yep, that would be a clear, easy to understand way to do it. Another, more involved way
was mentioned [here](https://github.com/NCEAS/metacatui/issues/410), which might be a way
to filter the (entire) list if the user knows what they are searching for, and the list is possibly long.

Can/should we have both "See more" to show everything, or "see just what I want"?, and how to
design a selection box that allows both?

**Comment by laurenwalker** [comment]
I think this issue needs to be bumped up in priority. I just tried to add an R program as a program in my prov chart and it didn't even show up as an option. It's an `application/octet-stream` file type with an `r` extension.


<img width="853" alt="screen shot 2018-02-28 at 1 58 58 pm" src="https://user-images.githubusercontent.com/6643222/36806983-bf9a7248-1c8f-11e8-88b3-ae0279572f51.png">

<img width="1054" alt="screen shot 2018-02-28 at 2 00 42 pm" src="https://user-images.githubusercontent.com/6643222/36806997-caa4b1f8-1c8f-11e8-9224-0e4237017e0e.png">

**Comment by laurenwalker** [comment]
In the future we may want to do some more advanced collapsing or sorting, but for now, let's just stop filtering out any files.
