### ISSUE TITLE
Missing image matlab-dataone.png

### ISSUE THREAD

**Issue by vchendrix** [NCEAS/metacatui#433]
`matlab-dataone.png` referenced in `js/templates/userSettings.html` is missing from metacat version `2_0_0RC1-284-g3633d0a4`

**Comment by laurenwalker** [comment]
That image was (erroneously) removed recently, in 2.0.0 RC 4. Are you truly still on version `2_0_0RC1-284-g3633d0a4` or have you been updating your MetacatUI?

**Comment by vchendrix** [comment]
Ah I see there have been 4 commits since I updated my code on Jan 2.  I
will update to `2_0_0RC1-288-g98065c9f`  to fix the issue.

**Comment by laurenwalker** [comment]
So it sounds like you are keeping your code consistenly updated, which means you are on at least version `2.0.0RC4`. Are you updating from the `master` branch?

In the future when making issues, it would be helpful to list the actual version you are using (which sounds like it hasn't been `2_0_0RC1-284-g3633d0a4` in a while). To be safe, it's best to use the latest tagged release, which is currently [2.0.0RC4](https://github.com/NCEAS/metacatui/releases/tag/2_0_0RC4). The latest tagged release can always be found at [https://github.com/NCEAS/metacatui/releases](https://github.com/NCEAS/metacatui/releases).

**Comment by vchendrix** [comment]
Lauren,

Yes, I am pulling from master and then using `git describe --tags` to
determine which version I am on.  That is how I came up with
2_0_0RC1-284-g3633d0a4 . The current version I just pulled from master
is 2_0_0RC1-289-g7eb3e4bf.  I will go ahead and build from `2_0_0RC4`

**Comment by laurenwalker** [comment]
Ok. We have been releasing the 2.0.0 tags on the 2.0 branch, not the master branch. You could either use the tagged releases (such as RC 4, RC 5, etc.) or you could switch to the 2.0 branch and pull the latest commit from there.

**Comment by vchendrix** [comment]
Great! Thanks for the tip!
