### ISSUE TITLE
Test Editor in Beta: "Copy to..." feature in 'People' triplicates entry

### ISSUE THREAD

**Issue by jagoldstein** [NCEAS/metacatui#434]
After entering information for "Creator", clicking "Copy to..." from the drop down, and choosing "Contacts", the info is copied to the "Contacts" section 3 times, instead of only once.

The info appears twice under the first "Contact" section and once more under a second "Contact" section.

**Comment by laurenwalker** [comment]
Hi @jagoldstein - I haven't been able to reproduce this bug. Have any suggestions? Do you remember what specific EML doc it was and which person you tried to Copy? If not, I'll keep trying to recreate it.

**Comment by jagoldstein** [comment]
@laurenwalker  I also just tried to reproduce the bug to no avail. I was entering a new EML and the person I copied was myself. I never actually clicked 'Submit' on that test run. If we can't recreate the bug I guess this isn't an actual issue and can be closed. I will continue testing and let you know if I see it again. thanks

**Comment by laurenwalker** [comment]
@jagoldstein Ok, I'll close this ticket but I'll keep my eye out for it. Thanks.
