### ISSUE TITLE
Filenames don't populate when describing data files

### ISSUE THREAD

**Issue by jeanetteclark** [NCEAS/metacatui#435]
If you are editing in beta, the pids populate instead of filenames in the "describe files" section.

<img width="1609" alt="screen shot 2018-01-05 at 3 03 46 pm" src="https://user-images.githubusercontent.com/24237074/34632948-a2f9b680-f22d-11e7-85a3-577a029080b6.png">

This makes it almost impossible to figure out which file you are describing without flipping back and forth between the old landing page and the editor. Anyone who doesn't know what the ids mean will be super lost

**Comment by csjx** [comment]
So my understanding of this is that the old editor submits EML via the old Metacat API, which is not DataONE-aware. So, Metacat auto-generates a `systemmetadata` entry.  The code for this was written during `v1` of the DataONE types, so the `v2` `SystemMetadata.fileName` attribute was not around back then, so it of course still does not get populated.  This is something that we might need to address on the Metacat side and specifically set the `fileName` for EML documents containing a valid `/eml/dataset/{entityType}/physical/objectName` string value. 

So, MetacatUI is falling back to the `pid` in the absence of a `fileName` attribute, which I think is the correct behavior.  However, we could also change MetacatUI to be more proactive and look for the `/eml/dataset/{entityType}/physical/objectName` value, or possibly the `/eml/dataset/{entityType}/entityName` value if the `fileName` isn't available. Thoughts @laurenwalker ?

**Comment by mbjones** [comment]
@csjx I think both of those are appropriate: 1) fix metacat to add in the additional sysmeta fields, and 2) have MetacatUI be more proactive about finding missing info from EML files.

**Comment by laurenwalker** [comment]
I have decided that the Editor should:

1. Find the file names in the entity metadata just like the MetadataView does
2. Update the DataONEObject model with the filename from the metadata
3. Update the system metadata for each DataONEObject when the user clicks Submit.

**Comment by laurenwalker** [comment]
Use the `objectName` from the `physical` EML module first, then fall back to the `entityName` if it is not available.
