### ISSUE TITLE
Methods section duplicates

### ISSUE THREAD

**Issue by jeanetteclark** [NCEAS/metacatui#438]
Updating this submission from this version:
https://arcticdata.io/catalog/#view/arctic-data.14493.2

to this version:
https://arcticdata.io/catalog/#view/urn:uuid:9431dcb1-2bac-407c-a19d-68cad599ca45

resulted in the methods section mysteriously getting duplicated.

Updates made were the addition of attribute information to two of the data files.

**Comment by laurenwalker** [comment]
This was fixed in #637
