### ISSUE TITLE
Add a simple 'changed' flag to the DataONEObject model 

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/metacatui#44]
Change the 'changed' flag to true when the user changes any part of the Editor form. (Rather than listen to changes via the Backbone API).

Hide the save button until the changed attribute is true

**Comment by csjx** [comment]
We now have a `changed` flag in `MetacatUI.rootDataPackage.packageModel`, and it's used to show and hide the save bar.  I still see an issue when saving the title at first, so need to track that down, but I think the basic functionality is there.  For instance, after adding files and saving, the bar is hidden until the next change.

**Comment by laurenwalker** [comment]
Awesome! I've played around with it and it is working nicely (except for the title-only save you mentioned)

**Comment by laurenwalker** [comment]
I think this is done - can we close?

**Comment by csjx** [comment]
Yes, I'll close it - I think we dealt with the title issue, but if it crops up again, we'll re-open.
