### ISSUE TITLE
When an EMLAttribute is invalid, the DataItemView should show the validation error

### ISSUE THREAD

**Issue by jagoldstein** [NCEAS/metacatui#440]
This is a suggestion; not a bug per se (in that I think the behavior is expected by the devs).

After uploading a data object, clicking the yellow "Describe" button, and selecting the "Attributes" tab, I selected the toggle for "Numeric" under "Category" and clicked "Done" (thus closing the Describe entry box for that file). I did not enter any other fields nor choose any other options even though they are marked with a red asterisk (which seemingly denotes a required field).

My issue is that this led to the "Describe" button turning Green and the display of a green check that when hovered over says "Complete" next to the data file... but the attribute descriptions are very incomplete. I made one arbitrary selection, but entered no meaningful metadata.

I believe that if a submitter chooses to define an attribute, they should have to fill in all the fields marked with a red asterisk before being rewarded with the "Complete" check marked message for that file. In fact, for every data file uploaded, there should probably be SOME description entered, even if it's only a file "Description" in the "Overview" tab.

**Comment by mbjones** [comment]
Thanks, @jagoldstein -- I agree.  And maybe some of these validation requirements should be configurable so that different repositories can make decisions as to whether or not to require entity/attribute metadata.  Need to be careful though, as not all entities need it, and sometimes when there are lots of identical entities, we may want to make it easy to bypass and add that in programatically.  Let's talk through these features in this ticket.

**Comment by laurenwalker** [comment]
I agree that if a file has incomplete attribute metadata, it should not be marked in green as complete. It should be red, like the rest of the editor, when there is missing information. This is something we have thought about before but punted down the line, but I'm thinking maybe we should go ahead and complete this feature before the public release. 

As for requiring a description for each file - I can see that being problematic for huge datasets, like Matt suggested. But it's also not much to ask for datasets with only a few files. So I could see us going either way. Like all required fields in the Editor, it would be configurable.

**Comment by jagoldstein** [comment]
I wasn't considering submitters using the web form to submit a large amount of files since the current web form does not support that and we usually find other ways to transfer many files, but after some testing, uploading many files seems to be well supported and went smoothly in beta. So, yes, I agree with you both that we don't want to require file descriptions for uploads of a large number of files.

**Comment by jagoldstein** [comment]
This is still an issue. Only 1 of the fields marked with a red asterisk in the 'Attributes' section needs to be entered (and then the 'Done' button clicked) to change the uploaded file to having a green check. For example, "Attribute Name" and "Definition" do not have to be entered.

Resolving this would save the data team lots of time in the long-run as otherwise we will have to do a lot more QA/QC, have longer back and forths with contributors to tell them that some of their attribute definitions are incomplete, and to attempt to garner the missing info.

**Comment by laurenwalker** [comment]
@isteves - No, at this time we don't require any of the entity metadata. We certainly could if we wanted to. I'll create a separate issue for that slated for the 2.0.1 release.

I think this particular issue is resolved now with the recent commits referenced above. I do need to update test.arcticdata.io with these latest changes.
