### ISSUE TITLE
EML Model: make system attribute configurable

### ISSUE THREAD

**Issue by vchendrix** [NCEAS/metacatui#441]
Is it possible to make `system` attribute configurable in order to override the default `knb` value?

```xml
<eml ... system="myvalue">...</eml>
```

**Comment by robyngit** [comment]
Hey @vchendrix, is this still an issue for ESS-DIVE? If so, could you provide a little more context for the problem? Thanks!

**Comment by vchendrix** [comment]
Sure!  The following line hardcodes 'knb' we would like to configure this to populate the attribute as 'ess-dive'.  

https://github.com/NCEAS/metacatui/blob/26e1a46bd428522b43e6ba696109dfee710eb1a2/src/js/models/metadata/eml211/EML211.js#L2091

In our code base we achieve this extending `EML211.createXML`.

https://github.com/ess-dive/ess-dive-catalog/blob/31210a9c0ce4467f01dd9f6abaa569d286cbc9d5/theme/models/metadata/eml211/EML211.js#L49-L69

and configure it in our theme's `config.js`

https://github.com/ess-dive/ess-dive-catalog/blob/31210a9c0ce4467f01dd9f6abaa569d286cbc9d5/theme/config.js#L2

**Comment by robyngit** [comment]
@vchendrix this is fixed in the develop branch and will be included in the next release - sorry it took so long!
