### ISSUE TITLE
Design project views for SASAP

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/metacatui#445]
- [x] Develop a list of features that we want in the project views
- [ ] Create wireframes of the project views and review and revise them until a design is approved by the SASAP team
- [ ] Create graphical mockups of the approved wireframes.

**Comment by mbjones** [comment]
@laurenwalker Can you add a link to where that list of features is?  Thanks.

**Comment by laurenwalker** [comment]
A list of features we want in the project views is here: https://docs.google.com/document/d/1wzcCDFnp8AsvQxg8qaxzDSy894vjjgmbSb2OUWcaLoo/edit

**Comment by laurenwalker** [comment]
Anyone, feel free to add more feature ideas or discuss here on this GitHub ticket.
