### ISSUE TITLE
No `accessPolicy`s set on objects submitting via the Test Editor

### ISSUE THREAD

**Issue by jagoldstein** [NCEAS/metacatui#451]
There are no `accessPolicy`s being set on EMLs, res maps, nor data objects submitted via the test editor. I'm unsure if this is intentional, but I would think `accessPolicy`s should be set to r/w for the `submitter` and to full access for the ADC admin group.

Example: https://test.arcticdata.io/#view/urn:uuid:6de80a8a-f674-4b5d-b1ff-e9bbcea52634
```
> pid <- 'urn:uuid:6de80a8a-f674-4b5d-b1ff-e9bbcea52634'
> sysmeta <- getSystemMetadata(mnT, pid)
> sysmeta@accessPolicy
[1] subject    permission
<0 rows> (or 0-length row.names)

> pid <- 'urn:uuid:e28dc3b1-ffe9-4e79-994a-7d72848d5874'
> sysmeta <- getSystemMetadata(mnT, pid)
> sysmeta@accessPolicy
[1] subject    permission
<0 rows> (or 0-length row.names)
```

**Comment by laurenwalker** [comment]
@csjx Did we do this intentionally? We should definitely support it at some point, but did we decide to do this for the first pass of the editor?

The access policies should be configurable per theme.

**Comment by laurenwalker** [comment]
At our Feb 6 ADC team meeting in SBA, we decided that we need to add theme-configurable access policies to set to each object created in the Editor. 

For the Arctic theme, the access policy should give the ADC Team all permissions.

**Comment by amoeba** [comment]
Hey @laurenwalker, did we also discuss adding real moderators into Metacat so we can deprecate this (since it’s a hack and makes R package development harder?).

**Comment by laurenwalker** [comment]
No, we didn't discuss that, but that would be a great feature to have.
Maybe we can discuss at the next dev meeting?

**Comment by amoeba** [comment]
Sounds great, thanks @laurenwalker !
