### ISSUE TITLE
New editor should require a 'Methods' section

### ISSUE THREAD

**Issue by jagoldstein** [NCEAS/metacatui#452]
NSF requires the submission of a comprehensive 'Methods' section for all ARC-supported projects. The Data Team will not publish packages without this section of the EML. Therefore, the editor should require a 'Methods' section too, rather than having it be optional.

**Comment by laurenwalker** [comment]
The methods are now configured as 'required' for the arctic theme, as of the next release (MetacatUI 2.19.0). The new Ethical Research Practices question for the editor (#1864) will also be required, so this means that users will be required to submit an answer to the Ethical Research Practices *and* at least one Method Step in the methods section.
