### ISSUE TITLE
FGDC format cannot be viewed by SID

### ISSUE THREAD

**Issue by vchendrix** [NCEAS/metacatui#453]
**From Master Branch:** fd21de11bcf6ea470158077409bb5f00dee1354e

If the dataset metadata is not EML (e.g. FGDC) using a series id to view the metadata returns the following message.  

I have a solution in my [private fork](https://github.com/vchendrix/metacatui/tree/issue_fgdc_sid_not_viewing). I can submit a pull request if it is desired. 

**https://localhost/#view/CUB.1**
![screen shot 2018-01-24 at 1 38 22 pm](https://user-images.githubusercontent.com/1558129/35358580-f61f0ab2-010b-11e8-8ad7-b8f6686f8732.png)

**Comment by laurenwalker** [comment]
Thanks Val. Go ahead and create a pull request and I'll approve it. Good catch.

**Comment by vchendrix** [comment]
Done!
