### ISSUE TITLE
improve searching for identifiers

### ISSUE THREAD

**Issue by mbjones** [NCEAS/metacatui#455]
Ensure that identifiers can be found by typing all or part of the identifier in both the general search box and the identifier search.  Substring matches should work in both.

This feature is needed by ESS-DIVE, and would be useful for Arctic Data Center and DataONE.

This likely involves an indexing change on Metacat as well.

**Comment by amoeba** [comment]
This is great to see! I wasn't sure how much uptake I'd have on this but @mpsaloha requested this privately to me the other week and I was going to bring it up on a dev call soon.

**Comment by mbjones** [comment]
We also just found out that the SID is not searched in these text boxes either.  So please ensure that both the PID and SID are indexed and searchable in both locations.
