### ISSUE TITLE
Set EML name automatically to science_metadata.xml

### ISSUE THREAD

**Issue by maier-m** [NCEAS/metacatui#464]
The data support team has a standard to set short EML names, typically "science_metadata.xml". It would be great if the EML name was automatically set to "science_metadata.xml".

**Comment by laurenwalker** [comment]
Are you referring to the EML file name when you download the .xml file from the data catalog website?

**Comment by maier-m** [comment]
Yes. The Sysmeta.

**Comment by laurenwalker** [comment]
It's tricky to decide on a good science metadata file name since we want the file name to be easily recognizable by scientists using the site as well as convenient for our internal team. Might require more discussion...

**Comment by amoeba** [comment]
+1 for group discussion. I've occasionally used a sanitized and shortened version of the EML title as the filename and I wonder if that might work better for scientists/users.

**Comment by laurenwalker** [comment]
We decided to set the file name to the EML title, which was done in commit acc778c66f0573c14b15cfeac9c7f81889248a83
