### ISSUE TITLE
Unexpected 'file already exists' error when submitting file

### ISSUE THREAD

**Issue by isteves** [NCEAS/metacatui#465]
Hi @laurenwalker,

I encountered a 'file already exists' error associated with the code autogen.2018......1.  Do you know what that means? (see below)

Some side effects:

- Since there was no way for remove the bad file (describe is grayed out), I went ahead describing the other csv's
- When I submitted, none of the csv's uploaded but the otherEntity _did_ appear on the page with the attribute information
- When I "edited" and resubmitted one of the files, there was no way for me to retrieve the attribute info so it just disappeared (see campbell_data15.csv https://test.arcticdata.io/#view/urn:uuid:23c73c0f-6d95-436e-a406-c327a87c1853)

<img width="938" alt="filealreadyexists" src="https://user-images.githubusercontent.com/25118334/35993292-b3e43836-0cc1-11e8-9c5c-fd9e3b861a03.png">

**Comment by laurenwalker** [comment]
Thanks Irene - Did you previously upload the `hobo_climate.csv` file to this dataset or did the "file already exists" error show up when you tried uploading it for the very first time?

(Note to self: It looks like this was with Chrome on a Mac)

**Comment by laurenwalker** [comment]
I'm unable to reproduce this error and I've recently made some changes that stabilize duplicate files and entities, so I think this is most likely fixed. If not, we can reopen this issue.
