### ISSUE TITLE
Attributes sidebar jumps off screen in Firefox

### ISSUE THREAD

**Issue by maier-m** [NCEAS/metacatui#468]
<img width="906" alt="screen shot 2018-02-08 at 1 49 33 pm" src="https://user-images.githubusercontent.com/16710796/36000164-e9b39c9e-0cd6-11e8-8389-ec0a825e230a.png">

Firefox 57.0.3 (64-bit)
macOS Sierra (10.12.6)

**Comment by smfreund** [comment]
I had a similar problem with my view being distorted using Internet Explorer on Windows 7: The "Attributes" tab gets pushed offscreen
![attribute-editor-iw](https://user-images.githubusercontent.com/35786348/36004621-722e6656-0ce8-11e8-8df8-6863d0646abe.PNG)

**Comment by smfreund** [comment]
Another issue with the sidebar (Internet Explorer, Windows 7): cannot add more attributes once list gets long, unless you zoom way out on the screen
![cant-add-more](https://user-images.githubusercontent.com/35786348/36004691-ced09ca8-0ce8-11e8-80a0-60095f34706b.PNG)

**Comment by laurenwalker** [comment]
I created a new issue for the other two rendering issues (see #487)
