### ISSUE TITLE
Have to submit twice to get rid of data lost warning

### ISSUE THREAD

**Issue by maier-m** [NCEAS/metacatui#470]
When submitting, I am getting the top successful banner. The dataset is created in the ADC with a valid pid.

But, when trying to leave the editor I get (Do you want to leave this page? All information you've entered will be lost). 

I can then click the `submit dataset` button again without any changes being made and a new pid is given to the dataset and then the warning does not pop up when navigating away.

Both in Chrome and Firefox

**Comment by jagoldstein** [comment]
I would be good to have a clear way for submitters to navigate directly to their submitted package after they get the "Thank you" confirmation message.

I like the button on the registry "Thank you" confirmation message:
![image](https://user-images.githubusercontent.com/18270215/36047074-e1165a22-0d8f-11e8-90a0-b1253c725d4e.png)

related to #459

**Comment by jagoldstein** [comment]
I see now that it is fairly easy to navigate to by closing the confirmation message and then clicking on the data set title, but it is not super obvious, especially for hasty users. Also, needing only one click would be better than two.

**Comment by laurenwalker** [comment]
I created a new issue specifically for the View your data set link. - #480
