### ISSUE TITLE
As a stop-gap, create "Other" Unit options in the dropdown menu until Custom Units are supported

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/metacatui#471]
The "Other (Dimensionless)" option can be serialized as "Dimensionless". This can be a flag to the support team to review all "Dimensionless" units and possibly create a custom unit behind-the-scenes.

Put "Other" at the top of the dropdown

**Comment by jagoldstein** [comment]
This is a priority from the perspective of the support team. We advocate for an "Other" choice at the top of the units dropdown, possibly with a divider (line) under it before the list of standard units.
