### ISSUE TITLE
Confusing error dialogue when submitting a dataset before attributes are complete

### ISSUE THREAD

**Issue by emilyodean** [NCEAS/metacatui#472]
Windows 7, Chrome v63. This error message is correct (I didn't submit complete attributes) but it's probably not what we want to show to the user. 

![image](https://user-images.githubusercontent.com/11021304/36005689-a9f71920-0ced-11e8-9bcf-8ac3896bc4a8.png)

**Comment by laurenwalker** [comment]
Yeah, the editor should not be attempting to save the EML if it is invalid.

**Comment by vlraymond** [comment]
Windows 10 / Edge
<img width="1924" alt="kuparak_error" src="https://user-images.githubusercontent.com/7627276/36860841-456eaa86-1d37-11e8-8743-31fd921da4b9.png">
<img width="1918" alt="kuparak_error2" src="https://user-images.githubusercontent.com/7627276/36860850-4ad77746-1d37-11e8-9cd4-e294718cc9a3.png">

**Comment by laurenwalker** [comment]
I moved Vanessa's comment to a new issue: #505

**Comment by csjx** [comment]
I'll work on this @laurenwalker - it seems like we have a client side validation issue for the `attributes` section, so I'll work on `validate()` to make sure we're sending good XML to the server.

**Comment by csjx** [comment]
Also, let's think about the `details` section of the error message. We certainly don't want to show raw errors to the scientist.  We may need to figure out a way to enumerate the invalid sections and provide links into the editor so the scientist can add in the required metadata.

**Comment by laurenwalker** [comment]
FYI - I just pushed some code changes to the EMLEntity and EMLAttribute validation that may help the work you're doing on this issue.

**Comment by laurenwalker** [comment]
Going to close this issue since Chris mentioned yesterday that this bug seems to be fixed with recent commits. We can reopen this issue if we encounter this bug in the future.
