### ISSUE TITLE
Error submitting on test node related to an older, but valid funding number

### ISSUE THREAD

**Issue by jagoldstein** [NCEAS/metacatui#473]
In Safari v 11.0 on macOS Sierra v 10.12.6:
I was able to reproduce my submission error to test.arcticdata.io when manually copying the metadata from this package into the new web form:
https://arcticdata.io/catalog/#view/doi:10.18739/A2F50X

This package has no data objects.

<img width="1302" alt="screen shot 2018-02-08 at 12 10 45 pm" src="https://user-images.githubusercontent.com/18270215/36006305-ff30a2aa-0cf0-11e8-8a7a-9012b43a9dad.png">

I received this error both when pasting-in the funding number and when typing it in manually. I have not tested this in other browsers or OSs yet. The error message relates to elements missing from the `project` section of the EML. So far, I have only encountered this error with this NSF funding number: "0756708". It is a valid award number discoverable at www.nsf.gov/awardsearch.

**Comment by laurenwalker** [comment]
I wasn't able to reproduce this error, but I looked over the parsing and serialization of EMLProjects and found a few ways this bug could have happened. I improved the stability of those functions so (hopefully) fix this bug. If it crops up again, we can reopen this issue.

See 7004111004103281775c76adb04d8b2afa55efc5
