### ISSUE TITLE
editor: prompted to fix errors before submitting but no errors are identified

### ISSUE THREAD

**Issue by smfreund** [NCEAS/metacatui#475]
This is in Internet Explorer on Windows 7. I received the warning at the top saying "Fix the errors flagged below before submitting." The "people" section has a red exclamation point, so I assume the problem is somewhere in how I filled out this section, but there are no indicators on this page showing what the problem is. 

![image](https://user-images.githubusercontent.com/35786348/36041138-789ae62e-0d7c-11e8-9352-cba8325b8622.png)

**Comment by smfreund** [comment]
Continuation of this issue. I clicked inside the boxes on this people section to see if the errors show up by doing so. The problem might be that I hadn't filled out the Position name in addition to the person's last name and organization, even though only one of those is described as required.
![image](https://user-images.githubusercontent.com/35786348/36047223-467e4442-0d90-11e8-8c59-c218efee2702.png)

**Comment by smfreund** [comment]
Another related comment to this issue: The text above the entry fields says "if none are entered, you will be set as the creator of this document". This suggests that filling in the form is not actually required, but the settings really do require it. Currently, the "People" link does not have a red asterisk next to it indicating that required fields are in this section.

**Comment by smfreund** [comment]
After filling in all possible required fields for the creator, the "submitting" button runs continuously and does not complete the submission. I cannot submit this dataset.

![image](https://user-images.githubusercontent.com/35786348/36277212-2176516c-1245-11e8-86cd-b708e647b107.png)

**Comment by areevesman** [comment]
Same behavior as @smfreund 
![screen_shot_2](https://user-images.githubusercontent.com/11857896/36702646-d2b3318a-1b4f-11e8-9547-907b8066894f.png)

**Comment by areevesman** [comment]
@laurenwalker We have been unable to submit through IE 11. In one instance the submission button is spinning but doesn't finish.
![submission_button](https://user-images.githubusercontent.com/11857896/36703804-54e0ac28-1b55-11e8-992b-df3a5ad91488.png)

In the other instance, the submission button disappears and does not come back even after filling in "required" fields
![requirements](https://user-images.githubusercontent.com/11857896/36704262-82a228ba-1b57-11e8-9dc4-25b0181e3f67.png)

**Comment by smfreund** [comment]
This same problem is occurring for me with Chrome on Mac.

**Comment by laurenwalker** [comment]
I believe this was occurring when parties were removed via manually erasing all the input values from the form rather than using the "Remove" button in the UI. When all the values are erased, the model should be removed from the EML211 model and then re-added once values are added again.

While fixing this I also found a bug with the "Copy" functionality.
