### ISSUE TITLE
"Describe" circle will not fill in once attributes are complete

### ISSUE THREAD

**Issue by smfreund** [NCEAS/metacatui#476]
Internet Explorer, Windows 7. Circles next to "describe" button for data files still say "This file needs to be described" even after all sections are completed.

**Comment by emilyodean** [comment]
Same behavior in Chrome.

**Comment by jagoldstein** [comment]
probably related to #440, but sounds like the reverse

**Comment by laurenwalker** [comment]
This is likely fixed with the recent changes in #440 but I will try to reproduce to be sure.

**Comment by laurenwalker** [comment]
I haven't been able to reproduce this error with a lot of the recent changes to attribute validation, so I think it's fixed. If anyone experiences this bug again, please reopen this issue.
