### ISSUE TITLE
Incorrect personnel information auto-populating from updating with test editor

### ISSUE THREAD

**Issue by jagoldstein** [NCEAS/metacatui#477]
In Safari v 11.0 on macOS Sierra v 10.12.6:
I submitted ONLY the required fields in the editor on test.arcticdata.io.

I did NOT fill in any info for "People" before the first submit since it is not required. So, the first version auto-filled with my info for "Creator".

I then went back and edited the package and changed the "People" info. I entered an organization as the "Creator" and removed my pre-populated ORCiD. I then copied this entry to "Contacts", entered Martin Nweeia's info as the PI, and resubmitted.

The new version wrongly added my ORCiD ID back in under the "Creator" and "Contact" organization listed.

Also, in all versions, I am listed as the PI under the `project` section of the EML, which is incorrect.

See the package here:
https://test.arcticdata.io/#view/urn:uuid:0b4718a3-5e58-49af-9cde-00e66282ef62

**Comment by laurenwalker** [comment]
I added a new issue for the project personnel issue: https://github.com/NCEAS/metacatui/issues/525
