### ISSUE TITLE
Citations do not display on ADC

### ISSUE THREAD

**Issue by isteves** [NCEAS/metacatui#485]
Currently, citations (references) do not display on the webpage.  Here's an example of a dataset which includes citations in the EML: https://arcticdata.io/catalog/#view/doi:10.18739/A2C857

<img width="947" alt="screen shot 2018-02-13 at 4 58 30 pm" src="https://user-images.githubusercontent.com/25118334/36182580-3292080e-10df-11e8-9b74-b86206f058dc.png">

**Comment by amoeba** [comment]
Hey @isteves. Thanks for the bug report! This is, somewhat confusingly, an issue with another piece of software with a related name (Metacat). I've filed this over there with your link and screenshot: https://github.com/NCEAS/metacat/issues/31.

**Comment by isteves** [comment]
Gotcha.  Thanks for moving it over!  Where to file the issue was a guess on our part anyway.  We figured stuff related to the website qualified as UI.
