### ISSUE TITLE
IE and Windows 7 rendering issues with the attributes tab

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/metacatui#487]
From @smfreund in #468:

> I had a similar problem with my view being distorted using Internet Explorer on Windows 7: The "Attributes" tab gets pushed offscreen
![image](https://user-images.githubusercontent.com/6643222/36273744-8309bcf8-1253-11e8-9a8a-139198fe4763.png)

> Another issue with the sidebar (Internet Explorer, Windows 7): cannot add more attributes once list gets long, unless you zoom way out on the screen
![image](https://user-images.githubusercontent.com/6643222/36273753-8dd1c22a-1253-11e8-8a15-4bd49db5353e.png)

**Comment by rachelsun97** [comment]
Same behavior on MacOS High Sierra v. 10.13.2 for Firefox Quantum version 58.0.2 (64-bit)
<img width="1608" alt="screen shot 2018-02-26 at 2 34 16 pm" src="https://user-images.githubusercontent.com/35986952/36701450-4e228476-1b08-11e8-90a4-8541f7b096c6.png">

**Comment by areevesman** [comment]
Same behavior as @smfreund but on Windows 7 IE 11 
![screen_shot](https://user-images.githubusercontent.com/11857896/36702323-88c7cf8c-1b4e-11e8-95a6-caa0e92fd181.png)

**Comment by laurenwalker** [comment]
I just updated test.arcticdata.io with the fix for this issue. @rachelsun97 and @areevesman -
 can you refresh your web browser at test.arcticdata.io and see if that behavior is still happening?

Thanks!

**Comment by rachelsun97** [comment]
Hi @laurenwalker !

I just retried it on test.arcticdata.io and it's still happening

**Comment by areevesman** [comment]
Hi @laurenwalker, it is still happening to me too
