### ISSUE TITLE
Text wrapping issue in prov display

### ISSUE THREAD

**Issue by amoeba** [NCEAS/metacatui#49]
I was just browsing Jesse's test Hydrocarbon prov page and saw a minor text wrapping issue:

<img width="454" alt="screen shot 2017-03-03 at 3 04 20 pm" src="https://cloud.githubusercontent.com/assets/563/23573506/c8ee15b4-0022-11e7-9dc1-4712a070cb49.png">

I'm not sure if this has been fixed since the deployment of this version of MetacatUI but I thought I'd point it out!

**Comment by laurenwalker** [comment]
I just tested this in all themes and it seems to be fixed already.

<img width="468" alt="screen shot 2017-12-01 at 1 42 17 pm" src="https://user-images.githubusercontent.com/6643222/33498006-e6288ea0-d69d-11e7-9a2f-42cfcf527d97.png">
