### ISSUE TITLE
Add support for bibliographic import tools 

### ISSUE THREAD

**Issue by amoeba** [NCEAS/metacatui#491]
@mbjones mentioned today that, at some point in the past, bibliography importing tools such as the one built into Zotero were able to pick up basic bibliography from our dataset landing pages. I'm not sure when or why this broke but I was just able to confirm that it doesn't work with Zotero or Mendeley's Chrome extensions. I think that getting this implemented would (1) not be a lot of work and (2) aid us in our mission to treat datasets in DataONE as first-class, citable resources.

After a bit of research into how these integrations work, it appears to be a total mess as to *how* to do this but it appears very doable. I quickly found some helpful links:

- https://www.zotero.org/support/dev/exposing_metadata
  They support:
  - Embedded Metadata (`<meta>` tags): Dublin Core and Google/Highwire
  - COinS
  - unAPI
- https://scholar.google.com/intl/en/scholar/inclusion.html#indexing
  - Highwire
  - Eprints
  - BE press
  - PRISM
  - Dublin Core, though they note:
  > Use Dublin Core tags (e.g., DC.title) as a last resort - they work poorly for journal papers because Dublin Core doesn't have unambiguous fields for journal title, volume, issue, and page numbers.
- I found the source code for what appears to be Zotero's implementation:
 https://github.com/zotero/translators/blob/b76abc351e5d6c88f09b8159b532cb4415700458/Embedded%20Metadata.js#L40
- https://webmasters.stackexchange.com/questions/11613/indexing-for-google-scholar-which-tags-to-use
- http://web.archive.org/web/20160408141640/https://www.mendeley.com/import/information-for-publishers/

  From Mendeley:
  > There are 4 supported "standards" for describing articles in the META elements, listed in the order of usage preference:
  > - Highwire Press tags (citation_*)
  > - Eprints tags (eprints.*)
  > - PRISM tags (prism.*)
  > - Dublin Core (dc.*/dcterms.*)

It looks like Highwire Press tags are a pretty well-supported standard so maybe they'd be a good start?

To implement this, we should resolve some questions:

1. Can the systems that support these standards pull the information from a client-side webapp?
2. Where would we get the information and what information would we expose?
3. Which standard would we use? Highwire?

I think checking (1) should be pretty easy and would be good to check first as it'd be a dealbreaker if it didn't pan out.

**Comment by amoeba** [comment]
Tested this out real quick with Zotero and Mendeley's import tools and it works to dynamically inject the `meta` tags into the `head` tag. So (1) resolved.

**Comment by amoeba** [comment]
Talked on call today with @mbjones. Decided it would be great to ship this with the router refactor and json-ld injection features.

**Comment by amoeba** [comment]
So I tinkered with this today. Looking across various tools, it seems like Highwire Press (e.g., `<meta name="citation...`) style tags are the way to go. Mendeley, Zotero, and other tools support extracting them. I found the Mendeley importers for common web browsers worked better overall and some of the implementations of Zotero's plugins to be finicky with respect to this. It looks like Zotero's support for grabbing Highwire Press tags doesn't always work when the tags are dynamically injected (as we have to do here) whereas Meneley's browser extensions seem fine with it.

This was committed on 93a759ed81b43f2ee4f3d8c11c2c57720035b05f and is ready for review.

**Comment by amoeba** [comment]
PR'd as #709

**Comment by amoeba** [comment]
Still waiting on a +1 but this is essentially GTG.

**Comment by laurenwalker** [comment]
I approved the PR, so I'll close this issue

**Comment by amoeba** [comment]
Thanks @laurenwalker I appreciate the second look!

**Comment by laurenwalker** [comment]
@amoeba  - Could you list all the known bibliographic tools that are now supported by MetacatUI? Is it just Zotero, Mendeley, and Highwire Press, or are there others?

**Comment by amoeba** [comment]
I only tested Mendeley and Zotero and not on all browsers so what's supported is more of a theory for the time being. Mendeley's Chrome extension is a 👍 , Zotero's bookmarklet-based importer is a 👍 but their extensions are a 👎 . AFAIK this isn't to do with which bibliographic metadata standards they extract but that we inject the metadata dynamically on the client side rather than on the server.

Are you looking for release notes details? I think I'd write:

> MetacatUI now speaks Highwire Press! From dataset landing pages, you should be able to use some web-based reference importers, notably Mendeley's extensions and Zotero's importer bookmarklet, to automatically import relevant dataset citations details into those reference managers.

Optional addon:

> This paves the way for Google Scholar, if they ever decided to start indexing datasets, to include DataONE datasets.

**Comment by laurenwalker** [comment]
Yes, this is for the release notes. Thanks, I will add these details.
