### ISSUE TITLE
Methods for otherEntity does not display on ADC

### ISSUE THREAD

**Issue by isteves** [NCEAS/metacatui#497]
According to the eml-entity tree (https://github.com/NCEAS/eml/blob/master/eml-entity.png), it's possible to add a methods section to an otherEntity.  I tried it on the following package (currently still private): https://arcticdata.io/catalog/#view/urn:uuid:8e763b18-e0f9-492e-8797-aef320d2c56c
The EML validates, but the methods don't display.

In particular, I want to include example use for a python script in the package:

```
Example of use:
from Read_PMGeosChem import Read_PMGeosChem_Data
from Read_PMGeosChem import CLASSH
LIN, COL, PZE, RAD, TAU, TempTop, LWP, Mask, Num, Pres, MDUST, MTOT, Q850, SP, STAB, NIce, NLiq, CO_Concentration, ReLiq, ReIce, T700, T1000 = Read_PMGeosChem_Data('./DATA_SAVED_PM_GEOSChem.p', CLASSH)
```

**Comment by amoeba** [comment]
Hey @isteves thanks for the bug report. This is another one of those https://github.com/NCEAS/metacat issues. Would you please file over there?

I looked at your EML and it looks good and that's definitely a good place to put that information. In cases like these, I favor doing the best job with the EML and I don't worry about whether it displays right.
