### ISSUE TITLE
Create a pricing page in the KNB theme

### ISSUE THREAD

**Issue by csjx** [NCEAS/metacatui#498]
We have had many pricing question on large contributions. Create a pricing page, and add it into the top menu.  Matt's comment was $2500/TB with possibilities of prorating for less than a TB, and our current "free" storage is 5GB, which may need some review.

**Comment by taojing2002** [comment]
Another question is how we enforce the price. So far we don't have any 
mechanism to control this.

**Comment by mbjones** [comment]
I have purposely omitted the price from our pages because we have not yet gotten policy approval from ucsb.  And yes, we don't have an enforcement mechanism either, but I think that is not a big deal quite yet.

**Comment by laurenwalker** [comment]
We're currently working on this for DataONE paid features, so I'll close this issue
