### ISSUE TITLE
UX Testing of Editor

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/metacatui#50]
We need to have some people test the new Editor, starting with the Overview, Dates, People, and Taxa sections. The Arctic Data Center data team would be the best group to test the new Editor.

**Comment by amoeba** [comment]
@laurenwalker sent out an email yesterday to Jesse, Jeanette, and Matt generally inviting them to test so that's 👍 .

Given how busy everyone is, some prodding may be necessary so I'll put that on my calendar for Wednesday.

**Comment by csjx** [comment]
An aspect we need to focus on here is testing on Windows with both IE 11 and Edge. Let's discuss.

**Comment by laurenwalker** [comment]
Closing this issue for now since Bryce, Chris, and I are currently testing the editor and will be collecting more UX feedback starting next week when the Editor is internally deployed to Arctic Data Center in beta mode.

**Comment by laurenwalker** [comment]
Created a new ticket for cross-browser testing: #196
