### ISSUE TITLE
Downloads graph at arcticdata.io/catalog/#profile appears cropped

### ISSUE THREAD

**Issue by jagoldstein** [NCEAS/metacatui#500]
The "Downloads" graph at https://arcticdata.io/catalog/#profile (which shows all downloads over time, by month sine July 2012) appears to be cutoff after January 2017. The screenshot shown below was taken of only the right edge of the image:

<img width="133" alt="screen shot 2018-02-27 at 12 04 18 pm" src="https://user-images.githubusercontent.com/18270215/36752207-348fc3a2-1bb7-11e8-9ba4-0104058feebb.png">

**Comment by vlraymond** [comment]
Seeing this behavior continuing with bar for March 2018
<img width="1102" alt="screen shot 2018-03-20 at 3 48 49 pm" src="https://user-images.githubusercontent.com/7627276/37687265-19aaeed4-2c58-11e8-8a13-9eb729e7fdf3.png">

**Comment by laurenwalker** [comment]
We're replacing these charts with the newer interactive/zoomable charts
