### ISSUE TITLE
Creator field in Search sidebar queries the wrong Solr field

### ISSUE THREAD

**Issue by amoeba** [NCEAS/metacatui#501]
We've already talked about this in Slack and @laurenwalker is aware but I thought I'd file a ticket for the sake of tracking this.

I wrote:

> Hey lauren, chris: I just noticed that the Creator search box searches the `originText` Solr field. By default, what I type in there gets wrapped in `*`, e.g., `Ricketts` => `*Ricketts*`. Looking at the schema for the `originText` field, it looks like it's a `text_general` field. On a hunch, I removed the surrounding `*` and the search came back as expected. Are the * not needed and do they actually get in the way?
https://arcticdata.io/metacat/d1/mn/v2/query/solr/?q=originText:*Ricketts*
https://arcticdata.io/metacat/d1/mn/v2/query/solr/?q=originText:Ricketts

We decided that this is a bug and should be fixed.

**Comment by laurenwalker** [comment]
Fixed in b3397ba7953ffdeabf24237824d63a2f4891efc2

**Comment by amoeba** [comment]
Thanks @laurenwalker !
