### ISSUE TITLE
Selecting more than one file in the prov editor doesn't Save correctly

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/metacatui#502]
1. I clicked the "Add" button in an empty Source prov chart. 
2. I selected two files and clicked "Done." 
3. The prov charts were re-rendered correctly, showing two wasDerivedFrom relationships.
4. I clicked the "Submit" button and the package was saved. 
5. When I view the RDF XML for the updated resource map, I see only one prov:wasDerivedFrom relationship instead of two. 
6. When I refresh the #view MetadataView, the prov charts are incorrect, because they only are rendering one prov:wasDerivedFrom relationship instead of two.

This happened in Safari 11 and Chrome.

**Comment by gothub** [comment]
Fixed in commit 24395fceb3d2959a76cc11216cd63bf62c790b88
