### ISSUE TITLE
Top navbar not disabled in editor when editing (as opposed to creating) a dataset

### ISSUE THREAD

**Issue by maier-m** [NCEAS/metacatui#508]
When creating a dataset, navigating away from the editor is disabled or gives warnings... when editing an already created dataset, this is not so.

**Comment by laurenwalker** [comment]
The only time the confirmation message wasn't displaying was when clicking the Submit Data button. The window.onBeforeUnload event was not fired in those cases. So the router now handles the display of the confirmation message before rerouting to the Editor view.
