### ISSUE TITLE
[handy-owl] Submit Page not working.

### ISSUE THREAD

**Issue by rushirajnenuji** [NCEAS/metacatui#513]
- Submit not working.
    - All the pages such as `Overview`, `People`, `Dates`, `Location`, `Taxa`, `Methods`, - not working. It takes the user to the homePage.
        - Reason : The server config is such that it removes the # from the link. In this case it is part of the page (the id). And all the unknown links are redirected to the `index.html`.
    - Also the `submit` button does not work.

**Comment by amoeba** [comment]
Closing as we've made a lot of progress on this and many other URL fixes. These are all working for me now.
