### ISSUE TITLE
Possible CSS issue in dataone theme

### ISSUE THREAD

**Issue by amoeba** [NCEAS/metacatui#516]
Can anyone reproduce this? I just checked out the latest `dev-2.0` branch, switched to the `dataone` theme and I'm seeing this odd display:

<img width="384" alt="screen shot 2018-03-07 at 11 55 42 am" src="https://user-images.githubusercontent.com/563/37117783-a870d2c8-21fe-11e8-96ed-8102c4ef596a.png">

The behavior on search.dataone.org, and my usual experience, is that there is a max-width and auto margin on the container element so there's a nice amount of padding around it:

<img width="241" alt="screen shot 2018-03-07 at 11 57 23 am" src="https://user-images.githubusercontent.com/563/37117823-cb830308-21fe-11e8-95cd-0d5f21f511fc.png">

I see in the git history some changes have been made that might be related to this, such as 437fefb5.

**Comment by laurenwalker** [comment]
This does not seem to be an issue anymore
