### ISSUE TITLE
Title is not editable in IE 11 on Windows 10

### ISSUE THREAD

**Issue by csjx** [NCEAS/metacatui#52]
Clicking on the title doesn't make the field editable, although on `hover` the cursor changes to a `pointer`. Assigning to @amoeba since he's most familiar with this section.

refs https://github.com/NCEAS/metacatui/issues/6

**Comment by amoeba** [comment]
IE11 (maybe IE10 too) doesn't support the `contenteditable` attribute on a single `td` but it does support wrapping the entire table in a contenteditablen div, which propagates down to the `contenteditable` attributes on all `td`s.

**Comment by amoeba** [comment]
Put up a pen with a "working" IE 11 solution and how it behaves (Chrome and IE11 display this one the same): http://codepen.io/anon/pen/WpEaQR

**Comment by amoeba** [comment]
Alternatively, it looks like putting a div inside the td that is contenteditable works: http://codepen.io/petridish/pen/evEPzM. Shall I test this out a bit more and make the change if it works? See pen: http://codepen.io/petridish/pen/evEPzM

**Comment by csjx** [comment]
Well, all I can say is huh? IE? What are ya doin'??
Anyway, I guess I prefer the `div` inside the `td` if we have to choose, and hopefully that doesn't mess up any event handling in the DOM, but I don't think it will since it's just a child element.

**Comment by amoeba** [comment]
Event handling on the DOM is honkey dory AFAICT.

**Comment by amoeba** [comment]
This looks good and works well for me. We'll find out if there are any more edge cases as we test I suppose but I can't break it now.
