### ISSUE TITLE
If one or more data objects are private, hide the Download All button

### ISSUE THREAD

**Issue by ThomasThelen** [NCEAS/metacatui#522]
When viewing `https://search.dataone.org/#view/knb.92238.1`, I see a number of files referenced in the `Data Table, Image, and Other Data Details` section. In the file listing table, I only see the EML document. This _may_ be on Metacat's side.

When I clicked `Download All`, I received a file named `zip.xml` with contents

```
<?xml version="1.0" encoding="UTF-8"?><error detailCode="1400" errorCode="401" name="NotAuthorized">
    <description>READ not allowed on knb.92232.1</description>
</error>
```

**Comment by laurenwalker** [comment]
It looks like these data objects are all private, so the resource map packaging fails, and the objects rightfully do not appear in the data table.

The UI should not display a Download All button if one or more of the objects are private.

**Comment by laurenwalker** [comment]
Also, Metacat should return a better response than that XML. It should ideally package up all the accessible objects.
