### ISSUE TITLE
Citation isn't rendering correctly in Safari on Mac

### ISSUE THREAD

**Issue by csjx** [NCEAS/metacatui#53]
For Safari 10.0.3 on OS X El Capitan 10.11.6, the Citation section isn't rendering the title correctly.

See attached screenshot.

![citation-broken](https://cloud.githubusercontent.com/assets/1437565/23707359/41ec9274-03cf-11e7-9e70-72712357e501.png)

**Comment by laurenwalker** [comment]
This seems to be the same issue we were looking at today (where the author name is "htt"). I wonder if this is fixed with my latest commit.

**Comment by amoeba** [comment]
Looking good to me. Wanna close and re-open if it crops up again?

**Comment by laurenwalker** [comment]
Sounds good
