### ISSUE TITLE
Publish DOI includes old metadata PID in new resource map

### ISSUE THREAD

**Issue by jeanetteclark** [NCEAS/metacatui#530]
I used the "Publish with a DOI" button on this dataset: https://knb.ecoinformatics.org/knb/d1/mn/v2/meta/urn:uuid:dcd79c6d-62a0-4076-84e7-e72492185fc1, and the result (https://knb.ecoinformatics.org/#view/doi:10.5063/F1RX997V) shows two metadata records.

from Peter: it looks like  metadata pid `urn:uuid:dcd79c6d-62a0-4076-84e7-e72492185fc1` is obsoleted by `doi:10.5063/F1RX997V` but the old pid is still in the resmap. 

The old resmap seems normal, was created through `arcticdatautils`.

**Comment by laurenwalker** [comment]
Moves this over to the Metacat repo since Metacat performs the updating. https://github.com/NCEAS/metacat/issues/1228

**Comment by amoeba** [comment]
Hey @jeanetteclark thanks for taking the time to write this up. That is indeed really weird behavior and definitely a bug. I'll take a look and update over on https://github.com/NCEAS/metacat/issues/1228
