### ISSUE TITLE
PDF output improvements

### ISSUE THREAD

**Issue by maier-m** [NCEAS/metacatui#531]
Hello,

When users at ADC `Download All`, a METADATA.pdf file is created and downloaded. This pdf file has a tendency to cut off text on the right margin. I am filing this issue on behalf of an ADC PI who was concerned by this behavior. Some of the concern was likely caused by not being familiar with xml files.

<img width="655" alt="screen shot 2018-03-20 at 10 33 00 am" src="https://user-images.githubusercontent.com/16710796/37671959-19ea219a-2c2a-11e8-8430-28b32718b2f4.png">

**Comment by laurenwalker** [comment]
Thanks for filing this ticket. I've moved it over to the Metacat repo: https://github.com/NCEAS/metacat/issues/1229
