### ISSUE TITLE
Methods carryover text

### ISSUE THREAD

**Issue by vchendrix** [NCEAS/metacatui#535]
When submitting multiple records, the text in the methods carries over from the previous submission.

*Browser:* Version 65.0.3325.162 (Official Build) (64-bit)

Steps to Reproduce:

1. Create new dataset
2. Add lots of methods sections
3. Submit Dataset
4. Click to view dataset
5. Click Submit Data
6. View methods of new form.  Should have methods from previous submission

**Comment by mbjones** [comment]
@laurenwalker @csjx Sounds like this may be a serious bug for 2.0.0.  Can you triage it please?

**Comment by vchendrix** [comment]
@laurenwalker @csjx From our users: to reproduce you don't have to add lots of methods sections (Step 2 above). You just need to add one.

**Comment by laurenwalker** [comment]
Hi Val, I haven't been able to reproduce this bug. Can you tell me if this is correct:

- Open up new, blank editor
- Enter metadata, including at least one method step
- Click Submit Dataset
- Upon successful save, click View Your Dataset
- View the metadata and see that the method steps are displayed correctly
- Click Edit
- Go to the Methods section and see the Methods steps form. 

In that last step, my method steps are shown correctly in the editor.

**Comment by vchendrix** [comment]
Matt,

Step 6: instead of "Click Edit" > "Click Submit Data" to create a new
dataset.
