### ISSUE TITLE
Display the "newer version" message on MetadataView before the view finds the newest version pid

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/metacatui#543]
The "newer version is available" message on the MetadataView currently only displays after the view has climbed up the obsolescence chain to find the newest version pid. Since this can take several seconds for long chains, we should display that message as soon as the view knows the metadata doc is obsolete. 

We should indicate that the app is still searching for the pid/link to the newest version. This lets the user know as soon as possible that the page they are viewing is obsolete. 

Message from Jeanette:

> I've had a couple wg members now ask me why there are two versions of the same dataset on the knb, when really they are all part of the same version chain but the banner takes minutes to show up

**Comment by laurenwalker** [comment]
Here is the new look of the "newer version" messages, while loading and then after the newest version is found:

<img width="855" alt="screen shot 2019-02-27 at 3 23 21 pm" src="https://user-images.githubusercontent.com/6643222/53520633-130a4b00-3aa4-11e9-94c0-30fd9b177d93.png">

<img width="855" alt="screen shot 2019-02-27 at 3 23 12 pm" src="https://user-images.githubusercontent.com/6643222/53520634-130a4b00-3aa4-11e9-9d32-f56eb52acda0.png">

**Comment by jagoldstein** [comment]
This is excellent!
