### ISSUE TITLE
Added datafiles do not inherit the permissions of the package

### ISSUE THREAD

**Issue by vchendrix** [NCEAS/metacatui#546]
If a data package has non-default permissions added, then when a user uploads a new data file it does not inherit the permissions of the data package.  It seems like the expected behavior would be for the uploaded data file to inherit the package access policy.

Additionally, if the rights holder is different than the current user then the current user is set as the rightholder of the data file.  However, if the package is  owned (rightsholder) by  a group then this is not optimal. It would be desireable for the original rightsholder to always have access to any data added to the package created by them.  So, either the 

1. rights holder of the package should be the rightsholder of the newly uploaded file
1. the package rights holder should be given access to newly uploaded file

Option 1 above seems cleaner to me.

**Comment by laurenwalker** [comment]
Related to #344. We can add these features once we add the ability to change the permissions of each file using the editor UI.

**Comment by laurenwalker** [comment]
I believe that this has been fixed since this issue was created. The `inheritAccessPolicy` config option needs to be set to true.
