### ISSUE TITLE
Edit attributes UI issue in Firefox

### ISSUE THREAD

**Issue by emilyodean** [NCEAS/metacatui#548]
OSX Firefox 59.0.2. In the attributes editor, click on any of the category selectors to see this behavior. Prevents user from adding additional attributes - same behavior occurs after clicking "Done" and then reopening attribute editor.

![picture1](https://user-images.githubusercontent.com/11021304/38268965-3e7c6224-3734-11e8-8751-31e6e474956f.png)

**Comment by isteves** [comment]
Same with Windows Firefox 58.0.2
