### ISSUE TITLE
Editor Testing: Doubles produced in People and Associated Parties

### ISSUE THREAD

**Issue by sharisochs** [NCEAS/metacatui#551]
Using Safari for Mac. I added Sally MacIntyre as a Co-Principal Investigator and Alicia Cortes as the metadata provider but it ended up showing duplicates of each:

<img width="882" alt="screen shot 2018-04-03 at 12 15 47 pm" src="https://user-images.githubusercontent.com/36999120/38270692-086bed6c-3739-11e8-816d-614dcdc4c559.png">

There are also duplicate roles in the Project Information area:

<img width="885" alt="screen shot 2018-04-03 at 12 18 22 pm" src="https://user-images.githubusercontent.com/36999120/38270747-34ac0010-3739-11e8-94f7-09cfdad1e770.png">

 Not sure where the roles for each person came in or if it is related at all to the other doubles issue.

**Comment by laurenwalker** [comment]
This dataset is: https://test.arcticdata.io/#view/urn:uuid:1f7be5f0-b26c-412f-833a-178425081bc3
