### ISSUE TITLE
Able to submit dataset without funding information

### ISSUE THREAD

**Issue by emilyodean** [NCEAS/metacatui#554]
OSX Firefox 59.0.2. To reproduce, first try submitting with funding information but missing another required piece (title, abstract), then correct title/abstract but remove funding. This seems to be specific to funding and doesn't happen with other fields.

![image](https://user-images.githubusercontent.com/11021304/38275389-939ffbaa-3746-11e8-871b-657cfe0199ba.png)

**Comment by laurenwalker** [comment]
This was fixed already
