### ISSUE TITLE
Editor testing: Windows7 IE11 - problems with sign-in

### ISSUE THREAD

**Issue by isteves** [NCEAS/metacatui#556]
After logging in, my name disappears from the upper right corner (it shows up briefly when loading and then vanishes).  This does not happen on Chrome on the same computer.  In addition, I'm getting redirected to these pages (note the URLs):

![data-sets](https://user-images.githubusercontent.com/25118334/38318546-185bd00c-381f-11e8-9da7-807aab03d3a7.PNG)
![groups](https://user-images.githubusercontent.com/25118334/38318547-187a7ea8-381f-11e8-9b2f-76f254c3a585.PNG)
![profile](https://user-images.githubusercontent.com/25118334/38318548-189d3376-381f-11e8-84c8-c78047a52277.PNG)

I've tried signing out and in again, I still get the same results. Would be curious to see if anyone else had this problem.

**Comment by laurenwalker** [comment]
This seems to be the same error as #504. I think the `my-data` and `s=settings/s=groups` links are not working because you were not successfully logged in. I'll close this issue for now but it's good to know that this is another behavior of failed IE 11 login.
