### ISSUE TITLE
Editor testing: unable to fix attribute errors

### ISSUE THREAD

**Issue by isteves** [NCEAS/metacatui#559]
I ran into some difficult error behavior when I tried (and then decided not to) edit attributes. I did the following sequence of actions:

1. Clicked "Describe" --> "Attributes"
2. Typed something into Attribute Name and then deleted it
3. Pressed Done (without removing the empty attribute that had been created automatically)
4. Clicked "Submit Dataset"

I got this error message: "There was a caught exception during your submission, so the submission was cancelled." But I was also unable to fix the problem because the Describe buttons were grayed out.

I eventually got the Describe buttons to un-gray by changing the title and clicking "Submit," but it wasn't intuitive.  Also, I ended up with "The previous identifier has already been made obsolete by: urn:uuid:a2490416-e31b-4865-be1c-8244858457d8" as I was clicking around trying to fix it.

![attr](https://user-images.githubusercontent.com/25118334/38336211-dd5d4ffc-3815-11e8-9e5a-b4d6bf1777e5.PNG)

_Tested using Microsoft Edge_

**Comment by laurenwalker** [comment]
It sounds like the EML was trying to serialize an empty EMLAttribute model. The EML model should just skip over empty attributes and the view should remove them from the UI.
