### ISSUE TITLE
In Windows: Editor testing: csv file type defaults to "Microsoft Excel"

### ISSUE THREAD

**Issue by isteves** [NCEAS/metacatui#560]
I uploaded a csv through the web editor, and the default file type is "Microsoft Excel" instead of "text/csv."  Doesn't affect the download though, so it's low-priority.

![csv](https://user-images.githubusercontent.com/25118334/38337531-7e5937dc-381a-11e8-886f-a4b1c177428e.PNG)

https://test.arcticdata.io/#view/urn:uuid:d5bb4409-29a0-4520-984d-4742aad67154
_Tested with Microsoft Edge_

**Comment by laurenwalker** [comment]
I tested this on Chrome and the formatId is text/csv so I wonder if this behavior is exclusive to Edge.

**Comment by isteves** [comment]
Also just checked it on Mac Firefox and it was text/csv

**Comment by isteves** [comment]
Just tried Windows 7 Firefox/Chrome and I got the same `Microsoft Excel` file type.

**Comment by laurenwalker** [comment]
This just happened again in Beta using the new editor. This CSV file was given an excel formatId but it has a .csv file extension so should have a format id of text/csv.

https://beta.arcticdata.io/metacat/d1/mn/v2/meta/urn:uuid:a277281e-5797-49b3-8720-cbebb84f6e88

I believe this happened on Windows and Firefox.

**Comment by laurenwalker** [comment]
Fixed in #930
