### ISSUE TITLE
New editor -- units pick list other/none -- to me, not the same!

### ISSUE THREAD

**Issue by brunj7** [NCEAS/metacatui#561]
Hi there,

First I like the new editor; it is really nice!

Regarding the units list for the attribute level metadata:

-  I do not agree that `none` and `other` should be one pick. I would suggest the two to be separated, although `none` might be a little bit confusing with `dimensionless` 
-  I would suggest to add `percentage`.  It is frequent enough to deserve its own pick. For example, in the data I uploaded, the cell values will be like 0.22, but in fact it is really 22%.

Hope it helps!

**Comment by laurenwalker** [comment]
Thanks for the feedback, Julien. The `none/other` option is secretly saved as `dimensionless`, we just put that there as a more understandable wording for those that are unfamiliar with unit names.
