### ISSUE TITLE
Project Titles not displaying properly on ADC when there are more than one

### ISSUE THREAD

**Issue by jagoldstein** [NCEAS/metacatui#565]
[This package](https://arcticdata.io/catalog/#view/urn:uuid:96a40678-aa0f-446e-8f1a-a70a4c2931ac) has this section of the EML:

```
<project>
   <title>Design and Initialization of an Ice-Tethered Profiler Array Contributing to the Arctic Observing System</title>
   <title>Towards an Arctic Observing Network: An array of Ice-Tethered Profilers to sample the upper ocean water properties during the International Polar Year</title>
   <title>AON: Continuation of the Ice-Tethered Profiler contribution to the Arctic Observing Network</title>
   <title>Collaborative Research: An Arctic Ocean Sea Surface pCO2 and pH Observing Network</title>
```

There are 4 different projects, each with a different title and this is valid EML.
However, in the metacatUI metadata view the Project Titles render like so:

<img width="925" alt="screen shot 2018-04-10 at 10 11 15 am" src="https://user-images.githubusercontent.com/18270215/38572297-961fc002-3ca7-11e8-984d-830d220190f6.png">

Note that the first title is repeated 4 times, instead of displaying the other 3 titles.

**Comment by amoeba** [comment]
Hey @jagoldstein thanks for the report. This looks like a bug in the view service (part of Metacat). I took a look at the source code and that does appear to be the case. I'll copy your issue over to https://github.com/NCEAS/metacat/issues and close this.

**Comment by jagoldstein** [comment]
ah, ok, thanks for organizing the issues into the correct repos!
