### ISSUE TITLE
MetadataView display order

### ISSUE THREAD

**Issue by isteves** [NCEAS/metacatui#571]
Particularly for projects with a lot of data objects, some of the metadata content gets "buried" at the bottom of the page.  Re-ordering the sections should be a quick fix for that.  I would ideally like to see this general order (no particular order preference within each section):

Top:
- General

Middle:
- Geographic Region
- Temporal Coverage
- Project Information

End:
- People and Associated Parties
- Data Table, Image, and other Data Details

@jagoldstein

**Comment by laurenwalker** [comment]
In https://github.com/NCEAS/metacat/pull/1568 I have moved the Entity details to the bottom of the page. I'm going to close this ticket since that seems to be the primary focus of the re-ordering needed.
