### ISSUE TITLE
Consider locally referencing jquery-1.9.1.min

### ISSUE THREAD

**Issue by vchendrix** [NCEAS/metacatui#575]
This morning `https://code.jquery.com/jquery-1.9.1.min` is unavailable for a time which made ESS-DIVE available. 

Since [`jquery.1.9.1.min.js`](https://github.com/NCEAS/metacatui/blob/master/src/components/jquery-1.9.1.min.js) is already checked into the metacatui code base I propose referencing it in `app.js` [here](https://github.com/NCEAS/metacatui/blob/403baccb4af080aecc33512c2c2a3962b080582c/src/js/app.js#L37).

**Comment by csjx** [comment]
Hmm, yeah, we used to reference it locally, which seems fine with me. I'm not sure when it changed. But if we do use a web-based version, it should be from a high availability CDN, of which Google runs one with many popular libraries, and there are others.
