### ISSUE TITLE
Add "Expand All" button to the data package table

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/metacatui#58]
After using the Editor a bit, I've found it a bit frustrating to always view the data package table only three rows at a time while carefully scrolling inside the div. (If you scroll too fast, you scroll further down the page). It would be nice to always show an "Expand" link on the bottom, or a draggable edge, to allow the user to view more rows at a time.

**Comment by csjx** [comment]
I've been thinking that a draggable edge would be good, and would work well with a lazy-loading table.  We could probably do both, like clicking on the edge would show the whole table, clicking and dragging it would let the user adjust the div size.

**Comment by laurenwalker** [comment]
I added a resizable edge to the data package container so that the user can drag the bottom edge down to heighten the table container, and drag back up to shorten it.
