### ISSUE TITLE
Widen view service container in MetadataView

### ISSUE THREAD

**Issue by amoeba** [NCEAS/metacatui#582]
We discussed changes I've been making to the display of ISO metadata documents in the view service over in https://redmine.dataone.org/issues/8499 and decided on our dev call today to widen the container for the view service to match the PackageTable. Should be a quick change.

**Comment by amoeba** [comment]
PS: this should be deployed in the same CCI release as the view service changes.

**Comment by amoeba** [comment]
here's a link to the metacat issue https://github.com/NCEAS/metacat/issues/1232 for the view service changes

**Comment by laurenwalker** [comment]
Just a clarification: It looks like the view service container is at the same width as the table for EML documents ([example](https://dev.nceas.ucsb.edu/#view/https://pasta.lternet.edu/package/metadata/eml/knb-lter-arc/10008/7)), so there must be a container element created in the ISO xsl which has padding applied via CSS. 

The container element returned by the EML xsl is `<article class="container" id="Metadata"></article>`

**Comment by amoeba** [comment]
Ooh thanks for looking at that! That'll save me some time.

**Comment by amoeba** [comment]
Looks like this is just caused by search-stage having an old copy of MetacatUI running. A few months ago an explicit:

```css
#Metadata{
	padding-left: 0px;
	padding-right: 0px;
    width: 100%;
}
```

was added to `metacatui-common.css` which widens the view.

**Comment by amoeba** [comment]
Tested this locally against the dev2.0 branch and all looks good.
