### ISSUE TITLE
Prov icons not displaying jpeg thumbnail image

### ISSUE THREAD

**Issue by gothub** [NCEAS/metacatui#585]
After adding a prov relationship for a JPEG image, the prov icon displays the image for a CSV file, not the JPEG image of the object (df35b.266.1.jpg), although the object has the correct 'image/jpg' type:

![screen shot 2018-04-27 at 11 29 20 am](https://user-images.githubusercontent.com/6412946/39379176-5670b900-4a0f-11e8-8ea7-388d613d04e5.png)

This is for dataset https://dev.nceas.ucsb.edu/#view/urn:uuid:c4509792-9ca3-4600-b8ba-1ec64577d42c

BTW, The jpg object was added using the metadata editor, and the original data package was added via the R client.

**Comment by gothub** [comment]
Fixed in commit 894c19ccb832416f8398c8ace09c76a0f1b72e79 (branch: dev_2.0).

I should note that this fix involved modifying `DataONEObject.isData()` and `isImage()`, by now identifying formatId `image/jpg` as an `image` type. I also change the following from being `data` types to `image` types:

```
image/jpeg
image/svg xml
image/svg+xml
image/bmp
```

but am now realizing that this may have been a  bit optimistic, as detailed in browser support for image files [here](https://en.wikipedia.org/wiki/Comparison_of_web_browsers#Image_format_support).

What do you think @laurenwalker? Should we put  `bmp` and `svg*` go back to their old classification?

**Comment by laurenwalker** [comment]
Yeah, we had chosen to exclude svg and bmps as images since they aren't displayed consistently across browsers, so we should remove those from the isImage list

**Comment by gothub** [comment]
@laurenwalker ok, the list is now correct. thx!

Fixed in commit 2101fd658691ecbb873e99b2febcd8cf603e497c
