### ISSUE TITLE
Display MDC usage and citation counts on landing pages

### ISSUE THREAD

**Issue by mbjones** [NCEAS/metacatui#594]
Display usage and citation info on landing page following new mockup designs.  Right now these are total and unique requests and investigations, plus citations.

**Comment by mbjones** [comment]
See mockups here: https://projects.invisionapp.com/share/7MFRHSL6WZT#/278315639_LandingPage

**Comment by laurenwalker** [comment]
The MetadataView should create a Metric model for each metric type and will fetch() each model. When the model has been synced (i.e. the fetch is complete), the MetadataView will create a new MetricView and insert it into the controls area of the MetadataView.

**Comment by rushirajnenuji** [comment]
Update: Working on debugging the working of `Copied CItation Success Message` when the citations text are copied from the clipboard.

**Comment by rushirajnenuji** [comment]
Update: @laurenwalker solved the `copy citation` issue with the commit https://github.com/NCEAS/metacatui/commit/9908c37f028bb2040c1338378677c5ebb285c5dc

**Comment by rushirajnenuji** [comment]
Added the MetricsModel and Metric Views for the metrics in the Metadata view. The metrics display is working for all the themes and querying the metrics-service hosted on `logproc-stage-ucsb-1` server. 
The UI reflects appropriate design decisions made for the MVP.
