### ISSUE TITLE
New editor does not set ORCID iD userId directory in EML

### ISSUE THREAD

**Issue by jagoldstein** [NCEAS/metacatui#596]
Data Team intern Rachel Sun discovered that after adding ORCID iDs with the new editor, the `userId directory` in the EML was not populated correctly.

The EML looks like this 
`<userId directory="unknown">https://orcid.org/0000-0001-5305-8140</userId>`
instead of
`<userId directory="https://orcid.org">https://orcid.org/0000-0001-5305-8140</userId>` 

Note the `userId directory="unknown"` instead of `userId directory="https://orcid.org`.

This leads to an issue in the metacatUI metadata view shown below:
<img width="362" alt="screen shot 2018-05-02 at 4 01 20 pm" src="https://user-images.githubusercontent.com/18270215/39554057-8cab5fa6-4e25-11e8-9dfe-3e53c8f5a670.png">
instead of
<img width="421" alt="screen shot 2018-05-02 at 4 01 48 pm" src="https://user-images.githubusercontent.com/18270215/39554061-959bd56e-4e25-11e8-9316-8a38bb28c7e9.png">

The former (created with new editor) is not a hyperlink as it ought to be.

**Comment by laurenwalker** [comment]
The EMLParty model will now format all usernames that seem to be ORCIDs into the correct `https://orcid.org/xxxx-xxxx-xxxx-xxxx` format. The following usernames would be identified as an ORCID and formatted as such. They would also all get `https://orcid.org` saved as the `userId` `directory`:

https://orcid.org/0000-0003-2192-431X
http://orcid.org/0000-0003-2192-431X
https://www.orcid.org/0000-0003-2192-431X
http://www.orcid.org/0000-0003-2192-431X
www.orcid.org/0000-0003-2192-431X
orcid.org/0000-0003-2192-431X
0000-0003-2192-431X

**Comment by jagoldstein** [comment]
awesome! nice work @laurenwalker 

thanks so much
