### ISSUE TITLE
Create Metric model

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/metacatui#597]
The metric model is going to represent one single metric, such as investigations over all time or investigations in a single month.

**Comment by rushirajnenuji** [comment]
Initially created a single metric model for each type of metric. However, the problem with that was we were having n `fetch()` calls for n metrics. (so in our case 3 fetch() calls for 3 metrics, each fetching the same information!)

In the [meeting](https://hpad.dataone.org/IYJgrAxgHGCcsFoAsB2VywGYBGDsDYBTCBTARkJX2CjIBM6RCg==#june-14-2018) we decided to rename it to `metricsModel` which would handle all n metrics (3 for the MVP) and would do only a single fetch call. 

Solved with https://github.com/NCEAS/metacatui/commit/f1f0cb949c658bdc5bc6de48c7be037ef3163b21
