### ISSUE TITLE
Create Metric view

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/metacatui#598]
This is a single button in the UI that gets inserted into the controls area of the MetadataView. It has a one-to-one relationship with a Metric model.

**Comment by rushirajnenuji** [comment]
Created Metric View which would render the Metric buttons inside the metric well, and use the MetricsModel's fetched information to populate the UI.

Solved with the commits https://github.com/NCEAS/metacatui/commit/92f6c37f618851d46a3874f349c0ce456a7ab3d3 and https://github.com/NCEAS/metacatui/commit/2b652185a79b799768df71ee98e366a090d98145
