### ISSUE TITLE
Create Metric Modal view

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/metacatui#599]
(Name to be determined later)

This view is for a single modal window that contains metric details over time

**Comment by laurenwalker** [comment]
The only thing left here, I think, is to enable the links in the modal footer that go to the previous and next metric type.

**Comment by rushirajnenuji** [comment]
Added CitationList modal and Metrics time series charts for Downloads and Views.

Solved with Robyn's PR: https://github.com/NCEAS/metacatui/pull/755 and https://github.com/NCEAS/metacatui/pull/766
And other commits: https://github.com/NCEAS/metacatui/commit/3b09a714f79de42828eaa93214323588aff2d741 and https://github.com/NCEAS/metacatui/commit/417fdb982629ac7898d35521a7111bd7dd90d0fd
