### ISSUE TITLE
Complete the overview section of the EML

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/metacatui#6]
### Title and abstract
- [x] Update the title in the EML doc during serialize()
- [x] Update the abstract in the EML doc during serialize()
- [x] Focus the title field immediately

### Keywords
- [x] Display a keywords section in the editor form
- [x] Update the keywords in the EML model when the UI is changed
- [x] Update or add the keywords in the EML doc during serialize()

### Alt Ids
- [x] Display a alt ids section in the editor form
- [x] Update the alt ids in the EML model when the UI is changed
- [x] Update or add the alt ids in the EML doc during serialize()

### Usage
- [x] Display a usage section in the editor form
- [x] Update the usage in the EML model when the UI is changed
- [x] Update or add the usage in the EML doc during serialize()

### Award Number
- [x] Display an award number section in the editor form
- [x] Update the award number in the EML model when the UI is changed
- [x] Update or add the award number in the EML doc during serialize()

**Comment by amoeba** [comment]
@csjx mentioned that the Add Metadata use case [1] shows the title being highlighted when the user starts a new EML doc. I'll do that early on today. 

[1] https://github.com/NCEAS/metacatui/blob/master/metacatui/docs/design/editor/use-cases/add-metadata.rst

**Comment by laurenwalker** [comment]
Alt ids section done

**Comment by amoeba** [comment]
Hey, on 'Focus the title field immediately', I wondered what makes the most sense to do. The title 'field' is a `td` with `contenteditable` set to true. If I focus the field when the page loads, the placeholder text is in still there so the users cursor (^) starts at the beginning of

> ^Untitled dataset: Add a descriptive title for your dataset

The tip is useful (perhaps crucial) but if the user starts typing they will just be prepending to the above string or they will be forced to delete it before they start. What if (for new docs only), there was no content there but there was also a tooltip providing instruction. The tooltip could disappear when the user enters something.

Something (way less crappy than):

![asdf](https://cloud.githubusercontent.com/assets/563/22358319/90db7abc-e3ea-11e6-906b-b9d3820d86be.png)

**Comment by amoeba** [comment]
Oh yeah.. An alternative is to just use an `input` element instead with the HTML5 `placeholder` attribute.

**Comment by mbjones** [comment]
That's really awkward if the help text is actually in the field.  If you use the HTML5 input with a `placeholder` attribute, then the help text doesn't interfere with data entry.  Much cleaner.

**Comment by laurenwalker** [comment]
It doesn't look as nice as the content-editable table cells, but I vote we just put in input elements with the placeholder text.

**Comment by amoeba** [comment]
I'll give it a shot and we can play around with it. Thanks.

**Comment by amoeba** [comment]
Okay, I implemented that and it now looks like this:

![screen shot 2017-01-27 at 12 25 34 pm](https://cloud.githubusercontent.com/assets/563/22388200/cb39f3b8-e48b-11e6-9525-1f2df257d509.png)

Events are hooked up to the new element and the underlying model is updated on change (when appropriate). I'll make it auto-focus when a new document is loaded in the editor.

**Comment by csjx** [comment]
Hey all - So, I'm not a fan of the always-on input field.  When I mocked this up, I intended it to be either a content-editable `td` or switch to an `input` on focus.  Also, WRT the `focus()` text awkwardness, I actually had planned to not only `focus()` the field but also `select()` the text content so that the user needs to delete the placeholder or edit it.  So, I vote we try that route, and if it doesn't work, at least hide the input field when not in focus. I have seen some SO issues regarding browser impl for the `.focus().select()` calls, so we may need to figure out what's best. See:

http://stackoverflow.com/questions/480735/select-all-contents-of-textbox-when-it-receives-focus-javascript-or-jquery
http://stackoverflow.com/questions/6470123/select-text-on-focus

**Comment by amoeba** [comment]
Sound reasonable to me. I should be able to revert my changes and add the auto-select functionality.

**Comment by amoeba** [comment]
I reverted those changes but haven't cracked the selecting-all-the-text part of that. So that's a TODO. I added it as a checklist item.

**Comment by csjx** [comment]
I suggest we punt on the "Select the title text immediately" feature.  I see that the JQuery `select()` function is limited to `input` and `textarea` elements, and I'd rather stick with the contenteditable `td` for now.  I think calling `focus()` suffices.

**Comment by laurenwalker** [comment]
The overview section is now complete. 🎉

Each field in the overview section, including the title, can now be parsed, displayed, edited, and serialized. If there are any issues, let's create a new ticket for the individual bug.

I agree with punting on punting the "Select the title text immediately" feature.
