### ISSUE TITLE
Silent removal of custom units

### ISSUE THREAD

**Issue by maier-m** [NCEAS/metacatui#607]
Editing a metadata with custom units will **silently** remove the custom units from the unit metadata and replace with `dimensionless`

**Comment by laurenwalker** [comment]
This is a critical bug. We certainly don't want to remove metadata. Do you have an example dataset where this happened?

**Comment by maier-m** [comment]
See attribute `Intensity` in  https://test.arcticdata.io/#view/resource_map_urn:uuid:0c790b89-8452-4f9f-a17d-1ef4548aa02c  and its subsequent `newer version`. All that was changed was the title.

**Comment by laurenwalker** [comment]
@maier-m - Thanks Mitchell, I'll look into fixing this soon
