### ISSUE TITLE
typo in Geographic Region "Bounding Coordinates" in metacatUI metadata view

### ISSUE THREAD

**Issue by jagoldstein** [NCEAS/metacatui#608]
Some packages we replicated from LTER to the ADC display an elevation or "altitude" along with the `boundingCoordinates` under `gepographicCoverage`.

While the version on LTER does not use these terms, the ADC displays this elevation metadata next to "Mimimum Altitude" and "Maximum Altitude".

Note the typo in "Miminum" here https://arcticdata.io/catalog/#view/https://pasta.lternet.edu/package/metadata/eml/knb-lter-arc/20047/1.

<img width="516" alt="screen shot 2018-05-07 at 1 09 13 pm" src="https://user-images.githubusercontent.com/18270215/39722816-a8d37d04-51f8-11e8-984c-2fa7235a5771.png">

It should be "Minimum".

**Comment by amoeba** [comment]
Thanks for the report. This is another one of those things that's a Metacat bug, not MetacatUI. I [fixed the typo](https://github.com/NCEAS/metacat/issues/1244) just now and you should see the change reflected sometime in the future. I think I fixed this in the past but it musta got un-fixed.

Good find, and please keep reporting here or there as needed!
