### ISSUE TITLE
Helper text for new editor: change wording for "attribute definition"

### ISSUE THREAD

**Issue by jagoldstein** [NCEAS/metacatui#613]
What it says now:
"Fully explain the context of this attribute in relation to the data file. Be as specific and accurate as possible, so your data can be re-useable by others. This data may be a description that is standard to your domain, or a description that captures your specific research, analysis, or collection methods."

What it ought to say:
"Define this attribute. ~Fully explain the context of this attribute in relation to the data file.~ Be as specific and accurate as possible so your data can be _interpreted and reused_ by others. ~This data may be a description may be that is standard to your domain, or a description that captures your specific research, analysis, or collection methods.~

So, change first sentence. Change words in 2nd sentence from "re-usable" to "interpreted and reused". Remove 3rd sentence.

The example is good and should be retained.

**Comment by mbjones** [comment]
Also, some groups use the term 'attribute' (e.g., geospatial analysts), while others use the term 'variable' (e.g., many ecologists).  Consider wording that would make it clear that attribute and variable are synonymous.

**Comment by maier-m** [comment]
I think we were having confusion over the term `research domain`. `Field of study` or `field of expertise` may be more common phrasing. Also `specific and complete` may be appropriate (hopefully we don't have to encourage accurate data)

```Define this attribute (i.e. variable). Be as specific and complete as possible so this data can be interpreted and reused by other scientists not familiar with your research or field of study.```

**Comment by csjx** [comment]
Yes, I like "complete" better than "accurate" too. Same with "field of study" - that's much more approachable.  The phrase "this data" should be "these data" since "data" is plural, or revert it back to "your data" to avoid the issue.

**Comment by jagoldstein** [comment]
@maier-m While you have some convincing arguments for using the words "data" and "metadata" as singular mass nouns, you did admit that scientific journals would/ should insist these words are used as plurals. Since we are a scientific research center, I contend that we too should stick with the plural forms. Even if just for the sake of consistency. The singular versions may be more suitable for general audiences, but the community we serve is made up of scientists.

(Personally, I prefer the plurals and believe they are more correct, as does NCEAS Director Ben Halpern, but let's try not to debate that any further here please.)
