### ISSUE TITLE
Methods duplication

### ISSUE THREAD

**Issue by maier-m** [NCEAS/metacatui#618]
A dataset (https://beta.arcticdata.io/catalog/#view/urn:uuid:d5e96c25-b3b1-4a1a-9ea8-2977922e2151) was edited in the beta editor. After submitting the edits, the methods were duplicated (https://beta.arcticdata.io/catalog/#view/urn:uuid:ed8244aa-8261-4455-8217-01219c64eba5)

**Comment by laurenwalker** [comment]
This was fixed in #637
