### ISSUE TITLE
Change all Solr query syntax to use the "AND" operator

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/metacatui#619]
Currently, the queries in MetacatUI are constructed with using the space character (or `%20` or `+`) as an 'AND' operator. We need to change this to using the word `AND`, to be compatible with Solr 7 in the future.

**Comment by laurenwalker** [comment]
Dave V found a Solr parameter that could solve this issue. The `q.op` parameter specifies a default query operator. So we could possibly add the `q.op=AND` parameter to each query rather than replace all our spaces with ` AND `s.

Examples:

https://cn.dataone.org/cn/v2/query/solr/?start=0&rows=0&fl=id%2Ctitle%2CformatId&q=title%3Atest%20page&debug=query&q.op=AND

https://cn.dataone.org/cn/v2/query/solr/?start=0&rows=0&fl=id%2Ctitle%2CformatId&q=title%3Atest%20page&debug=query&q.op=OR

**Comment by taojing2002** [comment]
CN has solr 5 and we need to test it at solr 7.3.

**Comment by laurenwalker** [comment]
This is done already
