### ISSUE TITLE
Browser resize causes screen issues (Windows)

### ISSUE THREAD

**Issue by vchendrix** [NCEAS/metacatui#620]
A user of ours (ESS-DIVE) had some issues with resizing the data packge edit form.

She was using Chrome on a PC with Microsoft Windows 10 Enterpris and had zoomed in and out plus resized the window on the laptop (Lenovo Thinkpad).  The text runs under the side navigation.  See image.

![image001](https://user-images.githubusercontent.com/1558129/39894473-d2b23f4c-545b-11e8-9651-1b6ab03bf2a0.jpg)

**Comment by laurenwalker** [comment]
I haven't been able to reproduce this in Windows 10 and Chrome. Added the cannot reproduce label so it can easily be found later and fixed if I see it crop up in the future or we find out more details on when it happens.
