### ISSUE TITLE
Add a test for the MetadataView

### ISSUE THREAD

**Issue by amoeba** [NCEAS/metacatui#645]
Could I get another look at this? I'm struggling to get a basic test for a view (MetadataView) working. What I _actually_ want to test is a completely independent method on the view but it wouldn't be bad to have some basic view tests anyway. What I want to test is the behavior of 

https://github.com/NCEAS/metacatui/blob/c7409f7c96f08b119e541fdd938439ff0dd0c8cd/src/js/views/MetadataView.js#L140

for various possible states of the model backing the view. So if it'd be better to refactor this method so it's easier to write a spec file for it I'm all for that.

What I did that nearly got me there but not quite is:

1. Created a file to hold the MetadataView unit tests, `test/js/specs/views/MetadataView.spec.js`

```js
"use strict";

define(["chai", "chai-jquery", "chai-backbone",
    "../../../../src/js/views/MetadataView"],
    function(chai, chaiJquery, chaiBackbone, MetadataView) {

        // Configure the Chai assertion library
        var should =  chai.should();
        var expect = chai.expect;

        // Pull in Jquery and Backbone-specific assertion libraries
        chai.use(chaiJquery); // exported from chai-jquery.js
        chai.use(chaiBackbone); // exported from chai-backbone.js

        describe("MetadataView Test Suite", function (){
            var view;

            beforeEach(function() {
              view = new MetadataView();
            });

            describe("the view can be constructed", function() {
              it("should exist", function() {
                expect(view).toBeDefined();
              })  
            });
        });
    });

```

2. Changed `runner.spec.js`:

```patch
--- a/test/js/specs/runner.spec.js
+++ b/test/js/specs/runner.spec.js
@@ -10,6 +10,7 @@ require.config({
     paths: {
         // Pull common libs from the app components library
         "jquery": "../src/components/jquery-1.9.1.min",
+        "jqueryui": "../src/components/jquery-ui.min",
         "underscore": "../src/components/underscore-min",
         "backbone": "../src/components/backbone",
         "mocha": "./js/mocha",
@@ -19,6 +20,11 @@ require.config({
         "uuid": "../src/components/uuid",
         "md5": "../src/components/md5",
         "x2js": "../src/components/xml2json",
+        "rdflib": "../src/components/rdflib",
+        "annotator": "../src/components/annotator/v1.2.10/annotator-full.min",
+        "bioportal": "../src/components/bioportal/jquery.ncbo.tree-2.0.2",
+        "fancybox": "../src/components/fancybox/jquery.fancybox",
+        "clipboard": "../src/components/clipboard.min",
         // The paths to the app components
         "models": "../src/js/models",
         "collections": "../src/js/collections",
@@ -50,7 +56,8 @@ define(["require", "mocha"], function(require, mocha) {
             "js/specs/models/metadata/eml211/EMLNonNumericDomain.spec",
             "js/specs/models/metadata/eml211/EMLNumericDomain.spec",
             "js/specs/models/metadata/eml211/EMLDateTimeDomain.spec",
-            "js/specs/models/metadata/eml211/EMLTemporalCoverage.spec"
+            "js/specs/models/metadata/eml211/EMLTemporalCoverage.spec",
+            "js/specs/views/MetadataView.spec"
         ];

         // Include model and view tests
```

3. And then when I run the tests (by opening `./test/index.html`) and was greeted by a blank page with the following JS errors in the Console:

```
require.js:163 Uncaught Error: Script error for: gmaps
http://requirejs.org/docs/errors.html#scripterror
    at makeError (require.js:163)
    at HTMLScriptElement.onScriptError (require.js:1666)
...
NodeModel.js:15 Uncaught ReferenceError: MetacatUI is not defined
    at NodeModel.js:15
    at Object.execCb (require.js:1635)
    at Module.check (require.js:871)
    at Module.enable (require.js:1142)
    at Module.init (require.js:779)
    at callGetModule (require.js:1169)
    at Object.completeLoad (require.js:1529)
    at HTMLScriptElement.onScriptLoad (require.js:1656)
...
require.js:163 Uncaught Error: Script error for: text
http://requirejs.org/docs/errors.html#scripterror
    at makeError (require.js:163)
    at HTMLScriptElement.onScriptError (require.js:1666)
```

I don't have a good handle for how `require.js` really works but I see that `app.js` defines `MetacatUI` and `gmaps`. Not sure where `text` comes from just yet. It makes sense that this view test needs to instantiate the global `MetacatUI` object first.

Any and all help appreciated!

**Comment by laurenwalker** [comment]
Chris started work on the [`support-full-app-tests`](https://github.com/NCEAS/metacatui/tree/support-full-app-tests) branch to fix this same issue. Since your JSON-LD work is so close to merging into the `dev` branch I hesitate to suggest that you merge from that branch since it's a total refactor of the way the app is initialized. 🤔

**Comment by amoeba** [comment]
Oh nice! I'm glad I filed an Issue. The JSONLD work is [pretty self-contained](https://github.com/NCEAS/metacatui/compare/dev-2.0...feature-jsonld) so I could just wait until that stuff is wrapped up and we could add a proper test later. How does it sound if I just close this and add a separate issue to write a proper test later. In the mean time I'll just test what I was going to test in the repl.

**Comment by laurenwalker** [comment]
Sounds good, thanks Bryce!
