### ISSUE TITLE
If the DataONE accounts/pendingmap request fails for an ORCID, try to find the account with other ORCID formatting

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/metacatui#651]
We recently had someone try to link their older account to their ORCID account by inputting their ORCID in the text input as '0000-0000-0000-0000". The request failed because the account username has the ORCID formatted as `http://orcid.org/0000-0000-0000-000`. An error message was displayed to the user.

What we should really do is try to find the ORCID account with various ORCID formats before displaying an error message to the user. 

Also, the error message received from LDAP could be translated to be more understandable. The error message of ```[LDAP: error code 32 - No Such Object]``` is really difficult to understand. It should instead say something like, `The username {username} does not exist in our system. Please check that your username is spelled correctly and that you have logged into your account at least once on the {repo name}.`

**Comment by mbjones** [comment]
In our discussions with @csjx on modifying the account support for ORCIDs, we discussed making all forms of ORCIDs equivalentIdentities automatically without a specific user request to do so, so that when logins switch from http to https, the old http identities in access rules will still be valid.

**Comment by laurenwalker** [comment]
Until that work is complete, I went ahead and added a stopgap where we reformat ORCIDs on the user's behalf when they have used an incorrect format.
