### ISSUE TITLE
When an account mapping request has already been sent, display a better message

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/metacatui#652]
This is the message that is displayed when you try to map your accounts after there is already a pending map request:

![image](https://user-images.githubusercontent.com/6643222/41359119-cad520a8-6ef7-11e8-98ff-5cb30f3395f7.png)

There isn't truly an error, so it shouldn't be styled with the red font color and background color. It should be more informational. It should tell the user that they need to log into their other account and approve the request. We could even display a Sign Out button right there.

**Comment by mbjones** [comment]
All true, but I should also note that, when I log both of these accounts, neither shows a map request pending, so there is no way to approve it in the UI.  That is the crux of the problem.  I tried re-requesting the map to see if I could get it to show up in either account, and that is what produced the message above.

**Comment by laurenwalker** [comment]
I improved the error message and fixed the bug preventing pending requests from displaying.
