### ISSUE TITLE
Beta editor setting "submitter" as contact instead of "creator"

### ISSUE THREAD

**Issue by jagoldstein** [NCEAS/metacatui#680]
I submitted through Beta, setting Noelle Selin (https://orcid.org/0000-0002-6396-5622) as `creator`.

"The editor messaging claims "If a contact is not provided, the first editor's information will be used as for the contact."
<img width="593" alt="screen shot 2018-06-25 at 12 52 11 pm" src="https://user-images.githubusercontent.com/18270215/41872593-33a7acd0-7877-11e8-988e-3c69f2443c65.png">

This is not what happens. Instead the `submitter`'s info is used as the "contact".

Either the person set as default "contact" in these cases needs to be changed to the first `creator`, or the messaging needs to be updated.

**Comment by jagoldstein** [comment]
example:
https://arcticdata.io/catalog/#view/urn:uuid:3fb7bfde-b63d-4a64-b814-79b4bcd02d58

**Comment by laurenwalker** [comment]
The behavior of this part of the editor was changed a while ago. To simplify things, the first creator and contact are now automatically filled in with the submitter info.

<img width="885" alt="Screen Shot 2019-03-19 at 12 05 47 PM" src="https://user-images.githubusercontent.com/6643222/54622132-689c9c80-4a3f-11e9-9d72-d4d62af2662b.png">
