### ISSUE TITLE
Check for write permission on the resource map when the editor loads

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/metacatui#682]
Sometimes the metadata doc will have different permissions than the resource map, so we need to check explicitly.

**Comment by laurenwalker** [comment]
Related to #1392

**Comment by laurenwalker** [comment]
Looking at this again, I'm not sure we need to check for `changePermission` permission since `write` should be sufficient. 

If a user has `write` permission on the package, they should still be able to edit a package and it's contents. But they shouldn't have access to the access policy editor.

This will become more important once the AccessPolicyView is added to the editor and users start giving people `write` permission but not total "ownership" (`changePermission`).

**Comment by robyngit** [comment]
This works now, except that I think we also need to hide the Edit button in the MetadataView when a user does not have `write` permission on the resource map. I'll work on that next.

In the editor, I also switched from checking for `changePermission` to checking for `write` permission for the metadata doc, but I can revert that part if this doesn't make sense.

 > If a user has write permission on the package, they should still be able to edit a package and it's contents. But they shouldn't have access to the access policy editor.
> This will become more important once the AccessPolicyView is added to the editor and users start giving people write permission but not total "ownership" (changePermission).

Related to: https://github.com/NCEAS/metacatui/issues/1232
