### ISSUE TITLE
EML Text not correctly rendering eml tags and special characters

### ISSUE THREAD

**Issue by vchendrix** [NCEAS/metacatui#685]
- **MetacatUI:** 2.0.0-rc14
- **Metacat:** 2.8.7

We are testing MetacatUI 2.0.0-rc14 and found that special characters in  EMLText is not rendering EML text tags correctly.  
 * Single quotes become `&apos;`.  
 * `ulink` is not being rendered as a link but being treated literally.

## Title Field
Noticed that  Single quotes become `&apos;` after saving the data package
<img width="595" alt="screen_shot_2018-06-29_at_9_08_33_am" src="https://user-images.githubusercontent.com/1558129/42103260-61baf1dc-7b7d-11e8-9e5d-65c49fda890e.png">

## Abstract field
Notice that the link is not rendered for the second image.

### MetacatUI 2.0.0-rc13
<img width="931" alt="screen shot 2018-06-29 at 9 13 30 am" src="https://user-images.githubusercontent.com/1558129/42103257-61747838-7b7d-11e8-96b5-17b22d363263.png">

### MetacatUI 2.0.0-rc14
<img width="985" alt="screen shot 2018-06-29 at 9 12 36 am" src="https://user-images.githubusercontent.com/1558129/42103258-6198a8de-7b7d-11e8-8583-d14d2f4ec4f0.png">

**Comment by laurenwalker** [comment]
Thanks Val, I will take a look at this.

**Comment by vchendrix** [comment]
BTW we are currently overriding `EML211.cleanXMLText` to not escape html characters

This line has been removed
```javascript

              textString = textString.replace(/&(?!(?:apos|quot|[gl]t|amp);)/g, '&amp;')
                                     .replace(/</g, '&lt;')
                                     .replace(/>/g, '&gt;')
                                     .replace(/"/g, '&quot;')
                                     .replace(/'/g, '&apos;');
```

**Comment by laurenwalker** [comment]
Thanks Val, this is something that I am planning on fixing ASAP.
