### ISSUE TITLE
Fix double-flash when navigating from Quality report back to MetadataView

### ISSUE THREAD

**Issue by amoeba** [NCEAS/metacatui#703]
Steps to repro:

- Go to a dataset landing page
- Click quality report button
- Use your back button in the browser

Observe the quality report page flashes before you're returned.

![kapture 2018-07-18 at 16 57 52](https://user-images.githubusercontent.com/563/42915338-d521ca0a-8aab-11e8-803a-1e3df011ed18.gif)

**Comment by laurenwalker** [comment]
Moving this to a later milestone since we need to get 2.1.0 out in the next 3 days

**Comment by amoeba** [comment]
👍

**Comment by laurenwalker** [comment]
Now that quality reports are generated when objects are first created, this loading icon doesn't display anymore and this issue is fixed.
