### ISSUE TITLE
"Role" field is duplicated in MetacatUI metadata view under "Project Information"

### ISSUE THREAD

**Issue by jagoldstein** [NCEAS/metacatui#705]
Within the `project` section of EML, the `role` field display is duplicated in the MetacatUI metadata view on arcticdata.io. 

Here is an example from https://arcticdata.io/catalog/#view/urn:uuid:dfe13582-97e1-4871-9252-319dff614fef:
<img width="701" alt="screen shot 2018-07-20 at 12 29 13 pm" src="https://user-images.githubusercontent.com/18270215/43021574-f9c8fc2a-8c18-11e8-87d5-d3287abce055.png">

**Comment by amoeba** [comment]
Hey @jagoldstein, thanks for the report. Not sure how we never noticed this. It looks isolated to the EML project section though which makes us not seeing it make a bit more sense. This looks like a https://github.com/NCEAS/metacat bug. I've filed it over there and I'll close this one.
