### ISSUE TITLE
Feature request: Support deep linking into metadata landing pages to support citation of data entities directly

### ISSUE THREAD

**Issue by amoeba** [NCEAS/metacatui#708]
This has come up numerous times and has been a common feature request from @mpsaloha.

If you want to link or cite a particular data entity described in your EML, you currently have either:

- Send the person the d1 Object service URI which is opaque and not really a great thing to send someone
- Tell someone to go to the dataset landing page (/view/X) and scroll down to where you want to point them

What if they could just grab a link for the section of the landing page describing their entity? i.e., to send someone a link to data object `D` that is described by EML record `M`, they'd send a link like `/view/M#D`. This is nicely enabled by the routing refactoring work we're doing which makes it a lot easier construct these links. Previously, we would've had to find something to append to `/#view/M` other than a fragment.

A working example of this is deployed on http://neutral-cat.nceas.ucsb.edu/view/urn:uuid:5c34fdde-aad3-4897-ae8c-78d73fbcf42e#urn:uuid:797e230e-c4d6-46cf-9311-4fa4e8d192e5

What do others think? Is this a good idea? Can we push it further?

**Comment by amoeba** [comment]
Example code to implement in 038589ed7c6719f3337bd3affbcabeaf629baeca.

**Comment by mbjones** [comment]
We also have proposed conditionally requiring an if on EML-attributes so that we can deep link for annotations.  I am in the process of writing that up.

**Comment by amoeba** [comment]
Cool 👍

**Comment by laurenwalker** [comment]
I second this notion. We already have a ticket for this: https://github.com/NCEAS/metacatui/issues/83 created last year. I'll close this one since it is a duplicate.

**Comment by amoeba** [comment]
Cool, thanks. Didn't see that Issue.
