### ISSUE TITLE
README.md in dev-2.1 branch was not merged properly

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/metacatui#710]
The README file on the dev-2.1 branch was not merged properly with the dev-2.0/master branch. There are many changes, mainly including installation instructions, in the README on the master branch that need to be present on the dev-2.1 branch

**Comment by amoeba** [comment]
Hrm, I haven't done any merges but I can certainly take a look. 👍

**Comment by laurenwalker** [comment]
I can merge it over if needed, I just wanted to get this filed so we don't forget

**Comment by amoeba** [comment]
I'll give it a go and let you know if I have any trouble.
