### ISSUE TITLE
loader.js is not loaded (404 error) when metacatui is not installed at root

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/metacatui#711]
We cannot assume that metacatui will always be installed at root, so we should removed the leading `/` in index.html for the loader.js src.

**Comment by amoeba** [comment]
I haven't found a way to not have loader.js get loaded by specifying the URL as `/loader.js`. I'll circle around and see if I can find a fancy solution.

**Comment by laurenwalker** [comment]
An absolute path needs to be set with the way the new routing works. This is because when the app is entered from any path other than root, such as `/data`, the `loader.js` file will be incorrectly retrieved from that non-existent directory, e.g. `/data/loader.js`.

**Comment by amoeba** [comment]
So are you good with not trying to find any solution to this and just going ahead with the current approach?

**Comment by laurenwalker** [comment]
I don't think this is a bug to fix anymore. I am able to set the loader.js path to a full URL and it is loaded fine. Or an absolute path starting at root, e.g. /subdir/loader.js. It just can't be a relative path, which makes sense. So yes, I think it is fine as-is. Should just be very clear in documentation.

**Comment by amoeba** [comment]
Great, that makes sense to me. Thanks!
