### ISSUE TITLE
Add new apache configuration details to the installation documentation in README

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/metacatui#712]
The README has some basic installation instructions, which should now include the new Apache config requirements.

**Comment by laurenwalker** [comment]
Any other configuration changes need to be in the instructions there as well, such as the new `MetacatUI.root` property.

**Comment by amoeba** [comment]
Thanks for filing this. I'm already part-way drafting a document outlining this and more but I didn't have an Issue filed for that. 👍

**Comment by amoeba** [comment]
On today's dev call, @rushirajnenuji said he wanted to help out here so I just assigned him. @rushirajnenuji do you still want to do this?

**Comment by amoeba** [comment]
Reminder to myself that Metacat view service XSLTs need to be updated and fixed when this is deployed. AFAIK the only issue is the ORCID images need their paths changed.

**Comment by laurenwalker** [comment]
What is the issue with the ORCID image paths?

**Comment by laurenwalker** [comment]
I like Option 2 (base64 encode the image). I think that is the most fool-proof way to do it.

**Comment by rushirajnenuji** [comment]
Added the routing refactoring documentation to the README.md with the commit https://github.com/NCEAS/metacatui/commit/706a9c9c592d2c2e8e701f294d26ddc60ed06dda

**Comment by amoeba** [comment]
All done, thanks @rushirajnenuji

**Comment by amoeba** [comment]
ORCID image issue fixed in https://github.com/NCEAS/metacat/issues/1272.
