### ISSUE TITLE
Make onclick handler catch control/command clicks

### ISSUE THREAD

**Issue by amoeba** [NCEAS/metacatui#715]
@laurenwalker pointed out that the onclick handler in app.js that is put in to support pushState doesn't let the user control/command click. We decided on today's dev call to catch this if possible.

**Comment by amoeba** [comment]
Looks like the browser-native way this can be done is by looking at the click event object's properties: https://developer.mozilla.org/en-US/docs/Web/Events/click.

Particularly, `metaKey` and `ctrlKey`. On Macs, command-clicking sets `metaKey` to true and I'm thinking that, on Windows, control clicking sets `ctrlKey` to true. Testing now.

**Comment by amoeba** [comment]
After doing some testing on IE11 and Edge, it looks like their way to open a new tab on click is Ctrl+Shift+Click. On the Mac it's Cmd+Click. In the JS events API, Windows' Control is detected by the value of `e.ctrlKey` and the Mac's Command key is detected by theh value of `e.metaKey`. So I think this was @laurenwalker 's (?) idea but just detecting whether some modifier keys are being held down seems simple but effective. My solution is just to return early if either the control or meta keys are being held down and this looks like it's working nicely.

**Comment by amoeba** [comment]
Closed by dfc72f9.

**Comment by laurenwalker** [comment]
Sounds good to me - thanks Bryce!
