### ISSUE TITLE
Check IE11 and Edge against latest dev-2.1 changes (JSONLD, routing)

### ISSUE THREAD

**Issue by amoeba** [NCEAS/metacatui#716]
I'll update this list with check boxes as I go.

| Feature          | IE11 | Edge |
|------------------|------|------|
| Sign in/out      |      | ✅   |
| Stateless entry  | ✅   | ✅   |
| Attribute tabs   | ✅   | ✅   |
| JSON-LD          | ✅   | ✅   |
| Editor           | ✅   | ✅   |
| Metrics          | ✅   | ✅   |
| PROV Editor      |      | ✅    |

Doesn't work:

- [x] Sign in doesn't work?
- [x] Script errors due to IE's JS engine
- [x] ~~On Edge, http://neutral-cat.nceas.ucsb.edu/view/doi:10.5063/F1X63K4V constantly reloads.~~ This affects `master` too.

**Comment by amoeba** [comment]
@laurenwalker mentioned the sign-in issue is likely just the age-old IE11 issue we've seen before. I can't find the issue now, @laurenwalker can you please pull it up and link it here just for ref?

**Comment by laurenwalker** [comment]
The IE 11 + Windows 10 original login issue is here: https://github.com/NCEAS/metacatui/issues/504

**Comment by amoeba** [comment]
👍 thanks @laurenwalker

**Comment by amoeba** [comment]
@laurenwalker looks like you were testing out the editor in IE11. I can only test on Edge due to my login issue. Does it work fine? I took care when refactoring things to make sure the tabs on the sidebar and tabs in the entity editor worked fine.

**Comment by laurenwalker** [comment]
Yep, it was working fine after I fixed a couple of (unrelated) bugs

**Comment by amoeba** [comment]
Odd. Attribute tabs aren't working for me anymore. Unchecking and investigating.

**Comment by amoeba** [comment]
The attributes tabs thing fixed itself once I cleared cache. As usual! All good here.

**Comment by rushirajnenuji** [comment]
Tested the metrics service on Edge - on all the themes, and it is working perfectly fine.
Was just able to test it on DataONE theme on IE, after that IE 11 kept on crashing.

**Comment by amoeba** [comment]
Added PROV editor to the list and it works great on Edge. Can't test on IE11 but Edge is a pretty good test as it is.

**Comment by amoeba** [comment]
Hey @rushirajnenuji what's the crash thing? Is it something we should look into?

**Comment by amoeba** [comment]
This is all set.
