### ISSUE TITLE
Metadata landing page reloads infinitely in Edge

### ISSUE THREAD

**Issue by amoeba** [NCEAS/metacatui#717]
What's going on: When I visit a dataset landing page, Edge infinitely refreshes every 10-20 seconds.

To reproduce:

- Open Edge
- Go to https://search.dataone.org/#view/doi:10.5063/F1X63K4V
- Wait at least 15 seconds
- Observe the page refreshes

OS: Win 10
Browser: Microsoft Edge 42.17134.1.0

I seem to recall something related to logging in / being logged in that could cause a refresh but I haven't look for the cause here just yet.

**Comment by robyngit** [comment]
Couldn't reproduce this on Windows 10 and the latest Edge (v 117), nor on the oldest Chromium-based Edge (v 80).
