### ISSUE TITLE
Testing the features on dev-2.1

### ISSUE THREAD

**Issue by rushirajnenuji** [NCEAS/metacatui#719]
The branch `dev-2.1` consists of the following features combined:
- Routing refactoring.
- Injecting JSON LD to dataset landing page
- Metrics display

So far, @amoeba and I have been testing the bugs on Google Chrome (Version 67.0.3396.99 (Official Build) (64-bit)) and Firefox (61.0.1 (64-bit)) browser on MacOS High Sierra (v 10.13.6).
Here's a list of all the bugs that we've found and fixed so far: [HackPad - Testing MetacatUI `dev-2.1`](https://hpad.dataone.org/AwMwpgHGygtAJseB2WAWAnCARrDBGAQ1wCZgI1gA2bQjAZhOyA==?view)

Some of the testing sub-tasks are:

- [x] Testing MetacatUI on Internet Explorer.
- [ ] Possibly getting some of our arctic data center data team to try these features on `dev-2.1`.

**Comment by rushirajnenuji** [comment]
Same issue as #716

**Comment by amoeba** [comment]
@rushirajnenuji does the metrics display stuff work well in IE11 and Edge? It looks good to me but I think you might have a better feel for whether it works or not.

**Comment by amoeba** [comment]
Closing in favor of #716
