### ISSUE TITLE
Internet explorer - links not working. [dev-2.1]

### ISSUE THREAD

**Issue by rushirajnenuji** [NCEAS/metacatui#720]
Testing MetacatUI on `Internet Explorer (v11.0.10240...)`
With rerference to #719 

Dataset links are not working. Getting error : 

```
SCRIPT445: Object does not support this action.
router.js (224,6)
```

Occured in DataONE theme. Still testing other themes.

**Comment by rushirajnenuji** [comment]
Solved with [Bryce's commit](https://github.com/NCEAS/metacatui/commit/eede23d7d780218b8919d509e11bfcc814c50f2b)

The Dataset landing pages on Data Catalog pages seems to be working right now with this fix. Moving this issue to review.

**Comment by amoeba** [comment]
Hey @rushirajnenuji sorry I didn't see that you added the review label. LGTM
