### ISSUE TITLE
Navbar links in Arctic theme not working

### ISSUE THREAD

**Issue by rushirajnenuji** [NCEAS/metacatui#721]
For all the three themes, the navbar links in Arctic data theme needs to be fixed.
Reference issue #719 

- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

**Comment by amoeba** [comment]
Hey @rushirajnenuji which links? For most of them, it's okay if they don't work locally because they point at links WordPress manages. Like https://arcticdata.io/support/, for example, MetacatUI isn't responsible for that URL.

**Comment by amoeba** [comment]
PS though I did just fix a bad link in the Submit Data button.

**Comment by rushirajnenuji** [comment]
Hey @amoeba - none of the `Support`, `About` and `Community` links are working. And when I add the `<%= MetacatUI.root %>`, it redirects to the /index because of the FallbackRresource directive. 

So, if wordpress would be managing these links, my question is do we still have to add the `MetacatUI.root` to these `href` attributes? - [Navbar.html](https://github.com/NCEAS/metacatui/blob/dev-2.1/src/js/themes/arctic/templates/navbar.html#L17)

Or is this issue good to be closed?

**Comment by laurenwalker** [comment]
Those links are to Wordpress pages, not MetacatUI views, so we don't want to add the MetacatUI.root to their href attributes. If those are the only broken links, this issue can be closed.

**Comment by amoeba** [comment]
HEy @rushirajnenuji thanks for trying to fix those. @laurenwalker is right: Those should be left as-is. When MetacatUI with the Arctic theme is deployed in its proper home (on arcticdata.io), the links will work fine as-is.
