### ISSUE TITLE
Create table of contents sidebar in ProjectView

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/metacatui#728]
The sidebar is on the left here:

<img width="1157" alt="screen shot 2018-08-01 at 5 07 53 pm" src="https://user-images.githubusercontent.com/6643222/43549039-8e451c1a-95ad-11e8-82ab-72d6c3c32694.png">

It corresponds to the various sections of the page on the Home tab, including subsections for the markdown sections. Clicking on a table of contents item will scroll you down to that section of the page.

**Comment by jkibele** [comment]
Superseded by #818
