### ISSUE TITLE
Editor in IE 11 cannot submit dataset due to caught error

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/metacatui#732]
I can edit a dataset, but not submit a new one. Error message screenshot:

<img width="1016" alt="screen shot 2018-08-03 at 2 03 49 pm" src="https://user-images.githubusercontent.com/6643222/43658212-3a50150e-9726-11e8-8b0e-fbe18c5f8796.png">

**Comment by amoeba** [comment]
We see these IE11-specific issues that look like they're related to differences in the JS engine IE11 uses versus Chrome and Firefox. I wonder if there's a linter of some sort that would check some of this stuff, or perhaps another/different polyfill in some of these cases.
