### ISSUE TITLE
IE11 bug: HTTP GET to cn/v2/accounts fails, so the UserModel is never populated with the user info

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/metacatui#733]
The request never gets past the OPTIONS point in the Network tab. The `error` callback is executed. 

This is causing issues with submission, the my-profile, and the my-data views because there is no username pulled from /accounts. (We do get the username from the token but it is reset when the call to /accounts fails)

**Comment by laurenwalker** [comment]
This will never get fixed because Microsoft does not have any plans to fix it. See https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/1282036/

**Comment by laurenwalker** [comment]
I made a fix that causes most of the app to still work when the username and fullname is grabbed from the token. Other parts of the app that show user info, like the user profiles, may not work in IE 11 unless the CN stops asking for client certificates.

**Comment by csjx** [comment]
In theory, the CN shouldn't be asking browser-based clients for client certificates because it is configured with:
```
        SSLVerifyClient none
        <Location "/cn">
            <If " ! ( %{HTTP_USER_AGENT} =~ /(windows|chrome|mozilla|safari|webkit)/i )">
                SSLVerifyClient optional
            </If>
        </Location>
        SSLVerifyDepth 10
```

**Comment by laurenwalker** [comment]
Hmm, I'm not sure why IE is blocking the preflight OPTIONS request, then.
