### ISSUE TITLE
Should I add these KNB dev specific install instructions somewhere?

### ISSUE THREAD

**Issue by jkibele** [NCEAS/metacatui#734]
I'm preparing to contribute to the data portal project so I had to get a local version of metacatui working. With help from @ThomasThelen and @laurenwalker I set it up a bit differently from the readme installation instructions to suit my purposes. I kept track of what I was doing (notes included below). Seems like it could be useful to include these notes somewhere. ...but it might clutter the readme to add them there. Should I put them somewhere as a markdown document? 

# Installing KNB Themed Metacatui with Test Server
I am going to install metacatui and link it to an existing test server so I can work on metacatui development tasks. I'm working on OS X and these instructions are specific to working with the KNB themes.

1. Clone metacatui: `git clone https://github.com/NCEAS/metacatui.git`  **Note**: Don't clone the repo into a directory inside of your `Documents` directory. That directory only has permissions for the owner, so apache won't be able to serve from there. You'll get a 403 error.
2. `git fetch --all`
3. `git checkout the-feature-branch-you-want` (`feature-project-pages` in my case).
4. Edit `metacatui/src/index.html`:
	- make `data-theme="knb"`
	- make `data-metacat-context="knb"`
	- change `data-map-key` to your api key (optional)
5. Configure Apache to serve files from this location by opening `/etc/apache2/httpd.conf` and changing the `DocumentRoot` to your repository path. (`/Users/jkibele/Repos/metacatui` for me). 
6. Start Apache with `sudo apachectl start` (`restart` if you make changes, `stop` when not in use)
7. Changes to `metacatui/src/js/themes/knb/AppModel.js`:
	- set `d1CNBaseURL` to `https://cn-stage-2.test.dataone.org/`.
	- set `baseUrl` to `"https://dev.nceas.ucsb.edu"`

**Comment by ThomasThelen** [comment]
I think we saw the line 
> Set baseUrl to the URL where the remote Metacat is (e.g. https://dev.nceas.ucsb.edu)

in [this readme section](https://github.com/NCEAS/metacatui#step-2-configure-metacatui). Since @jkibele  isn't running metacat locally, I pointed it over to `https://dev.nceas.ucsb.edu`.

**Comment by laurenwalker** [comment]
Thanks for writing up these docs. I will use some of this as an installation option when we write more detailed installation documentation soon. 

I think the only difference is that you were coming at it from a development perspective rather than a user-only perspective. (e.g. we probably don't want to encourage everyone to do a `git clone` unless they are planning on contributing to the code).

**Comment by jkibele** [comment]
Right. I was thinking this would be more for new developers and whatnot rather than for a general audience. ...so the readme probably isn't the best place for it. Maybe even just leave it here and point people to it as needed?

**Comment by laurenwalker** [comment]
Yep, we can just leave it here for now and like I mentioned, we can add it to our future documentation which will be more detailed and developer-oriented.

**Comment by jkibele** [comment]
As an addition to the above, I'm going to put down the following notes on using metacatui with live-server. Specifically, I'm using the live-server extension for MS Visual Studio Code:

# Setting up MetacatUI with live-server:

1. Edit `metacatui/src/index.html`:
	- make `data-theme="knb"`
	- make `data-metacat-context="knb"`
	- change `data-map-key` to your api key (optional)
2. Edit `metacatui/src/loader.js` and change `MetacatUI.root` so that `MetacatUI.root = "/src"`
3. Changes to `metacatui/src/js/themes/knb/AppModel.js`:
	- set `d1CNBaseURL` to `https://cn-stage-2.test.dataone.org/`.
	- set `baseUrl` to `"https://dev.nceas.ucsb.edu"`

Then you can just start live-server from MS Visual Studio Code with `index.html` open. That'll open metacatui in your browser and it will reload whenever you save changes to files.

**Comment by robyngit** [comment]
Can confirm these instructions also work with the atom live-server extension

**Comment by jkibele** [comment]
As a hack to get around the "disappearing #" problem with live-server, you can edit `app.js` and set `pushState` to `false` in the `Backbone.history.start` call on line 245. That probably breaks something (browser back button maybe?), but it works so far for my workflow.

**Comment by csjx** [comment]
Heya @jkibele - Ultimately the `#` is not disappearing - we've changed the client API to use hashtagless-URLs in order support Google indexing of landing page content using the injected JSON-LD. So while your `pushState=false` change will certainly add a `#` back into the URL, it's a bit of a regression.  This feature relies on the server-side configuration equivalent to the Apache `FallbackResource` feature.  It seems like you should be able to configure your live-server to default to serving `index.html` in the way that @amoeba did in his ExpressJS example.

**Comment by jkibele** [comment]
I agree that this is a silly hack and that it seems like I should be able to default to serving `index.html`. I spent a while trying to do that with the Visual Studio Code live-server extension I'm using and @robyngit tried with the Atom live-server thing she's using. We've both struck out so far. I think there probably is a better solution out there somewhere, but this works for the moment (better than retyping the `#` into the address bar). 

I spoke to @robyngit about this, and she asked me to add it to this issue. Several of use who use live-server have been using this issue as a reminder of how to set up our environment. I'll try again at some point to come up with a better solution.

**Comment by laurenwalker** [comment]
With your respective set-ups, @jkibele and @robyngit  are you able to navigate around the app and directly to views without the hash in the URL? i.e. does the app navigation work how it is supposed to?

I think it's important that when we're developing in MetacatUI that we have it installed locally in a way where it is 100% functional. Or a bug is bound to be overlooked.

**Comment by robyngit** [comment]
No, since the hashtagless-URL update, we haven't been able to navigate around the app without manually adding in the hashtag (when using live-server). @jkibele's hack keeps the hashtag in the URL so that we're able to refresh and navigate to views easily. If this might lead us to overlook a bug though, it seems we should change our setup. I really like live server because it auto-refreshes anytime you save a file. Is there a way to set up Apache or ExpressJS to work similarly?

**Comment by csjx** [comment]
Hey @robyngit - Looking at https://atom.io/packages/atom-live-server, it looks like you can set up a `.atom-live-server.json` file in your project root directory, and within that, you can set an `entry-file=index.html` option, which looks to me like it would be the fallback needed to serve the single page app correctly. Let us know what you find.
Setting up Apache to serve live changes would be more involved, as well as Express, so if you can find the correct configuration for live-server, it would be convenient.

**Comment by robyngit** [comment]
Hey @csjx, thanks for looking into this! I've already tried setting the `entry-file` option to `index.html`. I also tried setting the `spa` option to `true`, which should "translate requests from /abc to /#/abc (handy for Single Page Apps)". I tried the combing those options as well. Nothing worked! All the config options can be viewed [here](https://github.com/tapio/live-server).

**Comment by jkibele** [comment]
There's a very similar entry file setting in the VS Code editor. I've monkeyed with it extensively, but haven't gotten anything to work.

**Comment by jkibele** [comment]
Okay, I got it working finally. I'll list the whole setup so we don't have to wade through everything above.

# Setting up MetacatUI with live-server:
1. Edit `metacatui/src/index.html`:
	- make `data-theme="knb"`
	- make `data-metacat-context="knb"`
	- change `data-map-key` to your api key (optional)
        - change `src="loader.js?v=2.3.2"` to `src="/loader.js?v=2.3.2"`
2. Edit `metacatui/src/loader.js`:
        - change `MetacatUI.root` so that `MetacatUI.root = "/"`
3. Changes to `metacatui/src/js/themes/knb/AppModel.js`:
	- set `d1CNBaseURL` to `https://cn-stage-2.test.dataone.org/`.
	- set `baseUrl` to `"https://dev.nceas.ucsb.edu"`

## live-server settings:
1. set the live-server root to `/src`
2. set the entry file to `/index.html`

for the [VS Code live-server extension](https://github.com/ritwickdey/vscode-live-server), the settings JSON looks like this:

```
"liveServer.settings.file": "/index.html",
"liveServer.settings.root": "/src"
```

When this is all done, you can access the SASAP project at `http://localhost:5500/projects/SASAP` (or `127.0.0.1` instead of `localhost` if you're set up that way).

**Comment by jkibele** [comment]
I made a patch for the setup above. So, to make the changes above to `index.html`, `loader.js`, and `AppModel.js`, you can just do `git apply metacatui_local_setup.txt`.

[Here's the patch](https://github.com/NCEAS/metacatui/files/2733563/metacatui_local_setup.txt)

**Comment by laurenwalker** [comment]
These instructions are obsolete as of 2.12.0 when we moved to an external configuration. See #1237 and #281
