### ISSUE TITLE
Look into and possibly remove now-outdated usage of code that uses window.location.hash

### ISSUE THREAD

**Issue by amoeba** [NCEAS/metacatui#735]
This was really part of 2.1.0 but I didn't get to it and it wasn't a big deal to leave this code in.

A few places in the code, https://github.com/NCEAS/metacatui/search?q=window.location.hash&unscoped_q=window.location.hash, reference window.location.hash. I'm not sure if all of these are necessary any longer so it'd be good to do a quick scan at some point and remove any dead code.

**Comment by laurenwalker** [comment]
Yeah, there are a few of these that need to be changed or they will break certain parts of the app. I think just doing a wholesale change of `window.location.hash` to `window.location.pathname` would work.

**Comment by laurenwalker** [comment]
I'm also going to move this to a patch release.

Thanks for catching this.

**Comment by amoeba** [comment]
> Yeah, there are a few of these that need to be changed or they will break certain parts of the app. I think just doing a wholesale change of window.location.hash to window.location.pathname would work.

Roger that. That sounds reasonable to me.
