### ISSUE TITLE
Clicking 'Download All' downloads the package then directs the client back to /data

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/metacatui#736]
I'm not sure exactly how this is happening, but it seems like the client is being redirected to the packages URL (and falling back on index.html so it looks like its being redirected to /data).

The package *is* downloaded successfully, so this isn't a breaking bug, but definitely disruptive and annoying, so it should be fixed in a patch release.

**Comment by amoeba** [comment]
Thanks for catching! I tested the Download All button and it worked at some point. I'll look into this.

**Comment by amoeba** [comment]
Ah, I think this was hard to catch on my local testing. The DataONE deployment hosts both MetacatUI and the D1 API at the same base URL. e.g.,

- MetacatUI: https://search.dataone.org/view/urn:uuid:49f12230-3210-4ef2-94dd-32f4b059e379
- API: https://search.dataone.org/cn/v2/packages/application%2Fbagit-097/resource_map_urn%3Auuid%3Ab05e9c33-c4a2-40e5-a3d7-aec649cd259c

All of our test deployments would use a pattern similar to:

- MetacatUI: https://search.dataone.org/view/urn:uuid:49f12230-3210-4ef2-94dd-32f4b059e379
- API: https://cn.dataone.org/cn/v2/packages/application%2Fbagit-097/resource_map_urn%3Auuid%3Ab05e9c33-c4a2-40e5-a3d7-aec649cd259c

The logic in the click handler hijacks links that start with the same base URL:

https://github.com/NCEAS/metacatui/blob/961723574553fee4524b48c9dee95d70d09acf41/src/js/app.js#L263

I have some ideas for fixing, which are:

- Expand the logic in the on-click handler to not hijack calls to `https://search.dataone.org/cn/v2/packages. Seems brittle and hacky.
- Change the AppModel's baseUrl from search.dataone.org to cn.dataone.org (requires a CORS reconfiguration on cn.dataone.org IIRC. 
- Make the on-click handler even smarter about what it doesn't hijack. It'd be super nice if the Backbone Router allowed reflection so you could make it only hijack URLs the Router can catch (via the routes table).

Does anyone feel one way or another about these ideas of have any others?

**Comment by laurenwalker** [comment]
I like this: 

> Make the on-click handler even smarter about what it doesn't hijack. 

I think we could ignore routes that use the DataONE API. Routes with either `mn/v2` or `cn/v2` would be ignored.
