### ISSUE TITLE
MNs get repeated multiple times in the search list

### ISSUE THREAD

**Issue by rushirajnenuji** [NCEAS/metacatui#737]
On search.dataone.org in the filter section, the MNs are repeated multiple times. The list shows a total of 120 MNs, whereas it should be ~40 MNs on the list. Each MN is repeated about three times, here's a screenshot of the bug - 

![screen shot 2018-08-07 at 12 33 58 pm](https://user-images.githubusercontent.com/19696935/43798053-38c47278-9a3e-11e8-8c42-e03928630e96.png)

To reproduce the bug: 
If you visit the DataCatalog page directly on search.dataone.org, the filter list works just fine and shows the correct number of MNs in the list. But, if you visit any Dataset landing page and then return back to DataCatalog page, it shows each MN multiple times on the list.

**Comment by amoeba** [comment]
This'd be good to fix ASAP. Do you wanna tackle this one?

**Comment by amoeba** [comment]
I'm not seeing this now. Was this already fixed?

**Comment by rushirajnenuji** [comment]
@amoeba - no it is not fixed yet. It occurs only when you visit the DataCatalog page back from a Dataset landing page. Bit weird. Yes, sure, I would love to work on this. Thanks!

**Comment by amoeba** [comment]
Nice catch! That sounds right but @laurenwalker will know more confidently for sure. Did this change fix the bug in this Issue?


> should we have that logic added to this function?

Are you referring to adding logic to `NodeModel.saveNodeInfo()` to check if a certain MN is in `NodeModel.members`?

**Comment by rushirajnenuji** [comment]
Yes, I'm pretty sure this was the reason for the bug and it did fix the issue.

And, yes, I'm referring to adding logic to `NodeModel.saveNodeInfo()` to check if a certain MN is in `NodeModel.members`

- Though if we're making a single call then there would always be unique values in `NodeModel.members` because we get unique values from the `https://cn.dataone.org/cn/v2/node` endpoint.

**Comment by amoeba** [comment]
> Yes, I'm pretty sure this was the reason for the bug and it did fix the issue.

👍 and sorry if I didn't catch that during any code reviews we did.

> And, yes, I'm referring to adding logic to NodeModel.saveNodeInfo() to check if a certain MN is in NodeModel.members

Hrm, not sure about what. It looks like `NodeModel.saveNodeInfo`'s job is to fetch the info from the CN about which nodes are in the node list. Maybe there's another place in the application that can take on the responsibility of checking if a node is in `NodeModel.members`? What parts of the application need this logic?

**Comment by rushirajnenuji** [comment]
We're reading the members list (array) at multiple places in the application: [Search results](https://github.com/NCEAS/metacatui/search?q=MetacatUI.nodeModel.get%28%22members%22%29&unscoped_q=MetacatUI.nodeModel.get%28%22members%22%29)

But, really we set it just once in NodeModel file. So, if we decide to add this logic (if it makes sense), then I think it has to be somewhere in the NodeModel.js. Not sure, if I answered your question. 

- We can probably keep it the way it is right now, it was just a mistake on my part while I got started with JSONLD few months back.

**Comment by amoeba** [comment]
> So, if we decide to add this logic (if it makes sense), then I think it has to be somewhere in the NodeModel.js.

That makes sense and sounds reasonable.

**Comment by ThomasThelen** [comment]
I see this happening on Firefox-Chrome seems to be fine

**Comment by laurenwalker** [comment]
I think it's ok to add that check in the `saveNodeInfo()` function, even though it should theoretically never get used because the NodeModel is only fetched once. But it may be helpful in the future.

**Comment by rushirajnenuji** [comment]
Tested this on handy-owl. Seems like this bug is solved.
Related commits: https://github.com/NCEAS/metacatui/commit/dd487d62005b33ea2bd6fe6c41fc88af69449200 and https://github.com/NCEAS/metacatui/commit/05804f4eeaa0bb985ae288a4d20ec6bf66b2fe0b
