### ISSUE TITLE
Search from DataONE.org main page (not search.dataone.org) not working

### ISSUE THREAD

**Issue by amoeba** [NCEAS/metacatui#740]
I noticed that the main search page on dataone.org stopped working with our routing refactor. I see a `ReferenceError: appSearchModel is not defined` in the console in the DataONE `router.js` which makes total sense because of this: https://github.com/NCEAS/metacatui/blob/master/src/js/themes/dataone/routers/router.js#L147

I think it's just missing `MetacatUI` before the reference so it references the app-global `SearchModel`. I'll give this a test and see if that's the fix.

**Comment by amoeba** [comment]
The search box on the dataone.org Drupal site.
<img width="749" alt="screen shot 2018-08-15 at 11 25 39 am" src="https://user-images.githubusercontent.com/563/44168505-f796a000-a07d-11e8-84c7-ad67bbccaf2a.png">

**Comment by laurenwalker** [comment]
Ah ok, thanks
