### ISSUE TITLE
What is the criteria for filtering suites list?

### ISSUE THREAD

**Issue by gothub** [NCEAS/metacatui#741]
Currently the quality report view (MdqRunView) fetches the list of available suites from the quality server for selection in the suites drop down menu. Should this list be culled for each MN view, or do we want the entire list available for everyone? Here is what it looks like currently, from the `feature-quality-k8s` branch:

![screen shot 2018-08-15 at 1 08 07 pm](https://user-images.githubusercontent.com/6412946/44170831-66c7c080-a08d-11e8-9e9f-f85a73c2398f.png)

**Comment by gothub** [comment]
Update: on the production version of MetacatUI on arcticdata.io, the `suites` drop down doesn't display. On KNB, it does, but only a few suites are displayed, as that is what is currently available from the production `quality.nceas.ucsb.edu`.

**Comment by amoeba** [comment]
I wonder if we were thinking of keeping this View at all since it forces the suite to get run on-demand rather than just pulling a pre-computed score/report from the  backend. What do you think?

As far as this view goes: Without significantly more detail about each suite, potentially with some tasteful and probably significant pruning, that list seems very overwhelming. Better names and potentially including more branding (like logos) might give the user a better chance to make sense of the myriad suites.

**Comment by gothub** [comment]
The plan is to pre-compute quality reports for all current metadata pids, starting with KNB and ADC. The `MdqRunView` uses the default quality suite set for a view as before, so for the `arctic` view, the report for suite `arctic.data.center.1` is fetched and hopefully already prepared. 

For ADC, for example, what other suites may user want to run? The list of suites available to run could be set for each view, or it could be removed.

Yeah, more detail about the suites would be great. At the very least, the suite descriptions should be expanded and made available in the View somehow.

**Comment by mbjones** [comment]
I think each metacatui deplyment should be able to choose which suites are available for display, presumably based on their knowledge of which are being computed for that deployment.  Sites like Arctic Data Center will likely only want one suite displayed, and so wouldn't even need the dropdown menu.  At DataONE, we'd want to choose between several suites, but only from the ones we have configured to be calculated.  Also, each Metacatui deploy should be able to set a default even if they support mutliple suites.

I fully agree with Bryce that the names must also be much more readable and intuitive, probably with values like:

- Arctic Data Center compliance
- LTER Network compliance
- DataONE metadata completeness
- Catalog Services for the Web completeness

Maybe these could be shortened to just the organizational names. Let's discuss.

**Comment by gothub** [comment]
@laurenwalker The original behavior  of the suite selection dropdown was to reload the page with a new quality report when a different suite was selected from the menu. How do you think the user should request that they want to display the quality report for a different suite than the one that is currently displayed? I currently have the drop down menu disabled, but since DataONE would allow reports to be displayed from one of several suites, this needs to be accounted for.

**Comment by laurenwalker** [comment]
For themes that want to allow more than one suite option, I think keeping the dropdown is fine. I could probably use a little UX polishing, if that is what you're asking.

**Comment by amoeba** [comment]
I'm not sure a dropdown is the only idea to go with. I think we've already done some promising mockups for this project and going back to those might be useful here.

For example, I mocked up a UI that'd push the suite selector dropbox out of its own view and onto the MetadataView itself so, from the landing page, a user could see whether any (and which) suites have been run. https://github.com/NCEAS/metadig-engine/blob/master/docs/mockups/package-view/badge.md 

We could imagine each Suite shown where Identification, Citability, Discoverability. This fits in line with the Suites as Badges concept from our earlier design work.

**Comment by gothub** [comment]
Yep, this was/is a really good idea. At the DataONE AHM, it was mentioned that the quality report view should have a usability review, and the badge/metadata view idea should be included in that.

The current release, however, should probably be focused on patching up current functionality.

@laurenwalker is a metacatui github issue the proper place to coordinate a usability review?

**Comment by gothub** [comment]
Updated in commit cb49add70deae92b1205e41dffe6f8f7f9c4d4f0

With this commit, the desired list of quality suites is entered in the theme `AppModel.js`, in the `suiteIds` and `suitelabels` attributes. This can be changed to the metacatui config file when that feature is available. 

Note that the suite name does not appear in the 'arctic' theme, as it is disabled in CSS.

**Comment by gothub** [comment]
@laurenwalker  I'm reopening this because I'd like to get your feedback on the behavior of the quality report view when a report is not available for a dataset/suite. In this case, the metadata view for the dataset is displayed, then an error msg indicating that the quality report is not available. Keep in mind that this shouldn't happen very often, as the k8s MetaDIG engine will poll member nodes (and the production CN) to create reports for newly added content.

**Comment by laurenwalker** [comment]
I thought that when a quality report did not exist, we would send the EML to the quality engine and have the report generated on the fly?

**Comment by gothub** [comment]
Having the user wait around to have a quality report created may not be the best user experience. Currently the quality suites are fairly simple, but if they get any more complex, especially if metadata/data congruency checks are added, the wait times could be long.

The proposed functionality of the k8s MetaDIG engine is that it will poll MNs and/or the CN for newly indexed datasets and have quality reports created them. This could easily be done for the DataONE staging and test environments as well.

A user shouldn't see this error msg very often - the worst case scenario is that they save a dataset and immediately look at the quality report, in which case they will see the error message.

**Comment by gothub** [comment]
@mbjones what are your thoughts on how the quality view should behave in the event of a report not being available? Should the quality view fetch the metadata document and the sysmeta, then submit a request to generate a quality report to the k8s metadig-engine, then wait for the report to come back, or should it display an error to the user? (Note that the topic of this issue changed a bit since being re-opened).

**Comment by gothub** [comment]
The 'metadig-scheduler' is now running on the k8s cluster. This k8s 'deployment' polls KNB and ADC every 5 minutes for new content using the DataONE 'listObjects()' service, and submits quality report requests for any new EML content. So a user may see the message 'A quality report has not been created for this dataset' if they click the button within 5 minutes of submitting the dataset. This message will also display for formats that aren't currently being scored (ISO, Dryad, FGDC,...). These formats will be supported in the 2.1.0 MetaDIG engine release.

**Comment by gothub** [comment]
I'm using `listObjects()` to determine what new content to send to the quality engine, so it is fast, and happens independently of when the content is indexed. If necessary, the frequency of polling the MNs can be increased. The current 5 minute interval is arbitrary. It generally takes about 15-30 seconds from when a report is queued for generation to when it is available.

**Comment by csjx** [comment]
Yeah, I was thinking that closer polling would help too.

 It also seems like we have the information create a better experience with regard to the quality service.  Since we know the `formatId` of the  science metadata being displayed, we can conditionally show the `Quality Report` button for supported formats.  Ultimately, we shouldn't be showing a button when we know it will not work.  Then, if someone does get a button, and they click it, and the `get()` fails for the report, we should then make a call to queue the `pid` for report generation, and give them a more positive message that the report is pending in some way.  

My overall thought here is that we don't want to provide dead end experiences for the researchers with messages like "A quality report has not been created for this dataset".  It leaves them with

**Comment by gothub** [comment]
@csjx Yep, all good points. I'll decrease the polling interval, and come up with a way to selectively display the quality report button. I also totally agree with not wanting to give the user a "dead end, no recourse" outcome - I'll work on making the UX better.

Here is a new issue for the proposed changes https://github.com/NCEAS/metacatui/issues/849.
