### ISSUE TITLE
Restrict project view search to project collection items

### ISSUE THREAD

**Issue by jkibele** [NCEAS/metacatui#749]
I'm breaking out this issue from [a more general issue](https://github.com/NCEAS/project-papers/issues/35). I suspect I'm going to need to have some back and forth about this, and I can use it to track what I'm doing.

**Comment by jkibele** [comment]
I'm currently baffled by the relationship between the `SearchModel` that's created in the `ProjectView` and how it's supposed to relate to the `CollectionModel`. I can restrict the search in a really wonky way by putting `search.set("all", ["state or alaska salmon and people"])` into that `insertProjectSearch` function of `ProjectView`, but I don't think that's really what we're after.

I think I'm a bit hamstrung by not really understanding the project collection model. The SASAP project collection is defined somewhere in metacat, right? ...and metacatui is working with that collection in [this format](https://github.com/NCEAS/project-papers/blob/master/project-schema/examplecollection.json), right? 

So I think that metacatui is supposed to restrict the search the `listOfIdentifiers` on [this line](https://github.com/NCEAS/project-papers/blob/master/project-schema/examplecollection.json#L7), right? ...and to set up the filters in the search box according to the rest of that...

Don't feel compelled to answer any of this in writing. I'm just trying to document my current level of (mis)understanding so I can come back to it later.

**Comment by jkibele** [comment]
Er... Okay. Seems like I was mistaken about my assumption that the search should be restricted based on `listOfIdentifiers`. We are just restricting based on a "sasap" keyword. For the moment, I've just messed with hard coding this. That's obviously not a long term solution. I think it's supposed to come from `listOfFilterGroups` ([on this line](https://github.com/NCEAS/project-papers/blob/42c14bdaa065fbc6ec91e1aab51b49e3598e01f5/project-schema/examplecollection.json#L14)) but I'll need to verify that before I get too far down that road.

**Comment by laurenwalker** [comment]
There are two different ways to restrict the search - either by a list of identifiers or a set of Solr filters. The `CollectionModel` parses the collection JSON file which contains that information. The `CollectionModel` needs to use that parsed JSON (it will be set in the Backbone model attributes) in order to construct the Solr query. The Solr query is constructed by the `Search` model. It may be helpful to draw a flow chart of this work. I can sketch something later if that would be useful.

**Comment by jkibele** [comment]
I can't figure out how to get at the collection JSON from within the CollectionModel. A flow chart may help. ...or maybe just a call when you have time?
