### ISSUE TITLE
Describe auth token use in API overview

### ISSUE THREAD

**Issue by mbjones** [NCEAS/metacatui#75]
The current [KNB API overview](https://knb.ecoinformatics.org/#api) describes how to authenticate with client certificates, but not with Auth Tokens.  Add a short description as an intro.

**Comment by mbjones** [comment]
Committed initial draft in sha 70bfa7f55acb45fdbea69f73002f5d8653b06556

Needs to be reviewed and deployed in subsequent releases of the KNB theme.

**Comment by mbjones** [comment]
I also just added links to R and Matlab clients in SHA 03d520c22807b49d051768697825299e9262afff.

**Comment by laurenwalker** [comment]
I added a .gif of the auth token UI to the api docs, and used the theme's title instead of "DataONE catalog", and linked to #signin and #my-profile instead of search.dataone.org
