### ISSUE TITLE
After signing in, I am redirected back to a sign in button

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/metacatui#750]
I clicked on a link to a MetadataView for a private data set
The "This is private" message displayed, which contains a "Are you signed in?" link.
I clicked on the "Are you signed in?" link and was directed to the #signin view which shows a big sign in button
I clicked the sign in button which takes me to Orcid and I signed into Orcid
After successfully signing into Orcid, I am redirected back to the #signin view, which still shows the sign in button. But I am authenticated at this point (my name is displayed in navigation)

<img width="1711" alt="screen shot 2018-08-30 at 2 59 25 pm" src="https://user-images.githubusercontent.com/6643222/44881766-9f5ac300-ac65-11e8-8d50-b41d64d86999.png">

I think this may be what is happening when some people have reported that they signed in but are still not signed in.

The sign in view should send the last route as the redirect URL, never the sign in view.

**Comment by mbjones** [comment]
This seems exactly like what I have been experiencing.  RIght now, successful logins via ORCID always redirect me back to the signin button.  I haven't figured out why the session is not being recognized.

**Comment by laurenwalker** [comment]
This seems to already have been fixed in the 2.0 branch. ADC will be fixed once its upgraded.
