### ISSUE TITLE
Prov display problems on DataONE search page

### ISSUE THREAD

**Issue by gothub** [NCEAS/metacatui#756]
When displaying the [GOA hydrocarbon dataset](https://search.dataone.org/view/urn:uuid:3249ada0-afe3-4dd6-875e-0f7928a4c171) on the DataONE search page, multiple display problems are present:

- for "Total_Aromatic_Alkanes_PWS.csv" package member detail, PNG thumbnails don't appear in derivation prov charts:

![screen shot 2018-09-04 at 10 01 58 am](https://user-images.githubusercontent.com/6412946/45046010-b4e73880-b029-11e8-9d16-cce3b1f34492.png)

- for "Data merging R script" detail, arrowhead doesn't appear for derivation prov chart:

![screen shot 2018-09-04 at 10 04 17 am](https://user-images.githubusercontent.com/6412946/45046077-ee1fa880-b029-11e8-894e-ffc531c82049.png)

- Similar problems for both source and derivations charts for "Locations map R script"
![screen shot 2018-09-04 at 10 06 23 am](https://user-images.githubusercontent.com/6412946/45046172-3c34ac00-b02a-11e8-99d5-dc336994343e.png)

![screen shot 2018-09-04 at 10 07 00 am](https://user-images.githubusercontent.com/6412946/45046203-4f477c00-b02a-11e8-80b6-4857b07dd1cf.png)

Note that these problems seem to be unique to the DataONE theme, as they don't appear on GOA MN:

https://goa.nceas.ucsb.edu/#view/urn:uuid:3249ada0-afe3-4dd6-875e-0f7928a4c171

**Comment by gothub** [comment]
Update - this display problem doesn't occur on GOA: https://goa.nceas.ucsb.edu/#view/urn:uuid:3249ada0-afe3-4dd6-875e-0f7928a4c171, so it may be related to the 'dataone' theme and/or obtaining objects via the DataONE resolve service.

**Comment by laurenwalker** [comment]
The image issue seems to be fixed already.

I fixed the issue with the missing connecting arrows.
