### ISSUE TITLE
Refactor metadata quality view/model

### ISSUE THREAD

**Issue by gothub** [NCEAS/metacatui#757]
Currently the metadata quality report view ([MdqRunView.js](https://github.com/NCEAS/metacatui/blob/master/src/js/views/MdqRunView.js#L160)) makes several XHR requests to either retrieve an existing quality report, or submit a request to have the report generated. These XHR requests and the data representation should really be in models/collections and not in the view.

A proposed Backbone.js representation for this quality info:

- a `suite` collection that has
  - `check` members models, one model for each check in a suite
    - fetch
       - the standard Backbone `fetch()` routine would retrieve the quality report and see if the corresponding sysmeta, metadata is already loaded
    - save
       - submits a request to generate a quality report from the sysmeta, metadata, suiteId
  - contains a DataONE object that contains the sysmeta & metadata objects
    - these can usually be obtained from the DataPackage already loaded into MetacatUI
- a `check` model has:
  - check name, description, etc
  - check run status

Note that having separate `check` models may make future integration of `on the fly` quality checks easier and more robust, i.e. checks run when a user is entering data into the metadata editor.

Referring to this info as a `suite` is a different way of thinking about about it, as apposed to calling it `quality report`, but makes sense, as a quality report is a display derived from a suite run. The JSON data for a quality suite run contains the suite, including all check source code, and each check result.

Related:
https://github.com/NCEAS/metacatui/issues/413

**Comment by gothub** [comment]
This issue was first mentioned in https://github.com/NCEAS/metacatui/issues/413

A refactor of `MdqRunView.js` with basic functionality is available in commit 96673a9940a48b8a610aa8749f889bb27e858385. Additional functionality and display fixes detailed in #413 still need to be added.

**Comment by laurenwalker** [comment]
This is looking really good, Peter. Thanks for your work on this.
