### ISSUE TITLE
Project info abstract display

### ISSUE THREAD

**Issue by drkrynstrng** [NCEAS/metacatui#761]
For data packages that have project information, the display for the project abstract is off. It seems that there should be a bounding box like the other fields.

![screenshot_2018-09-07 knb](https://user-images.githubusercontent.com/36723171/45246815-571c5000-b2b8-11e8-97ea-7439d7551ce4.png)

**Comment by laurenwalker** [comment]
Thanks for reporting this, Derek. I've moved this issue to the Metacat repository: https://github.com/NCEAS/metacat/issues/1279
