### ISSUE TITLE
Do not get the metric type from the HTML

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/metacatui#764]
Regarding this line of code:
https://github.com/NCEAS/metacatui/blob/feature-metrics-service/src/js/views/MetadataView.js#L1083

The MetadataView is getting the metric type (download, citation, view) from the inner HTML of the button. It's not great design for the app to retrieve  data from the display when it is already stored in the models. I think the flow should look like this:

- The MetricView should listen to clicks on itself (This is what is great about breaking up parts of the UI into smaller views - big views like the MetadataView don't have to do all the work for every little click. Views just take care of their own part of the UI). This listener would be set in the `events` hash in the MetricView (https://github.com/NCEAS/metacatui/blob/feature-metrics-service/src/js/views/MetricView.js#L20).

- When clicked, the callback function gets the metric type from the `metricName` attribute on the view

- The MetricView will create, render, and show the MetricModalView

This can wait until 2.3.0 if the rest of 2.2.0 is ready to be released. Feel free to move to the 2.3.0 milestone if this is the case.

**Comment by rushirajnenuji** [comment]
@laurenwalker - Thank you for the suggestions. I've made the corresponding changes in the above commit  - and tested the click function. It looks good to me.
