### ISSUE TITLE
Include APA style citation formatting for Metrics Citations.

### ISSUE THREAD

**Issue by rushirajnenuji** [NCEAS/metacatui#777]
There has been some discussion in the MDC channel regarding re-formatting the Citation format that the Metrics Modal window publishes. Martin Fenner from DataCite suggested that we should consider using APA citation format - since that is the only format that provides a format for citing dataset. The format structure is as follows:

- Basic form:
`Author/Rightsholder. (Year). Title of data set (Version number) [Description of form]. Location: Name of producer`.
or
`Author/Rightsholder. (Year). Title of data set (Version number) [Description of form]. Retrieved from http:// `
Note: Author format: `Author, F. N.`

- Example: 
`Pew Hispanic Center. (2008). 2007 Hispanic Healthcare Survey [Data file and code book]. Retrieved from http://pewhispanic.org/datasets/`
or
`Smith, J. N. (2008). 2007 Hispanic Healthcare Survey [Data file and code book]. Retrieved from http://pewhispanic.org/datasets/`

The DOI resolving endpoint gives us enough metadata to be able to publish the information needed in this format.

Also, in the CI meeting - I remember @laurenwalker mentioning that ESS-DIVE requires their dataset citations to be in the same format. So, if we decide to go ahead with this format, we can re-use the functionality for ESS-DIVE.

Another option would be to keep the format similar to what we have right now and add the missing metadata to the citation structure - like - journal, volume, pages, etc.

@laurenwalker, @csjx, @mbjones - thoughts?

**Comment by rushirajnenuji** [comment]
Okay, it looks like ESS-DIVE already has APA style citation format. It still doesn't explain the `:` after the year in parenthesis.

Example: 
```Gibbs H K; Brown S (2007): Geographical Distribution of Woody Biomass Carbon in Tropical Africa: An Updated Database for 2000 (NDP-055.2007, NDP-055b)). Carbon Dioxide Information Analysis Center (CDIAC), Oak Ridge National Laboratory (ORNL), Oak Ridge, TN (USA). doi:10.3334/CDIAC/LUE.NDP055.2007```

Found at : https://data.ess-dive.lbl.gov/#view/ess-dive-cb126697bf31ead-20180904T225447307

**Comment by rushirajnenuji** [comment]
I was not able to complete this feature in time for release `2.3.0` but I've added correct publisher name, and other metadata like volume and pages to the lists of citations displayed on Citation Modal window. 

Relevant commit: https://github.com/NCEAS/metacatui/commit/20061f99d9b25f133f4d5e75d74439b3f7fcd7d5

Note: This feature is still under development.

**Comment by robyngit** [comment]
The only task left to make citations follow APA style format is to fix the way that organization names are displayed so that we can abbreviate individual names. We have an issue for that already (#2106), so I am marking this issue as closed.
