### ISSUE TITLE
Improve visualization of missing data in metrics charts

### ISSUE THREAD

**Issue by robyngit** [NCEAS/metacatui#778]
Currently, the metrics line chart interpolates views and downloads in months where data is missing. In other words, the data appears continuous when there are, in fact, gaps. For example, in the views chart in  [doi:10.5063/F1TX3CKH](https://knb.ecoinformatics.org/view/doi:10.5063/F1TX3CKH), data is missing for July 2018. However, because a line is drawn between 0 views in June and 14 views in August, it appears as though this package was viewed 7 times in July. To better represent missing data, I'm experimenting with different chart styles, specifically:

- [x] a cumulative line chart
- [x] a line chart with blanks or dotted lines where there is no data
- [x] both of the above, but with the addition of dots to show actual data points
- [x] a bar chart with different background shading for months with no data (to differentiate between no data and zero views/downloads)
- [ ] ...?

**Comment by robyngit** [comment]
[Here is a preview](http://bl.ocks.org/robyngit/raw/981590aa194d930b22aa45cdba79beaf/) of a potential bar chart style. It still needs minor tweaks, as well as some sort of visual indication of which months are actual zero counts and which are missing data. My original idea was to add lighter or darker background shading in areas with missing data, but this didn't look quite right. Ideas/feedback would be much appreciated!

**Comment by aebudden** [comment]
I think this look great. What would be an example of missing data? When the event data service didn't report? What is the expected timeline on putting this in place? And will this resolve the issue in #785? Would be great to announce the functionality soon.

**Comment by robyngit** [comment]
> What would be an example of missing data? When the event data service didn't report?

I don't know the root cause of the missing data, but it's something I've been wondering about. It seems to be common that datasets are missing at least one month (often more) of view or count data.

> What is the expected timeline on putting this in place?

As is, I could have a pull request ready today or tomorrow. However, I am working on a version that's closer to a lollipop style chart because I think this would make it easy to differentiate between months with zero counts and months missing data. (The missing data months could have a circle at zero, but without any fill colour. Besides giving a visual indication of missing data, these empty circles would also give the viewer something to mouseover so that a tooltip could explain that there's no data available for the given month). I estimate I could have this version ready by Friday or Monday at the latest.

> And will this resolve the issue in #785?

Yes

**Comment by robyngit** [comment]
I think the first explanation, "all the download/view activity occurred in a single month," is the most likely. I can confirm this if you send me a couple of examples of these records with high counts but no figure. In any case, if it's possible to "identify and resolve the reason for it missing in the first place," as you suggested, that would clearly be the best solution.

**Comment by datadavev** [comment]
I think the "missing" data is probably an artifact of the service counting results - so missing data should be equivalent to "0".

**Comment by robyngit** [comment]
Thanks for the explanation @datadavev! Is this always the case, or are there true instances of missing counts for certain months? If so, is there a way to differentiate between the two? The reason I ask is that the metrics request does provide actual "0" counts for some months, whereas other months are just not listed at all.

**Comment by robyngit** [comment]
Here's an example from views for [doi:10.5063/F1TX3CKH](https://knb.ecoinformatics.org/view/doi:10.5063/F1TX3CKH). There are plenty of months showing 0 views, but nothing at all for July 2018.

<img width="1139" alt="screen shot 2018-10-17 at 1 40 26 pm" src="https://user-images.githubusercontent.com/26600641/47115052-501b2280-d212-11e8-8835-a5babd2b00fe.png">

**Comment by rushirajnenuji** [comment]
I'm not quite sure, what we're considering as "missing" data. We have the following structure:
```
results: {
    months: ['07-2018', '09-2018', '10-2018'],
    downloads: [0, 1, 0],
    views: [2, 3, 4],
    citations: [0, 0, 1]
}
```
The API is designed in such a way that - we include a month if either one of the metric is `non-zero`!
So, if for `08-2018` if all the metrics are 0, then we don't include that month in the result as @datadavev  explained.

So, if anyone metric is non-zero, let's say for `07-2018` the `views` are 2 and no downloads, then we include the month and set the download and citation counts to 0, with view count to 2. (Read each month as a column to interpret the results)

API documentation: https://app.swaggerhub.com/apis/nenuji/data-metrics/1.0.0.3

**Comment by aebudden** [comment]
Robyn - here is a record with a lot of data and no figure https://search.dataone.org/view/https://pasta.lternet.edu/package/metadata/eml/knb-lter-nes/1/2

**Comment by rushirajnenuji** [comment]
Hey @aebudden , the response for this dataset from the Metric Service is as follows:

![screen shot 2018-10-17 at 1 55 10 pm](https://user-images.githubusercontent.com/19696935/47115737-59a58a00-d214-11e8-9394-74e63a699e3a.png)

We should have a resolution to this with #785

**Comment by robyngit** [comment]
@rushirajnenuji, thanks for the super clear explanation! That makes sense now. Is there ever a reason that counts would be missing, and should we check for that some how? Or would you say that it's always safe to assume that any month not listed in the results had zero views and zero downloads?

**Comment by aebudden** [comment]
OK, so that one is a case where all the activity was in one month. Great. In #785 it was suggested that this thread would resolve so sorry if I am talking in the wrong ticket :). If missing data are in fact zeros, can we proceed with the bar chart? Do we need to distinguish missing from 0?

**Comment by robyngit** [comment]
If there isn't actually any missing data then, in my opinion, the bar chart is appropriate. Any other input / suggestions for improvement?

**Comment by rushirajnenuji** [comment]
Robyn, yes, if data for that month is available to us then we'll always have that month in the response. So, missing monthly data would always mean 0 counts - for that month. There could be some rare unlikely scenarios where counts could be missing - but in that case, they'd be missing for all the months and not a single month. We can always trace back the pipeline and check where things are going wrong!

And, yes, I agree that a bar chart would be appropriate. It would interesting to see clear monthly trends of usage metrics. Thanks!

**Comment by csjx** [comment]
@robyngit - This looks great. My only suggestion is to rename the `data` button to `all` if that makes sense to you.  Thanks for working on this.

**Comment by kameyer** [comment]
All looks great! We're looking forward to sharing this in an announcement - do you know when this will be deployed @robyngit?

**Comment by robyngit** [comment]
Just working on some minor adjustments so that everything looks right whether a data package has many months of data, or just one. Should have a pull request ready by the end of the day today.

**Comment by laurenwalker** [comment]
@kameyer Here is a list of all the issues we have talked about that need to be completed before the announcement: https://github.com/NCEAS/metacatui/milestone/49

@rushirajnenuji Can give more insight into the status of these issues.

As soon as they are done, I can deploy these changes to the production website immediately.

**Comment by rushirajnenuji** [comment]
Hey @kameyer - The issues with `review` tag are pretty much done (and tested). I'll have [2.3.2](https://github.com/NCEAS/metacatui/milestone/49) ready once I merge the PR from @robyngit.

**Comment by aebudden** [comment]
This is great. @rushirajnenuji Any chance this will be ready for announcement on Wednesday? I need a day lead time my end.

**Comment by rushirajnenuji** [comment]
Hey @aebudden  - yes, we'll be ready with the patch deployed to production pretty soon - Lauren is testing it right now. The changes are deployed on my dev server and are up for review: `https://handy-owl.nceas.ucsb.edu/metacatui/data`.

So, yes, we should be able to make the announcement on Wednesday.
