### ISSUE TITLE
broken link on KNB webpage

### ISSUE THREAD

**Issue by jeanetteclark** [NCEAS/metacatui#779]
not a metacatUI bug, but for lack of a better place to put it...

from the EML section on https://knb.ecoinformatics.org/tools
https://knb.ecoinformatics.org/external/emlparser/docs/index.html is a dead link

I think it should be:
https://knb.ecoinformatics.org/external//emlparser/docs/eml-2.1.1/index.html

**Comment by amoeba** [comment]
Thanks for reporting. Maybe I introduced that with the URL refactor.
