### ISSUE TITLE
See if we can get Google to see MetacatUI's JSON-LD

### ISSUE THREAD

**Issue by amoeba** [NCEAS/metacatui#781]
After the launch of the JSON-LD feature, something on Google's end seems to changed with respect to how it sees JSON-LD. While testing, it was clear that Google was seeing our client-injected JSON-LD and after we launched it, that stopped working. At the DataONE AHM, we discussed testing to see if there are any ways to make this work while still injecting the JSON-LD client-side such as injecting the JSON-LD earlier.

If all else fails, we'll have to deliver the JSON-LD on the server side and disable the current injection w/in MetacatUI.

**Comment by amoeba** [comment]
I did a bit of profiling today and it looks like the JSON-LD usually gets inserted before the 5 second cutoff we think Google imposes. I tested this by recording the time the app starts loading (`loader.js` executes), and comparing that to (1) when `SolrResult.js` does the query for the data we need for the JSON-LD and (2) when the JSON-LD gets inserted. I see lots of times in the 2-5 second range from Juneau on my ~150Mb connection. If I throttle it to a 10Mb connection, injection times jump up to 7-8 seconds. Regardless, `SolrResult` does it query at nearly the same times as the JSON-LD gets injected so we'd have to move SolrResult's query earlier and not just the JSON-LD injection earlier.

But there's more: I tested to see if Google's tool was now blocking MetacatUI completely and this does seem to the case: If I inject the JSON-LD in `loader.js` via an IIAF, ala

```js

(function() {
	document.addEventListener("DOMContentLoaded", function(event) { 
		console.log("inserting eager ld+json");
		var head = document.getElementsByTagName("head")[0];
		var script_tag = document.createElement("script");
		script_tag.setAttribute("type", "application/ld+json");
		script_tag.innerHTML = '{"@context":{"@vocab":"http://schema.org"},"@type":"Dataset","@id":"https://dataone.org/datasets/doi%3A10.5063%2FF1MS3R06","datePublished":"2018-01-01T00:00:00Z","publisher":"Knowledge Network for Biocomplexity","identifier":"doi:10.5063/F1MS3R06","url":"https://dataone.org/datasets/doi%3A10.5063%2FF1MS3R06","schemaVersion":"eml://ecoinformatics.org/eml-2.1.1","name":"Arthropod associations with Larrea tridentata, Mojave Desert, California, USA. April 10 - May 5, 2017","creator":["Jenna Braun","Christopher Lortie"],"citation":"Jenna Braun and Christopher Lortie. 2018. Arthropod associations with Larrea tridentata, Mojave Desert, California, USA. April 10 - May 5, 2017. Knowledge Network for Biocomplexity. doi:10.5063/F1MS3R06.","spatialCoverage":{"@type":"Place","additionalProperty":[{"@type":"PropertyValue","additionalType":"http://dbpedia.org/resource/Coordinate_reference_system","name":"Coordinate Reference System","value":"http://www.opengis.net/def/crs/OGC/1.3/CRS84"}],"geo":{"@type":"GeoCoordinates","latitude":34.77403,"longitude":-115.65861},"subjectOf":{"@type":"CreativeWork","fileFormat":"application/vnd.geo+json","text":"{\"type\":\"Point\",\"coordinates\":[-115.65861,34.77403]}"}},"temporalCoverage":"2017-04-10T00:00:00Z/2017-05-05T00:00:00Z","description":"We tested for changes in arthropod community composition associated with the desert shrub Larrea tridentata (creosotebush) before and after entering a full bloom (average 300 blooms). We found that L. tridentata supports arthopod abundance (excluding Melyridae beetles) and species richness relative to open areas, but both abundance and richness decreased as L. tridentata bloomed.","keywords":"arthropod, creosotebush, Mojave, desert"}';
		head.appendChild(script_tag);
	});
})();
```

The Structured Data Testing Tool _still_ doesn't see the JSON-LD. Hosted example available at https://neutral-cat.nceas.ucsb.edu/view/doi:10.5063/F1MS3R06. We can see it still _does_ support client-side injection with a simple page like:

```html
<html>
  <head>
    <script>
      document.addEventListener("DOMContentLoaded", function(event) { 
        console.log("inserting eager ld+json");
        var head = document.getElementsByTagName("head")[0];
        var script_tag = document.createElement("script");
        script_tag.setAttribute("type", "application/ld+json");
        script_tag.innerHTML = '{"@context":{"@vocab":"http://schema.org"},"@type":"Dataset","name":"TestDataset"}';
        head.appendChild(script_tag);
      });
    </script>
  </head>
  <body>
    JSON-LD test
  </body>
</html>
```

which works fine. Hosted example at https://neutral-cat.nceas.ucsb.edu/jsonld.html.

So I don't think this has anything to do with timing (I did before) but really some intricacy of Google's technique for seeing JSON-LD. I'm fairly certain now that the only way forward is moving the JSON-LD server side.

**Comment by amoeba** [comment]
I just tested an Ember.js app that works like MetacatUI against the tool. The app dynamically injects the JSON-LD on the client side and the Structured Data Testing Tool works with it. It seems like it's not specifically a problem with client-side JS apps in general but more something about MetacatUI.

**Comment by laurenwalker** [comment]
Let's talk through this tomorrow during/after our dev call.

**Comment by amoeba** [comment]
A note from our dev call today: @laurenwalker tried this on [mn-demo-1](https://mn-demo-1.test.dataone.org/view/72f9a5e3-ae19-4f1a-a1e2-5e0dab2cd051) and actually had success. I'm going to re-check my tests to see why we saw different results.

**Comment by amoeba** [comment]
Weird, now my test where I inject the JSON-LD in loader.js is working... Thanks a ton for double-checking and saving us a ton of pain! 

Now that we've tested, is `loader.js` the right place to put this? It seems we could either (1) hard-code this to search.dataone.org across all themes and then we could put it in loader.js or app.js, or (2) we'd want to put it somewhere deeper in the application so we have access to the theme-specific API settings.

If we go with (1), we could at least put it in app.js so we can do the XHR in a way that works in older browsers for free. At least there we'd have access to the theme name so we could inject the JSON-LD jus for DataONE deployments. Thoughts?

**Comment by amoeba** [comment]
@laurenwalker 	can you push what you've deployed at https://mn-demo-1.test.dataone.org/view/72f9a5e3-ae19-4f1a-a1e2-5e0dab2cd051 to a branch or send a patch file? I just tested this again on my neutral-cat VM and the testing tool isn't picking up the JSON-LD.

**Comment by laurenwalker** [comment]
The only thing I changed is `loader.js`. Here is the `loader.js` file I used on mn-demo-1: https://gist.github.com/laurenwalker/93c8e4a0a4ee8ef32448bba5ecb51056

**Comment by amoeba** [comment]
Huh, super weird. I applied your loader.js to the tip of dev-2.2 and the Structured Data Testing Tool isn't seeing the JSON-LD at https://neutral-cat.nceas.ucsb.edu/view/p17.ds429_20180930_0300. Is that what you see too? https://search.google.com/structured-data/testing-tool/u/0/#url=https%3A%2F%2Fneutral-cat.nceas.ucsb.edu%2Fview%2Fp17.ds429_20180930_0300

**Comment by laurenwalker** [comment]
That's what I see, too. Do you think it has something to do with Apache settings on the two different virtual hosts?

**Comment by amoeba** [comment]
Not sure, but that wouldn't be a bad thing to check. I wonder if it could be a performance thing at the network level too, though these are all UCSB hosts I think. I'll get ask to mn-demo-1 and look around. Thanks for verifying!

**Comment by amoeba** [comment]
Okay so I copied your MetacatUI source from mn-demo-1 to neutral-cat and it started working so I think I was just goofing somewhere. I'll work up a feature branch with an initial implementation.

**Comment by laurenwalker** [comment]
That's good to hear!

**Comment by amoeba** [comment]
Okay, so I think I've learned a lot. More than I really wanted to I guess. **I don't think this will work**.

I migrated the existing JSON-LD implementation to `loader.js` as a more complete test of this idea than the above snippet and the Structured Data Testing Tool couldn't see the JSON-LD. After some testing, I think I divined some of the characteristics of the Tool:

1. It aggressively caches JS assets in a similar way as browsers. To force the tool to fetch fresh JS when I edited the source, I had to cache-bust the asset's URL (i.e., `loader.js?v=2.2.999`).
2. I am pretty sure the tool blocks external requests. **This is key**

Re (2): I tested whether this was a restriction on requests entirely or just requests outside of requests to the same origin. We need to query Solr to get enough info to populate the JSON-LD so this is critical. My test looked like this:

(These are snippets from `loader.js`):

**Works**

```js
(function() {
	document.addEventListener("DOMContentLoaded", function(event) { 
		console.log("inserting eager ld+json");
		var head = document.getElementsByTagName("head")[0];
		var script_tag = document.createElement("script");
		script_tag.setAttribute("type", "application/ld+json");
		script_tag.innerHTML = '{"@context":{"@vocab":"http://schema.org"},"@type":"Dataset","@id":"https://dataone.org/datasets/XYZ", "name":"Test Dataset"}';
		head.appendChild(script_tag);
	});
})();
```

Does not work:

```js
(function() {
	document.addEventListener("DOMContentLoaded", function(event) {
		if (window.fetch) {
			fetch("https://neutral-cat.nceas.ucsb.edu").then(() => {
				console.log("inserting eager ld+json");
				var head = document.getElementsByTagName("head")[0];
				var script_tag = document.createElement("script");
				script_tag.setAttribute("type", "application/ld+json");
				script_tag.innerHTML = '{"@context":{"@vocab":"http://schema.org"},"@type":"Dataset","@id":"https://dataone.org/datasets/XYZ", "name":"via Fetch"}';
				head.appendChild(script_tag);
			})
		} else {
			console.log("inserting eager ld+json");
			var head = document.getElementsByTagName("head")[0];
			var script_tag = document.createElement("script");
			script_tag.setAttribute("type", "application/ld+json");
			script_tag.innerHTML = '{"@context":{"@vocab":"http://schema.org"},"@type":"Dataset","@id":"https://dataone.org/datasets/XYZ", "name":"Not via fetch"}';
			head.appendChild(script_tag);
		}
	});
})();
```

To test that it's not just because the JS engine doesn't have `window.fetch`, I tested this and **it works**:

```js
(function() {
	document.addEventListener("DOMContentLoaded", function(event) {
		if (window.fetch) {
				console.log("inserting eager ld+json");
				var head = document.getElementsByTagName("head")[0];
				var script_tag = document.createElement("script");
				script_tag.setAttribute("type", "application/ld+json");
				script_tag.innerHTML = '{"@context":{"@vocab":"http://schema.org"},"@type":"Dataset","@id":"https://dataone.org/datasets/XYZ", "name":"via Fetch"}';
				head.appendChild(script_tag);
		}
	});
})();
```

I'd love a second opinion on this but I think this approach might be dead in the water if the tool is truly blocking external requests.

**Comment by amoeba** [comment]
Found a kinda obscure doc that wasn't entirely about the structured data testing tool but it appears the tool, and Google's crawler in general, may not support ES6: https://developers.google.com/search/docs/guides/rendering. I'm going to try switching this code to ES5 as a test of that.

**Comment by amoeba** [comment]
I *think* the above explanation is still right as I ran into issues that appeared to have been caused by usage of `window.fetch` and some newer `Array` methods. I spent most of the day incrementally adding and removing code as things broke and this was looking good. Of course, as I was wrapping up my code to PR it, the whole thing broke again. More on this tomorrow.

**Comment by amoeba** [comment]
So I had this all buttoned up yesterday, did extensive testing, and then this morning I went to PR this and everything broke again. I might re-visit this in the future to see if it's just an intermittent issue with Google's crawling infrastructure but I don't think I can sink any more time into this right now. If anybody else wants to take a look before then, please do.

**Comment by amoeba** [comment]
Okay I let the structured data testing tool sit over the weekend and the same code that wasn't working last week is working now. I'll update this by the end of the day once I do one more check.

**Comment by amoeba** [comment]
Just (belatedly) circling back on this. Since this issue was created and last updated, Google has made some sort of changes to their crawler so they see our JSON-LD fine now so this can be closed.

**Comment by yvanlebras** [comment]
Amazing!

Testing Google web page structuration tool several weeks ago, it appears it doesn't recognize the licence part of metacatui data pages. Moreover I was trying to look at Google data search how to add metacatui based website.... But don't find the way to do that. DataOne doesn't seem to be on it isn't it ?

**Comment by amoeba** [comment]
Hey @yvanlebras, the licensing issue is something that we are aware of and working on over on https://github.com/NCEAS/metacatui/issues/1076.
