### ISSUE TITLE
Metrics charts not rendering the graph data.

### ISSUE THREAD

**Issue by rushirajnenuji** [NCEAS/metacatui#785]
There are some datasets where the metric counts are non-zero, and yet the charts do not render the graph data.

Example: https://search.dataone.org/view/urn:uuid:79b70fe3-189c-4fea-9370-ca2519355d69

![screen shot 2018-09-27 at 12 42 31 pm](https://user-images.githubusercontent.com/19696935/46170519-e632dd00-c252-11e8-8943-d0f53a919c25.png)

**Comment by robyngit** [comment]
Thanks for pointing this out! In the current line-chart style, lines connect consecutive data points. However for this dataset, there is only one point at Sept 2018:

<img width="1498" alt="screen shot 2018-09-27 at 12 46 10 pm" src="https://user-images.githubusercontent.com/26600641/46170852-cc45ca00-c253-11e8-88c9-c12af2ee011a.png">

With no other point to connect this point to, nothing is displayed. What would you imagine the chart to look like in this case? Perhaps, a dot at y=5 and x=Sept 2018? How could we make it look consistent with the metrics charts with more complete data? I will consider this in the re-design of the metrics charts: https://github.com/NCEAS/metacatui/issues/778

**Comment by rushirajnenuji** [comment]
Hey @robyngit - Oh yes, that's a very interesting edge-case. Thanks for debugging and finding the root cause of the problem.

A point representation at `y=5` and x=`Sept 2018` would work, but I'm not sure how intuitive it would be for the users - considering some of the  Metrics display parts are a bit confusing for them. If we decide to go ahead with the `bar-chart` (#778) - I believe it would cover this scenario pretty well.

@csjx, @laurenwalker: thoughts?

**Comment by aebudden** [comment]
Do we have a status update on this? I believe we wanted this to be resolved prior to announcing. Is this a complex fix? What is the expected timeline?

**Comment by robyngit** [comment]
Hi @aebudden, we decided on replacing the line chart with a bar chart, which I'm working on at the moment. I'm hoping to have a version to share by Friday (Oct 12) at the latest, tomorrow (Oct 11) at the earliest.

**Comment by aebudden** [comment]
Awesome. Thanks for the update. Look forward to seeing the new version.
