### ISSUE TITLE
Metrics shown on search results page do not match metrics on dataset view

### ISSUE THREAD

**Issue by datadavev** [NCEAS/metacatui#786]
The number of views shown on the search results / browse page does not match the metrics shown on the dataset view page.

The search results page should be updated to retrieve metrics from the same source as the dataset results page.

**Comment by rushirajnenuji** [comment]
Solved by adding the search page and data catalog page metrics support to both `MetacatUI` and `DataONE Metrics Service`.

Relevant commits: https://github.com/NCEAS/metacatui/commit/5a5175837f918aa9acaf5ea685bfd9413cfa3414 and https://github.com/NCEAS/metacatui/commit/741ee1a64e4428a8ea34d22763e3cd19bd2e20e3
