### ISSUE TITLE
Prov icon doesn't display in ADC catalog view

### ISSUE THREAD

**Issue by gothub** [NCEAS/metacatui#788]
In the ADC catalog view (https://arcticdata.io/catalog/#data), the prov icon doesn't display for the dataset `doi:10.18739/A2QB9V51M`.

The prov icon does appear for this dataset on the related project page https://arcticdata.io/catalog/#profile/CN=DBO,DC=dataone,DC=org.

Initially reported by @jagoldstein

**Comment by laurenwalker** [comment]
The 25 results on the `data` page contain over 3,000 objects and the response from Solr looking for provenance relationships is limited to 150, to minimize response time. We should probably look at that query and see if we can improve it.

**Comment by laurenwalker** [comment]
This issue will be fixed once Metacat allows POSTs to the query service. https://github.com/NCEAS/metacat/issues/1317

See #392
