### ISSUE TITLE
Beta submissions not creating resource maps 

### ISSUE THREAD

**Issue by dmullen17** [NCEAS/metacatui#789]
I've noticed a few submissions recently that aren't generating resource maps when there are data objects present in the EML.  The `otherEntity` objects in the EML still reference data objects in their `entityName` field.  In most cases these data objects were successfully uploaded (although none were associated with a res map) and I can recover them using a solr query with their `fileName`. 

This is the first instance where the data objects were not uploaded at all https://arcticdata.io/catalog/#view/urn:uuid:11e2a7ea-138c-45dd-b79b-bd7136b69b81.  

Currently I'm unclear whether this a PI workflow-related problem or a bug.  So far I've been unable to re-create it on a test node.

**Comment by jagoldstein** [comment]
Thanks @dmullen17 . Either way, this seems like a bug. Otherwise, there would not be `otherEntity`s OR there would be resmaps and data objects.

This is definitely a hinderance as it creates a lot of extra work for the support team and is also an inferior experience for `submitter`s.

**Comment by jagoldstein** [comment]
Peggy Sullivan reports:
"I am now attempting to re-load the files for 2017.  Metadata seems to have
been retained.  It is taking forever, so I may kill the window, log out,
then do a fresh start (maybe use the non-beta version?).  Too bad.  Lost
work & time.

I took the survey.  It did not ask about browser, etc.
Here is some additional information:
     I was using Firefox, 62.0.3
     Windows 7 OS on Dell Precision tower 5810"
here https://support.nceas.ucsb.edu/rt/Ticket/Display.html?id=16267#txn-384929

**Comment by laurenwalker** [comment]
Something is stopping the RDF from saving at all because there are no save errors in Google Analytics. Since Sullivan was using a Windows 7 machine, I'll try testing on that today.

**Comment by laurenwalker** [comment]
Since this looks related to the beta testing of our new editor, I'm closing.
