### ISSUE TITLE
Bad timing of indexing after package save causes data files to disappear

### ISSUE THREAD

**Issue by vchendrix** [NCEAS/metacatui#790]
We have a number of data packages that are replicated and noticed that when we add data files via MetacatUI the entire resource map goes missing and the data files appear lost in the UI. A little investigative work shows that a resource map is created but for some reason it is not index. 

### The Issue
The test data package *Annual Fossil-Fuel CO2 Emissions: Mass of Emissions Gridded by One Degree Latitude by One Degree Longitude** was previously published and replicated on the ESS-DIVE dev system. I added one  data files and they never showed up in the final version

However, I was able to find a resource map that references the updated EML file (See https://data-dev.ess-dive.lbl.gov/view/ess-dive-fff1eb14535fc7b-20181005T215140258). I found it by searching v2/object api for resource maps created today. ( See v2/object?fromDate=&formatId=)

The Fix
In production, I was able to fix this issue on data package Estimates of Monthly CO2 Emissions and Associated 13C/12C Values from Fossil-Fuel Consumption in the U.S.A. by creating a new resource map manually that is not set to replicate. The resource map was then indexed successfully. Afterward, I needed to go back and update the resource map to replicate.

The Question
Do resource maps marked as replicate not get indexed?
```
Search by ID: doi:10.3334/CDIAC/FFE.NDP058.2016.test1
id=ess-dive-e36d820b3c260ca-20181005T215135666 seriesId=doi:10.3334/CDIAC/FFE.NDP058.2016.test1
	formatType=METADATA
	title=Annual Fossil-Fuel CO2 Emissions: Mass of Emissions Gridded by One Degree Latitude by One Degree Longitude
	obsoletes=ess-dive-e36d820b3c260ca-20181005T131737934298
	obsoletedBy=
	resourceMap=
	documents=
	isDocumentedBy=
id=ess-dive-e36d820b3c260ca-20181005T131737934298 seriesId=doi:10.3334/CDIAC/FFE.NDP058.2016.test1
	formatType=METADATA
	title=Annual Fossil-Fuel CO2 Emissions: Mass of Emissions Gridded by One Degree Latitude by One Degree Longitude
	obsoletes=ess-dive-4d2c097b534e485-20180320T153359785396
	obsoletedBy=ess-dive-e36d820b3c260ca-20181005T215135666
	resourceMap=['ess-dive-c47d7d15547a284-20181005T131749259423']
	documents=['ess-dive-e36d820b3c260ca-20181005T131737934298']
	isDocumentedBy=['ess-dive-e36d820b3c260ca-20181005T131737934298']
id=ess-dive-4d2c097b534e485-20180320T153359785396 seriesId=
	formatType=METADATA
	title=Annual Fossil-Fuel CO2 Emissions: Mass of Emissions Gridded by One Degree Latitude by One Degree Longitude
	obsoletes=ess-dive-c2f62cf0f76c5f1-20180320T152034768435
	obsoletedBy=ess-dive-e36d820b3c260ca-20181005T131737934298
	resourceMap=['ess-dive-3f852a3976a249e-20180320T153402137125']
	documents=['ess-dive-4d2c097b534e485-20180320T153359785396']
	isDocumentedBy=['ess-dive-4d2c097b534e485-20180320T153359785396']
id=ess-dive-c2f62cf0f76c5f1-20180320T152034768435 seriesId=doi:10.3334/CDIAC/FFE.NDP058.2016
	formatType=METADATA
	title=Annual Fossil-Fuel CO2 Emissions: Mass of Emissions Gridded by One Degree Latitude by One Degree Longitude
	obsoletes=ess-dive-ee6d90a94e626c8-20180320T151704924357
	obsoletedBy=ess-dive-4d2c097b534e485-20180320T153359785396
	resourceMap=['ess-dive-158fb2413fc7932-20180320T152037574624']
	documents=['ess-dive-c2f62cf0f76c5f1-20180320T152034768435']
	isDocumentedBy=['ess-dive-c2f62cf0f76c5f1-20180320T152034768435']
id=ess-dive-ee6d90a94e626c8-20180320T151704924357 seriesId=
	formatType=METADATA
	title=Annual Fossil-Fuel CO2 Emissions: Mass of Emissions Gridded by One Degree Latitude by One Degree Longitude
	obsoletes=
	obsoletedBy=ess-dive-c2f62cf0f76c5f1-20180320T152034768435
	resourceMap=['ess-dive-cbaf965a4d3b3b4-20180320T151705604630']
	documents=['ess-dive-ee6d90a94e626c8-20180320T151704924357']
	isDocumentedBy=['ess-dive-ee6d90a94e626c8-20180320T151704924357']
```

### Reproducing the Issue
I am able to consistently reproduce this now on our development server which has replication enabled. (See https://data-dev.ess-dive.lbl.gov/). This issue seems like is could be isolated to MetacatUI but I will let you guys decide that.

I can give you read/write access to this server if you give me the Orcid that you would like to authenticate with.

I started out with a new data package created via the REST interface using python scripts with:

- some number of data files
- replicationAllowed ( and has been replicated): if the package is marked as replicated but has not been replicated yet then the problem will be temporary (until metacat fixes things on its own)
- a public/read access policy.
- a series id

**NOTE: the data package must have all three: a series id, replicationAllowed and a public/read access policy for this issue to surface.**

**Comment by laurenwalker** [comment]
I've moved this issue over to the Metacat repo since it is an indexing bug. https://github.com/NCEAS/metacat/issues/1288

**Comment by vchendrix** [comment]
@laurenwalker We (@csjx @taojing2002 ) have already investigated this on the metacat end and it is not a metacat bug.  I apologize for not referencing the Metacat issue where we discussed this. See NCEAS/metacat#1277

**Comment by laurenwalker** [comment]
Just to clarify - it looks like the indexing issue only occurs during the following scenario:

1. A resource map with a series id
2. A resource map with replication allowed in the system metadata
3. A resource map with a public read access policy
4. A resource map that aggregates data files
5. When a new data file is added to this resource map via the MetacatUI editor, the updated resource map fails to index.

**Comment by vchendrix** [comment]
Yes that is essentially it.  However there is one caveat WRT item 2
(replication allowed). If the data package has not been replicated yet,
Metacat seems to figure out that the data package needs to be index and it
"fixes" itself after a day or so.  If the data package has been replicated,
it never gets indexed automatically.  However, I can fix things by indexing
the metadata object and resource map in the proper order.

**Comment by vchendrix** [comment]
We are now having this problem with a data set on production.  I updated
the EML with scripts (no problem) but then the metadata was edited via
metacatui and now the data files are missing (AKA the resource map has not
indexed).  This is critical as we have a user that wants to know that their
data package is available on our site.

See https://data.ess-dive.lbl.gov/#view/doi:10.3334/CDIAC/ATG.DB1001

I then tried to create a resource map programmatically and replace the one
that wasn't indexed but that didn't work.  The two unindexed resource maps
in question are:

{'id': 'ess-dive-97e1a221a78f563-20181019T144817202877',
  'replicationAllowed': True,
  'obsoletes': 'ess-dive-96b83d82e16f56c-20181019T204936299'},
 {'id': 'ess-dive-96b83d82e16f56c-20181019T204936299',
  'replicationAllowed': True,
  'obsoletes': 'ess-dive-8d9f20fba1a5546-20181019T133922478096',

'obsoletedBy': 'ess-dive-97e1a221a78f563-20181019T144817202877'}

I tried individually indexing the resource maps and metadata files but that
didn't work.  I am wondering if metacat will self heal in a day...  My next
approach will be to create a new resource map that is not a part of the
obsolescence chain of the old resource maps....I think that has worked for
me in the past.

**Comment by mbjones** [comment]
@taojing2002 @laurenwalker Could you clarify the status on this issue, and be sure it is being addressed?  Thanks.

**Comment by laurenwalker** [comment]
@vchendrix Could you give me upload access to your dev environment? My ORCID: http://orcid.org/0000-0003-2192-431X

**Comment by vchendrix** [comment]
@laurenwalker You should have access now

**Comment by vchendrix** [comment]
@laurenwalker  I am happy to provide instruction on how to use our python tools to upload the data package to ESS-DIVE.   However, are you aware the @taojing2002 fixed this issue with a metacat patch to the indexer?

**Comment by laurenwalker** [comment]
No, I didn't know that. Guess I can stop trying to reproduce the issue now... Thanks @vchendrix and @taojing2002

**Comment by taojing2002** [comment]
@vchendrix Thanks for the clarification. I wasn't sure the status. Thank you @laurenwalker for taking looking at this issue.
