### ISSUE TITLE
Group list pagination buttons don't work

### ISSUE THREAD

**Issue by amoeba** [NCEAS/metacatui#791]
I missed these in the routing refactor:

<img width="513" alt="screen shot 2018-10-05 at 2 05 16 pm" src="https://user-images.githubusercontent.com/563/46562271-bebdbf00-c8a7-11e8-8234-e5e86cfaf610.png">

The 1, 2, 3 pagination buttons redirect back to the root instead of showing the pages. While we're in here fixing this, look for similar types of issues I mighta missed.

**Comment by laurenwalker** [comment]
This was fixed. See #831
