### ISSUE TITLE
/view/ vs /view Behavior

### ISSUE THREAD

**Issue by ThomasThelen** [NCEAS/metacatui#792]
Visiting [this link](https://knb.ecoinformatics.org/view) and [this link](https://search.dataone.org/view) have the correct behavior of redirecting the page to `/data`.

Placing a `/` at the end of `/view` shows a blank page on DataONE, and an error page on the KNB. See [here](https://search.dataone.org/view/) and [here](https://knb.ecoinformatics.org/view/) and the screenshot below.

<img width="1677" alt="screen shot 2018-10-05 at 3 39 12 pm" src="https://user-images.githubusercontent.com/9289652/46563253-3e05bf80-c8b5-11e8-8b62-af21cf695687.png">

**Comment by laurenwalker** [comment]
This was fixed in #1030 in 2.6.5
