### ISSUE TITLE
inconsistent setting of `formatId` by beta editor

### ISSUE THREAD

**Issue by jagoldstein** [NCEAS/metacatui#796]
In this submission via the beta editor (https://arcticdata.io/catalog/#view/urn:uuid:b7a7c195-f8f4-412b-95ca-6fd624d853da), the .csv files did not have their `formatId`s set properly. Instead of `text/csv` they were set as `application/octet-stream`. See attached screenshot.

While the .xlsx files were uploaded with the first version of the package (resmap: `urn:uuid:385a23f8-c429-4aa7-9d55-8feb05db71df`), the .csv files were added to a later version (resmap: `urn:uuid:a2279ca5-6662-4f16-a10b-3f77e1aceafa`).

<img width="698" alt="screen shot 2018-10-09 at 10 27 27 am" src="https://user-images.githubusercontent.com/18270215/46687124-ed40e000-cbae-11e8-8d78-c22c4f664ccd.png">

**Comment by csjx** [comment]
Thanks @jagoldstein  - was the first version created with the editor as well (along with the Excel files)?

**Comment by dmullen17** [comment]
@csjx yes it was

**Comment by jagoldstein** [comment]
@csjx Yes, the first version of the package was submitted through the beta editor and included the EML, the 4 .xlsx files, and its resmap.

https://arcticdata.io/catalog/#view/urn:uuid:385a23f8-c429-4aa7-9d55-8feb05db71df

**Comment by laurenwalker** [comment]
This is a duplicate of #954
