### ISSUE TITLE
Make ProjectModel a subclass of CollectionModel

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/metacatui#798]
- [x] ProjectModel should be a submodel of CollectionModel
- (An example submodel is the EML211 model which is a subclass of the ScienceMetadata model which is a subclass of the DataONEObject model)
- The CollectionModel will likely stay the same - it will need to work on its own - fetching, parsing, etc.

- [x] ProjectModel will overload the parse and fetch functions
    - During fetch, the ProjectModel needs to fetch both the collection JSON document and the project XML document. The project XML document will have the identifier for the collection XML document, so the project XML needs to be fetched first (likely via a jQuery $.ajax() function)
    - During parse, the ProjectModel needs to parse both of those documents as well

- [x] During ProjectModel.parse(), the query filters will need to be extracted and set on a SearchModel. The SearchModel will be set on the ProjectModel as a Backbone model attribute. 

FYI:
- The ProjectModel will need to store all the attributes from the CollectionModel (its superclass) and the ProjectModel. -- this should be taken care of automatically by Backbone

**Comment by jkibele** [comment]
Note to self:

- Here's where to find the [example collection json](https://dev.nceas.ucsb.edu/knb/d1/mn/v2/object/urn:uuid:c665d6ed-553d-4d62-87e9-d49612352645).
- Here's where to find the [example project xml](https://dev.nceas.ucsb.edu/knb/d1/mn/v2/object/urn:uuid:efd93adf-d2eb-4241-99ce-d4f11550fa4a).

**Comment by jkibele** [comment]
I just spoke to @laurenwalker, but I'm still confused. I'm focused on trying to get `ProjectModel.fetch` to fetch both the project xml and the collection json, but I can't figure out how to make that happen. I'm looking that the jquery [jqXHR documentation](http://api.jquery.com/jQuery.ajax/#jqXHR) to see if I can figure out how to smoosh two response objects together, but I'm not sure if this is the right track. 

I had @rushirajnenuji come in an take a look. ...it may just be that I'm terrible at explaining to him what I'm trying to do, but he couldn't come up with anything immediately either.

**Comment by rushirajnenuji** [comment]
Hey @jkibele - Sorry I couldn't look into it more yesterday, I got engaged into a super weird bug with the DataONE Metrics System.

I think you explained it pretty well, I was just not sure how `inheritance` works in Backbone. One way could be to make the `CollectionModel.fetch` in the `ProjectModel.fetch`. I was thinking of something like the following:

File: `ProjectModel.js`

```
var ProjectModel = CollectionModel.extend({

defaults: function(){ return _.extend(CollectionModel.prototype.defaults(), {
    ...,
    ...
}) },



// Other methods
...
...



// ProjectModel's fetch function
fetch: function() {
    // Call the super class fetch method
    this.collectionModel = this._super;
    this.collectionModel.fetch();
    
    // Function body for Project Model's fetch
},


...

});
```

I'm not sure if this would be the right approach and good backbone SE practise. May be Lauren could suggest some better tips and / or the right approach.

**Comment by laurenwalker** [comment]
> I'm looking that the jquery jqXHR documentation to see if I can figure out how to smoosh two response objects together, but I'm not sure if this is the right track.

You can't send a request to two different URLs with the same XHR. You will need to send two separate XHR requests inside `ProjectModel.fetch()` - one to get the collection JSON document, and one to get the project XML document.

I think @rushirajnenuji  is on the right track with calling `CollectionModel.fetch()` inside `ProjectModel.fetch()`. This would be a good place to start. Alternatively, you can send use `jQuery.ajax()` to send an XHR to the `CollectionModel.url`, which would be a manual `fetch()`. That alternative is only necessary if you discover we need to bypass the default `CollectionModel.fetch()` Backbone behavior for some reason.

**Comment by jkibele** [comment]
...I'm thinking that maybe this is why Emily set it up the way she did. She doesn't try to access the collection model from within the project model or vice versa. She waits until project view, and starts to get at them there.

**Comment by laurenwalker** [comment]
So we know that the requirements are as follows:

1. When `ProjectModel.fetch()` is called, we want the model to retrieve two things - the collection JSON and the project XML.
2. We need to get the project XML first since it contains the collection id
3. Backbone is designed to only send a single XHR during `fetch()`. Therefore, we need to heavily customize the `fetch` and `parse` functions. 

Given these requirements, I suggest the following workflow:
- Get the project XML via an $.ajax() call and get the collection identifier from the XML response. Save the XML to fully parse later. Then call Backbone fetch to get the collection JSON.
- In parse, you will be able to parse both the project XML and collection JSON at this time, since parse()  won't get called until Backbone.model.fetch() is complete.

Here is some pseudo code.

**ProjectModel:**
```js

fetch: function(){
   // Get project XML 
   $.ajax({
     ...
     success: function(...){
       //Get the collection ID from the XML doc

       //Cache the XML document in a model attribute so we can fully parse it later
    
       //Call Backbone fetch to get the collection JSON
       var requestOptions = {
           ...
           url: collectionURL
       };
       Backbone.Model.prototype.fetch.call(this, requestOptions);

     },
     error: function(...){

       //Handle errors here  

    }
  });
},

parse: function(collectionJSON){

    //Get the project XML from the model attribute that it was cached in earlier

   // Parse this JSON response
   var parsedResponseJSON = {};

   return parsedResponseJSON;

}

```

**Comment by jkibele** [comment]
I tried a very similar approach initially. I had to set {async: false} in order to get it to work. That triggered a deprecation warning and slowed things down. Are we okay with using async: false, or is there some way to do this asynchronously that I'm missing?

**Comment by jkibele** [comment]
I've been looking for an example of where query filters get set on a SearchModel and I haven't found any so far. I've also been looking through the Search Model (Search.js). I don't see any way to set the filters in there either. Can anyone (maybe @laurenwalker ) point me toward how to set those query filters on the Search Model?

**Comment by jkibele** [comment]
Regarding this part of the task:

> During ProjectModel.parse(), the query filters will need to be extracted and set on a SearchModel. The SearchModel will be set on the ProjectModel as a Backbone model attribute.

It seems like it might be better to set the query filters in CollectionModel.parse() rather than ProjectModel.parse() since the optional filters are defined in the collection JSON rather than in the project XML. So, a collection that's not part of a project could also need to set query filters.
