### ISSUE TITLE
Complete the dates section of the Editor

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/metacatui#8]
- [x] Display a begin date and end date input in the Editor UI
- [x] Update the dates in the EML model when the UI is changed
- [x] Update or add the dates in the EML doc during serialize()

**Comment by amoeba** [comment]
I can take this. I worked on this a bit this morning and so far, I have round-trip editing working for the overly simple case of a beginDate/endDate. I mean round-trip in the sense of...

1. The EMLTemporalCoverage object is turned into form elements which are rendered
2. The form elements are watched for changes by the EML211 view
3. The change event triggers a mutation of the the underlying EMLTemporalCoverage instance

There are lots of next steps:

1. Expand the functionality of to support cases other than just a begin/endDate
2. Set up routing so People button works and move the Date/time pickers there. Right now it's rendered on the Overview temporarily
3. Consider what we are doing when a dataset has multiple coverage elements at both
  a. The dataset level
  b. Other levels

![kapture 2017-01-23 at 12 07 56](https://cloud.githubusercontent.com/assets/563/22222796/b0d09d76-e164-11e6-83da-3077f9aeb036.gif)

**Comment by amoeba** [comment]
4. I'm also going to hook in Times as was mocked up
![screen shot 2017-01-23 at 12 10 40 pm](https://cloud.githubusercontent.com/assets/563/22222849/f876cc22-e164-11e6-96d6-33b77e8c135f.png)

**Comment by amoeba** [comment]
Okay this is hooked in.

![screen shot 2017-01-25 at 5 17 10 pm](https://cloud.githubusercontent.com/assets/563/22317732/21ab631e-e322-11e6-80fd-ef09127ee5d5.png)

I still need to check if serialization works so that's up next.

**Comment by laurenwalker** [comment]
I've pushed some changes to fix some things that weren't working for me, and finished the serialize() function, so I think this section is done.
