### ISSUE TITLE
Improve “alternate identifier” field help text

### ISSUE THREAD

**Issue by brunj7** [NCEAS/metacatui#802]
I find this field confusing. Maybe adding an example of more description could help

**Comment by laurenwalker** [comment]
Does this seem better to anyone?

**Before:** `If available, provide pertinent information that can identify and locate the data set within your site's data management system.`

**After:** `If available, provide information that identify and locate this data set within another data management system or the web, such as an identifier or URL.`

**Comment by amoeba** [comment]
The description from the schema is pretty similar and is probably about as good as we could do:

> An additional, secondary identifier for this entity. The primary identifier belongs in the "id" attribute, but additional identifiers that are used to label this entity, possibly from different data management systems, can be listed here.

I'd also add:

> You probably don't need to fill this in except in special circumstances where your dataset is archived in more than one location.

**Comment by jeanetteclark** [comment]
Since the primary identifier is automatically assigned I'd consider: ```Additional identifiers that are used to label this dataset, possibly from different data management systems, can be listed here. Use if this dataset is archived in more than one location.```

**Comment by laurenwalker** [comment]
Thanks guys. Here's a combination of all the input so far:

`If this dataset is archived in another location, such as a different data management system, list any additional identifiers that can be used to locate or label the dataset, here.`

Yay or nay?

**Comment by amoeba** [comment]
👍 	but w/o the extra comma at the end.
