### ISSUE TITLE
Consider dynamic zooming for the gmaps embed

### ISSUE THREAD

**Issue by amoeba** [NCEAS/metacatui#82]
Sometimes, embedded gmaps feel too zoomed-in, sometimes just right, and other times show non-sense due to webmercator projections issues. A possible solution would be to dynamically choose a zoom level appropriate for a wide variety of possible bounding boxes. Some of the cases we've identified are:

- If very small regions, zoom in
- If very large, zoom out to global
- If sufficiently near the poles, show global

This isn't a dealbreaker or really a bug, but more of a wish-list item.

**Comment by robyngit** [comment]
This was addressed in PR https://github.com/NCEAS/metacatui/pull/2219 as a fix to https://github.com/NCEAS/metacatui/issues/2198
