### ISSUE TITLE
"Methods" section appears as if it is within "Project Information"

### ISSUE THREAD

**Issue by jagoldstein** [NCEAS/metacatui#828]
In the metacatUI metadata view, the `methods` section of EML appears as if it is a subcategory beneath `project`. Please see this example from https://arcticdata.io/catalog/#view/doi:10.18739/A2901ZF74:

<img width="1089" alt="screen shot 2018-11-06 at 3 10 28 pm" src="https://user-images.githubusercontent.com/18270215/48100000-67787a80-e1d6-11e8-8662-e04d85aabfd1.png">

The "Methods" header should be larger and bold so that it is clearly seen as its own category rather than a sub-header.

Here is another example from the CN (https://search.dataone.org/view/urn:uuid:054536f3-205f-4441-ac01-3f93b81665ea) where the `methods` appear to be a subcategory beneath `taxonomicCoverage`:

<img width="1472" alt="screen shot 2018-11-06 at 3 15 54 pm" src="https://user-images.githubusercontent.com/18270215/48100167-000efa80-e1d7-11e8-81d8-faf4b68845ad.png">

**Comment by amoeba** [comment]
Thanks for the report. I agree. Can I close #827? Also, I'll move this to https://gitub.com/nceas/metacat as the code causing this behavior lives there.

**Comment by amoeba** [comment]
How does this look? https://neutral-cat.nceas.ucsb.edu/view/urn:uuid:06e37992-6074-4690-b947-37f95a7a3497

**Comment by jagoldstein** [comment]
@amoeba the example you just posted above looks great!

I closed #827 (I'm unsure how that got created; the Beta of GitHub's Related Issues feature tripped me up.)

Yes, please move this to the appropriate repo. Thanks.

**Comment by amoeba** [comment]
👍
