### ISSUE TITLE
Catalog view incorrectly displaying data file logo

### ISSUE THREAD

**Issue by jagoldstein** [NCEAS/metacatui#833]
The catalog view shows the data file logo on some packages that no longer have any data objects. See this screenshot:
<img width="695" alt="catalogview" src="https://user-images.githubusercontent.com/18270215/48502262-f8151300-e7f3-11e8-996f-43c4c5fd3d5f.png">

Note that the data file logo is displayed, and when hovered over shows the message "This result includes data files". However, when the [package landing page](https://arcticdata.io/catalog/view/urn:uuid:351b8cdb-cbd7-4639-a965-d984854864bc) is navigated to, no data objects are part of the package. `arcticdatautils::get_package()` confirms this:
```> pid <- 'urn:uuid:b2f24314-3a76-4bb2-8d4d-c5d368a09c9e'
> get_package(mn, pid, file_names = T)
$metadata
                           science_metadata.xml 
"urn:uuid:351b8cdb-cbd7-4639-a965-d984854864bc" 

$resource_map
[1] "urn:uuid:b2f24314-3a76-4bb2-8d4d-c5d368a09c9e"

$data
named character(0)

$child_packages
named character(0)
```
Previous versions of the package DID have data objects. After the metadata were updated through the Editor, the data objects were wrongly removed from the resmap by the Editor (but NOT by `submitter` @dmullen17). (This is another bug, BUT we have not been able to consistently recreate that issue.) The EML still includes the `otherEntity`s left over from the previous versions, and perhaps that is why the data file icon displays in the catalog view, but it is inaccurate.

**Comment by amoeba** [comment]
Thanks for the report!

This is expected behavior, though not desired. The icon is shown when the metadata record is in a package (which it is) and not only when the metadata record is in a package that has data objects in it. Changing this is a tad tricky but I think it'd be a good thing to work on.

**Comment by jagoldstein** [comment]
Hmmm... that makes little sense to me @amoeba . How would a package show in the catalog view if it did not have a metadata record (EML)?

<img width="673" alt="catalog" src="https://user-images.githubusercontent.com/18270215/48504830-88eeed00-e7fa-11e8-9cc2-1d10ec2e208c.png">

This example ^ shows no data file icon, but it certainly has a [metadata record](https://test.arcticdata.io/view/urn:uuid:7ec832e8-21a1-4cb4-a952-fea3d3bb059d).

If it is expected behavior for the icon to be "shown when the metadata record is in a package", the message it gives when hovered over is inaccurate ("This result includes data files") and should be altered.

**Comment by amoeba** [comment]
> How would a package show in the catalog view if it did not have a metadata record (EML)?

That's not quite the thing: A metadata record can show in the DataCatalog view if it isn't in a package.

> and should be altered.

Yeah I don't disagree.

**Comment by jagoldstein** [comment]
I think I understand now. By 

> in a package

you mean that it has a resmap. Ok, that seems to line up with what I am seeing. Thanks for the explanation.

**Comment by laurenwalker** [comment]
I fixed this issue. I also added the number of data files in the package in the hover text so it now says, "This dataset contains X data files." This number will include the number of nested packages.
