### ISSUE TITLE
Arctic Data Broken API Page

### ISSUE THREAD

**Issue by ThomasThelen** [NCEAS/metacatui#838]
The page describing how to use the API is running into an error and fails to render.

Date Seen: 16-November-2018
Location: https://arcticdata.io/catalog/api
Error: 
```
router.js?v=2.3.2:81 Uncaught ReferenceError: appModel is not defined
    at n.renderAPI (router.js?v=2.3.2:81)
    at n.execute (backbone.js:1517)
    at Object.callback (backbone.js:1505)
    at app.js?v=2.3.2:180
    at Function.m.some.m.any (underscore.js:258)
    at e.History.loadUrl (app.js?v=2.3.2:178)
    at e.History.start (backbone.js:1728)
    at app.js?v=2.3.2:235
    at Object.execCb (require.js:1635)
    at Module.check (require.js:871)
```

Offending Code:
```
		renderAPI: function (anchorId) {
			this.routeHistory.push("api");

THIS LINE 	appModel.set('anchorId', anchorId);
			var options = {
					pageName: "api",
					anchorId: anchorId
			}

			if(!MetacatUI.appView.textView){
				require(['views/TextView'], function(TextView){
					MetacatUI.appView.textView = new TextView();
					MetacatUI.appView.showView(MetacatUI.appView.textView, options);
				});
			}
			else
				MetacatUI.appView.showView(MetacatUI.appView.textView, options);
		},
```

**Comment by rushirajnenuji** [comment]
`renderAPI` is trying to reference the appModel object that doesn't exist.

[This should be](https://github.com/NCEAS/metacatui/blob/master/src/js/themes/arctic/routers/router.js#L81): `MetacatUI.appModel.set('anchorId', anchorId); `

**Comment by csjx** [comment]
Doing a regex search for `\sappModel\.` across the codebase shows two more spots where this needs fixing - one in `UserModel` and one in `AnnotationModel`.

**Comment by laurenwalker** [comment]
Looks like those two references are in commented-out code. I removed them anyway.
