### ISSUE TITLE
Make the DataCatalogViewWithFilters work with geohash Filter models

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/metacatui#846]
Right now when the map is interacted with in the project view (for example, clicking on a tile), the search gets messed up and no search results are returned.

The DataCatalogView right now applies the geohash filter using the old Search model. This needs to be refactored to work with the new Filters. We may need to create a specialized SpatialFilter model for this.

Things that need to work:

- [x] Clicking on a tile, dragging the map, or changing the zoom should update the SpatialFilter model appropriately
- [x] The SpatialFilter should be added or removed from the query string based on whether the map is at full zoom (off) or if the "Limit my search" checkbox is checked (on)

**Comment by csjx** [comment]
I've pushed a bunch of changes to the project pages that revolve around how we manage `collections/Search` filters in the project views, but also so we maintain backwards-compatibility with managing `models/Search` filters for the main `DataCatalogView`.

While I have a number of issues to resolve (below), the basic change is that `DataCatalogView` uses a `models/Search` to store filters, but `DataCatalogViewWithFilters` extends `DataCatalogView` and uses `models/Search` to store search model properties, one of which is the `Search.filters` property, an instance of `collections/Search`.

I've added a `SpatialFilter` model that keeps track of the state of the map-based search, translating from map bounds and zoom into geohash strings and precision.  This was handled by `models/Search` previously.

When the map is zoomed, we add a `SpatialFilter` to the collection, so on `fetch()`, we add in the spatial Solr query fragment.  When we zoom all the way back out, we remove the `SpatialFilter` instance from the filters collection.

Here is a list of outstanding things I'm working on:
- [ ] Update custom filters to add/remove `Filter` instances from the filters collection (Lauren may have handled this already)
- [ ] On the first click of the map, the map zooms but the search is not triggered. On second and subsequent clicks it is. This is an event timing issue it seems
- [ ] Ensure the spatial query fragment being sent is correct. I encountered an `Entity Too Large` error, and so I may be accruing too many geohash strings for the zoomed area
- [ ] CORS is blocked from `localhost:{port}` - not sure why I saw this
- [ ] Resetting the results list back to the original when zooming all the way out to `minZoom` gives an incorrect count.  For instance, for SASAP, the original reloaded-page query hits are 102, but after zooming in, then back out, the results remain at 92 (the last query result I presume).
- [ ] We seem to be sending 3 Solr queries for every event, even page load.  Figure out why.  We may need to use `silent: true` in some places when updating the filters collection
- [ ] Override `DataCatalogView.toggleMapFilter()`
- [ ] Ensure `DataCatalogView.drawTile()` listeners are correct, maybe override

**Comment by csjx** [comment]
@laurenwalker - I fixed the rendering issue with the filters in the filter groups, but I see that changes to the filters aren't firing a search trigger. I thought that was working yesterday. I'll track it down this morning.

**Comment by csjx** [comment]
I've enabled the  "Limit my search to the map area" in the projects view map. The last outstanding issue is 
> Resetting the results list back to the original when zooming all the way out to `minZoom` gives an incorrect count.  For instance, for SASAP, the original reloaded-page query hits are 102, but after zooming in, then back out, the results remain at 92 (the last query result I presume).

which I will work on next.

**Comment by laurenwalker** [comment]
When I uncheck "Limit my search to the map area", the query is correctly adjusted to omit the geohash filter. But the map tiles don't work as expected anymore. I can zoom in and out on the map but the tiles don't update. When we zoom in, the map should re-render with smaller geohash tiles and when we zoom out, the map should re-render with larger geohash tiles.

![map](https://user-images.githubusercontent.com/6643222/52805227-21904580-3054-11e9-980e-f79a6217a335.gif)

**Comment by csjx** [comment]
Ah yes - thanks @laurenwalker - I'll have a look.

**Comment by laurenwalker** [comment]
Works great for me now, Chris. I'm going to close this since the only outstanding issue I can tell is #895, which has its own GH issue

**Comment by csjx** [comment]
These issues are fixed now, so I'm moving on to the map toggle in #895.
