### ISSUE TITLE
Display 'Quality Report' button only for supported formats

### ISSUE THREAD

**Issue by gothub** [NCEAS/metacatui#849]
Currently, the MetacatUI deployment (v2.4) on KNB and ADC displays an error msg when the 'Quality Report' button is clicked for datasets using metadata formats that aren't currently supported by the KNB and ADC suites. (Only EML is currently supported, but the MetaDIG engine 2.1 release will have support for ISO and Dryad).

For unsupported formats, don't display the 'Quality Report' button in the MetadataView.

**Comment by laurenwalker** [comment]
I think we should also hide the button when the metadata is private, since quality reports for private metadata docs are not generated.

**Comment by gothub** [comment]
Quality reports for private content are being created on KNB, ADC, but the metadata itself is never exposed.

**Comment by laurenwalker** [comment]
Ah, ok. Awesome!

**Comment by jagoldstein** [comment]
The support team, as well as external users, really benefit from being able to run automated quality checks on private EML, especially considering that publication standards continue to become more strict.

**Comment by gothub** [comment]
Fixed in commit 1f239da1b2c1b5c4af58e821a8c8635ea0abd236 (branch dev-2.9)

This feature uses the config parameter displayDatasetQualityMetric, which is set to
'true' for themes: 'arctic', 'knb' and 'false' for themes: 'default', 'dataone'.
