### ISSUE TITLE
Editor shows an error icon in the People section but no message. Never submits.

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/metacatui#851]
We heard from a user trying to submit to the ADC who encountered an error after clicking submit.

From the user:

> I’ve tried two to submit some data for NSF report on two separate occasions now using two different browsers (chrome and safari) and am getting similar results, spinning submission button. 

Serialized EML from the user's local memory: 

`
<eml:eml xmlns:eml="eml://ecoinformatics.org/eml-2.1.1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:stmml="http://www.xml-cml.org/schema/stmml-1.1" xsi:schemaLocation="eml://ecoinformatics.org/eml-2.1.1 eml.xsd" packageId="urn:uuid:9eae9f15-1284-41d5-bbe4-03a8b09b5563" system="knb"><dataset><title>ReCAP ice core gas data</title><creator id="6405812397975239"><individualName><givenName>Todd</givenName><surName>Sowers</surName></individualName><organizationName>Penn State University</organizationName><positionName>Sr. Scientist</positionName><address><deliveryPoint>2217 EES Bldg, Earth and Environment Systems Institute</deliveryPoint><deliveryPoint>Penn State University</deliveryPoint><city>University Park</city><administrativeArea>PA</administrativeArea><postalCode>16802</postalCode><country>USA</country></address><phone phonetype="facsimile">(814) 865 - 3191</phone><phone phonetype="voice">(814) 865 - 1921</phone><electronicMailAddress>tas11@psu.edu</electronicMailAddress><userId directory="https://orcid.org">Http://orcid.org/0000-0001-5496-5113</userId></creator><pubDate>2018-12-05</pubDate><abstract><para>This proposal seeks to drill, analyze, and interpret a new ice core from the Renland Ice Cap on the eastern coast of Greenland. The project is collaborative between US researchers (T. Sowers, Penn State and J. White, Univ. Colorado, this proposal) and researchers in Denmark’s Center for Ice and Climate (led by B. Vinther) and Alfred Wegener Institute in Bremerhaven, Germany (led by S. Kipfsthul). US efforts described here will focus on gas concentrations and gas isotopes (Sowers) and ice isotopes (White).</para><para>Primary objectives of this proposal are: 1) link the recent, rapid warming seen in Greenland over the past decade to the baseline record of the past few centuries, as well as the broader Holocene record; 2) provide, for the first time, high-quality records of gases and gas isotopes throughout the Holocene from a Greenland core, and test current theories about the evolution of greenhouse gases in the Holocene and the impact of humans on that evolution; 3) provide, for the first time, a record of ice isotopes at their highest possible resolution available in the ice record, which we hope will provide a high resolution record of Holocene sea ice near eastern Greenland, as well as a history of climate in this region going back into the last interglacial period.</para></abstract><keywordSet><keyword>ReCAP gas data</keyword><keywordThesaurus>GCMD</keywordThesaurus></keywordSet><intellectualRights><para>This work is dedicated to the public domain under the Creative Commons Universal 1.0 Public Domain Dedication. To view a copy of this dedication, visit https://creativecommons.org/publicdomain/zero/1.0/.</para></intellectualRights><coverage><geographicCoverage><geographicDescription>ReCAP Ice Sheet</geographicDescription><boundingCoordinates><westBoundingCoordinate>-26.72</westBoundingCoordinate><eastBoundingCoordinate>-26.72</eastBoundingCoordinate><northBoundingCoordinate>71.3</northBoundingCoordinate><southBoundingCoordinate>71.3</southBoundingCoordinate></boundingCoordinates></geographicCoverage><temporalCoverage><singleDateTime><calendarDate>2018-12-05</calendarDate><time>11:00:00</time></singleDateTime></temporalCoverage></coverage><contact id="2940906010390095"><individualName><givenName>null</givenName></individualName><userId directory="https://orcid.org">https://orcid.org/0000-0001-5496-5113</userId></contact><methods><methodStep><description><para>We utilized a wet extraction method to remove the trapped gases from --15 g samples of ice [Sowers et al., 1989]. Each ice sample was placed into the extraction vessel and attached to a high vacuum manifold. The vessel was evacuated for 1 hour at a temperature of-20øC. The vessel was then isolated and warmed to 40øC, thereby melting the ice and releasing the trapped air into the head space above the water. The water was then frozen allowing the dry air sample to be quantitatively transferred to a stainless steel sample tube which was immersed in liquid helium. At this point the sample tube with the fossil air was isolated and removed from the liquid helium. The air sample was then either expanded into the sample reservoir of the mass spectrometer or equilibrated into a glass ampoule and sealed for later analysis [Sowers et al., 1991]. The air samples were analyzed using isotope ratio mass spectrometry with a sample of dry compressed air as a reference. The standard deviation about the mean of all replicate •515N measurements was 0.006 permill.</para></description></methodStep><sampling><studyExtent><description><para>Samples are from various depths along the ReCAP main ice core</para></description></studyExtent><samplingDescription><para>Samples are cut in a freezer, loaded into a precooled extraction vessel and then attached to the "Spider" extraction device. Laboratory air is evacuated before sealing the vessels. Ice is melted and refrozen to liberate trapped air. Frozen into tubes in liquid He and then analyzed on a mass spectrometer.</para></samplingDescription></sampling></methods><project><title>ReCAP ice core gas data</title><personnel id="7056814876493734"><individualName><givenName>Todd</givenName><surName>Sowers</surName></individualName><organizationName>Penn State University</organizationName><positionName>Sr. Scientist</positionName><role>principalInvestigator</role></personnel><funding><para>NSF 1304077</para></funding></project><otherEntity><entityName>Final d18Oatrm ReCAP data 120418.xlsx</entityName><entityDescription>Elemental and isotopic composition of trapped O2 and N2 in ReCAP ice core</entityDescription><attributeList><attribute id="hTXcDTpVWqkFGE1XiP28QbwpVtD927"><attributeName>Down core gas data</attributeName><attributeLabel>Depth</attributeLabel><attributeDefinition>Elemental and isotopic composition of trapped gases in ice core</attributeDefinition><measurementScale><ratio><unit><standardUnit>meter</standardUnit></unit><numericDomain><numberType>real</numberType></numericDomain></ratio></measurementScale></attribute></attributeList><entityType>application/vnd.openxmlformats-officedocument.spreadsheetml.sheet</entityType></otherEntity></dataset></eml:eml>"
`

Screenshot from the user:
![image](https://user-images.githubusercontent.com/6643222/49599187-56926480-f94e-11e8-891e-e798b0b21a65.png)

**Comment by jagoldstein** [comment]
actually there are many missing characters and elements. some examples:

`<attributeName>dO2/N2/attributeName>` (line 187)

`otherEntity` and `dataset` not closed at end (~line 217)

**Comment by laurenwalker** [comment]
The error icon in the people section may be coming from the contact, which was serialized as `null`:

`<contact id="2940906010390095"><individualName><givenName>null</givenName></individualName><userId directory="https://orcid.org">https://orcid.org/0000-0001-5496-5113</userId></contact>`

**Comment by csjx** [comment]
@laurenwalker - Is the issue here that Todd's attribute names have `/`s in them, and we're not escaping them, so they jack up the XML?

**Comment by mbjones** [comment]
Could we develop some validation tests that try really hard to break the app using a variety of unusual characters and character sequences -- both valid and invalid -- to be sure the application can serialize those all correctly and not error out?  If these included a set of unicode characters, a wide variety of reserved characters in XML (<>/'&";), well-formed and malformed entity references (e.g., &nbsp;, &amp;, &quote; &foo;, etc.), undefined entity references, and characters from character encodings that are not the current encoding (e.g., Windows-1252 or CP-1252 or ISO-8859-1 characters in a UTF-8 doc), we might be able to prevent some of these surprises from emerging slowly one at a time.

**Comment by laurenwalker** [comment]
The simplest way to handle the People section bug is to create the creator and contact when the Editor first loads rather than later when the user clicks Submit. We've talked before about doing it this way anyway, so I went ahead with that route. A creator or contact will be created during Submit if the user deletes either of them without adding a replacement party.

<img width="1356" alt="screen shot 2018-12-10 at 5 44 51 pm" src="https://user-images.githubusercontent.com/6643222/49766515-853c7200-fca3-11e8-8bd0-df885c3a5a1f.png">


I'll look into the attributes stuff next. I think developing some tests for these scenarios is a great idea.

**Comment by laurenwalker** [comment]
Jesse and I discussed the odd serialization errors where there are missing `<`'s. 

From Slack:
>trying to decipher his email it sounds like this XML is perhaps where Sowers “…downloaded the 
> meta data from [his] previous submission and cut and pasted in new information for the current submission.”
> the `cut and pasted` seems like a probable explanation for the oddly absent `<`s
> if that’s true, it’s probably not a helpful GH comment for debugging efforts

I think the `<`'s may have been erased when he manually edited the plain XML in a text editor. I haven't been able to recreate the missing `<` bug and I don't see any `invalid EML` errors in our Google Analytics, which would have happened if the saving process got that far.

I think the People section was the only bug that prevented him from saving. I'll close this issue.
