### ISSUE TITLE
"Undefined" metrics count when searching for a dataset

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/metacatui#854]
When I see a dataset in the search results with 0 metric counts, the display is as expected (the metric badges are not displayed at all).

When I search for that dataset, the metrics are displayed incorrectly. The badges are shown without a number and when I hover over, it says "undefined citations/downloads/views"

Before a search filter is applied:
<img width="726" alt="screen shot 2018-12-06 at 2 58 47 pm" src="https://user-images.githubusercontent.com/6643222/49608763-7da96000-f967-11e8-8d4c-81ab824857ca.png">

After a search filter is applied:
<img width="726" alt="screen shot 2018-12-06 at 2 54 31 pm" src="https://user-images.githubusercontent.com/6643222/49608735-68343600-f967-11e8-962c-f1eb84609fb9.png">

**Comment by rushirajnenuji** [comment]
Added a check for non-zero length of response object before displaying the metrics for search items.
Related commit: https://github.com/NCEAS/metacatui/commit/bb1ac0b6ec2a347a44b79a4815671a5c6c84058e
