### ISSUE TITLE
search for ORCID link should open in new tab

### ISSUE THREAD

**Issue by mbjones** [NCEAS/metacatui#872]
During the Arctic training, participants lost entered metadata when clicking on the 'Search for ORCID' tooltip in the ORCID box in the People section.  They were prompted to leave the site, and when they chose to leave, they lost their form information.  It would be better if the ORCID search link opened in a new tab and didn't cause them to leave the site.

Even better, look up their ORCID via their email / name and suggest it for them without having to manually search.

**Comment by laurenwalker** [comment]
Fixed in https://github.com/NCEAS/metacatui/commit/4891fd5cd80075ce1da47c3d15b72b259ef91cc5#diff-feab99efdcbeebe4e9b08539514c7df3
