### ISSUE TITLE
Copy to... link does not appear in Firefox 64.0

### ISSUE THREAD

**Issue by mbjones** [NCEAS/metacatui#873]
In the Arctic Data training, the vertical elipsis showing the "Copy to" menu does not appear for one of our Firefox users who was using version 64.0 of Firefox on MacOS X.   When I tried with version 63.0 of Firefox, it appeared fine.   I then upgraded my browser to 64.0.2, and then the menu item disappeared for me as well.  So, it appears that recent versions of Firefox 64.0.x have an issue with this display.  See screenshots below.  

Screenshot showing the working elipsis on Firefox 63.0:
<img width="1649" alt="people-firefox-63 0" src="https://user-images.githubusercontent.com/766407/51146194-f9ba8180-180a-11e9-9395-33dce87bfc68.png">

Screenshot showing the missing elipsis on Firefox 64.0.2:
<img width="1658" alt="people-firefox-64 0 2" src="https://user-images.githubusercontent.com/766407/51146205-04751680-180b-11e9-900a-abd6f99aadc3.png">

**Comment by laurenwalker** [comment]
I notice this issue on Firefox 64.0.2 on both test.arcticdata.io and demo.arcticdata.io (both at MetacatUI 2.1.1), but not on my local MetacatUI (several commits ahead of 2.4.1). There were some recent changes to the People section so I think this may have been resolved already in one of those commits.
