### ISSUE TITLE
Attribute scroll bar covers last attribute name; does not go away after moving off of list

### ISSUE THREAD

**Issue by jagoldstein** [NCEAS/metacatui#882]
The new scroll bar to view the list of `attributeName`s is an important and very helpful feature! Thanks @amoeba and @laurenwalker.

However, I did notice that the last `attributeName` is covered by it (the scroll bar overlaps). See screenshot:

<img width="640" alt="attributescrollbar" src="https://user-images.githubusercontent.com/18270215/51937372-55663c80-23bf-11e9-8375-33c50b1476a8.png">

The issue only occurs _after_ one of the `attributeName`s is clicked on, because then the scroll bar does not go away when the cursor is moved off of the attribute list. (Perhaps that is the real issue.) The scroll bar _does_ go away after moving the cursor off of the list if used _without_ ever clicking on any `attributeName`. Clicking outside the attribute list does not cause the scroll bar to go away either.

**Comment by laurenwalker** [comment]
I'm not seeing this issue on my end. Which OS and browser were you using (and version)?

**Comment by jagoldstein** [comment]
This doesn't appear to be an issue anymore. I suppose it was fixed in a recent release.

**Comment by jagoldstein** [comment]
I found this issue again here: https://arcticdata.io/catalog/view/urn:uuid:32801ed8-f9e1-4533-bc43-26472cd3a893 .

I am using Google Chrome Version 72.0.3626.119 (Official Build) (64-bit) in macOS Sierra Version 10.12.6.

See this screenshot:

<img width="195" alt="screenshot20190228" src="https://user-images.githubusercontent.com/18270215/53599543-44dee880-3b5c-11e9-949d-8312bcbff26c.png">

**Comment by amoeba** [comment]
This is a UI/UX behavior of recent-ish versions of macOS and not entirely the fault of MetacatUI. macOS no longer provides a unique space for scrollbars and puts them inside the frame. Whether that happens depends on whether you have a mouse plugged in. See the gif. I'm just unplugging and replugging my mouse.

![kapture 2019-02-28 at 14 07 20](https://user-images.githubusercontent.com/563/53604865-2da2f980-3b62-11e9-86e6-1bca66d6323d.gif)

We _could_ make an affordance for this in the UI but it'd only be for people that meet the following criteria and not all users:

- Run recent macOS
- Have this feature turned on
- Don't have an external mouse plugged in

I'm curious to hear what others think about making an affordance.

**Comment by laurenwalker** [comment]
Thanks for the sleuth work, Bryce. I'll just add a padding to the bottom for everyone, of 25ish pixels, which shouldn't look weird even when the scrollbar doesn't overlap.
