### ISSUE TITLE
'Quality Report' button is live for `dataone` theme

### ISSUE THREAD

**Issue by gothub** [NCEAS/metacatui#890]
This button is active for https://search.dataone.org, but should be disabled until the DataONE quality suite is available in production. This button is disabled by setting `mdqBaseUrl = ""` in `src/js/themes/dataone/models/AppModel.js`. The `AppModel.js` version in the master branch is incorrect. @laurenwalker where should I update the source, e.g. in master?

**Comment by laurenwalker** [comment]
This is fixed already
