### ISSUE TITLE
Problem while editing package's version after DOI

### ISSUE THREAD

**Issue by brunj7** [NCEAS/metacatui#891]
Hi,

As we discussed on Slack, it seems there was a problem when I edited this package's version https://doi.org/10.5063/F1CF9NCJ and created a truncated resource map causing the non-indexation of the data package https://knb.ecoinformatics.org/view/urn:uuid:5c913d14-3ee3-4813-950d-e0ca02bff113

The change between the two versions was minor, I edited one letter in the EML (correcting a creator's name from _Martin Cicowiezb_ to _Martin Cicowiez_).

Unfortunately my recollection of the order of the events is partial, here is what I can best report:

1. When I edited the package with the web editor, I made the change in the creator name. I also wanted to edit the project section. I realized I could find how to do that. So I asked around. The main point is that I left the session in edit mode without doing anything on it around 10min.
2. Then I can not clearly remember the exact order of what I did :( . I think I clicked the back button because I could not edit the section, then realized I had the name to edit so hit the forward button. Clicked submit. Then it stayed with the spinning wheel for about a minute. I hit refresh and could only see the eml entry with no data

**Comment by mbjones** [comment]
Can this be closed now? Looks like the package was fixed?
