### ISSUE TITLE
Add media type application/x-ipynb+json

### ISSUE THREAD

**Issue by gothub** [NCEAS/metacatui#892]
Add the media type 'application/x-ipynb+json' to `models/DataONEObject.js` `isSoftware()` so that files with this DataONE formatId will be recognized by the metadata and prov editors as a `program`.
This type is not yet registered with DataONE, here is the ticket that requests that it be added: https://redmine.dataone.org/issues/8762

**Comment by laurenwalker** [comment]
Maybe we could add a feature to the prov editor to show all objects in the package when choosing a program? Like a "Show all" link that expands the list of files. That way we don't have to update MetacatUI each time a new format ID is added and we can account for uncommonly-used program file formats as well.

**Comment by amoeba** [comment]
👍 	to that, @laurenwalker

**Comment by gothub** [comment]
Added format 'application/x-ipynb+json' to DataONEObject.js in commit 4d019cbfd896c8cf4e4e84b337404895b33ab4e4
