### ISSUE TITLE
Search result items don't show prov icon it seems they should

### ISSUE THREAD

**Issue by amoeba** [NCEAS/metacatui#894]
I'm not entirely sure this is a bug, maybe I'm (1) mis-remembering or (2) at some point this was changed on purpose. The search result listing for our usual Mark Carls Hydrocarbon example, I thought, used to show a prov icon underneath it but I'm not seeing it.

To reproduce:

1. Visit https://search.dataone.org/data
2. Under "Filter By" in the sidebar, expand the toggle for "Creator"
3. Enter "Mark Carls" and hit Return
[You should see 6 results]
4. Observe no provenance icon under the second result:

> Mark Carls. 2017. Analysis of hydrocarbons following the Exxon Valdez oil spill, Gulf of Alaska, 1989 - 2014. Gulf of Alaska Data Portal. urn:uuid:3249ada0-afe3-4dd6-875e-0f7928a4c171.

<img width="525" alt="screen shot 2019-02-08 at 2 56 49 pm" src="https://user-images.githubusercontent.com/563/52512583-089a1700-2bb2-11e9-9d30-6d6c124fc34e.png">

Wasn't there a prov icon there before?

<details>
<summary>OS & Browser</summary>

- Chrome 72.0.3626.81
- Safari 12.1 14607.1.30
- Mac OS 10.14.4 Beta
</details>

**Comment by laurenwalker** [comment]
Yes, the prov icons should still display there. I'll look into it

**Comment by amoeba** [comment]
Thanks!
