### ISSUE TITLE
enable scrolling to the right in "add file" window in prov editor

### ISSUE THREAD

**Issue by jeanetteclark** [NCEAS/metacatui#898]
for long, similar filenames it is impossible to distinguish between files. a scroll bar to allow you to view the whole name would be helpful. See example for a problematic list of files below:

![screen shot 2019-02-11 at 4 18 05 pm](https://user-images.githubusercontent.com/24237074/52602757-a98a0b80-2e18-11e9-855b-d47c7aabd25f.png)

**Comment by gothub** [comment]
@laurenwalker what do you recommend here - a horizontal scrolling window? I'm a little rusty on CSS tricks, so any suggestions are most welcome. Also, I know that there are other (old) issues regarding this dialog, maybe we can discuss those at the next dev meeting.

**Comment by amoeba** [comment]
@jeanetteclark 	can you please share a link to where you see this? It'd be easier to see what's going on and also easier to make a fix.

**Comment by laurenwalker** [comment]
Let's start by making the select tool the full width of the modal window

**Comment by jeanetteclark** [comment]
@amoeba https://knb.ecoinformatics.org/view/urn:uuid:27606fcc-879f-4260-a259-fac31067d477

**Comment by csjx** [comment]
Fixed. The select box is the full modal width, and x-axis scrolls for wicked long file names. Pushed to `dev-2.4`.

**Comment by laurenwalker** [comment]
Can you merge to `dev-2.5` for the next patch release? :)
