### ISSUE TITLE
Complete the Locations section of the Editor

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/metacatui#9]
- [x] Display a locations section in the editor form, by adding points manually one-by-one
- [x] Update the EMLGeoCoverage model when the UI is changed
- [x] Update or add the locations in the EML doc during serialize()

**Comment by laurenwalker** [comment]
I'm going to start on this now

**Comment by laurenwalker** [comment]
This is almost done, just need to double check serialization.

**Comment by laurenwalker** [comment]
The only thing that needs to be done is add the remove button. I think we can develop that in parallel with user testing today.

**Comment by amoeba** [comment]
I can add the remove buttons in. I need to document the remove button API anyway.

**Comment by laurenwalker** [comment]
Should be totally complete now.
