### ISSUE TITLE
Annotations indexed as format type RESOURCE are displayed in MetadataView as a package

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/metacatui#903]
<img width="1616" alt="screen shot 2019-02-12 at 1 52 34 pm" src="https://user-images.githubusercontent.com/6643222/52660395-92f1bc00-2ecd-11e9-9d75-b537b5e6b1f9.png">

The annotator json documents are indexed as formatType=RESOURCE so the MetadataView sees this as a nested package.

**Comment by mbjones** [comment]
Annotator documents should not have made it into production.  Can we just delete them to fix this, as we've decided to not use that approach for annotation for now?

**Comment by laurenwalker** [comment]
Yes, that seems reasonable. Actually, I'm not sure if any annotation documents even made it into production since I found this bug on cn-stage-2, so I'll look.
