### ISSUE TITLE
Default theme generates objects having null value at authoritative member node

### ISSUE THREAD

**Issue by taojing2002** [NCEAS/metacatui#907]
MetacatUI 2.5.0 will go with the Metacat 2.10.1 release. However, I found that the package generated by the editor (the default theme) can't be updated by the same user. It turns out that the authoritativeMemberNode is null on the system metadata. Note: the java authoritativeMemberNode object is not null. But its string value is literal "null".  In the create method, Metacat only checks if the java authoritativeMemberNode object is null. If it is not null, it just save its value. In this case, the string "null" itself will be set as the authoritativeMemberNode  value.  So the update failed. 
I believe many people will ask the help for not able to update the objects when they start to use the metadata editor.

**Comment by mbjones** [comment]
@taojing2002 I think I saw some debugging of something closely related to this issue on slack in the last two weeks.  Please check in with @csjx and @laurenwalker to see if they already have a fix.

**Comment by laurenwalker** [comment]
We decided to omit the `authoritativeMemberNode` from the system metadata if it is not configured in MetacatUI. Metacat will automatically fill in the `authoritativeMemberNode` when the object is created.

**Comment by taojing2002** [comment]
Metacat also add code to check if the `authoritativeMemberNode` is with the string value `null`. So it can handle old versions of MetacatUI.
