### ISSUE TITLE
Project Page fails to render completely under Windows 10 IE and Edge

### ISSUE THREAD

**Issue by csjx** [NCEAS/metacatui#908]
The `ProjectHomeView` fails to load the `TOCView` nor any search results (likely doe to the errors.  It loads fine on Windows with Chrome 72. Track down the errors in the Microsoft browsers.

**Comment by csjx** [comment]
I've tracked down a couple of issues, see commits, and Lauren fixed the `Router` issue that IE was having issues with. 

The last issue that I've yet to be able to track down is that on project page load, the `DataCatalogView` shows 0 results, and nothing on the map (IE and Edge).  I'm not seeing any related syntax errors.  I do see two console errors about XHR requests failing, but they look to be unrelated (they happen even before the project document XHR request, so shouldn't be related to the Solr queries.
That said, when zooming into the map, results show up just fine.  So, there's something going on with the initial load's Solr query.  Lauren mentioned that the first query is not typed as `text/json` whereas subsequent ones are. Needs more troubleshooting.

**Comment by csjx** [comment]
Ugh. So I think I tracked this down, and I'm thinking it's not a code issue.  The initial Solr query sent by IE and Edge has a garbled quote character in the `project:State of Alaska's Salmon and People` parameter.  When I changed the SASAP project document to use an ASCII single quote character, I still get zero results, but I also get zero results on Mac browsers too now.  So I think we're using Mac smart quotes in all of the science metadata documents in this title field.  The search worked on MacOS, but Windows perhaps interprets the characters as other than UTF-8?? Not sure.  Since @jeanetteclark can probably change all of the SASAP test EML titles to use an ASCII single quote faster than I can, I will recruit her and then test again. 🙂

**Comment by jeanetteclark** [comment]
I updated all of the documents but 3 on dev, switching the smart quote to an ASCII single quote.  I am going to make the same updates on prod as I go through and make other metadata improvements on those documents

**Comment by csjx** [comment]
Note to self: update `sysmeta` to include Jeanette for these three `pids`:
```
urn:uuid:9f6f7c79-472b-4712-b785-52b31a58db9d
urn:uuid:b35abeb3-2128-4b3f-9ef6-b6a2f99507b4
urn:uuid:7eb7e612-6c1f-4c3a-94e9-d9ad3d56de0e
```

**Comment by jeanetteclark** [comment]
@csjx just one more to fix, the other two I was able to do myself. This one only has knbadmin LDAP group in the access policy

"urn:uuid:b35abeb3-2128-4b3f-9ef6-b6a2f99507b4"

**Comment by csjx** [comment]
The pids above have the correct access policy for @jeanetteclark to update them, so I'm going to close this issue now.  The main code issues have been fixed.
