### ISSUE TITLE
provide visual indicator for required fields in editor

### ISSUE THREAD

**Issue by mbjones** [NCEAS/metacatui#91]
We got extensive feedback during Morpho development to provide visual indicators for fields that are required.  Most applications use an asterisk to flag a field as required.

**Comment by laurenwalker** [comment]
Right now we only require a title to save, but the Editor should allow each theme to configure its own set of required fields.

**Comment by laurenwalker** [comment]
We decided to keep the title as the only required field for now, and come back to this when we have more time after the advisory board mtg May 15.

From discussions in Slack:

if we use the standard Backbone `model.validate()` for required fields, and in the view call `isValid()`, we can return the list of fields that don’t validate, or maybe a map of `fieldname: error message` so we can highlight the field and provide messages:
```
validate: function() {
                var errorMap = {};
                // will be run by calls to isValid()
                if ( ! this.get("entityName") ) {
                    errorMap.entityName = new Error("An entity name is required.");
                }

                return errorMap;
            }
```
