### ISSUE TITLE
Attribute list's panes show up below rather than to the right at wide browser widths

### ISSUE THREAD

**Issue by amoeba** [NCEAS/metacatui#916]
Possibly could close this one along with #910.

On https://arcticdata.io/catalog/view/doi:10.18739/A2RF5KF5N, I see at super wide browser widths:

<img width="389" alt="screen shot 2019-02-22 at 3 03 36 pm" src="https://user-images.githubusercontent.com/563/53278011-4ec3a000-36b3-11e9-8522-b7879836640f.png">

and at narrower widths, I see what is expected:

<img width="396" alt="screen shot 2019-02-22 at 3 03 41 pm" src="https://user-images.githubusercontent.com/563/53277967-2176f200-36b3-11e9-92b1-67b891ec2b4a.png">

It wasn't immediately clear to me what was going on but I did wanna report it.

**Comment by laurenwalker** [comment]
Which browser were you using? I can't seem to replicate this.

**Comment by amoeba** [comment]
A recent Chrome 72. I can reproduce it on Safari and Firefox too. For an idea of how wide I'm talking, the body element on my page is 2500px wide when I see this. The right pane snaps into place around at body width of 1920px or narrower.
