### ISSUE TITLE
Remove XML from all editor interface displays

### ISSUE THREAD

**Issue by mbjones** [NCEAS/metacatui#92]
Currently XML messages from the server are shown in the 'Details' dropdown when an error occurs.  This will be confusing for end users.  At a minimum, we should strip out the XML and only display the 'message'.  But better, let's use an error dictionary to handle errors well and highlight appropriate elements in the UI with well-crafted communication to the user of how to fix the issue (e.g., for a field validation error).

**Comment by amoeba** [comment]
Hey @mbjones this is a great idea. For time, we think splitting this into two tickets makes sense so I've done ahead and done that: #96 and #97.
