### ISSUE TITLE
MetacatUI User + Repository profile - Review

### ISSUE THREAD

**Issue by rushirajnenuji** [NCEAS/metacatui#927]
- Review of Repository & User profiles:
    - Issues that need urgent work:
        - [x] Re-render charts on change browser window
        - [x] Remove scrollbar, fixed width for citations table - Basically all the CSS set on metacatui-common.css:2185 (`.citations-metrics-list > .metric-table.table.table-striped.table-condensed,
.citations-metrics-list > .empty-citation-list`) and metacatui-common.css:2102 (`.metric-table.table.table-striped.table-condensed`)
        - [x] Update `Summary of holdings` section with the actual user information
        - [ ] Add user's groups to the profile as mocked up [here](https://projects.invisionapp.com/d/main#/console/13323020/289784181/preview)
        - [ ] Scrollspy - figure out why it is not working
        - [x] Retrieve Metrics only for user's date range
            - [x] Currently it is set from the beginning of time
                - Use First upload date from the `statsModel`
            - [x] [Similar] - Time Period of user's data
        - [x] Fix DataONE profile 
            - When any `id` is not passed to the `/profile` url, it should render DataONE profile
        - [ ] Scroll property for user's group -- maybe we should just collapse the list by default (with a caret icon like in the mockups)
        - [x] Scroll property for the entire left-side column --- I am seeing it get cut off a lot on the member node profiles because the MN description gets long
        - [ ] Tooltip for abstract gets cut off in its container element 

    - Low priority but needs to be taken care of:
        - [ ] Tooltip for metric charts should be within the time-series chart frame
        - [ ] Spinner to indicate wait 
        - [ ] Show error on failure to retrieve metrics
        - [x] For citation data that have incorrectly escaped HTML entities like `&amp;apos;`, change `CitationView.render()` to replace the `&amp;` with `&` whenever it is directly followed by the regex pattern `/[A-Za-z0-9];/`
        - [x] Add comma to the metrics displayed next to the time range just above the charts (e.g. `34107 Downloads from Jan 2012 to Mar 2019` should be `34,107 Downloads from Jan 2012 to Mar 2019`)

**Comment by laurenwalker** [comment]
If any of these items end up getting pushed to the backlog, then go ahead and make a new issue for them so we don't overlook them in the future.
