### ISSUE TITLE
Plural form grammar issues in Projects filters

### ISSUE THREAD

**Issue by amoeba** [NCEAS/metacatui#928]
(Not sure if I chose the best labels so please re-label as needed)

I took a whirl through https://dev.nceas.ucsb.edu/projects/SASAP and it works well and looks great. I did find a few minor grammar issues w/ plurals:

Two things:

- Should be 'an' instead of 'a'
- Probably be ADF&G, unless there are special reasons it shouldn't be. The '&' is the canonical way to show the initialism for ADF&G.

<img width="249" alt="Screen Shot 2019-03-14 at 12 33 29 PM" src="https://user-images.githubusercontent.com/563/54389885-0bc36f80-4656-11e9-9a7b-faf2a467e935.png">

and

<img width="252" alt="Screen Shot 2019-03-14 at 12 33 34 PM" src="https://user-images.githubusercontent.com/563/54389891-0e25c980-4656-11e9-9e2f-e9e9e51de3ce.png">

- Should be 'an' instead of 'a'

I didn't look for more cases but thought I'd report them.

**Comment by laurenwalker** [comment]
@jeanetteclark - see Bryce's second point here for the project document.

I'll fix the "an" grammar issue in the MetacatUI code
