### ISSUE TITLE
use of <> in text elements generates arbitrary invalid elements

### ISSUE THREAD

**Issue by jeanetteclark** [NCEAS/metacatui#939]
Submitting a dataset with some text surrounded by carats will generate an XML element, and invalid EML. So submitting with an abstract of:

> this is a \<thing\>

Results in:
```Error inserting or updating document: urn:uuid:6692a999-8332-4c4f-bbbb-f04a29b5686e since <?xml version="1.0"?><error>cvc-complex-type.2.4.a: Invalid content was found starting with element 'thing'. One of '{value, itemizedlist, orderedlist, emphasis, subscript, superscript, literalLayout, ulink}' is expected.</error>```

Seems there should be a way to recognize and escape or sanitize these characters prior to trying to write the EML?

**Comment by laurenwalker** [comment]
This issue just came up last week with ESS-DIVE. #935 

I'll look into this. Closing this issue since it's a duplicate
