### ISSUE TITLE
Navbar jumps around in weird ways

### ISSUE THREAD

**Issue by amoeba** [NCEAS/metacatui#94]
Just noticed this weird behavior of the side/nav bar when my browser is reasonably large:

![cast](https://cloud.githubusercontent.com/assets/563/25364148/b828b5c8-290c-11e7-9eb1-34fc8553c41f.gif)

See how, without any scrolling, the bar jumps up and down as I go through each page?

**Comment by laurenwalker** [comment]
This is a side effect of the new navigation layout, which I knew was there but I wanted to get it out to testing ASAP. It's getting fixed by me now

**Comment by amoeba** [comment]
Perfect, thanks!

**Comment by laurenwalker** [comment]
Should be smooth as buttah now
