### ISSUE TITLE
API access to citation metrics?

### ISSUE THREAD

**Issue by brunj7** [NCEAS/metacatui#941]
As part of the evaluation impact of the SNAPP working groups,  we would like to gather SNAPP working group data packages. I was wondering if there is a way to get the citations using a query?

**Comment by mbjones** [comment]
There sure is.  We could eve create a project page for SNAPP that would have metrics available for the whole collection.

**Comment by rushirajnenuji** [comment]
Hey @brunj7  - Is this resolved? Please let me know if there is anything else you need for this ticket.
Or we can close this.

**Comment by brunj7** [comment]
Hi @rushirajnenuji ,

I have not had time to test further following our discussion. Since the DOIs are generally not added in the reference section, I think at this point my best metric is going to be the number of downloads instead of citations.

I will look into leveraging Google Scholar full text search to see if I can produce a different metric for citation containing any mention of the DOI in the text, but that might be for the next iteration.

You can close the issue. Thank you for your help!
