### ISSUE TITLE
OAI-DC view: Hyperlink the `dc:relation`

### ISSUE THREAD

**Issue by rogerdahl** [NCEAS/metacatui#944]
In this OAI-DC doc:

https://search.dataone.org/view/10.25390/caryinstitute.7395032.v1

* The Service Endpoint link, pulled from `dc:relation`, should be made clickable.
* It would also be good to have the link displayed more prominently closer to the top of the page.
* Cary Institute may add more alternate Service Endpoints by adding multiple `dc:relation`s. We should list them all, perhaps visually separate them a bit.
* Can we remove the empty lines between each field in the `People and Associated Parties`, `Access Control` and `Other` sections?

**Comment by laurenwalker** [comment]
I think it would be a good idea to hyperlink any URL taken from metadata documents. That's something we've discussed before, so this seems like an opportunity to add that in now.

> Can we remove the empty lines between each field in the People and Associated Parties, Access Control and Other sections?

I'm not sure what you mean by this. Can you point out what empty lines you are referring to?

Ideally, an XSLT should be made for that metadata standard, so that the display can be controlled better. The view you see now is just a simple display of all the Solr fields for that object, which is a fallback view for metadata standards without an XSLT.

**Comment by rogerdahl** [comment]
@laurenwalker I like the idea of turning all URLs into links.

Each of the single line elements are rendered as separate sections, with a box drawn around it and an empty area around the box. I think it would look better if we removed the boxes and empty areas.

![Selection_004](https://user-images.githubusercontent.com/561416/56591841-b2305800-65a6-11e9-8c98-06c9c9f76193.png)

**Comment by amoeba** [comment]
Hey @laurenwalker, dfab941dc7721a6714e4b10c7d427d7fff3e5a58 appears to introduce an XSS vulnerability. Do you think we should sanitize anything that's turned into a link here?

**Comment by laurenwalker** [comment]
What kind of sanitation were you thinking? Only values that start with a `http` are turned into links, so that should prevent `javascript:` and `data:` links.

**Comment by amoeba** [comment]
Something like `http://whatever</a><script>mycode</script>`. Are we safe from stuff like that with underscore?

**Comment by rogerdahl** [comment]
Just wanted to note that the links are not a special case and that we need to escape anything that originates from users, anything pulled from SysMeta, EML, etc, before inserting it into HTML.

**Comment by amoeba** [comment]
Very true. For the most part, the view service should be getting us most of the way there.

**Comment by amoeba** [comment]
Very true. For the most part, the view service should be getting us most of the way there.

**Comment by laurenwalker** [comment]
This is something that needs to be done throughout the app, so I created a new ticket - #966

**Comment by amoeba** [comment]
Sounds good, thanks @laurenwalker
