### ISSUE TITLE
Simplify code tree structure

### ISSUE THREAD

**Issue by csjx** [NCEAS/metacatui#95]
When the MetacatUI code structure was originally laid out, we had a Java-based proxy component assumed to be installed as a Tomcat web app.  The MetacatUI source was then nested underneath this structure in the `metacatui/metacatui/src/main/webapp` directory.  Since we've moved to Apache-based proxying as needed and have removed the Java proxy code, I propose we simplify the tree structure and make the Javascript application conform to traditional JS app structures.  To do this, we would:

- Remove the duplicate `metacatui` folder
- Move `src/main/webapp/*` into `src`
- Remove the `src/main/scripts` folder
- Add a `test` folder for unit tests

To do this, we have to be cognizant of the `1.x` merge issues it will cause, so we need to do any merging beforehand.  Also, all outstanding `2.x` code commits should pushed to `origin/master` so we don't cause merge headaches in this branch either. Once the tree structure is re-organized, @amoeba @laurenwalker and @csjx can resume coding.

The tree would change from: 
```
metacatui/
└── metacatui
    ├── docs
    │   └── design
    └── src
        └── main
            ├── resources
            ├── scripts
            └── webapp
                ├── WEB-INF
                ├── components
                ├── css
                ├── font
                ├── img
                ├── js
                └── resources
```
to:
```
metacatui/
├── docs
│   └── design
├── src
│   ├── components
│   ├── css
│   ├── font
│   ├── img
│   ├── js
│   └── resources
└── test
```

**Comment by laurenwalker** [comment]
A million times yes! I've been wanting to do this forever.

**Comment by mbjones** [comment]
@csjx Yes, please, I've wanted to do this too many times too.

**Comment by laurenwalker** [comment]
This was done in bcbf79d5edd0acdca75514498bd64f437467fba9
