### ISSUE TITLE
Search page should link via dataset series ID 

### ISSUE THREAD

**Issue by FiannaOBrien** [NCEAS/metacatui#955]
**Suggestion**: When user selects a dataset from search page, the dataset page should have series ID in URL rather than PID. Many of our users don't know about the series ID or how wonderful a tool it is.

**Comment by FiannaOBrien** [comment]
On the ESS-DIVE search page, the citation is displayed with the DOI/series ID, similar to how ESS-DIVE datasets are displayed on DataOne. I'm talking about the URL of a dataset landing page.

What we've found is when users select their datasets from the search page, they are linked to the dataset via a URL that includes the PID and not the series ID. Users will copy what's in their browser bar and share that link, which may direct to an out of date dataset version.

For example, on ESS-DIVE, if you search for the series identifier "doi:10.21952/WTR/1508396" & open the landing page for that dataset, you'll be directed to the dataset landing page where the URL includes the PID ("https://data.ess-dive.lbl.gov/view/ess-dive-9cbf0e9afc200ed-20190510T180837963").  If the search page linked to dataset via a URL including the series id ("https://data.ess-dive.lbl.gov/view/doi:10.21952/WTR/1508396"), users would be more able to share the most up to date version of their dataset.

**Comment by laurenwalker** [comment]
Ah, I see now. I think that's a good idea.

**Comment by laurenwalker** [comment]
This issue has been fixed, but @vchendrix will need to update the CitationView in the ess-dive theme for the changes to take effect there. I tried to create a new branch to do a PR on the ess-dive-catalog repo but it looks like I don't have access?
