### ISSUE TITLE
Improve display of DataONE error messages

### ISSUE THREAD

**Issue by amoeba** [NCEAS/metacatui#96]
This Issue is a split of #92.

From @mbjones:

> Currently XML messages from the server are shown in the 'Details' dropdown when an error occurs. This will be confusing for end users. At a minimum, we should strip out the XML and only display the 'message'.

**Comment by laurenwalker** [comment]
We now parse the XML response from the server and attempt to find the XML node with the error  to display it's textual contents only. If the error node is not found, the entire XML will be displayed.
