### ISSUE TITLE
data objects with .xml "formatId"s show up in catalog view

### ISSUE THREAD

**Issue by jagoldstein** [NCEAS/metacatui#961]
Data objects with .xml extensions and xml "formatId"s show up in the [catalog view](https://arcticdata.io/catalog/data), even though they are meant to be data objects within a package, not discoverable metadata records for the entire packages themselves.

Example:
https://arcticdata.io/catalog/view/urn:uuid:fcab9044-cfe6-423c-bb5b-6dc755f6b2f8

**Comment by laurenwalker** [comment]
This has a formatId of `http://www.esri.com/metadata/esriprof80.dtd` - `ESRI Profile of the Content Standard for Digital Geospatial Metadata, March 2003` - which is indexed as a `METADATA` type. Data objects with an xml formatId - `application/xml` - are indexed as a `DATA` type and won't show up in the catalog view.

**Comment by jagoldstein** [comment]
ok, so we'll use that `formatId` for xml data objects
