### ISSUE TITLE
Content-Disposition ignored when setting local filename for package

### ISSUE THREAD

**Issue by rogerdahl** [NCEAS/metacatui#965]
When using the Download All button to download a package, it appears that the local filename is determined by downloading the corresponding SysMeta and looking up `fileName`. If `fileName` is not provided in the SysMeta, the local filename is set up to just `.zip`. This is even if the MN includes a `Content-Disposition` header with a filename in the response.

When downloading the package directly from the MN from a browser, the browser sets the local filename based on the  `Content-Disposition` header, so I think that should be the standard behavior also when downloading via the Download All button. This also allows the MN to calculate a filename on the fly if one was not supplied in the SysMeta, and may allow skipping the SysMeta download.

Example:

Download All on this page will set the local filename to just `.zip`:

https://search.dataone.org/view/doi:10.5063/F1MK6B5J

That is even though, in this case, Metacat is providing a dynamically generated filename.

`Content-Disposition: inline; filename="resource_map_doi_10_5063_F1MK6B5J.zip"`

**Comment by laurenwalker** [comment]
Thanks Roger, I'll look into this

**Comment by laurenwalker** [comment]
This was fixed in #1020
