### ISSUE TITLE
Quality report "Interpretation" category is reported twice

### ISSUE THREAD

**Issue by gothub** [NCEAS/metacatui#967]
The summary section of the metadata quality report shows the `Interpretation` category twice:

<img width="951" alt="Screen Shot 2019-06-07 at 11 05 31 AM" src="https://user-images.githubusercontent.com/6412946/59124451-7b26c380-8914-11e9-8b34-17d913c4c9d7.png">

Each category should only appear once.

Here is an example: https://arcticdata.io/catalog/quality/doi%3A10.18739%2FA2VT1GP7Q

**Comment by jagoldstein** [comment]
Here is another example where the 2 `Interpretation` scores are different:
https://arcticdata.io/catalog/quality/urn%3Auuid%3Af33509cd-4ca0-4b9b-85d6-b97125c182bb
