### ISSUE TITLE
Data summary page show Janurary 2018 but it should be 2019

### ISSUE THREAD

**Issue by vchendrix** [NCEAS/metacatui#969]
I am not sure if this is a MetacatUI bug but I will start here.  The data repository summary page shows the downloads graph as having January 2018 data right before Feb 2019 data. 

https://data.ess-dive.lbl.gov/profile

![Screen Shot 2019-06-13 at 10 09 43 AM](https://user-images.githubusercontent.com/1558129/59452914-a18ca900-8dc3-11e9-8857-56f836c2cc96.png)

**Comment by rushirajnenuji** [comment]
I can reproduce this on ESS dive profile page as well as other repository profile pages on https://search.dataone.org

Here's a snap from the KNB repository:

![Screen Shot 2019-06-13 at 10 15 53 AM](https://user-images.githubusercontent.com/19696935/59453324-80788800-8dc4-11e9-860f-ef79ccbdc6ba.png)

Thanks for filing this bug @vchendrix

**Comment by jagoldstein** [comment]
Nice catch @vchendrix .
I now notice the same issue on https://arcticdata.io/catalog/profile :

<img width="1317" alt="Screen Shot 2019-06-13 at 10 16 30 AM" src="https://user-images.githubusercontent.com/18270215/59453529-efee7780-8dc4-11e9-8c4e-6741cdf64210.png">

When I tried to view the CN summary, I found the link from https://www.dataone.org/data is broken:
https://www.dataone.org/data-holdings .
That may be a separate issue though.

**Comment by jagoldstein** [comment]
_Every_ "January" in the x-axis labels above ^ display the incorrect year.

**Comment by laurenwalker** [comment]
Thanks everyone, I'll fix this

**Comment by laurenwalker** [comment]
This type of chart is being replaced with the new interactive metrics charts
