### ISSUE TITLE
[Bug] When dataset contributors exceed 10, the contributors numbering returns to #1.

### ISSUE THREAD

**Issue by HeshamElbashandy** [NCEAS/metacatui#974]
**Steps to reproduce:** 
 
1. Go to https://data-dev.ess-dive.lbl.gov/submit and choose people tab.
2. Start writing in the contributor till you reach 10 authors. 
3. The next open field labeled Creator says 1 and it should say 11.

**Expected result:** 
New contributor open field be numbered 11.

**Actual result:** 
New contributor open field showed be numbered 1.

**Comment by laurenwalker** [comment]
I believe the contributor titles (e.g. Creator #1, etc) are part of the ESS-DIVE extended code, so I'll have to change this in the ess-dive-catalog repo in Gitlab

**Comment by HeshamElbashandy** [comment]
I wasn't aware that this is part of our extension, thanks @laurenwalker for pointing that out. 

BTW we moved our repos from Gitlab to Github. I believe you are in the ESS-DIVE Github organization users.

**Comment by laurenwalker** [comment]
Ah, I see that now, thanks!
