### ISSUE TITLE
[Bug] Empty files upload hangs on the UI.

### ISSUE THREAD

**Issue by HeshamElbashandy** [NCEAS/metacatui#975]
**Steps to reproduce:** 
1. Go to https://data-dev.ess-dive.lbl.gov/submit 
2. Upload an empty (0 bytes) file. 

**Expected result:** 
UI will indicate that the file is corrupted or empty. 

**Actual result:** 
File upload hangs and it doesn't upload anything.

**Comment by laurenwalker** [comment]
The editor will now show an error message when an empty file is uploaded, but the rest of the dataset can be submitted without it.

<img width="910" alt="Screen Shot 2019-06-26 at 11 33 46 AM" src="https://user-images.githubusercontent.com/6643222/60194033-a1020280-9806-11e9-8913-bd3fbfb31856.png">
