### ISSUE TITLE
Create and fetch() the ProjectModel in the editor

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/metacatui#981]
During render, the ProjectEditorView creates a new ProjectModel with the given id and calls ProjectModel.fetch().

The ProjectEditorView needs to listen to the ProjectModel `sync` event and render the rest of the view once it's been fully fetched/synced. Until then, a loading icon should display in the editor.

There are three ways someone can enter the editor, and all three cases should be covered:
- `/edit/projects` 
   - A new, default ProjectModel is created
- `/edit/projects/urn:uuid:....`
   - A ProjectModel with the given seriesId is created and fetched from the server
- `/edit/projects/SASAP`
   - The project with the given short name is looked up in Solr and the seriesId is retrieved. Then a ProjectModel  is created and fetched from the server

The last route (with the project short name) will only work with the [feature-project-indexing](https://github.com/NCEAS/metacat/tree/feature-project-indexing) branch of Metacat. This may need to be developed after MVP-1.

**Comment by laurenwalker** [comment]
I added support for indexing projects on dev.nceas.ucsb.edu, so we can develop against that Metacat for this feature. In particular, looking up projects by their name in the Solr index rather than the MetacatUI app configuration. I'll start working on this now.

**Comment by rushirajnenuji** [comment]
Added a `createModel` method to the project editor that checks if the project exists - if it does it fetches the corresponding `projectModel`; if not - it creates a new `projectModel`.
