### ISSUE TITLE
Check user authorization in the project editor

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/metacatui#983]
The ProjectEditorView checks if the current user is authorized to edit the given ProjectModel. If not, a message is displayed and the view doesn't render anything else.
    - If the user isn't logged in at all, don't check for authorization and display a message and login button.

**Comment by rushirajnenuji** [comment]
Hi @laurenwalker  - by default, I'm checking for `changePermission` when a user tries to edit a project. Is this the correct permission or should we be checking the `writePermission` for it? Thanks!

**Comment by laurenwalker** [comment]
It should check for `writePermission`

**Comment by rushirajnenuji** [comment]
Hi @laurenwalker  - this authentication seems to be working as expected. Could you please review it? Thanks!

**Comment by laurenwalker** [comment]
The authorization isn't checked at all for me. `ProjectEditorView.authorizeUser()` is never called.

**Comment by rushirajnenuji** [comment]
Hi @laurenwalker  - could you please test this change and provide feedback regarding it whenever you get time. Thank you!

**Comment by laurenwalker** [comment]
Hi @rushirajnenuji. It is probably helpful to list all the scenarios we need to test, and see which are working and which aren't. I went ahead and tested them and listed them here:

## Test case: Attempting to edit a portal when you're NOT logged in
**Current behavior:** An error message states that the project is private and has a link to sign in.

<img width="1132" alt="Screen Shot 2019-08-13 at 1 38 26 PM" src="https://user-images.githubusercontent.com/6643222/62970833-fc4b7c80-bdd5-11e9-847b-c70aae35df0a.png">

**Desired behavior:** The SignInView should be rendered, just like it does for the metadata editor (replace "submit data" with "edit a portal".)
<img width="876" alt="Screen Shot 2019-08-13 at 2 23 03 PM" src="https://user-images.githubusercontent.com/6643222/62970803-ea69d980-bdd5-11e9-9469-c5855452100a.png">

## Test case: Attempting to submit a new portal when you're NOT logged in
**Current behavior:** The project editor view is rendered completely.
<img width="910" alt="Screen Shot 2019-08-13 at 1 39 13 PM" src="https://user-images.githubusercontent.com/6643222/62971406-63b5fc00-bdd7-11e9-8870-91088e7972a9.png">

**Desired behavior:** The SignInView should be rendered, just like it does for the metadata editor (replace "submit data" with "create a portal"):
<img width="876" alt="Screen Shot 2019-08-13 at 2 23 03 PM" src="https://user-images.githubusercontent.com/6643222/62970803-ea69d980-bdd5-11e9-9469-c5855452100a.png">

## Test case: Attempting to edit a portal that you DO have permission to edit, when logged in
This is working correctly

## Test case: Attempting to edit a portal that you DON'T have permission to edit, when logged in
<img width="993" alt="Screen Shot 2019-08-13 at 1 40 24 PM" src="https://user-images.githubusercontent.com/6643222/62971416-6d3f6400-bdd7-11e9-9b5f-70e1449d2d56.png">

This is working correctly, but let's change the error message text to be more helpful:

`The portal owner has not granted you access to edit this portal. Please contact the owner to be given edit access.`

In the future, we will want to make this more helpful, such as displaying the owner's name and the portal name, but for the MVP I think that message will do.

## Test case: Attempting to submit a NEW portal when logged in
This is working correctly

**Comment by laurenwalker** [comment]
Also, we need to remember to use the word "portal" instead of "project" in user-facing language

**Comment by rushirajnenuji** [comment]
Checked the funcitonality with the following test cases:
- Attempting to edit a portal when you're NOT logged in
    - Behaviour: Display a Sign In View to edit a portal
    - Status: working
- Attempting to submit a new portal when you're NOT logged in
    - Behaviour: Display a Sign In View to create a portal
    - Status: working
- Attempting to edit a portal that you DO have permission to edit, when logged in
    - Behaviour: Check for `write` permission; display the editor
    - Status: working
- Attempting to edit a portal that you DON'T have permission to edit, when logged in
    - Behaviour: Display error message
    - Status: working
- Attempting to submit a NEW portal when logged in
    - Behaviour: Display the project editor
    - Status: working

This issue is now complete.

**Comment by laurenwalker** [comment]
Looks great, thanks!
