### ISSUE TITLE
Display a helpful message when the collection is empty

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/metacatui#992]
When the collection is empty, display a message in the DataCatalogViewWithFilters that tells the user to add filters

**Comment by robyngit** [comment]
Re-opening the issue because the "collection is empty" message continues to display when year filters are added. This seems to be a problem with using `getCurrentilters()` from `collections/Filters` to determine whether there are filters or not.

**Comment by laurenwalker** [comment]
I just went ahead and moved this to the EditCollectionView since the message should only be relevant when editing collections. We'll want to use the FilterGroupsView in other places in the app (wherever searching may occur), so we don't want to bloat that view with collection-specific functionality.
