### ISSUE TITLE
When the "+" button is clicked, create a new ProjEditorSectionView

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/metacatui#996]
A new ProjectSectionModel and ProjEditorSectionView will be created. The default ProjEditorSectionView will show the section type options (see #995).

**Comment by robyngit** [comment]
@laurenwalker, should the `PortalSectionModel` be created as soon as the "+" button is clicked, or should we wait for a section type to be selected first?

**Comment by laurenwalker** [comment]
Let's wait for a section type to be selected first.
